### ISSUE TITLE
Code coverage highlighting no longer displaying and returns error message on Apex v60.8.0

### ISSUE THREAD

**Issue by zfrench** [forcedotcom/salesforcedx-vscode#5534] opened 2024-04-11 15:47 UTC
### Summary

Code coverage highlighting no longer displays and a pop error occurs

### Steps To Reproduce:

1.  Enable 'Highlight Apex Code Coverage'
1.  Select a unit test to run from a test class
1.  Click on the on class that you ran the code coverage for and an error message will be displayed.

### Expected result

Expected the code highlighting to display green or red lines depending on the code that ran.

### Actual result

No code highlighting occurred and error message was displayed.

### Additional information
Error Message:
Expected double-quoted property name in JSON at position 30195 (line 1 column 30196)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/4147537/04c7ec7d-74ff-4955-8cf6-10e4b8416be6)

If I downgrade the extension from 60.8.0 to 60.7.0 then it will display the highlighted coverage correctly.

**Salesforce Extension Version in VS Code**: Apex v60.8.0

**SFDX CLI Version**: 2.36.8

**OS and version**: Windows 10 Enterprise

**VS Code version**: 1.88.0

**Comment by alan-liu-ofx** [comment] 2024-04-12 00:39
Same for me.
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/62679825/dd0f46cf-ff09-4b29-b077-03b0873619b8)
@salesforce/cli/2.36.8 win32-x64 node-v20.11.1
VS Code 1.88.1 
Win 10 22H2

**Comment by maximojoinansel** [comment] 2024-04-12 19:49
Hi there! I am still getting this issue. I saw there is a work to fix it in progress but in the meantime Is there any workaround available to make this work? I really appreciate any help you can provide.

**Comment by peternhale** [comment] 2024-04-12 20:06
@maximojoinansel the only workaround would be to downgrade extensions to v60.7.0.

The work is in progress and we hope to have the fix out in our release next week.

**Comment by jh480** [comment] 2024-04-14 13:30
> Hi there! I am still getting this issue. I saw there is a work to fix it in progress but in the meantime Is there any workaround available to make this work? I really appreciate any help you can provide.

You can still get the first few uncovered lines from the Output section under "Apex Code Coverage by Class".

**Comment by maximojoinansel** [comment] 2024-04-15 15:11
@peternhale downgrading the extensions to v60.7.0. works! Thanks for your help here.

**Comment by AhmedElAmory** [comment] 2024-04-16 14:53
I thought I was the only one, thanks for reporting this. I'm waiting for the fix.

**Comment by rvanaken** [comment] 2024-04-19 18:30
I had trouble getting the test status indicators to show up after updating to v60.8.0.

The indicators always showed blue regardless of the test result for each test:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/18737223/8f401d13-5b8c-485e-a7f0-5d65b5ca0a4a)
It may be related to this JSON parsing error:

`SyntaxError: Expected double-quoted property name in JSON at position 12030`

I downgraded to v60.7.0 and it started working correctly.

Here is what it should look like: (after downgrading)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/18737223/f7aa3157-c426-41ac-a9e6-3ea460aa33a0)

I wasn't sure if you guys wanted a new issue logged, but can do.

**Comment by petehale** [comment] 2024-04-19 18:32
The issue with parsing result is probably the cause of the test indicators showing blue. The fix for the parsing issue should be in next week's release.

**Comment by daphne-sfdc** [comment] 2024-04-26 16:13
Hello everyone, this issue has been resolved and the fix is included in this week's release v60.10.0.  Please upgrade your extensions to the latest version for the best user experience.  Thank you for your patience.

**Closed by daphne-sfdc** 2024-04-26 16:13 UTC
Labels: area:apex, status:in review
