### ISSUE TITLE
Intellisense/codecomplete/autocomplete on packages

### ISSUE THREAD

**Issue by ikljaic-nubilum** [forcedotcom/salesforcedx-vscode#4725] opened 2023-03-02 13:01 UTC
**Is your feature request related to a problem? Please describe.**
With Unlocked packages it becomes really simple to prepare reusable libraries, however this reuseability drops significantly since intellisense does not work on them.
If it was a regular class, it would easily work, but unless you have codecomplete support for packages, it comes pointless since you would either have to remember everything from it or copy/paste.

**Describe the solution you'd like**
I could imagine a few outcomes. 
 - download the whole package into a hidden location and index it  in the server
 - add a config to the `sfdx-config.json` file a list of packageVersion Ids, from which you could build the index

I am not sure if this is a bug or a new feature, but whoever I asked, nobody can use intellisense on packages. please add some sort of support for this. we really need this.

**Comment by ikljaic-nubilum** [comment] 2023-03-02 17:06
Or is there at least a CLI command that I can point the server into the direction on what to index.

**Comment by ikljaic-nubilum** [comment] 2023-03-15 08:59
any updates? anyone?

**Comment by ikljaic-nubilum** [comment] 2023-04-18 15:06
@AnanyaJha

**Comment by randi274** [comment] 2023-05-10 15:33
Hi @ikljaic-nubilum - working with unlocked packages is definitely something we've heard our users would like support for! It looks like your request is a duplicate of #2075 - let us know if your request is different and we can keep this one open though.

**Comment by ikljaic-nubilum** [comment] 2023-05-10 16:11
@randi274 Seems to me to be the same request, that is already 3 years long. It would be amazing if there was some progress after 3 years, with something that is so basic for developers. This is something that drives developer satisfaction/addoption and improvement.
If you can make us developers more productive, it will make the business more happy and more willing to spend money on SF licences.

**Comment by randi274** [comment] 2023-05-10 17:19
💯 agree! Thanks for the speedy response too - we've re-prioritized that ticket, and will keep you updated on the status over there.

**Closed by randi274** 2023-05-10 17:19 UTC
Labels: more information required, type:feedback, area:packages, area:codecompletion
