### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sahithipriya** [forcedotcom/salesforcedx-vscode#3061] opened 2021-03-12 05:13 UTC
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6127973/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6127987/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `51.4.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\SA4501~1.MUP\AppData\

Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[Uploading salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt…]()

**Comment by smaddox-sf** [comment] 2021-03-16 21:50
Likely duplicate of #2410

**Closed by smaddox-sf** 2021-03-16 21:50 UTC
