### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by OdnanrefCamilo** [forcedotcom/salesforcedx-vscode#1115] opened 2019-03-04 12:22 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.3.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\fernandsilva\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment] 2019-03-04 19:23
@OdnanrefCamilo Can you confirm if the issue that you are seeing is similar to what is discussed in this thread? 

https://github.com/forcedotcom/salesforcedx-vscode/issues/1100

We are working on a fix to make the Apex editing experience more performant and should have some fixes in the upcoming extension update.

**Comment by praksb** [comment] 2019-03-04 19:23
Possible dupe of: https://github.com/forcedotcom/salesforcedx-vscode/issues/1100

**Comment by praksb** [comment] 2019-03-07 19:56
@OdnanrefCamilo We just released our latest Apex extension update which has fixes to improve the performance of Apex editing experience. Please upgrade to v45.5.0 and let us know if you still run into any issues.

**Closed by praksb** 2019-03-07 19:56 UTC
