### ISSUE TITLE
Retrieving v59 flow that includes the new Error_Message action fails from extension

### ISSUE THREAD

**Issue by MarcDBehr** [forcedotcom/salesforcedx-vscode#5178] opened 2023-10-23 18:14 UTC
### Summary

We have a v59.0 flow that includes the new "Error Message" action. When the flow is downloaded using the extension (org browser or retrieve), a critical part of the flow (the customErrors section( is not retrieved.

### Steps To Reproduce:

1.  Create a new v59.0 flow that includes the new "Error Message" action. In the action, define the error message.
2.  From VS Code, org browser, download the new flow
3.  Search the metadata for a section called "Error_Message" - Note that there is a connector reference to to it, but the message itself is not in the metadata.
4. Use the CLI command "sf force source retrieve -m Flow:flow_name -a 59.0"
5. Notice that the error message now exists 

### Expected result

The 'complete' flow version shoule be retrieved.

### Actual result

Got a version of the flow that can't be deployed anywhere

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

v59.1.2

**SFDX CLI Version**:

@salesforce/cli/2.13.9 darwin-x64 node-v20.6.0

**OS and version**:

MacOS Version 14.0 (23A344)

**VS Code version**:

Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (1 wk ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.0.0

**Comment by CristiCanizales** [comment] 2023-10-24 12:20
Hi @MarcDBehr,
I'm trying to repro this but even when running the sf command through the cli, the content of the xml is the same, with only the reference to the error. Could you send a screenshot of what you get when using our extensions and when sing the cli? Thanks in advance!

**Comment by MarcDBehr** [comment] 2023-10-24 13:36
@CristiCanizales From the extension, it looks like:

`<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <decisions>
        <name>Check_Lead_Status</name>
        <label>Check Lead Status</label>
        <locationX>314</locationX>
        <locationY>323</locationY>
        <defaultConnectorLabel>Default Outcome</defaultConnectorLabel>
        <rules>
            <name>Newly_Converted</name>
            <conditionLogic>and</conditionLogic>
            <conditions>
                <leftValueReference>Newlyconvertedlead</leftValueReference>
                <operator>EqualTo</operator>
                <rightValue>
                    <booleanValue>true</booleanValue>
                </rightValue>
            </conditions>
            <connector>
                <targetReference>Set_type_field_on_contact</targetReference>
            </connector>
            <label>Newly Converted</label>
        </rules>
    </decisions>
    <environments>Default</environments>
    <formulas>
        <description>Indicates if this is a newly converted lead.
Is this a new lead that is being converted (not likely) OR a lead that has just been converted AND there is an associated contact</description>
        <name>Newlyconvertedlead</name>
        <dataType>Boolean</dataType>
        <expression>((ISNEW() &amp;&amp; {!$Record.IsConverted}) || ISCHANGED({!$Record.IsConverted})) &amp;&amp;  ! ISNULL({!$Record.ConvertedContactId})</expression>
    </formulas>
    <interviewLabel>Lead: After Save {!$Flow.CurrentDateTime}</interviewLabel>
    <label>Lead: After Save</label>
    <processMetadataValues>
        <name>BuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>CanvasMode</name>
        <value>
            <stringValue>AUTO_LAYOUT_CANVAS</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>OriginBuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processType>AutoLaunchedFlow</processType>
    <recordUpdates>
        <name>Set_type_field_on_contact</name>
        <label>Set type field on contact</label>
        <locationX>50</locationX>
        <locationY>431</locationY>
        <faultConnector>
            <targetReference>Log_the_error</targetReference>
        </faultConnector>
        <filterLogic>and</filterLogic>
        <filters>
            <field>Id</field>
            <operator>EqualTo</operator>
            <value>
                <elementReference>$Record.ConvertedContactId</elementReference>
            </value>
        </filters>
        <filters>
            <field>Type__c</field>
            <operator>IsNull</operator>
            <value>
                <booleanValue>true</booleanValue>
            </value>
        </filters>
        <inputAssignments>
            <field>Type__c</field>
            <value>
                <stringValue>Sales</stringValue>
            </value>
        </inputAssignments>
        <object>Contact</object>
    </recordUpdates>
    <start>
        <locationX>188</locationX>
        <locationY>0</locationY>
        <connector>
            <targetReference>Check_Lead_Status</targetReference>
        </connector>
        <object>Lead</object>
        <recordTriggerType>CreateAndUpdate</recordTriggerType>
        <triggerType>RecordAfterSave</triggerType>
    </start>
    <status>Active</status>
    <subflows>
        <name>Log_the_error</name>
        <label>Log the error</label>
        <locationX>314</locationX>
        <locationY>539</locationY>
        <connector>
            <targetReference>Error_message</targetReference>
        </connector>
        <flowName>Debug_Info_Subflow</flowName>
        <inputAssignments>
            <name>debugInfoCaller</name>
            <value>
                <elementReference>$Flow.InterviewGuid</elementReference>
            </value>
        </inputAssignments>
        <inputAssignments>
            <name>debugInfoDebugData</name>
            <value>
                <elementReference>$Flow.FaultMessage</elementReference>
            </value>
        </inputAssignments>
        <inputAssignments>
            <name>debugInfoEndPoint</name>
            <value>
                <elementReference>$Flow.CurrentRecord</elementReference>
            </value>
        </inputAssignments>
    </subflows>
</Flow>`

If I run the command line: "sf force source retrieve -m Flow:Lead_After_Save " I get:

`<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <customErrors>
        <name>Error_message</name>
        <label>Error message</label>
        <locationX>314</locationX>
        <locationY>647</locationY>
        <customErrorMessages>
            <errorMessage>There was an error when trying to save the related contact. A log of the error has been saved.</errorMessage>
            <isFieldError>false</isFieldError>
        </customErrorMessages>
    </customErrors>
    <decisions>
        <name>Check_Lead_Status</name>
        <label>Check Lead Status</label>
        <locationX>314</locationX>
        <locationY>323</locationY>
        <defaultConnectorLabel>Default Outcome</defaultConnectorLabel>
        <rules>
            <name>Newly_Converted</name>
            <conditionLogic>and</conditionLogic>
            <conditions>
                <leftValueReference>Newlyconvertedlead</leftValueReference>
                <operator>EqualTo</operator>
                <rightValue>
                    <booleanValue>true</booleanValue>
                </rightValue>
            </conditions>
            <connector>
                <targetReference>Set_type_field_on_contact</targetReference>
            </connector>
            <label>Newly Converted</label>
        </rules>
    </decisions>
    <environments>Default</environments>
    <formulas>
        <description>Indicates if this is a newly converted lead.
Is this a new lead that is being converted (not likely) OR a lead that has just been converted AND there is an associated contact</description>
        <name>Newlyconvertedlead</name>
        <dataType>Boolean</dataType>
        <expression>((ISNEW() &amp;&amp; {!$Record.IsConverted}) || ISCHANGED({!$Record.IsConverted})) &amp;&amp;  ! ISNULL({!$Record.ConvertedContactId})</expression>
    </formulas>
    <interviewLabel>Lead: After Save {!$Flow.CurrentDateTime}</interviewLabel>
    <label>Lead: After Save</label>
    <processMetadataValues>
        <name>BuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>CanvasMode</name>
        <value>
            <stringValue>AUTO_LAYOUT_CANVAS</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>OriginBuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processType>AutoLaunchedFlow</processType>
    <recordUpdates>
        <name>Set_type_field_on_contact</name>
        <label>Set type field on contact</label>
        <locationX>50</locationX>
        <locationY>431</locationY>
        <faultConnector>
            <targetReference>Log_the_error</targetReference>
        </faultConnector>
        <filterLogic>and</filterLogic>
        <filters>
            <field>Id</field>
            <operator>EqualTo</operator>
            <value>
                <elementReference>$Record.ConvertedContactId</elementReference>
            </value>
        </filters>
        <filters>
            <field>Type__c</field>
            <operator>IsNull</operator>
            <value>
                <booleanValue>true</booleanValue>
            </value>
        </filters>
        <inputAssignments>
            <field>Type__c</field>
            <value>
                <stringValue>Sales</stringValue>
            </value>
        </inputAssignments>
        <object>Contact</object>
    </recordUpdates>
    <start>
        <locationX>188</locationX>
        <locationY>0</locationY>
        <connector>
            <targetReference>Check_Lead_Status</targetReference>
        </connector>
        <object>Lead</object>
        <recordTriggerType>CreateAndUpdate</recordTriggerType>
        <triggerType>RecordAfterSave</triggerType>
    </start>
    <status>Active</status>
    <subflows>
        <name>Log_the_error</name>
        <label>Log the error</label>
        <locationX>314</locationX>
        <locationY>539</locationY>
        <connector>
            <targetReference>Error_message</targetReference>
        </connector>
        <flowName>Debug_Info_Subflow</flowName>
        <inputAssignments>
            <name>debugInfoCaller</name>
            <value>
                <elementReference>$Flow.InterviewGuid</elementReference>
            </value>
        </inputAssignments>
        <inputAssignments>
            <name>debugInfoDebugData</name>
            <value>
                <elementReference>$Flow.FaultMessage</elementReference>
            </value>
        </inputAssignments>
        <inputAssignments>
            <name>debugInfoEndPoint</name>
            <value>
                <elementReference>$Flow.CurrentRecord</elementReference>
            </value>
        </inputAssignments>
    </subflows>
</Flow>`

Notice the customErrors section in the second version.

**Comment by CristiCanizales** [comment] 2023-10-30 17:52
Hi @MarcDBehr! Sorry for the delay. Could you tell me what's your `sourceApiVersion` in your sfdx-project.json?

**Comment by MarcDBehr** [comment] 2023-10-30 17:54
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "59.0"
}

**Comment by CristiCanizales** [comment] 2023-10-30 18:14
Could you try uninstalling sf cli and installing sfdx cli? Instructions [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm). Then, just try retrieving your flow. We've been playing around with versions and with sfdx cli it successfully retrieves the customErrors section

**Comment by MarcDBehr** [comment] 2023-10-30 18:53
But shouldn't we be moving away from from the sfdx CLI to the sf CLI?

**Comment by CristiCanizales** [comment] 2023-10-30 20:31
Yes, it's not mandatory though (yet). It was just to see if it worked for you and have more info to keep digging on the root cause.

**Comment by daphne-sfdc** [comment] 2023-10-31 02:44
Hi @MarcDBehr,
As another try, could you please clean the cache by deleting the .sfdx and .sf folders from the Explorer (left panel) and deleting the flow that you retrieved, then reload the VSCode window by running "Developer: Reload Window" from the command palette?  If that also does not fix the issue, please try restarting your computer.  Thanks a lot for trying with us.

**Comment by MarcDBehr** [comment] 2023-10-31 11:30
@daphne-sfdc I deleted the .sf and .sfdx folders and then I deleted the local version of the flow and reloaded the window. Next, I went to org browser and downloaded the flow and this time, I can see the error message correctly. So.... I guess there was something in the cache that was being referenced rather than the org itself? If so, this same thing happened to several people here, so this does not seem to be an issue on a single system.

**Comment by daphne-sfdc** [comment] 2023-10-31 20:31
Hi @MarcDBehr, Thank you very much for the confirmation, and glad to hear that everything is now working as expected on your system.  We're not sure why there is the cache issue, and you're right that it's not specific to any orgs, projects, or systems - although the solution to clean the cache has worked in most cases.  Closing this issue as completed.

**Closed by daphne-sfdc** 2023-10-31 20:31 UTC
Labels: more information required, investigating
