### ISSUE TITLE
Unknown exception deploying/retrieving source using a manifest

### ISSUE THREAD

**Issue by amulder87** [forcedotcom/salesforcedx-vscode#3152] opened 2021-04-15 20:44 UTC
### Summary

The  "SFDX: Deploy Source in Manifest to Org" or "SFDX: Retrieve Source in Manifest to Org" commands fail immediately and only give the feedback: "Unknown exception" in the Salesforce CLI output.

### Steps To Reproduce:

1.  Create a simple package.xml manifest, e.g. for my org I'm testing with the contents below:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>51.0</version>
</Package>
```

2.  Right click the manifest and choose SFDX: Deploy Source in Manifest to Org or SFDX: Retrieve Source in Manifest to Org

### Expected result

The sfdx force:source:deploy or force:source:retrieve commands should run, deploying or retrieving the contents specified in the manifest using the current default org.

### Actual result

The commands fail to run almost immediately and only give the feedback, "Unknown exception" in the Salesforce CLI output.

```
13:29:08.589 Starting SFDX: Deploy Source to Org

Unknown Exception
13:33:54.701 Starting SFDX: Retrieve Source from Org

Unknown Exception
```

### Additional information

The contents of the package.xml being used don't seem to matter at all. I get the same exception using an empty file or one with entirely invalid syntax. Running `sfdx force:source:deploy` and `force:source retrieve` commands and specifying a manifest works normally in a terminal, only failing in the VS code extension. I can, however, deploy/retrieve individual files or objects using the VS code extension without any issue. This started happening after recently updating VS code and the SDFX CLI extensions. I'm not sure what version I was on just before restarting VS Code to update.

**VS Code Version**:
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (2 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**SFDX CLI Version**:
sfdx-cli/7.97.0 darwin-x64 node-v15.14.0
Salesforce CLI Integration extension version 51.8.0

**OS and version**:
macOS Catalina
Version 10.15.7

**Comment by amulder87** [comment] 2021-04-15 23:53
I noticed a comment mention the `Salesforcedx-vscode-core › Experimental: Deploy Retrieve` setting in another open issue and found disabling it was a workaround for this as well. I only get the exception with the experimental setting enabled.

**Comment by smaddox-sf** [comment] 2021-04-19 15:45
Thanks for reporting this.  Duplicate of #3137 so I've linked this issue there.  Feel free to comment on that thread with any other feedback.

**Closed by smaddox-sf** 2021-04-19 15:45 UTC
Labels: area:deploy/retrieve, status:needs eng review
