### ISSUE TITLE
Option to clear Output console at the start of SFDX Command execution

### ISSUE THREAD

**Issue by codefriar** [forcedotcom/salesforcedx-vscode#2397] opened 2020-08-05 14:44 UTC
**Is your feature request related to a problem? Please describe.**
It can be hard to determine which parts of the output panel's data refer to the latest command. Especially if you trigger a save and test run back to back.

**Describe the solution you'd like**
As a developer, I would like an option to automatically clear my output panel when I start a SFDX command - say a deploy/push, or test execution - so that I can clearly see where the last commands' logs start and stop.

**Describe alternatives you've considered**
Manually doing this is a learnable habit. I've also considered suggesting an output 'header' / 'footer' to make it easier to see where one bit of output starts/stops.

**Additional context**
This would be especially useful as I live-code stream. Helps users on lower-res screens follow along as I'll not have to scroll back and forth to find the beginning of the log.

**Comment by smaddox-sf** [comment] 2020-08-17 16:59
Dupe of #941

**Closed by smaddox-sf** 2020-08-17 16:59 UTC
Labels: area:usability, status:duplicate, type:feedback
