### ISSUE TITLE
Announcement: Major Updates to the Apex Language Server 🎉 

### ISSUE THREAD

**Issue by AnanyaJha** [forcedotcom/salesforcedx-vscode#5046] opened 2023-08-25 01:17 UTC
With the latest release of the Salesforce Extension (V58.13.1), we've made major changes to the Apex Language Server. Learn more below - 

- **Performance Improvements**: We've heard that Apex Language Server startup often takes a significant amount of time - especially on Windows. With the latest changes, you should see faster startup times after the initial activation; local testing has shown the times go from 4 minutes to 16 seconds! Behind the scenes, we've switched to only indexing _changed_ files in your workspace now. This is a **major update** so please let us know if you're experiencing any issues or have feedback! 

- **View Current Status of Apex Language Server**: We're also making it easier for you to understand the current state of the Apex Language Server. Now you can check your bottom status bar to see if the Language Server is up and running - you can also pin the language server status to always have it handy. Take a look at the gif below to see it in action!

Let us know how the changes work for you; we'd love to hear feedback!

![ezgif com-video-to-gif](https://github.com/forcedotcom/salesforcedx-vscode/assets/21326913/2f289995-9dd5-4c2d-ab02-51b42986adba)

**Comment by FrancescoMasullo** [comment] 2023-08-25 09:34
After updating to the latest version the Apex Language Server fails to start. Restarting VS Code or reinstalling the extension didn't solve the issue. Am I doing something wrong? If is there a way to extract a more detailed log I would be happy to help fix this issue :)

**Comment by peternhale** [comment] 2023-08-25 11:35
Hi @FrancescoMasullo,

What are you seeing in the Apex status bar item?

Also, can you share your system configuration, include the version of java you have installed.

**Comment by FrancescoMasullo** [comment] 2023-08-25 12:52
Hi @peternhale,

> What are you seeing in the Apex status bar item?

The only error I get is this
<img width="453" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/98831025/15e678a6-d4c9-4e82-8ece-572fa029e5aa">


> Also, can you share your system configuration, include the version of java you have installed.

Sure, here's my system configuration and java version

Software:

    System Software Overview:

      System Version: macOS 13.5.1 (22G90)
      Kernel Version: Darwin 22.6.0

openjdk version "11.0.20" 2023-07-18 LTS
OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)

Feel free to ask any other relevant info, I'll to my best to help. Thank you!

**Comment by peternhale** [comment] 2023-08-25 13:07
@FrancescoMasullo thanks for the information. A couple more items. 

Would you mind sharing any output that is present in the "Output" tab for "Apex Language Server?"

Check these settings in vsce.
Salesforcedx-vscode-apex › Java: Memory
Salesforcedx-vscode-apex › Java: Home

**Comment by FrancescoMasullo** [comment] 2023-08-25 13:16
@peternhale reading the output probably the error is caused by a JR incompatibility, but I wait for your confirmation

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: apex/jorje/lsp/ApexLanguageServerLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
[Info  - 14:46:23] Connection to server got closed. Server will restart.
``` 

Also, the two settings you asked for:
<img width="772" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/98831025/2609387f-cef5-4b04-9c7c-cb393855f00d">

**Comment by peternhale** [comment] 2023-08-25 13:26
@FrancescoMasullo that is correct. The setting is pointing to apple's version of the JRE. As you shared, you have java 11 installed. If that is the version of java that is available on the path, remove the setting and restart vsce. I will look into the class version requirement as 55 is 11 and our minimum should be 8.

Let me know if the change helps.

**Comment by FrancescoMasullo** [comment] 2023-08-25 13:35
@peternhale Thanks for your help, changing the path to the correct one made the extension load right away

**Comment by peternhale** [comment] 2023-08-25 13:40
I am glad it worked and I apologize for the inconvenience.

**Comment by christopmj** [comment] 2023-08-30 13:34
Hello, I am having the same issue on windows:
I tried the following "_Salesforcedx-vscode-apex: Java Home_" settings, and am getting the following error. Is there an update or a particular JDK I need to install on my system?

Settings:
C:\Program Files\Java\jre1.8.0_191
C:\Program Files\Java\jdk1.8.0_161 (have been using this one for years)

_Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" [Info  - 9:31:41 AM] Connection to server got closed. Server will restart.
java.lang.UnsupportedClassVersionError: apex/jorje/lsp/ApexLanguageServerLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" [Error - 9:31:42 AM] Connection to server got closed. Server will not be restarted._

**Comment by peternhale** [comment] 2023-08-30 13:54
@christopmj Sorry for the inconvenience. Please install either Java 11 or 17. Either will correct this error.

**Comment by christopmj** [comment] 2023-08-30 14:01
Works like a charm, thank you!

For anybody else, to save some time...
https://www.oracle.com/java/technologies/downloads/#jdk17-windows

I downloaded the x64 zip and dropped here:
C:\Program Files\Java\jdk-17.0.8

**Comment by shivamnaik98** [comment] 2023-09-17 21:00
Hello Team,
I have the same error:
_[{
	"resource": "/ApexLSP",
	"owner": "apex",
	"severity": 8,
	"message": "Error: {\"errno\":-4047,\"code\":\"EPIPE\",\"syscall\":\"write\"} undefined",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]_
_java.lang.UnsupportedClassVersionError: apex/jorje/lsp/ApexLanguageServerLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"_ 

And here's my setup:
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

have been using the same even before encountering the issue

Salesforcedx-vscode-apex › Java: Home set to C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot

In the previous comment, it was recommended to either install Java 11 or 17, so does it mean that JDK8 is no longer supported? If not, then how can I fix it. I also faced the [https://github.com/forcedotcom/cli/issues/2447](url) which has been now fixed after reinstalling the CLI. I am not sure if its this issue or the one I just referred to has caused the issue I am currently facing. Any help is appreciated!

**Comment by peternhale** [comment] 2023-09-18 11:32
@shivamnaik98 yes, upgrading to java 11 or 17 will resolve this error.

**Comment by shivamnaik98** [comment] 2023-09-19 17:27
> @shivamnaik98 yes, upgrading to java 11 or 17 will resolve this error.

It worked! Thanks! @peternhale @christopmj

**Comment by zanon1101** [comment] 2023-09-21 02:04
Keep getting the issue on random classes when trying to run tests / debug tests 

`11:59:10.964 [pool-1-thread-1] ERROR a.j.l.impl.debug.ApexDebuggerService - Error trying to get line breakpoint info
java.lang.IllegalStateException: Method already defined: clone ApiAddress ApiAddress.clone() from the type ApiAddress`

and

This seems to prevent Apex from recognising breakpoints in VSCode when running CMD+SHIFT+P -> Update checkpoints in Org or when clicking Run Test or Debug Test

`You don't have any checkpoints enabled. Enable a checkpoint and try again.
11:59:04.654 ended Debug Test(s)
Starting SFDX: Update Checkpoints in Org
SFDX: Update Checkpoints in Org, Step 1 of 6: Retrieving org information
SFDX: Update Checkpoints in Org, Step 2 of 6: Retrieving source and line information
There is no line breakpoint information for the current project
SFDX: Update Checkpoints in Org, Step 3 of 6: Setting typeRefs for checkpoints
SFDX: Update Checkpoints in Org, Step 4 of 6: Clearing existing checkpoints
SFDX: Update Checkpoints in Org, Step 5 of 6: Uploading checkpoints
SFDX: Update Checkpoints in Org, Step 6 of 6: Confirming successful checkpoint creation
Ending SFDX: Update Checkpoints in Org`

i've tried renaming and re deploying the problem classes, uninstalling apex and the Salesforce VSCode package, i've uninstalled Github copilot as that was potentially causing an issue previously.

**Comment by laurakolkerappfire** [comment] 2023-09-25 19:02
@zanon1101 Have you tried clearing the apex language server's index? See: https://github.com/forcedotcom/salesforcedx-vscode/issues/5087#issuecomment-1717366728

**Comment by zerkz** [comment] 2023-09-29 16:43
Hell yeah!

**Comment by alicedora** [comment] 2024-01-13 19:55
Anyome have found a solution for this? 

I followed the steps but I still see a error here:

Unable to activate the Apex Language Server - Local Java runtime ({   "salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home" }) is unsupported. Set the salesforcedx-vscode-apex.java.home VS Code setting to a runtime outside of the current project. For more information, go to [Set Your Java Version](https://developer.salesforce.com/tools/vscode/en/vscode-desktop/java-setup).

I'm on a Mac and I have Java 17 instaled, I followed the exact same steps as this documentation, but its not working for me: https://developer.salesforce.com/tools/vscode/en/vscode-desktop/java-setup

**Closed** 2024-01-26 23:12 UTC
Labels: area:apex, area:performance, announcement
