### ISSUE TITLE
Unusually high java process CPU usage

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/salesforcedx-vscode#968] opened 2018-09-18 14:54 UTC
### Summary

This seems to happen when using the extension to connect to a sandbox with a fairly big apex codebase (66% of total apex "space" used). But I'm not sure if it happens with smaller codebases.

I tried updating the plugin, but with no success. Not sure if it is out of pre-release already.

### Steps To Reproduce:

1. Create test class.
2. Retrieve it.
3. Deploy it.
4. Process should be now eating ~300% of CPU resources.

![screen shot 2018-09-18 at 11 53 03](https://user-images.githubusercontent.com/6956403/45696215-76796f80-bb39-11e8-8dae-f8f81c056a00.png)

![screen shot 2018-09-18 at 11 53 16](https://user-images.githubusercontent.com/6956403/45696213-74afac00-bb39-11e8-9ef7-8f46595a16bd.png)

### Expected result

Java process to chew up a huge amount of CPU time only when running commands, like on extension start up, but then go back to not using that much CPU time, leaving Chrome to be the huge villain here.

### Actual result

Java process chews up 200~400% of CPU % even when not being used, compared to the biggest monster I usually have running (Google Chrome) eating up to 40% of CPU %.

### Additional information

The screenshot below shows how much the java process is keeping the CPU busy in my Macbook. The chart starts with the extension on idle (just VSCode open with 4 or 5 classes, not running anything, no big deal).

Then I proceed to close VSCode and kill the java process through Activity Monitor, and the blue lines go down completely. Then I proceed to open VSCode again with my project, and the chart goes crazy once more. It goes up on start up, and when running some command (like running tests or retrieving/deploying things). And then goes back to normal.

![screen shot 2018-09-17 at 17 59 35](https://user-images.githubusercontent.com/6956403/45694681-2c42bf00-bb36-11e8-8f43-b269cf28c2a1.png)

The thing is that at some point, when a certain command is executed, the java process seems to get stuck and unable to kill some background thread/process/task. The extension still works, but slowing my machine down.

### Workaround

Close VSCode, kill the java process, and restart the editor.

**VS Code Version**:

1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64

**SFDX CLI Version**: "sfdx-cli/6.31.0-32aa4b4408 (darwin-x64) node-v8.9.4", with the plugin "salesforcedx 44.0.14 (pre-release)"

**OS and version**: macOS High Sierra 10.13.6 (17G65)

**Comment by steals** [comment] 2019-01-28 19:36
I have similar issue. In my project I have around ~300 apex classes, 150 objects etc. The code completion works very slow. After several attempt it stops working and CPU usage increases a lot.

In the Output pane for Apex Language Server I can see the following error:

   >  21:11:44.428 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Jan 28, 2019 9:11:46 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7272051 shorts which is 13MB not including array overhead. Removed 6615472 shorts which is 12MB not counting array overhead. Took 39 ms.
21:11:54.307 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
21:11:54.340 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
21:11:56.431 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types.
21:11:56.430 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 12004 ms.
Jan 28, 2019 9:12:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 11
21:12:10.614 [ForkJoinPool.commonPool-worker-3] ERROR a.j.l.i.c.CodeLensesProviderAggregator - Encountered an error with code lens provider apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider@2e570ded
java.lang.IllegalArgumentException: expected one element but was: <public with sharing class CaseTriggerHandler extends TriggerHandler {

...

    >
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:316)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
	at apex.jorje.lsp.api.utils.CodeUnits.getMatchingElement(CodeUnits.java:35)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.lambda$provideCodeLenses$0(ApexTestRunCodeLensesProvider.java:88)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.codeLens.ApexTestRunCodeLensesProvider.provideCodeLenses(ApexTestRunCodeLensesProvider.java:86)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.lambda$provideCodeLenses$0(CodeLensesProviderAggregator.java:58)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at apex.jorje.lsp.impl.codeLens.CodeLensesProviderAggregator.provideCodeLenses(CodeLensesProviderAggregator.java:56)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$codeLens$7(StandardTextDocumentService.java:186)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
21:12:58.748 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types took 62315 ms.
Jan 28, 2019 9:16:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation

>

**Comment by nkadis** [comment] 2019-01-29 13:02
Hi again,

I think I got some new info, maybe this could help in debugging the issue.

This happened to me when I cmd + click on an existing method I call from another class, which would normally take me to the declaration of that method. Instead, I get this:

`12:35:36.403 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Jan 29, 2019 12:35:37 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7272051 shorts which is 13MB not including array overhead. Removed 6615472 shorts which is 12MB not counting array overhead. Took 33 ms.
12:35:40.999 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
12:35:41.007 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
12:35:42.547 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types.
12:35:42.546 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 6144 ms.
12:36:43.280 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types took 60731 ms.
Jan 29, 2019 12:42:42 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 34
Jan 29, 2019 12:42:54 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 53
Jan 29, 2019 12:42:55 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 54
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 64
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 65
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 69
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 70
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 71
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 72
Jan 29, 2019 12:43:19 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 76`
And I assume this would go on until the laptop gets fried

Now to stop this, what I used to do was just force stop the java process that was using up all that cpu, which would basically make the extension stop working. But now, when I do that I get this error, which restarts the process and tries to burn my laptop again (until I restart vscode that is):

`[Info  - 12:43:48 PM] Connection to server got closed. Server will restart.
12:44:00.490 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Jan 29, 2019 12:44:00 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7272051 shorts which is 13MB not including array overhead. Removed 6615472 shorts which is 12MB not counting array overhead. Took 37 ms.
12:44:07.876 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types.
12:44:07.876 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 7386 ms.`

Anyway, from what I understand, this doesn't have to do with either the outline, or the autocomplete, or any other feature. My best guess is that there is an issue with the way you guy might be handling large files or something.

Hope this helps :)

**Comment by nkadis** [comment] 2019-01-29 15:37
Oh and something else I noticed, is that when this issue occurs and I close vs code, the java process doesn't terminate, only the parent process. If you have a look at the image attached, the parent process is null, but before closing vs code, that process linked the the parent vscode process. Shouldn't this terminate since it's a child process?

![screenshot 2019-01-29 at 15 32 03](https://user-images.githubusercontent.com/12812036/51919591-a8e68380-23db-11e9-9dfc-789044041ab5.png)

**Comment by Aviad211** [comment] 2019-01-30 09:42
I have similar issue. I'm working on a large sandbox.  Whenever I try to retrieve source from manifest with the package.xml - VSCode crushes and I'll get the "out of application memory" error.

sfdx-cli/6.50.0-9817aece8a (darwin-x64) node-v8.9.4
MacOS Mojave 10.14.2 / 16GB RAM

**Comment by mfrenchlitify** [comment] 2019-02-07 19:08
I am also seeing this

**Comment by paul-drozd-itechart** [comment] 2019-02-11 06:30
Having the same issue

**Comment by gswinarski** [comment] 2019-02-14 12:20
I have the same issue.

**Comment by msrivastav13** [comment] 2019-02-17 02:38
I can confirm that this is a huge issue for me . The memory consumption went as high as 2GB . I have an org with 100 apex classes atleast and my computer ran out of memory .If there is anything that we could help will be happy to help with .Thanks

**Comment by mtetlow** [comment] 2019-02-17 03:06
I also have this issue. I have seen the memory consumption as high as 4GB and generally I will wind up just killing the apex language server java process when I am writing apex in vscode :|

**Comment by msrivastav13** [comment] 2019-02-17 03:11
I would prefer not to have auto complete than consuming my computer memory .How do you kill the language server ?

**Comment by mtetlow** [comment] 2019-02-17 03:34
I used to be able to kill the java process in the os x activity monitor... but it looks like now it is restarting the java process. I swear this worked a few weeks ago

**Comment by steals** [comment] 2019-02-17 07:11
@msrivastav13 You can disable APEX LSP and all related staff by removing the  salesforcedx-vscode-apex.java.home setting from User settings in vscode

**Comment by praksb** [comment] 2019-02-17 07:38
We are actively working on the performance issue related to the Apex LSP and should have some fixes shortly. I'll update this thread once the fix is rolled out.

**Comment by daniil-rozin-itechart** [comment] 2019-02-21 10:35
Have the same issue.  CPU raise up to 330%

**Comment by praksb** [comment] 2019-02-22 21:13
We have made some improvements to Apex LSP performance in our latest extension update. Can you all please update to the latest Apex extension (v45.3.0) and let us know if you still have any performance issues? Please open a new github issue if you still see any perf related problems.

https://github.com/forcedotcom/salesforcedx-vscode/pull/1092

**Closed by praksb** 2019-02-22 21:13 UTC
Labels: bug

**Comment by Jody-CS** [comment] 2019-03-07 20:07
This issue is still occurring. Running Apex extension v45.3.0

**Comment by praksb** [comment] 2019-03-07 20:15
@Jody-CS Can you please update to version v45.5.0 and let us know if you still see this problem? We made some more recent fixes.

**Comment by matteobosc** [comment] 2019-05-23 13:48
This issue still occurs on the version v45.15.1. Java process almost at 3GB. JDK version jdk1.8.0_211, here my specs:

![image](https://user-images.githubusercontent.com/43987657/58257854-f3688300-7d71-11e9-9e5b-efa0b608ec0e.png)

**Comment by praksb** [comment] 2019-05-23 17:36
@matteobosc When you load your project after starting VS Code, the Apex LSP tries to index your apex classes and triggers. Currently, it does take up a good chunk of memory since it loads all the source files in memory. This could be an issue if your org is very large. We are working on making this experience better.

**Comment by matteobosc** [comment] 2019-05-24 22:39
Hi @praksb, yes, my org is pretty large, but the CPU time is stuck on that Java process even after hours I loaded VSC. Hope this will be improved, thanks in advance for your work!

**Comment by jxzhangxing** [comment] 2019-08-29 01:46
I also seeing this when working with a large sandbox. 
I try to set "autoCompile" to **_false_** in .forceCode/ but still not helping.

**Comment by SaoBiz** [comment] 2019-08-29 23:59
I am also running into this issue where the Java process is using a large chunk of memory.

![image](https://user-images.githubusercontent.com/5320153/63983926-43db4380-cb0c-11e9-84d8-bce808512348.png)

Just over 2.5GB of memory and I only have 200 Apex Classes which totals to 2.6MB of source files (whole project adds up to just over 40MB in size). I am not experiencing any user experience issues but this process shouldn't be using this much memory.

No errors logged in the Output window. Screenshot taken after loading project into VSCode with no Apex Classes open.
OS: Windows 10 1903

**Comment by renatoliveira** [comment] 2019-08-30 02:37
Which Java version are you using? I stopped seeing this issue a while ago, and it never happened again. I'm on OpenJDK 11 now, by the way.

**Comment by architchhikara** [comment] 2019-11-08 08:27
Seeing the Same Issue. I too have OpenJDK 11.

**Comment by magaiverf** [comment] 2020-06-05 21:53
Hi everyone, this week I've started to have this issue, I tried different version of Java JDK but unfortunately the issue happens in all them, could someone help me on it? Thanks

![image](https://user-images.githubusercontent.com/481480/83925445-8eee4b00-a75d-11ea-9151-5bdeaf3f4461.png)

**Comment by 402332509** [comment] 2020-08-04 04:16
any progress? This issue is still occurring.

**Comment by johnpanos** [comment] 2020-08-11 05:38
I also have a fairly small org that I'm working with, and I'm getting super high RAM and CPU usage as well. They seem to fluctuate, when one is low the other is high.

![image](https://user-images.githubusercontent.com/25217527/89860941-84836f80-db59-11ea-9524-e48b0b006585.png)

![image](https://user-images.githubusercontent.com/25217527/89861150-ee037e00-db59-11ea-8c94-b02ebc179570.png)

**Comment by Jody-CS** [comment] 2020-08-11 13:50
I am also seeing this old nasty bug. Mac 10.15.6 | VSCode 1.47.3 | Salesforce Ext Pack 49.4.0

**Comment by FiruzzZ** [comment] 2022-04-25 13:28
This started to happen a few weeks ago, and it takes more than 30' to finish the scanning, and I move between branches, it starts again, I had to disable  Java by Red Hat, to be able to use the PC at all, the Problems' tab shows "14k+" issues, the amount is not new, it was always like that, but now it is taking all the CPU
