### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RKoch364** [forcedotcom/salesforcedx-vscode#2482] opened 2020-09-03 15:26 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.8.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.48.2`
[salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5169561/salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt)

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\rob.koch\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kumquatlily** [comment] 2020-09-03 18:47
@RKoch364 same here.  Just had my other issue fixed updating to 49.8.0 #2463 and now this happens.
I have updated my Path and have disable my auto proxy and have also restarted my laptop.

**Comment by RKoch364** [comment] 2020-09-03 18:57
@kumquatlily  thank you, that is good to know. An earlier version of Salesforce CLI did not have this problem. I was in the same situation. For 2 days I kept getting the error 'Apex.Home' points to a missing folder. Finally fixed that error by adding the JDK_11.0.8 path to my environment variable.  But now "Authorize an Org' and 'Open Org' fails to run. Now with this extension there are problems.   What did you add to your Path?

**Comment by kumquatlily** [comment] 2020-09-03 19:04
@RKoch364  I just reviewed all comments with this issue from stackexchange and developer.salesforce.  
they said to add to Env path C:\Windows\system32 and C:\Program Files\Microsoft Visual Studio Code\bin and C:\Program Files\Salesforce\bin.   it does not work for me.  
![Annotation 2020d](https://user-images.githubusercontent.com/62514479/92156280-987b6380-eddd-11ea-9a5f-3fcdc07efa41.jpg)
![Annotation 2020e](https://user-images.githubusercontent.com/62514479/92156283-9b765400-eddd-11ea-91dd-18fe28650246.jpg)

**Comment by RKoch364** [comment] 2020-09-03 19:45
@kumquatlily Here are my environment variables

![image](https://user-images.githubusercontent.com/57114477/92160038-02066c80-edf4-11ea-9654-9354412c98d1.png)

**Comment by RKoch364** [comment] 2020-09-03 19:47
And the user variables...

![image](https://user-images.githubusercontent.com/57114477/92160268-5c9fc880-edf4-11ea-80a1-3b12076cb225.png)

**Comment by lcampos** [comment] 2020-09-04 01:36
Looks like we have two different conversations going on here. @RKoch364 is the originally reported apex performance still a problem for you ?

@kumquatlily have you seen the troubleshooting docs on [Set Salesforce CLI Path](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows) ?

If we still have two different issues I suggest we have separate GitHub issues or it will be very difficult for us to help solve them.

**Comment by kumquatlily** [comment] 2020-09-05 00:38
@lcampos yes I have.  I don't believe is separate issue.  I might have confused with the other issue # as the other issue is resolved but as Rkoch described, I am having the same problem with the new extension 49.8.0.

**Comment by RKoch364** [comment] 2020-09-05 02:42
The common issue is problems with the current extension, it includes that
huge batch of code. No wonder it puts a strain on the CPU.

**Comment by gyadav4** [comment] 2020-09-07 06:17
I'm also facing this, also tried to restart several times. Everytime it is having same issue of not loading "Took very long time"
![image](https://user-images.githubusercontent.com/29378942/92354362-caebd000-f0ff-11ea-91a5-40acee2478ae.png)

**Comment by shashankSFDC** [comment] 2020-09-07 13:05
@gyadav4 I am facing the same issue 'Salesforce CLI Integration'.

**Comment by RKoch364** [comment] 2020-09-07 15:29
There was an earlier version of CLI that did not cause these problems. It
was in the 45 range, maybe 45.2?

**Comment by smaddox-sf** [comment] 2020-09-09 16:58
I believe this issue is a mix of two issues:

- Extensions are taking a long time to load - Duplicate of #2295
- High CPU for Apex extension - Duplicate of #2410 

Feel free to add feedback to those existing open issues.  (Please also feel free to open a new issue if I parsed this conversation incorrectly.  As noted above, let's stick to one problem per issue so we can effectively help)

**Closed by smaddox-sf** 2020-09-09 16:58 UTC
Labels: status:duplicate
