### ISSUE TITLE
@jean-feng would you mind opening a new issue. Thank you.

### ISSUE THREAD

**Issue by jean-feng** [forcedotcom/salesforcedx-vscode#5870] opened 2024-09-24 15:17 UTC
I got a new C driver, installed new Windows:
Edition Windows 10 Enterprise
Version 22H2
Installed on ‎9/‎6/‎2024
OS build 19045.4894
Experience Windows Feature Experience Pack 1000.19060.1000.0

Then I installed sf @salesforce/cli/2.58.7 win32-x64 node-v20.17.0

Visual Studio Code
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Once I installed Salesforce Extension Pack
v61.12.0

I got The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
er = new Error(er)
^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
at error (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
at strictFail (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
at closeTag (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
at SAXParser.write (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
at exports.Parser.Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
at Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
at c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
at new Promise ()
at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
at Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info - 10:25:57 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
er = new Error(er)
^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
at error (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
at strictFail (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
at closeTag (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
at SAXParser.write (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
at exports.Parser.Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
at Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
at c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
at new Promise ()
at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
at Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info - 10:26:09 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
er = new Error(er)
^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
at error (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
at strictFail (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
at closeTag (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
at SAXParser.write (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
at exports.Parser.Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
at Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
at c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
at new Promise ()
at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
at Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info - 10:26:21 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
er = new Error(er)
^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
at error (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
at strictFail (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
at closeTag (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
at SAXParser.write (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
at exports.Parser.Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
at Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
at c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
at new Promise ()
at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
at Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info - 10:26:33 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
er = new Error(er)
^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
at error (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
at strictFail (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
at closeTag (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
at SAXParser.write (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
at exports.Parser.Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
at Parser.parseString (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
at c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
at new Promise ()
at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
at Parser.parseStringPromise (c:\Users\yfeng.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Error - 10:26:44 AM] Connection to server got closed. Server will not be restarted.

**Comment by jean-feng** [comment] 2024-09-24 15:30
All the info is in desctiption, but do it again here:

**Salesforce Extension Version in VS Code:**

**Salesforce CLI Version:**
@salesforce/cli/2.58.7 win32-x64 node-v20.17.0
OS and version:
Edition Windows 10 Enterprise
Version 22H2
Installed on ‎9/‎6/‎2024
OS build 19045.4894
Experience Windows Feature Experience Pack 1000.19060.1000.0

**VS Code version:**
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Most recent version of the extensions where this was working:**
Salesforce Extension Pack
v61.12.0

**Comment by peternhale** [comment] 2024-09-24 15:36
Duplicate of #5869

**Closed** 2024-09-24 15:35 UTC
Labels: missing required information
