### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bschwas** [forcedotcom/salesforcedx-vscode#2648] opened 2020-10-20 15:37 UTC
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5409791/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.1.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\BRETT~1.SCH\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-10-22 16:19
I believe this is a duplicate of [2410](https://github.com/forcedotcom/salesforcedx-vscode/issues/2410#issuecomment-685023233).  Please check out that issue and the workaround I posted.  I'd be interested to know if that workaround helped.

**Closed by smaddox-sf** 2020-10-22 16:19 UTC
