### ISSUE TITLE
Cannot launch apex debugger

### ISSUE THREAD

**Issue by Siraris** [forcedotcom/salesforcedx-vscode#2160] opened 2020-05-01 17:03 UTC
### Summary

I am having a similar issue to https://github.com/forcedotcom/salesforcedx-vscode/issues/722 which seems to have been resolved in 2018... when I try to launch the apex debugger in VS code 1.44.2, it just pops this: 

![image](https://user-images.githubusercontent.com/280804/80823960-25e64700-8ba3-11ea-8ded-3e224e2762e7.png)

and never actually executes.

### Steps To Reproduce:

1.  Write an APEX class
2. Try to click the play button on Launch Apex Debugger

### Expected result

The debugger would run

### Actual result

I get a blank popup that seems to indicate an error, with a button to open the launch config.

**Comment by lcampos** [comment] 2020-05-05 23:16
Thanks for opening this issue @Siraris . I've been able to replicate this screen by trying to run Apex Interactive Debugger with a user that does not have the `Debug Apex` permission. Does adding that permission to your user get you past the blank error ?

We'll look into releasing a fix so the error screen actually has a message on it.

**Comment by mattaGIT** [comment] 2020-05-08 19:03
I have this exact same issue. It doesn't matter if the permission set is added or not to the user.

**Comment by streco** [comment] 2020-05-09 21:50
I have also it this same issue, regardless of if the permission set is added or not.

**Comment by Siraris** [comment] 2020-05-14 00:18
@lcampos Sorry I honestly didn't see your initial response (strange).  I am checking with our admin and I'll get back tomorrow with an answer.  Not too familiar with how SF permissions work.

**Comment by Siraris** [comment] 2020-05-14 18:06
@lcampos Our sys admin says he doesn't know of a permission called Debug Apex.  He says I'm a sysadmin on our sandbox.  Do you know exactly what he needs to do?

**Comment by Siraris** [comment] 2020-05-15 19:02
@lcampos Question, can I ONLY debug using VScode in scratch orgs?  Or can I debug in the sandbox too?

**Comment by jerhewet** [comment] 2020-05-22 14:20
Same issue for me as well.  Is there a "known good" version of all these tools (read as: specific versions of Visual Studio Code and versions of everything deployed as part of the Salesforce Extension Pack) that I can install so I can start getting some work done?  Failing that, are there specific, documented (and up-to-date documentation) guides that will help me get all of this stuff working?

Right now I have to do all my prototyping in my web browser because there are so many issues with the latest versions of SFDX that all seem to be related to configuration.  If you want me to supply specifics just let me know what (and HOW!) to turn on tracing and logging options for SFDX and I'll supply whatever logfiles are generated.

**Comment by permrevolution** [comment] 2020-05-23 13:55
Note as of writing this message, I updated all salesforce extensions in vsCode as well as SFDX CLI.

1. I also cannot find the step 9 setting in my scratch org: 9. Enable Debug Apex. The other permissions that Debug Apex requires are added automatically.

https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger/

2. I figure it's already enabled, but what can I do?

3. I get the same error as above. 

In the debug console I see:
Connected to Streaming API channel /systemTopic/ApexDebuggerSystemEvent.
Connected to Streaming API channel /systemTopic/ApexDebuggerEvent.

Then it fails with this blank error.

![image](https://user-images.githubusercontent.com/65817991/82732466-41380400-9cc2-11ea-8c6d-4864f207f077.png)

**Comment by mingjiefeng** [comment] 2020-05-23 14:15
I got the exact same error and symptom as permrevolution's

**Comment by lcampos** [comment] 2020-05-26 17:19
hi, there are several questions so I'll try to address all of them below.

> I have this exact same issue. It doesn't matter if the permission set is added to the user or if it is not.

This could be caused by the org having reached the limit of concurrent streaming api connections. You can run `SFDX: Stop Apex Debugger Session` and retry running the debugger.

> Our sys admin says he doesn't know of a permission called Debug Apex

This is a permission that gets enabled after purchasing a license. If you're org does not have it you would have to talk to your Account Executive. In the meantime you can use the Apex Replay Debugger which does not require additional licenses.

> can I ONLY debug using VScode in scratch orgs? Or can I debug in the sandbox too?

The Apex Interactive debugger can be used only in scratch orgs and sandboxes. The Apex Replay Debugger can be used in any org that generates Apex Debug logs.

> are there specific, documented (and up-to-date documentation) guides that will help me get all of this stuff working?

You can go to our doc site https://developer.salesforce.com/tools/vscode/ or go through the following trailheads https://trailhead.salesforce.com/content/learn/projects/quickstart-vscode-salesforce, https://trailhead.salesforce.com/en/content/learn/projects/quick-start-lightning-web-components/set-up-visual-studio-code. I'm sure there's more content but this should be a good start.

> Is there a "known good" version of all these tools ?

Yes, the latest version in the Microsoft marketplace. As with any open source software, if you run into bugs or feature gaps we ask you to open a github issue and we'll work with you to get it addressed.

> STOP CLOSING BUGS when it's pretty obvious there are so many developers that have the same reported issue.

We have automation that helps us with the management of the repo. There are situations in which we don't get enough details in an issue for us to work on it and if the author does not reply with additional details it will get closed. As you can see, if the author does reply or the issue is active we do re-open it if it was closed by the automation.

**Comment by lcampos** [comment] 2020-05-26 17:27
Specific to the issue, we have a fix that is currently under review and if everything goes well it will be released later this week. I've attached a zip file with the vsix file that contains the fix if you want to try out while we roll out the fix.
Again, thanks for providing feedback and sorry for the inconvenience this might've caused to your workflow.

[salesforcedx-vscode-apex-debugger-48.17.0.vsix.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/4683921/salesforcedx-vscode-apex-debugger-48.17.0.vsix.zip)

**Comment by Siraris** [comment] 2020-05-27 20:37
@lcampos Thanks for the response to this, and sorry some people are giving you a hard time.

**Comment by lcampos** [comment] 2020-05-29 17:00
Closing this since the fix was released as part of version 48.18.0. Thanks for providing feedback and sorry for the inconvenience this bug might've caused.

**Closed by lcampos** 2020-05-29 17:00 UTC
