### ISSUE TITLE
Apex Interactive Debugger not starting - says all licenses in use when one should be available

### ISSUE THREAD

**Issue by ApraChris** [forcedotcom/salesforcedx-vscode#2737] opened 2020-11-16 07:37 UTC
Hi there,

unfortunately I have an issue with the Apex debugger.
I cannot start the Apex debugger session.

Basically I have the same behavior as in issues #2666 and #1570.
I DO have a license (see below)

This is from my Dev Hub:

![image](https://user-images.githubusercontent.com/18393568/99061948-81f24500-25a2-11eb-8e41-ff45f0d88949.png)

In my scratch org where I've set up debugging it looks like this:

![image](https://user-images.githubusercontent.com/18393568/99061994-95051500-25a2-11eb-90ee-f0ec9f6a5ae0.png)

I get the exact same behavior as @deb761 mentions in #1570 .

My console shows:
```
Connected to Streaming API channel /systemTopic/ApexDebuggerSystemEvent.
Connected to Streaming API channel /systemTopic/ApexDebuggerEvent.
```

Afterwards I get the popup message telling me: "You exceeded the number of licensed number of debugging sessions. Please end other sessions or purchase more".

VS Code is 1.51
sfdx-cli/7.80.0-b979aae708 win32-x64 node-v12.18.3
OS is Win10 Pro Version 1909 build 18363.1198

Let me know if you need any more info to figure this out.

Cheers
Chris

**Comment by smaddox-sf** [comment] 2020-11-16 17:15
HI @ApraChris - Can you confirm which debugger you are seeking to use?  The [Interactive Debugger](https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger) or the [Replay Debugger](https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger)?

**Comment by ApraChris** [comment] 2020-11-17 07:21
Hi @smaddox-sf , the interactive debugger.

**Comment by AnanyaJha** [comment] 2020-11-19 01:16
Hi @ApraChris as mentioned [here](https://github.com/forcedotcom/salesforcedx-vscode/issues/1570#issuecomment-525470988), it's possible to run into this issue if there are enough users using the interactive debugger at the same time so all the available sessions get used. Is it possible that there are multiple users active at the same time? If not, can you try running the command `SFDX: Stop Debugger Session` and trying again?

**Comment by ApraChris** [comment] 2020-11-19 07:21
Hi @AnanyaJha , thanks for getting back to me. I'm the only person trying to get this to work.
However I've tried this but I'm still getting the same result.

`SFDX: Stop Debugger Session`

```
08:18:35.941 sfdx force:data:soql:query --query SELECT Id FROM ApexDebuggerSession WHERE Status = 'Active' LIMIT 1 --usetoolingapi --json --loglevel fatal
{
  "status": 0,
  "result": {
    "size": 0,
    "totalSize": 0,
    "done": true,
    "queryLocator": null,
    "entityTypeName": null,
    "records": []
  }
}
08:18:41.114 sfdx force:data:soql:query --query SELECT Id FROM ApexDebuggerSession WHERE Status = 'Active' LIMIT 1 --usetoolingapi --json --loglevel fatal
 ended with exit code 0
```

Afterwards I've tried to start an interactive debugging session but still get
```
Connected to Streaming API channel /systemTopic/ApexDebuggerSystemEvent.
Connected to Streaming API channel /systemTopic/ApexDebuggerEvent.
```

And this popup window.

```
[Window Title]
Visual Studio Code
[Content]
You exceeded your licensed number of debugging sessions. Please end other sessions or purchase more.
[Open launch.json] [Cancel]
```

FYI my launch.json looks like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Apex Debugger",
            "type": "apex",
            "request": "launch",
            "userIdFilter": [],
            "requestTypeFilter": [],
            "entryPointFilter": "",
            "sfdxProject": "c:\\Users\\chris\\Documents\\VS_Code\\Aduno_DX"
        }
    ]
}
```

**Comment by sfsholden** [comment] 2020-11-20 17:30
@ApraChris In referring to this [interactive-debugger](https://developer.salesforce.com/tools/vscode/en/apex/interactive-debugger) documentation, would you please confirm the following for me?

`Set Up Apex Debugger` Steps...

1-3: Was this scratch org created with the project scratch def that contained "features": "DebugApex"? (From your screen shots above I believe these steps were covered, but would like to make sure)

4: Has the Org Admin user been assigned the permission 'Debug Apex'?

**Comment by ApraChris** [comment] 2020-11-20 20:28
Hi @sfsholden ,

Yes, i can confirm all 4.

![image](https://user-images.githubusercontent.com/18393568/99846757-409bff80-2b77-11eb-9493-71618e04d8ca.png)

**Comment by sfsholden** [comment] 2020-11-20 21:25
@ApraChris Thank you for confirming. Some more sanity check questions:

- Is this dev hub org an LMO org with the LMA (License Management App)? 

- For your launch configuration, do you see any difference if you update `"sfdxProject": "c:\\Users\\chris\\Documents\\VS_Code\\xxx"` to `"sfdxProject": "${workspaceRoot}"`?


Also, I want to make sure that you are not blocked while we determine the root cause of this issue. I would recommend looking into the [replay debugger](https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger). This tool is less intensive and resource demanding on your org (the interactive debugger holds sessions while you are debugging), while the replay debugger does not.

Here are some additional resources for the Replay Debugger if you'd like more info:

- https://www.youtube.com/watch?v=RD1n2W3wFEA (10:00 to jump to the Replay Debugger)

- https://developer.salesforce.com/tools/vscode/en/apex/replay-debugger

**Comment by ApraChris** [comment] 2020-11-20 21:39
Hi @sfsholden, thanks for you reply.

- Regarding item 1: Yes, it's an LMO with License Management App installed

- Regarding item 2: No, that does not change anything. The behavior is exactly the same unfortunately.

Thanks for the info on the replay debugger.

**Comment by sfsholden** [comment] 2020-11-20 22:15
@ApraChris Okay, this is making more sense.

The license screen shot from above is more than likely the free license provided to LMOs for usage of the ISV Debugger. That license can only be used from within a Subscriber Org through the use of the ISV Debugger. It cannot be used to debug the LMO org itself with the Interactive Debugger. Let me know if this license was in fact purchased and is not the default provided to LMOs.

This sounds like the Replay Debugger really is the better option. The Replay Debugger is much easier to setup and use - if you hit any more roadblocks, please don't hesitate to reach out.

**Comment by ApraChris** [comment] 2020-11-23 07:38
Hi @sfsholden 

> Let me know if this license was in fact purchased and is not the default provided to LMOs.

No it was not purchased.

> That license can only be used from within a Subscriber Org through the use of the ISV Debugger.

Alright, sorry for this issue then - I misunderstood the documentation here.
I thought it worked the other way around (I can only debug subscriber orgs, when I have a ISV Debugger license, but can debug my own (local) code regardless of license type).

Thanks for making this clear

**Comment by sfsholden** [comment] 2020-11-24 16:20
@ApraChris Thank you for bringing this to our attention and apologies for the confusion. We'll be updating the docs in #2760

I'm closing out this issue as resolved.

**Comment by sfsholden** [comment] 2020-12-10 18:26
Reopening to associate bug for tracking the update of this error message. This needs to be more informative to a customer without forcing them to refer to documentation.

**Closed** 2020-12-10 18:27 UTC
Labels: area:debugger, status:needs eng review, type:bug
