### ISSUE TITLE
after hit the Break point if press F10 request had stopped message appear instead Debugger move to next line of code

### ISSUE THREAD

**Issue by kristualdandamudi** [forcedotcom/salesforcedx-vscode#315] opened 2018-02-21 03:11 UTC
### Summary
after hit the Break point if i press F10, request had stopped message appear instead of Debugger move to next line of code at both places proxy firewall and out of the firewall(home network)

### Steps To Reproduce:
1.Put the break point at line 12, after click the start debugging button(green play), 
2.Apex debug session started,
3.in browser enter my apex controller path
4.hit the break point ,  after i press F10, nothing happens

### Expected result
debugger cursor should move to next line and Request Should be Resumed.

### Actual result
nothinh happens , request stopped message appears in debug console.
![after f10 press break point stopped](https://user-images.githubusercontent.com/28848782/36461285-9c92f168-168a-11e8-9a7b-4a2210425c79.JPG)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.20.1

**SFDX CLI Version**:
sfdx-cli/6.3.0-7600a88 (windows-x64) node-v8.9.4

**OS and version**:
Windows 7 enterprise SP1

**Comment by vazexqi** [comment] 2018-03-20 04:41
@kristualdandamudi - From your screenshot, this looks similar to #304. I'm going to close this as dupe of that. Feel free to reopen if that is not so.

**Closed by vazexqi** 2018-03-20 04:41 UTC
