### ISSUE TITLE
push or deploy on save inop

### ISSUE THREAD

**Issue by Dre2300** [forcedotcom/salesforcedx-vscode#3659] opened 2021-11-18 18:23 UTC
The Salesforcedx-vscode-core › Push-or-deploy-on-save Setting is giving me the "File or Folder not found" error every time I try to save my source code.  However, I do not receive an error when pushing my source code to my org by right-clicking the class and clicking "sfdx: deploy source to org".

**Comment by rcoringrato-sfdc** [comment] 2021-11-18 18:31
Duplicate of #3655

**Comment by randi274** [comment] 2021-11-18 21:33
Thanks for logging this! Closing as a dupe.

**Closed by randi274** 2021-11-18 21:33 UTC
Labels: status:duplicate
