### ISSUE TITLE
Cannot deploy namespaced Apex classes in unlocked packages to org

### ISSUE THREAD

**Issue by Banuson** [forcedotcom/salesforcedx-vscode#5637] opened 2024-06-12 08:41 UTC
Hello,

I want to update a class from an unlocked packaged installed in my org with namespace MyPackage.

I am able to retrieve it, but if I want to change anything (adding a comment for example) in that file I am not able to deploy. 
I want to deploy using metadata API. The apex class file is : classes/MyPackage__myClass.cls with MyPackage namespace. 
public class myClass {
        // class content
}
But when I try to deploy I have this error message:
File name mismatch with class name: myClass

Another issue is that in Org Browser:
files shows with doubled namespace for example:
MyPackage__MyPackage__myClass.cls
Retrieve using the org browser throws this error:
Entity of type 'ApexClass' named 'MyPackage__MyPackage__myClass' cannot be found

Currently I can only edit the class from Dev Console or Setup>Apex Class.

Salesforce Extension Version in VS Code: v60.15.0
Salesforce CLI Version: @salesforce/cli/2.42.6 win32-x64 node-v20.12.2
OS and version: Microsoft Windows 11 Enterprise 10.0.22621 Build 22621
VS Code version: Version: 1.90.0
Most recent version of the extensions where this was working: N/A

**Comment by daphne-sfdc** [comment] 2024-06-12 15:00
Hi @Banuson, We're aware of the issue with the duplicate namespaces in the org browser, as it was previously filed here: https://github.com/forcedotcom/salesforcedx-vscode/issues/5598.  There is a workaround to retrieve using the manifest instead.

Let me try to replicate your issue with editing and deploying the namespaced Apex class in the unlocked package.  I'll let you know if I can replicate it.

**Comment by Banuson** [comment] 2024-06-13 10:36
Hi @daphne-sfdc,

Just checking in to see if you had a chance to look into the issue with editing and deploying the namespaced Apex Class in the unlocked package.
Thanks for your help!

**Comment by daphne-sfdc** [comment] 2024-06-13 13:33
Hi @Banuson, Sorry for the delay.  My team was working to resolve an urgent issue yesterday so I haven't gotten the chance to check this yet.  I'll get back to you with my findings later today.

**Comment by daphne-sfdc** [comment] 2024-06-13 16:37
@Banuson Looks like you're correct that this is a bug - I was able to reproduce this issue using a new unlocked package that I created and installed into an empty scratch org.  What's particularly interesting is that I'm unable to deploy namespaced Apex classes using the CLI either - we'll investigate our shared libraries to see what's going on.
```
daphne.yang@daphney-ltmkef9 classes % sf project deploy start --source-dir GlobalClass0000.cls
Error (1): GlobalClass0000.cls: File or folder not found

daphne.yang@daphney-ltmkef9 classes % sf project deploy start --source-dir svcideebot__GlobalClass0000.cls
Error (1): force-app: File or folder not found
```

Thanks for filing this issue, and sorry for the inconvenience.

**Comment by AndreiBanu-Diconium** [comment] 2024-06-13 17:49
@daphne-sfdc  Thanks for confirming the issue and looking into it.  Could you please provide an estimated timeline for a fix?

**Comment by Banuson** [comment] 2024-06-13 17:50
@daphne-sfdc Thanks for confirming the issue and looking into it. Could you please provide an estimated timeline for a fix?

**Comment by Banuson** [comment] 2024-06-28 09:00
Hello @daphne-sfdc,

Are there any updates regarding this issue?

Thank you!

**Comment by daphne-sfdc** [comment] 2024-07-01 17:57
Hi @Banuson, Our team is still actively investigating this issue.  We'll update you when we find anything important regarding this use case.  Thank you.

**Comment by daphne-sfdc** [comment] 2024-07-30 18:59
Hi @Banuson,

While investigating this issue, our team found that the error that you're seeing happens both when deploying using VSCode/CLI and Workbench.  Because it happens in Workbench, which directly calls the metadata API during the deploy, our team has determined that this issue is on the server side, owned by the Metadata API Team.

The Metadata API Team only receives issues via the official Salesforce support channels.  If you would like to connect with them directly on this issue, please file a ticket in Salesforce Help and an investigation will be routed to them.

As this issue is not owned by our team, we'll be closing this issue.

**Closed by daphne-sfdc** 2024-07-30 18:59 UTC
Labels: type:bug, area:namespaces, validated

**Comment by diyer** [comment] 2024-08-08 20:14
@Banuson this is the work item that support can use to file a case on for this issue W-16395605
