### ISSUE TITLE
No longer reports deployment errors to VSCode

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/salesforcedx-vscode#3494] opened 2021-08-12 04:15 UTC
This issue seems to come up re-occuringly with sfdx updates. If a file fails to deploy, the extension reports:

```
SFDX: Deploy Source to Org failed to run
```

But there's no output in the Salesforce CLI panel with information. You have to manually run the sfdx command on a terminal to see the deployment errors.

This issue has happened before, seems to be another breaking change from the recent update.

**Comment by smaddox-sf** [comment] 2021-08-12 19:12
Duplicate of #3488.  Closing this issue to keep the conversation consolidated.  Please follow that issue and add any other comments there.  Thank you!

**Closed by smaddox-sf** 2021-08-12 19:12 UTC

**Comment by AndrewRayCode** [comment] 2021-08-12 19:57
hi @smaddox-sf thanks for jumping in better late than never, can you please consider forcing a rollback, there are so many issues, this release needs to be redone, i've lost so much time contributing to the issues trying to help, seems to fall on indifferent team
