### ISSUE TITLE
Allow for syntax highlighting and better code completion for anonymous apex

### ISSUE THREAD

**Issue by arodriguez-cvent** [forcedotcom/salesforcedx-vscode#739] opened 2018-11-09 21:08 UTC
**The issue I am facing:**

Writing anonymous Apex in the VS Code tempApex.input file does not allow for code completion from the Salesforce Language Support extension. Also there is no syntax highlighting.

**The solution I would like:**

In the file that is used for execution when the "SFDX: Execute Anonymous Apex from Editor Contents" command is selected, tempApex.input, allow for syntax highlighting and code completion. Ensure that editing this file enables support for the features provided by the Salesforce Language Support extension. 

**Describe alternatives you've considered**

Compile an Apex method to be executed from the tempApex.input file so that code can be written in a .cls file that supports code completion and syntax highlighting.

**Additional context**

![image](https://user-images.githubusercontent.com/44903655/48288431-1668c080-e43a-11e8-81ae-2e30b57d641e.png)

**Comment by lcampos** [comment] 2018-11-09 22:51
Hi @arodriguez-cvent thanks for opening this issue. The apex language server currently only supports `.cls` & `.trigger` file extensions. In the meantime, you can get syntax highlighting and some basic code completion if you use `.apex` file extension instead of `.input`.

**Comment by arodriguez-cvent** [comment] 2018-11-09 23:10
thanks @lcampos  I did try changing the extension to .cls however the syntax and highlighting that results in the tempApex file as a result of doing this is not much better than having no syntax whatsoever:

![image](https://user-images.githubusercontent.com/44903655/48292938-97c84f00-e44a-11e8-834e-c024d345d5ed.png)

**Comment by ntotten** [comment] 2018-11-12 13:04
Duplicate of #441

**Closed by ntotten** 2018-11-12 13:04 UTC
Labels: feature
