### ISSUE TITLE
Extension issue - Apex 52.1.0 Unresponsive

### ISSUE THREAD

**Issue by Robanero** [forcedotcom/salesforcedx-vscode#3343] opened 2021-06-21 13:25 UTC
The Apex extension is not running and is listed as unresponsive.

- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.1.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 3048,
		"activateCallTime": 5,
		"activateResolvedTime": 8296,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Robanero** [comment] 2021-06-21 13:30
CPU profile file:  
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6686929/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by smaddox-sf** [comment] 2021-06-23 14:08
Duplicate of #2410

**Closed by smaddox-sf** 2021-06-23 14:08 UTC
