### ISSUE TITLE
Give user feedback that the SFDX: Set a Default Org command is running when the default org button is clicked

### ISSUE THREAD

**Issue by allileong** [forcedotcom/salesforcedx-vscode#1007] opened 2019-02-01 22:29 UTC
**Is your feature request related to a problem? Please describe.**
There is a noticeable lag between the time when the default org button is clicked, and the quick-pick dropdown appears with the list of available orgs. In the time that it takes for the dropdown to appear, the user might be confused as to why clicking on the button had no visible effect and she may click on the org button a few more times. When the dropdown finally appears, in the case where she decides to select `SFDX: Authorize an Org` from the dropdown, she will have to go through a few more dropdown menus to set values such as the `sfdcLoginUrl`, org alias, etc. However, because the multiple clicks on the org button have queued up multiple invocations of the `SFDX: Set a Default Org` command, she is interrupted in her authorization flow by the re-appearance of the org list dropdown. 

**Describe the solution you'd like**
1. Block further invocations of `SFDX: Set a Default Org` when the command is already in progress. 
1. Change the icon of the default org button from the plug icon to a spinner icon when the command is in progress so that the user knows that the button press was heard and work is being done in the background. Otherwise, it is easy to mistakenly believe that the button is broken and nothing is happening. 

**Describe alternatives you've considered**
Alternatively, we could have another progress notification appear in the status bar at the bottom of the vscode window when the `SFDX: Set a Default Org` command is in progress similar to the progress notification that appears when an SObject refresh is in progress.

**Comment by praksb** [comment] 2019-02-01 22:34
I see the lag that you mentioned. Any idea what is causing the lag? Is it just all due to VS Code or are we doing some work before showing the UI that is causing the lag?

**Comment by lcampos** [comment] 2019-02-02 00:49
@allileong @praksb based on what I've seen, the lag is caused by us running `sfdx force:config:set`to get some of the info needed to populate the quick-pick dropdown.  On top of preventing multiple executions of that command, we should also look at using the `@salesforce/core` module to get the info we need for these feature.

**Comment by lcampos** [comment] 2019-04-05 23:49
Closing this since it was addressed in release `45.7.0`

**Closed by lcampos** 2019-04-05 23:49 UTC
Labels: feature
