### ISSUE TITLE
Turn on apex debug log creating trace flag with name set to random user

### ISSUE THREAD

**Issue by msbagul** [forcedotcom/salesforcedx-vscode#1285] opened 2019-04-25 06:05 UTC
### Summary
Using VSCode having CLI extension installed, when I turn on apex debug log, it is creating trace flag with name set to any random user and not the one with which the org was authenticated. The "Requested By" column does properly show the org authenticated user. Due to this issue, it doesn't generate the log for the authenticated user and hence get debug logs fetches logs which are not of authenticated user.

### Steps To Reproduce:
1. Setup a Salesforce VS Code project and install Salesforce Extension for VS Code.
2. Authenticate to the org using my user name.
3. From the command palette, select SFDX: Turn On Apex Debug Log for Replay Debugger.
4. In the Salesforce instance, navigate to debug logs to see if trace flags are generated or not.
5. The trace flag record gets created where "Name" column doesn't show my user name but shows someone else user name.
6. Perform some action in the Salesforce instance to generate logs.
7. Turn off Apex Replay Debugger from VS Code
8. Get the logs from VS Code

### Expected result
The logs should be generated for authenticated user and also able to download using Get log command.

### Actual result
The logs fetched by Get log command are the logs generated for other users in the instance.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.33.1

**SFDX CLI Version**:
sfdx-cli/7.4.0-99233fd3af win32-x64 node-v10.15.3

**OS and version**:
Windows 10 Enterprise 64 bit

**Comment by lcampos** [comment] 2019-05-06 16:52
Thanks for reporting this @msbagul. This is the same as reported in issue #1280 and the fix is in PR #1315 .

The root cause was that the replay debugger tries to re-use an existing TraceFlag if there is one available. In doing so, we did not filter those results to the specific user and in some scenarios was causing the behavior you reported.

**Comment by msbagul** [comment] 2019-05-06 17:39
Hi there,

Thanks for looking into this. Since I am new to this issue reporting platform, could you please let me know when this fix will be available for me to update the CLI on my machine.

Thanks

Mahendra

**Comment by lcampos** [comment] 2019-05-06 17:51
Hi @msbagul, the fix is a change to the salesforce extensions for vscode not the cli. Once I merge PR #1315 it'll go out as part of one of our weekly releases. I'm working on including it on this Thursday's release. Once the release is publicly available I'll update this issue with the release version in which the fix is available (e.g. 45.x.0).

**Comment by msbagul** [comment] 2019-05-06 17:56
Perfect. Thanks.

**Comment by lcampos** [comment] 2019-05-09 16:03
I'm closing this since the fix is out as part of version `45.14.0` of the extensions. Thanks for opening the issue and being patient while we fixed it.

**Closed by lcampos** 2019-05-09 16:03 UTC
Labels: area:quality, lang:apex, type:bug
