### ISSUE TITLE
SFDX commands keeps on running without ending execution

### ISSUE THREAD

**Issue by rach12** [forcedotcom/salesforcedx-vscode#4710] opened 2023-02-23 22:31 UTC
Issue Type: <b>Bug</b>

Authorised an org successfully.
tried to open the org. Worked perfectly.
Tried to deploy a single file to org. Running infinately. No error. No end
retreive/ diff all other commands also seem to run infinately. 

Tried to restart the system multiple times. Reinstall vs code..cli and extensions..nothing seems to work.
OS: Macos

Extension version: 57.2.1
VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|32.00GB (7.01GB free)|
|Process Argv|--crash-reporter-id ac4244b8-c280-476c-90bd-3c3dc2b8396f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30664135
pythonb192cf:30669361

```

</details>

**Comment by randi274** [comment] 2023-02-24 00:16
Hey @rach12 - a few questions to get started:
- what kind of org are you working with? Dev/scratch/sandbox, etc?
- Are you working with a new project, or a larger existing project?
- Are you able to deploy a file to an org using the CLI [directly](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_deploy)?

**Comment by rach12** [comment] 2023-02-24 13:54
I am working on sandbox. I'm working on an existing large project. 
Thanks for mentioning . I was able to deploy the files to org using commands which works for now.
 However i'm still not able to deploy by right clicking a file I want and using SFDX:Deploy Source to Org

**Comment by gbockus-sf** [comment] 2023-02-24 23:00
This sounds like a dupe of https://github.com/forcedotcom/salesforcedx-vscode/issues/4674.  Could you please follow that issue @rach12? Thanks!

**Closed by gbockus-sf** 2023-02-24 23:00 UTC
Labels: more information required, area:usability
