### ISSUE TITLE
Retrieve Source From Org Not Retrieving Full LWC Package

### ISSUE THREAD

**Issue by Jwok90** [forcedotcom/salesforcedx-vscode#3079] opened 2021-03-19 20:39 UTC
### Summary

The `Retrieve Source From Org` functionality is not working correctly. Instead of displaying the HTML, JavaScript, and XML files as normal ([picture](https://i.stack.imgur.com/GA9Tx.png)), it is instead separating each file into its own folder, and is not including the XML file ([picture](https://i.stack.imgur.com/Tcjlb.png)). This also results in errors when attempting to deploy changes to the files to the org.

### Steps To Reproduce:

1. Go to the Org Browser section of VS Code
1. Find a Lightning Web Component and click the "Retrieve Source From Org" icon
1. Review the force-app/main/default/lwc folder to see the retrieved lwc package

### Expected result

The HTML, JavaScript, and XML file should be uploaded as normal ([picture](https://i.stack.imgur.com/GA9Tx.png)),

### Actual result

Each file into its own folder, and the XML file is missing ([picture](https://i.stack.imgur.com/Tcjlb.png)).

### Additional information

Attempted fixes I have tried:
- Restart Visual Studio Code
- Uninstall and reinstall Salesforce Extension Pack
- Reauthorize org
- Update Visual Studio Code
- Reinstall SFDX
- Start a new project with manifest

**VS Code Version**:
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**SFDX CLI Version**:
sfdx-cli/7.92.0-88320113e7 win32-x64 node-v14.15.4

**OS and version**:
OS: Windows_NT x64 10.0.18363

**Comment by Jwok90** [comment] 2021-03-22 17:14
While I don't know exactly what the solution was, completing the following steps (in this order) seems to have resolved the issues:

1. Uninstall and reinstall the Salesforce CLI
2. Uninstall and reinstall VisualForce
3. Uninstall and reinstall the Salesforce Extension Pack
4. Start a new project
5. Log out of all authorized orgs and re-log into the org

I suspect that number 5 may have been the key, but I wasn't able to isolate it in the process and can't confirm for sure.

I'm not going to mark this as "the solution" because I don't know exactly what did it, but hopefully this is helpful to anyone encountering this problem in the future.

**Comment by lcampos** [comment] 2021-03-24 01:04
Hi @Jwok90, thanks for logging this. The root cause of the problem is with a specific version of the Salesforce CLI (the Salesforce extensions for VSCode calls it for any Org interaction e.g. retrieves, deploys, etc) since there's been some issues with it that have been fixed in the last weeks. This is why reinstalling it fixed the issue you were experiencing. 

I'm going to close this issue since updating the Salesforce CLI addresses it.

**Closed by lcampos** 2021-03-24 01:04 UTC
