### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RaffaeleGranato** [forcedotcom/salesforcedx-vscode#2690] opened 2020-10-30 08:58 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.3.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

File: [salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5464030/salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-10-30 18:20
I believe this is a duplicate of [2410](https://github.com/forcedotcom/salesforcedx-vscode/issues/2410#issuecomment-685023233).  Feel free to check that out and comment with more info (or open a new issue if needed)  We are working on the activation speed so that it works nicely no matter your machines horsepower.

**Closed by smaddox-sf** 2020-10-30 18:20 UTC
