### ISSUE TITLE
Compile Not SFDX project

### ISSUE THREAD

**Issue by Shokhan** [forcedotcom/salesforcedx-vscode#519] opened 2018-07-09 08:38 UTC
It would be greate if plugin would have following simple functionality:
1) Compile non sfdx project;
2) Compile single opened file of non sfdx project(Like in mavensmate)
That will be helpful for work with sandboxes and Developer orgs.

**Comment by ntotten** [comment] 2018-07-09 13:17
Duplicate of #66 and #123

**Closed by ntotten** 2018-07-09 13:17 UTC
Labels: duplicate
