### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mak-23** [forcedotcom/salesforcedx-vscode#2706] opened 2020-11-05 05:53 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.3.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MOHAME~1\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-11-05 14:46
Duplicate of #2410.  We have work in flight to address the CPU spikes some users are experiencing

**Closed by smaddox-sf** 2020-11-05 14:46 UTC
