### ISSUE TITLE
Don't automatically create .eslintrc.json and jsconfig.json in the lwc/ folder every time vscode *opens*

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/salesforcedx-vscode#1578] opened 2019-08-22 01:01 UTC
Every time I **open** VSCode, the `.eslintrc.json` and `jsonconfig.json` files in my `lwc/` folder are created, or if they exist, they're mutated to have lines added to them.

You should not automatically overwrite user settings whenever an editor is opened! This is the third instance I've seen with behavior like this.

**Comment by ntotten** [comment] 2019-08-22 01:12
Duplicate of #1394

**Closed by ntotten** 2019-08-22 01:12 UTC

**Comment by AndrewRayCode** [comment] 2019-11-15 00:34
@ntotten as pointed out this is a separate issue than the linked ticket

**Comment by ntotten** [comment] 2019-11-18 13:13
You’re right, it’s not a dup, but this is by design. This is how the JS language server works. Our suggestion is to not commit this file to source.

**Comment by rtm** [comment] 2020-05-22 01:56
If we don't commit it to source, then how can we preserve options that we *want* to specify in jsconfig.json?

I'm confused by the notion that this is how the JS language server works. Are you referring to the JS language server? It doesn't even know about the non-standard "c/foobar" notation for referring to components, or where to find those, so how could it be doing that? Do you this behavior is by your design, or by Microsoft's design? 

It is especially weird to me that JS files that I happen to have in completely unrelated parts of my tree end up adding entries in the `paths` property of jsconfig.json. Who would be doing that and how could possibly imagine that it was necessary?

This is a great plug-in and we're very glad to have it, but this tiny flaw is quite annoying.

**Comment by erocheleau** [comment] 2020-08-20 14:29
This is still an issue today, every time I need to manually revert the jsconfig.json file because it appears as modified as tracked by source control, even if there appears to have no change to the file.

I also cannot "just ignore it" because I have a specific folder in the same project which doesn't concern LWCs, is outside of force-app, but was triggering errors because it includes js files that it did not like.

So what is the solution here?

**Comment by rtm** [comment] 2020-08-20 16:12
To amplify on my comment from three months ago, and following up on @erocheleau's post, I would like to suggest that jsconfig.json does not belong to you. It belongs to me. I understand that you need to manage and update the mappings from non-standard module syntax such as "c/foo" to the actual directory, but the answer to that problem cannot be for you to take over ownership of my jsconfig.json, which as mentioned could and should be able to contain my own persistent settings. 

Although I don't expect you to spend too much time worrying about people using non-standard IDEs, your designs should not *prevent* them from working. My IDE interfaces with the TS language service which picks up certain configuration settings from jsconfig.json. They should not be wiped out every time you decide to rewrite it.

Is there not some way your could paths information in a separate file, called .sfdx-lwc-path-mappings.json, and rewrite that to your heart's content, and then include that into jsconfig.json?

**Comment by timothywlewis** [comment] 2022-03-22 18:48
Just wanted to chip in my two cents: even when adding `jsconfig.json` to `.gitignore`, this leads to local deployment script failures (where one step is `sfdx force:source:convert ...`) such as: `force:source:convert:  Unexpected file found in package directory: ..../lwc/jsconfig.json`

I'm new to LWC and this VS Code creating `jsconfig.json` behavior - does manually creating a `jsconfig.json` in the parent directory (say next to the `sfdx-project.json` outside of the package path) prevent it from being created deep within the package folder?
