### ISSUE TITLE
New VSCode Project from Sandbox Org not retrieving LWC contents

### ISSUE THREAD

**Issue by troveryor** [forcedotcom/salesforcedx-vscode#1176] opened 2019-03-21 12:52 UTC
**Summary**:

Creating a new VSCode project from an existing Sandbox org using  [Org Development Model with VSCode](https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/org-development-model) results in a **force-app/lwc** folder that doesn't contain any Lightning web components that exist in the Sandbox.
**Repro**:

Using the above directions: 
1. Create a new project and auth against a sandbox that has LWC assests (html/js/css)
2. inspect the generated package.xml after  auth completes, notice no LWC related <types> node is present.
3. run and wait for **SFDX: Retrieve Source in Manifest from Org.** command to complete
4. notice an **lwc** folder was created but contains nothing.

**Expected result**:

package.xml should be generated with a <type> that will retrieve LWC assets
retrieve source from org should retrieve those assets.

**Actual result**:

An empty **lwc** folder was created.

**Additional information**:

**VS Code Version**: 1.32.3

**SFDX CLI Version**: sfdx-cli/6.56.0-e3fd846a1f (windows-x64) node-v8.15.1

**OS and version**: Windows 10 v1803

**Comment by troveryor** [comment] 2019-03-21 13:06
Here's a work around in the meantime.
Manually add this node to the package.xml

>     <types>
>         <members>*</members>
>         <name>LightningComponentBundle</name>
>     </types>

Right click on package.xml and run **SFDX: Retrieve Source in Manifest from Org**.

**Comment by ntotten** [comment] 2019-03-21 14:28
Duplicate of #1072

**Closed by ntotten** 2019-03-21 14:28 UTC
