### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by rajesh-k** [forcedotcom/salesforcedx-vscode#2065] opened 2020-03-11 17:00 UTC
I see the "Cannot read property 'get' of undefined" in vscode output anytime a javascript or xml file is saved. Uninstalling the Salesforce CLI Integration extension gets rid of this error. I need the Salesforce CLI Integration package along with the extension pack. Let me know how I can get rid of this error.
The vscode console log is attached.

[1583945690803.log](https://github.com/forcedotcom/salesforcedx-vscode/files/4319588/1583945690803.log)

**Comment by lcampos** [comment] 2020-03-12 19:35
Thanks for reporting this @rajesh-k . We've released a fix for this in version `48.6.0` of the extensions.

**Closed by lcampos** 2020-03-12 19:35 UTC
Labels: area:lwc, type:bug

**Comment by lgomezgwt** [comment] 2020-08-15 06:58
This error is happening again in version 49.5.0

**Comment by Lvkz** [comment] 2020-08-15 06:59
This error is happening again in version 49.5.0

**Comment by lcampos** [comment] 2020-08-17 16:29
Hi @Lvkz I've checked and even when you might be getting the same error message I couldn't find it being a regression on the original issue. Please open a new issue and add details on how to replicate the problem you are seeing so we can work on a fix.

**Comment by Eunix** [comment] 2020-08-25 09:28
I also have the same error again now.

**Comment by lohit398** [comment] 2020-09-11 10:42
I also have the error again in VS code for non-salesforce projects.

Thanks!

**Comment by alechko** [comment] 2020-09-14 04:40
I'm having this issue as well on non-salesforce projects, even on non-react projects, this seems to be triggered simultaneously with saving a file.

Salesforce CLI - 49.9.0
Code - 1.49
