### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by prapul436** [forcedotcom/salesforcedx-vscode#2541] opened 2020-09-17 12:15 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.10.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Pallavi\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-09-17 17:57
seems to be a duplicate of #2410 but not a lot of info here.  Check out that issue for a workaround and weigh in there if you have other input.

**Closed by smaddox-sf** 2020-09-17 17:57 UTC
