### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rakeshchatty** [forcedotcom/salesforcedx-vscode#3175] opened 2021-04-24 11:15 UTC
[-](url) Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.10.0`
- OS Version: `Windows_NT ia32 10.0.19041`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\RAKESH~1\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6369489/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by rakeshchatty** [comment] 2021-04-24 11:36
Here the file link,

[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6369492/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by sfsholden** [comment] 2021-04-29 17:33
Duplicate of #2410.

**Closed by sfsholden** 2021-04-29 17:33 UTC
Labels: area:performance, status:duplicate
