### ISSUE TITLE
Extension issue - CPU Usage 100%

### ISSUE THREAD

**Issue by transmutat0r** [forcedotcom/salesforcedx-vscode#2514] opened 2020-09-11 10:21 UTC
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.8.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment] 2020-09-14 17:33
Not a lot of detail here, but I believe it's a duplicate of #2410.  We posted a workaround on that issue.

**Closed by smaddox-sf** 2020-09-14 17:33 UTC
