### ISSUE TITLE
Activating extension `salesforce.salesforcedx-vscode-apex` failed:  spawn ENOTDIR extensionHost.ts :335

### ISSUE THREAD

**Issue by MarshallKHarrison** [forcedotcom/salesforcedx-vscode#71] opened 2017-08-27 01:18 UTC
### Summary
Intellisense/code completion doesn't find thing like System in a Apex class. 

### Steps To Reproduce:
1. create and apex class.
2. Add PropertyPageResult r = new PropertyPageResult();
3. Type r. 
4. Type System.

### Expected result
When typing something like System. I expect to get a list of methods or when typing r. O expect a  list of properties

### Actual result
No code completion is shown. In other words no properties for r. are shown. No methods shown for System. It doesn't even show 'System'

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959

**SFDX CLI Version**:
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959

**OS and version**:
Ubuntu 16.04 LTS

**Comment by vazexqi** [comment] 2017-08-28 16:17
@MarshallKHarrison - Could you see if you have the following:

1. You are using this with the Salesforce DX flow, meaning that you have a valid sfdx-project.json.
1. You have opened the folder that contains the sfdx-project.json as a top-level folder in VS Code.

These steps are illustrated in the video at https://vimeo.com/230965085

**Comment by MarshallKHarrison** [comment] 2017-08-28 16:23
Yes to both questions.

I used a terminal program and changed directory to the top level directory and used code .  to open Visual Code. I can push or pull code from the scratch Org. Only issue seems to be the Intellisense now working fully. Only thing I can thing that may possibly cause an issue is that Ubuntu is running in a virtual machine. But that should not be a problem.

I also have this on my MMP and it works fine. Seriously thinking about making it my default Salesforce editor.

**Comment by vazexqi** [comment] 2017-08-28 16:28
Great. Thanks for the prompt response.

On the non-functional Linux instance, could you check the results of the View > Output. Then select Apex Language Server from the drop-down list on the far right. Let me know if you see any errors. Also, if Apex Language Server is missing from the drop-down list, that means that it didn't activate and is also worth noting.

Current action items:

1. Add a page to this repo's wiki on tips-and-tricks for debugging what happened to the Language Server.

**Comment by MarshallKHarrison** [comment] 2017-08-28 16:41
OK. The apex Language Server is missing from the dopdown.

How do I go about installing that?

**Comment by vazexqi** [comment] 2017-08-28 17:31
Could you install the extension pack at  https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode? That should install *all* the extensions, including the Apex one.

**Comment by MarshallKHarrison** [comment] 2017-08-28 17:48
That didn’t change anything.

I’m going to try uninstalling VS Code and starting over.

**Comment by vazexqi** [comment] 2017-08-28 18:08
@MarshallKHarrison - I've added a page to the wiki with steps for troubleshooting. See https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server#troubleshooting

**Comment by MarshallKHarrison** [comment] 2017-08-28 19:12
Hi Nick,

I blew away the VM and started all over. I have Visual Code install, the Extensions Pack and the CLI. When I open VC I get an error stating “Java runtime could not be located. Set one using the salesforcedx-vscode-apex.java.home VS Code setting”

I know how to do that but not sure if I need to install any specific version. These are what’s available to install in in Ubuntu 16.04:

[cid:image001.png@01D3200F.FE4A5940]

**Comment by vazexqi** [comment] 2017-08-28 19:17
The image didn't attach properly so I can't see the options. But you need Java 1.8. 

I'll elaborate more on why we need Java for a nodejs project. The Apex compiler is written in Java so we need Java to run it for the code completuon and analysis.

**Comment by MarshallKHarrison** [comment] 2017-08-28 20:37
I figured out what is happening but don’t know how to fix it.

The Developer Tools shows:

[Extension Host] Activating extension `salesforce.salesforcedx-vscode-apex` failed:  spawn ENOTDIR
extensionHost.ts :335

[Extension Host] Here is the error stack:  Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
    at Promise (/home/parallels/.vscode/extensions/salesforce.salesforcedx-vscode-apex-40.7.0/out/src/requirements.js:81:12)
    at checkJavaVersion (/home/parallels/.vscode/extensions/salesforce.salesforcedx-vscode-apex-40.7.0/out/src/requirements.js:80:12)
    at Object.<anonymous> (/home/parallels/.vscode/extensions/salesforce.salesforcedx-vscode-apex-40.7.0/out/src/requirements.js:35:15)
    at Generator.next (<anonymous>)
    at fulfilled (/home/parallels/.vscode/extensions/salesforce.salesforcedx-vscode-apex-40.7.0/out/src/requirements.js:10:58)

**Comment by vazexqi** [comment] 2017-08-28 20:57
This is one of those cases where it is not detecting your version of Java automatically. We can set the location explicitly for it.

1. What does running `which java` show in your terminal?
1. What does running `java --version` show in your terminal?
1. Could you set the salesforce-vscode-apex-java.home setting to point to that location. On my Linux box it is /usr/local/java/jdk1.8.0_112. You can find it by doing File > Preferences > Settings. Look for apex and change the setting.
1. Restart VS Code (no need to uninstall, just restart).

![screen shot 2017-08-28 at 1 56 44 pm](https://user-images.githubusercontent.com/54414/29793482-d7626fac-8bf8-11e7-8fbe-8f02d4b116ab.png)

**Comment by MarshallKHarrison** [comment] 2017-08-28 21:14
For 1. And 2.

parallels@ubuntu:/usr/bin$ which java
/usr/bin/java
parallels@ubuntu:/usr/bin$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
parallels@ubuntu:/usr/bin$

salesforce-vscode-apex-java.home is already set to /usr/bin/java and I don’t get an error when starting. If I change the setting any I get errors at the top of the window. So it appears that it is finding the java engine.

**Comment by vazexqi** [comment] 2017-08-28 21:51
> salesforce-vscode-apex-java.home is already set to /usr/bin/java and I don’t get an error when starting. If I change the setting any I get errors at the top of the window. So it appears that it is finding the java engine.

Just to confirm, does setting salesforce-vscode-apex.java.home solve the issue? Or, even after you set it and you still get that stacktrace?

**Comment by MarshallKHarrison** [comment] 2017-08-28 22:23
I get it the stack trace I sent you even with salesforce-vscode-apex.java.home set to /usr/bin/java

Funny thing is on my Mac OS-X that variable is set to null and Visual Code works fine in OS-X

**Comment by vazexqi** [comment] 2017-08-28 22:43
> I get it the stack trace I sent you even with salesforce-vscode-apex.java.home set to /usr/bin/java. Funny thing is on my Mac OS-X that variable is set to null and Visual Code works fine in OS-X

Ah got it. It is not supposed to be set to `/usr/bin/java`. `usr/bin/java` is the location of the executable. We need the location of the JAVA_HOME. JAVA_HOME is the parent folder that contains the executable and its other libraries. So that's why in my screenshot, it's set to `usr/local/java/jdk1.8.0_112`.

I don't use OpenJDK, so I'm not sure where the JAVA_HOME is for that JVM.

When the value of that setting is null, it uses it's default look-up mechanism to find the location of JAVA_HOME. If you set that setting to something non-null, then it uses what you tell it.

Just to clear, needing to set the salesforcedx-vscode-apex.java.home should be a last resort. The auto-detection should work and we are going to file a bug to investigate why it doesn't. The steps I've outlined above to set JAVA_HOME is just to unblock you for the time being.

**Comment by MarshallKHarrison** [comment] 2017-08-28 23:04
It turns out that Under Ubunto the correct path is /usr/lib/jvm/java-8-openjdk-amd64

If I set salesforcedx-vscode-apex to that it works.

My $JAVA_HOME was null but I set it to and VSCode isn’t picking it up. Going to try putting it in my path or editing /etc/environment

I’ll let you know if that workslater.

**Comment by vazexqi** [comment] 2017-08-28 23:11
@MarshallKHarrison 

Good that you have a workaround. I'm still perplexed why you would need to set the setting explicitly.  I didn't need to set JAVA_HOME or the salesforcedx-vscode-apex.java.home setting on my Ubuntu VM. I'd like to get a reliable repro for this so our engineers can take a closer look. Are these the steps?

1. Install a VM with Ubuntu 16.04 (64 bit) (use http://releases.ubuntu.com/16.04/)
1. Install OpenJDK (sudo apt-get install default-jre or sudo apt-get install default-jdk, which did you use?)
1. Install Code (64 bit).
1. Install the Extension Pack for Salesforce DX at https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode
1. Open up a sample SalesforceDX repo.

See the stacktrace above. Did I miss anything?

**Comment by MarshallKHarrison** [comment] 2017-08-28 23:45
Nick,

I don’t remember for sure which it was but I believe it was openjdk-8-jre-headless that I installed as that was the only package available on my system for stated version 8

Step 5 is correct but prior to that I installed git and cloned the sfdx-dreamforce app

**Comment by vazexqi** [comment] 2017-08-28 23:47
@Sweetman - Could you check this as part of support rotation? Clean Ubuntu 16.04 image with OpenJDK 8 installed. Could you reproduce to see why the Apex Language Server cannot auto-detect java?

**Comment by MarshallKHarrison** [comment] 2017-08-29 02:03
Hi Nick,

I finally figured out what happened.

I created another VM and repeated the process. It turns out that when running sudo apt install openjdk-8-jre-headless  the install process did not set $JAVA_HOME. So I edited /etc/environment and set JAVA_HOME to “/usr/lib/jvm/java-8-openjdk-amd64“ then logged out and logged in again.

After that VisualCode worked fine. And the output terminal shows this for Apex Language Server

18:40:30.626 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
Aug 28, 2017 6:40:30 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
WARNING: Unsupported notification method: initialized
Aug 28, 2017 6:40:30 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
WARNING: Unsupported notification method: $/setTraceNotification
Aug 28, 2017 6:40:31 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7403062 shorts which is 14MB not including array overhead. Removed 6746470 shorts which is 12MB not counting array overhead.Took 10ms.
18:40:33.381 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
18:40:33.384 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
18:40:34.294 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types.
18:40:34.293 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 3668 ms.
18:40:34.441 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Scanning user-defined types took 147 ms.

Thanks for all your help. I really love the Salesforce Developer Experience and think there is a future in consulting and training Salesforce developers in how to make the most of SFDX.

Marshall Harrison
1.904.655.6502
Salesforce Developer Champion
Jacksonville Salesforce Developer Group Leader<https://www.meetup.com/Jacksonville-Salesforce-Developer-Group/>
sfdxBlue.com<https://sfdxblue.com/>

**Comment by MarshallKHarrison** [comment] 2017-08-29 12:02
I suggest adding a note about $JAVA_HOME to the troubleshooting wiki. After that this issue can be closed as far as I'm concerned.

**Comment by vazexqi** [comment] 2017-08-29 20:32
Thanks @MarshallKHarrison. I've added a section about how to set the java location at https://github.com/forcedotcom/salesforcedx-vscode/wiki/Apex-Language-Server#how-do-i-configure-the-version-java-that-is-used-for-the-apex-language-server

I'm still curious why VS Code is not able to detect just the java executable. If you look at https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/src/requirements.ts it looks at JDK_HOME, then JAVA_HOME, then just tries to find where `java` is. So, there is quite a bit automatic lookup that we do.

My suspicion is that when you start with a clean VM, and install Java, VS Code might not be able to detect the newly installed Java. This could depend on whether you launch VS Code from the terminal using `code` or if you use the VS Code launcher in Ubuntu. Sometimes, like on Windows, you need to restart (or log in again) after you set environment variables.

I'll let @Sweetman update us if he finds anything unusual.

**Comment by MarshallKHarrison** [comment] 2017-08-29 20:49
Thanks Nick.


1.       Neither JDK_HOME nor JAVA_HOME are set on the Ubunto VM or on my MBP. However VS Code works fine on the MAC. Not sure why the Ubuntu version isn’t searching for and finding the Java Runtime.

2.       I did log out and logged back in after setting the JAVA_HOME variable in /etc/environment

Let me know if I need to do any more testing/debugging.

**Comment by vazexqi** [comment] 2018-01-20 04:07
Closing this since we have not seen any other issues.

**Closed by vazexqi** 2018-01-20 04:07 UTC

**Comment by luigicampbell** [comment] 2019-09-28 15:21
Error >> The salesforcedx-vscode-apex.java.home setting defined in VS Code settings points to a missing folder. For information on how to setup the Salesforce Apex extension, see [Set Your Java Version](https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/java-setup).<<

After reading the set up instructions and docs, I have tried installing Open JDK, ZULU and Oracle. The path to the library is right, the settings JSON is showing the correct path and version (currently on 11.0.4). 

Not sure what's going on. On Windows x64 OS. Had no problems on my Mac.
Also had similar problems on Linux.

Also have sfdx extension pack, cli, plugins core etc. 
Can create sfdx projects and JSONs fine, login and auth all work but this error keeps happening.

Settings JSON for workspace:
"salesforcedx-vscode-apex.java.home": "C:\\Program Files\\Java\\jdk11.0.4"
also randomly tried: 
"salesforcedx-vscode-apex.java.home": "C:/Program Files/Java/jdk11.0.4"
![image](https://user-images.githubusercontent.com/32420254/65818705-ffa19880-e1c8-11e9-9e8d-cf0fc7122caa.png)
