### ISSUE TITLE
Getting Unknown Exception while retrieving via VScode package.xml retrieve

### ISSUE THREAD

**Issue by sushilultimate** [forcedotcom/salesforcedx-vscode#3155] opened 2021-04-19 19:32 UTC
### Summary

Error while retrieving in VS code. 

![image](https://user-images.githubusercontent.com/35816013/115292388-e3a37600-a123-11eb-916b-1204cea5562b.png)

### Steps To Reproduce:

1. create package xml as given in screenshot above and run retrieve by right clicking within package.xml

### Expected result

Validation rule should get retrieved

### Actual result

Getting unknown exceptiomn

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.55.1 
VS code extension pack - v51.8.0

**SFDX CLI Version**:sfdx-cli/7.97.0 darwin-x64 node-v15.14.0

**OS and version**: macos Mojave 10.14.6

**Comment by smaddox-sf** [comment] 2021-04-23 22:12
Thanks for reaching out on this. This is a duplicate of #3137 and we're working on a fix. Closing this issue and we will update #3137 as we have a resolution. In the meantime, you an try this workaround: disable the setting "Experimental: Deploy Retrieve"
https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements/#setup

CC @brpowell

**Closed by smaddox-sf** 2021-04-23 22:12 UTC
