### ISSUE TITLE
Extension issue -Apex 52.1.0 Unresponsive

### ISSUE THREAD

**Issue by vanglirajan** [forcedotcom/salesforcedx-vscode#3344] opened 2021-06-22 10:50 UTC
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.1.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 32584,
		"activateCallTime": 22,
		"activateResolvedTime": 41251,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```
[CPU-20210622T105233.159Z.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6693617/CPU-20210622T105233.159Z.cpuprofile.txt)

**Comment by vanglirajan** [comment] 2021-06-22 10:50
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 32584,
		"activateCallTime": 22,
		"activateResolvedTime": 41251,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment] 2021-06-23 14:08
Duplicate of #2410

**Closed by smaddox-sf** 2021-06-23 14:08 UTC
