### ISSUE TITLE
Prettier Not Working on Visualforce Pages

### ISSUE THREAD

**Issue by jonny-harte** [forcedotcom/salesforcedx-vscode#3387] opened 2021-07-04 21:20 UTC
### Summary

When saving a visualforce page prettier doesn't run. Works on Apex Classes, LWC etc.

### Steps To Reproduce:

1.  Save visualforce page.

### Expected result

Visualforce is formatted using the default formatter "Prettier - Code formatter".

### Actual result

No output is added to the prettier log, debug enabled.

### Additional information

I have Format on Save enabled and default formatter set to Prettier. I also have default visualforce formatter enabled and .prettierrc with the overrides in the root of the project.

**Salesforce Extension Version in VS Code**:
52.3.0

**SFDX CLI Version**:
7.94.3-a4e7c7955b

**OS and version**:
MacOS 11.4

**Prettier Version**:
2.2.1

**Comment by renzodupont** [comment] 2021-07-05 21:55
I am having the same issue. VS Code is also not highlighting VF tags anymore. Apex code works fine, VF page just don't work correctly anymore.

**Comment by smaddox-sf** [comment] 2021-07-06 17:57
#3383 may be a duplicate

**Comment by jonny-harte** [comment] 2021-07-07 08:24
@smaddox-sf yes appears to be the same issue.

**Comment by smaddox-sf** [comment] 2021-07-07 15:30
Closing this as a duplicate of #3383.  Feel free to add any other input to that issue.

**Closed by smaddox-sf** 2021-07-07 15:30 UTC
Labels: area:visualforce, status:needs eng review
