### ISSUE TITLE
Activating Extension and then nothing happens

### ISSUE THREAD

**Issue by ParulDua** [forcedotcom/salesforcedx-vscode#2283] opened 2020-06-22 15:17 UTC
Hi Team,

When I try to create a new project using Ctrl+P > SFDX: Create project with manifest, it shows "Activating Extension" in the status bar, then the message vanishes and nothing happens. I expect it to open a pop up to let me enter a Project name.

I have updates Java Home in VS code setting as "C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin" and also set up in Path var.

**Comment by smaddox-sf** [comment] 2020-06-22 16:24
Can you please include some additional information:

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

Also, can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?

**Comment by ParulDua** [comment] 2020-06-23 10:30
PFB requested info :

VS Code Version: 1.46.1

SFDX CLI Version: sfdx-cli/7.63.0-c897e8bb1a win32-x64 node-v10.20.1

OS and version: Windows 10 Pro and 10.0.18363

Yes I have gone through that article before raising the issue here. All the setup is verified but still I cant trouble shoot.

**Comment by lcampos** [comment] 2020-06-24 02:05
hi @ParulDua , do you get any error message in the bottom-right corner of VSCode's footer or in the Dev Tools console (Help > Toggle Developer Tools and select the Console tab). If you do can you provide those details ?

**Comment by ParulDua** [comment] 2020-06-24 06:34
Hi @lcampos ,

No I dont get any error message at bottom right corner. It just shows "Activating extensions" in a pop up for 3-4secs then it vanishes and nothing happens. Like I did not run any command at all.

Attaching the console screenshot for ref.
![vs code console](https://user-images.githubusercontent.com/66628966/85508995-c6407100-b612-11ea-974d-b619ee5b75d3.png)

**Comment by lcampos** [comment] 2020-07-10 00:22
hi @ParulDua we released some changes in version 48.24.0 that speed up the activation of the extensions. We're working on follow up enhancements but let us know if your experience got a bit better now.

I'm going to close this issue since it's a duplicate of #2295 which is where we'll keep posting updates.

**Closed by lcampos** 2020-07-10 00:22 UTC
