### ISSUE TITLE
When i run the apex replay debugger and select the log i am getting msg Generate the log with a log level of FINER or FINEST for VISUALFORCE and a log level of FINEST for APEX_CODE.

### ISSUE THREAD

**Issue by play62ca** [forcedotcom/salesforcedx-vscode#1372] opened 2019-05-26 11:54 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by soql101** [comment] 2019-05-28 05:24
I encounter the same error.

**Comment by lcampos** [comment] 2019-05-28 17:32
Hi @play62ca & @soql101 , this is caused by using a debug log that was not created using the Debug levels set by the Replay Debugger trace flag. The validation is in place to make sure that the data needed by the Replay Debugger is part of the debug log file. 

Below is a screenshot where I highlight a debug log line that has invalid levels (`APEX_CODE, FINE` instead of `APEX_CODE, FINEST`) and causes the same error message you are running into.

![debug_log_level_sample](https://user-images.githubusercontent.com/1041842/58498727-7eab9500-8133-11e9-85cb-9919ff7d0bdb.png)


You should be able to fix this by turning on the replay debugger `SFDX: Turn On Apex Debug Log for Replay Debugger`, executing the Apex code you want to debug and downloading the debug log generated by that execution `SFDX: Get Apex Debug Logs ...`.

**Comment by lcampos** [comment] 2019-05-28 17:33
I'm closing this issue since it is a valid error caused by a validation on the Replay Debugger.

**Comment by c4tch** [comment] 2019-09-18 14:13
this should be reopened, I can replicate this. Pulled large (4+MB) log from my org with correct settings, and also following above guidance and still received this error

**Comment by lcampos** [comment] 2019-09-18 16:16
@c4tch can you confirm this happened to you after running `SFDX: Turn On Apex Debug Log for Replay Debugger` or are you manually creating the Trace Flag in the org ?

Also, was the log generated using the Trace Flag for the Replay Debugger or was it generated for a different one ?

**Comment by c4tch** [comment] 2019-09-20 07:41
Yes I can confirm I ran SFDX: Turn On Apex Debug Log for Replay Debugger and the log was generated as per the advice above. I then ran the debugged, located the log file that was generated and got the error... Here's the header from the log...
```
47.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,FINER;DB,FINEST;NBA,NONE;SYSTEM,NONE;VALIDATION,NONE;VISUALFORCE,FINE;WAVE,NONE;WORKFLOW,INFO
14:07:07.0 (115382)|USER_INFO|[EXTERNAL]|00555000003Dn66|***********@************|(GMT+00:00) Greenwich Mean Time (GMT)|GMTZ
14:07:07.0 (151125)|EXECUTION_STARTED
14:07:07.0 (156564)|CODE_UNIT_STARTED|[EXTERNAL]|Aura

```

**Comment by lcampos** [comment] 2019-10-03 00:39
Ok, I haven't been able to replicate this on my side but I'll reopen the issue for now. @c4tch is there anything particular in your setup I should be aware of ? I'm testing on Mac OS, VSCode (version 1.38.1), Salesforce extensions (46.16.0), Salesforce CLI (7.25.3) and using a Dev Org and Scratch Org.

**Comment by c4tch** [comment] 2020-01-22 14:03
I think this was a vsCode / java issue as I've rebooted and reinstalled since I raised this and the issue seems to have gone for now

**Comment by lcampos** [comment] 2020-01-22 16:23
Thanks for the update @c4tch, I'll close this issue for now but feel free to reopen it if needed.

**Closed by lcampos** 2020-01-22 16:23 UTC

**Comment by eltoroit** [comment] 2021-07-01 19:39
I had to update the versions of the Apex classes to version 52 (from version 40) to get the logs working.

**Comment by cloudevolve** [comment] 2023-01-20 20:36
I also have this issue when running the "Debug" unit test option.  Please reopen as I ran SFDX: Turn On Apex Debug Log for Replay Debugger and followed all the other steps

**Comment by Timapheus** [comment] 2023-02-08 08:06
> I also have this issue when running the "Debug" unit test option. Please reopen as I ran SFDX: Turn On Apex Debug Log for Replay Debugger and followed all the other steps ![image](https://user-images.githubusercontent.com/33523990/213802205-b0f20fd6-38fb-43d0-8d34-111cfbde6536.png) ![image](https://user-images.githubusercontent.com/33523990/213803924-335d89da-6b1a-4611-aa02-165479083f0d.png)

I have the exact same issue with log:
56.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,INFO;VALIDATION,INFO;VISUALFORCE,FINE;WAVE,INFO;WORKFLOW,INFO

**Comment by cloudevolve** [comment] 2023-02-08 14:51
@Timapheus  I ended up opening a new ticket, please comment here that you are receiving the same issue as it has been getting some traction:

https://github.com/forcedotcom/salesforcedx-vscode/issues/4638

> I have the exact same issue with log: 56.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,INFO;VALIDATION,INFO;VISUALFORCE,FINE;WAVE,INFO;WORKFLOW,INFO

**Comment by dalovelace836** [comment] 2023-08-31 21:06
Has there been an update on this issue?  I just now started receiving the error.  I followed the steps above, but that did not resolve the issue

**Comment by eltoroit** [comment] 2023-08-31 21:49
This could help... `sf data create record --use-tooling-api --sobject=DebugLevel --values="DeveloperName=FINEST MasterLabel=FINEST Database=FINEST Callout=FINEST ApexCode=FINEST Validation=FINEST Workflow=FINEST ApexProfiling=FINEST Visualforce=FINEST System=FINEST Wave=FINEST Nba=FINEST " --json`

**Comment by nicofuru** [comment] 2024-07-09 08:56
I am getting the same issue and could not resolve it with the steps mentioned above. 
If I run the "Debug Test" on a sandbox it works correctly. The problem begins when I try to run it on a scratch org with namespace.
Sometimes after rebooting the computer it works for the first time but then stopos working. I am using the latest version of everything. When I run the apex tests with the "Run Test" the logs received have the correct log level but when I click the "Debug Test" the logs come with incorrect debug level for apex and visualforce.
