### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by ad1969** [forcedotcom/salesforcedx-vscode#535] opened 2018-07-26 20:21 UTC
### Summary

I installed the extensions, I don't get the features documented in Apex Code Editor for Visual Studio Code extension:

1. View Code Completion
2. Code snippets
3. View\jump definitions
4. Find all references

Is this because we don't implement DX yet? I would assume that this would work for any .cls file.

### Steps To Reproduce:

1. Clicked CTL or right click to peek definition.

### Expected result

The definition coming up.

### Actual result

Apex options not listed.
![image](https://user-images.githubusercontent.com/5445582/43286387-791594f2-90e7-11e8-83ab-c6e83dc93327.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.25.1

**SFDX CLI Version**: 43.8.0

**OS and version**: Windows 10

**Comment by vazexqi** [comment] 2018-07-27 17:54
@ad1969 - This is likely a dupe of #123. Do you have a sfdx-project.json? If not, then none of the features will activate.

**Comment by ad1969** [comment] 2018-07-27 19:49
Could be. Can you please provide me a location I can look at a sfdx-project.json file? Dreamhouse is mentioned, but not sure what it is.

Thanks
Alex

**Comment by ad1969** [comment] 2018-07-27 19:51
Never mind. Got it in github.

**Comment by ad1969** [comment] 2018-07-29 14:40
I'm now getting the features. Thank you very much.

Do you know if possible, I can get these extensions to work with sandboxes directly?

**Comment by vazexqi** [comment] 2018-07-30 21:37
@ad1969 - We are working on it right now. Those features are still behind a pref and require the latest unpublished version of the Salesforce CLI.

If you are curious, you can take a look at 

https://github.com/forcedotcom/salesforcedx-vscode/pull/523
https://github.com/forcedotcom/salesforcedx-vscode/pull/531

**Closed by vazexqi** 2018-07-30 21:37 UTC
