### ISSUE TITLE
Retrieve source from org make auto deploy when auto save activated

### ISSUE THREAD

**Issue by tom901** [forcedotcom/salesforcedx-vscode#981] opened 2019-01-29 09:58 UTC
### Summary

Retrieve source from org and auto deploy when the auto save feature enabled : 

 "salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true

### Steps To Reproduce:

1.  Open VSCode
2.  Preferences -> Settings 
3. Salesforce Feature Previews 
![image](https://user-images.githubusercontent.com/6650607/51899589-a07a5280-23b3-11e9-8cf2-52fa39cd892e.png)
4.  Set to true : 
salesforcedx-vscode-core.push-or-deploy-on-save.enabled
5.  Type the command to retrieve source : 
 sfdx force:source:retrieve --sourcepath c:\developpement\Salesforce\eDev\eDev\main\default

### Expected result

Retrieve all source from the org without save the change

### Actual result

Source was retrieved, but all metdata that was changed make an auto save

![image](https://user-images.githubusercontent.com/6650607/51899886-3ca45980-23b4-11e9-8b72-48a71517eb93.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:  1.28.2

**SFDX CLI Version**: 6.50.0-9817aece8a

**OS and version**: Windows 10

**Comment by ntotten** [comment] 2019-01-29 18:47
Duplicate of #883

**Closed by ntotten** 2019-01-29 18:47 UTC
