### ISSUE TITLE
Do not see a "Debug Apex" Permission

### ISSUE THREAD

**Issue by Julian88Tex** [forcedotcom/salesforcedx-vscode#499] opened 2018-06-21 01:14 UTC
Apex Debugger README mentions a **Debug Apex** permission under _System Permissions_, but I'm not seeing this in my _Enterprise Edition_ org (confirmed we have 1 License). Has this setting been renamed to **View and Debug Managed Apex** which I do see? If not, is this something that you need to contact support to have enabled? Thanks!

**Comment by DatGuyJonathan** [comment] 2018-06-21 14:55
Hey @Julian88Tex , is your org a License Management Org (LMO), meaning it has the License Management App installed? 

Per this document https://releasenotes.docs.salesforce.com/en-us/spring18/release-notes/rn_forcecom_debugging_isv_sessions.htm, LMOs get one free debugger license to debug their subscribers. The free license cannot be used with your sandboxes or scratch orgs. You would have to purchase at least one Apex Debugger license to debug your sandboxes or scratch orgs.

**Comment by Julian88Tex** [comment] 2018-06-21 22:49
@DatGuyJonathan , this for the link! Super helpful. Yes, our org is an LMO as well as our DevHub.

So even though our Org says "You have 1 license available." This license may only be for debugging subscriber orgs and not necessarily our own.

That seems a little odd to me since, as an ISV Partner, Salesforce benefits from us being able to debug our managed packages in Scratch orgs before we release updates. Is there a separate license provided if you have an org used for managed packages? Thanks again for your help!

**Comment by DatGuyJonathan** [comment] 2018-06-22 16:13
@Julian88Tex , the **Apex Debugger** license applies to your production org (which can be an LMO, a DevHub, etc.) and can be used to debug its child orgs on sandbox (which can be subscribers, scratch orgs, etc.). So, there's only one license, but there are two permissions for LMO use-case and non LMO use-case.

An alternative to the Apex Interactive Debugger is another product we recently released in beta: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-apex-replay-debugger. It leverages debug logs and the best part is it's free! Here are a couple of introduction videos; hopefully it can help you out:

YouTube—Salesforce Releases: [Platform Services: Apex Replay Debugger](https://www.youtube.com/watch?v=8GVuMT4MHWc)
TrailheaDX ’18 session video: [Banish the Bugs: Apex Debuggers to the Rescue!](https://www.salesforce.com/video/2520334/)

**Comment by Julian88Tex** [comment] 2018-06-22 16:30
@DatGuyJonathan Thanks once again for the helpful info! I am definitely going to do a deep dive into learning about Apex Replay Debugger and will be sharing it with our developers.

It sounds like what you're saying is that the License we have indeed is for debugging our scratch and sandbox orgs, but we may just be missing the permission **Debug Apex**. I'll be reaching out to support to see about why that may be. I'm guessing it's because we have Enterprise Edition and maybe at one point were given the license but not the permission to use the license.

**Comment by vazexqi** [comment] 2018-06-29 17:12
Closing this since this is working as designed and nothing has been identified for actions on our side.

**Closed by vazexqi** 2018-06-29 17:12 UTC
