### ISSUE TITLE
Request textDocument/hover failed error from LWC Language Server in VSCode

### ISSUE THREAD

**Issue by Bgallahue** [forcedotcom/salesforcedx-vscode#3929] opened 2022-03-16 14:48 UTC
### Summary

Persistent errors in VSCode coming from the LWC Language Server

```
Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'forEach' of undefined
  Code: -32603 
```

this is occurring for myself on two different computers in two different projects.

I am also gettting 
```
Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'find' of undefined
  Code: -32603
```
in another project from the LWC Language Server

### Steps To Reproduce:

1.  Open a LWC component in VSCode (does not need forEach method)
2.  Error pops up in Output section of VSCode: "Request textDocument/hover failed"
3.  Error is persistent, keeps occurring as i'm writing code

### Expected result

No errors

### Actual result

Error messages are continually popping up

### Additional information

<img width="905" alt="Screen Shot 2022-03-16 at 10 43 15 AM" src="https://user-images.githubusercontent.com/61252575/158616328-8d5bc475-201f-44ce-9d56-3c5fc7e5a9b3.png">

**Salesforce Extension Version in VS Code**: v54.4.1

**SFDX CLI Version**: sfdx-cli/7.139.0 darwin-x64 node-v16.14.0

**OS and version**: macOS Monteray

**Comment by mallik-svmx** [comment] 2022-03-18 05:51
I see the issue on my vscode, and its very annoying.

**Comment by jhernandezme** [comment] 2022-03-21 17:25
Same here, i was actually looking for a solution but it seems like it's not only me.

**Comment by nicholasglesmann** [comment] 2022-03-21 19:03
I'm also seeing this issue. It only started when I upgraded VSCode to version 1.65.2.


Additional info:

Salesforce Extension Version in VS Code: v54.5.0

SFDX CLI Version: sfdx-cli/7.137.1 win32-x64 node-v16.13.2

OS: Windows 10

**Comment by Himanshu-karnwal** [comment] 2022-03-22 12:26
I'm also facing the same issue. is there any update on this?
![image](https://user-images.githubusercontent.com/23718442/159481392-04be1a0a-175a-4620-af0b-86c7e008e533.png)

**Comment by balderm** [comment] 2022-03-22 17:35
Have been getting this issue myself for the past week.

SFDX Version: sfdx-cli/7.142.1 win32-x64 node-v17.1.0
LWC Extension version: 54.5.0

VSCode Version:  1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

![Screenshot 2022-03-22 183518](https://user-images.githubusercontent.com/6721489/159541461-1421d6d4-60ed-4387-86e9-cb4705e20125.jpg)

**Comment by soql101** [comment] 2022-03-25 18:59
Getting above error since 2 days
1. SFDX cli version: 
sfdx-cli/7.142.1 win32-x64 node-v16.14.0

2. Installed extension in vs code:

-   dbaeumer.vscode-eslint@2.2.2
-   eamodio.gitlens@12.0.5
-   esbenp.prettier-vscode@9.3.0
-   FinancialForce.lana@1.4.2
-   redhat.vscode-xml@0.19.1
-   redhat.vscode-yaml@1.5.1
-   salesforce.salesforce-vscode-slds@1.4.8
-   salesforce.salesforcedx-vscode@54.6.1
-   salesforce.salesforcedx-vscode-apex@54.6.1
-   salesforce.salesforcedx-vscode-apex-debugger@54.6.1
-   salesforce.salesforcedx-vscode-apex-replay-debugger@54.6.1
-   salesforce.salesforcedx-vscode-core@54.6.1
-   salesforce.salesforcedx-vscode-lightning@54.6.1
-   salesforce.salesforcedx-vscode-lwc@54.6.1
-   salesforce.salesforcedx-vscode-soql@54.6.1
-   salesforce.salesforcedx-vscode-visualforce@54.6.1
- 

VS code Version: 1.65.2 (user setup)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
<img width="711" alt="lwc error" src="https://user-images.githubusercontent.com/10097911/160184631-be38c640-c83b-403b-8a0a-de41d7bc46db.png">

**Comment by randi274** [comment] 2022-04-06 14:21
The fix for this has been merged in, and should be available in the following release of the extensions (likely next Wednesday).

**Closed** 2022-04-14 14:25 UTC
Labels: type:bug

**Comment by Bgallahue** [comment] 2022-04-18 14:18
has the updated extension been released with this fix?
I upgraded to 7.146.1-fcbd623 and I am still gettting this issue

[Error - 10:16:11 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read properties of undefined (reading 'find')
  Code: -32603

**Comment by randi274** [comment] 2022-04-18 14:59
@Bgallahue that issue we're actually tracking separately, as the root cause is different. It's on our near-term roadmap though, and should be fixed soon. https://github.com/forcedotcom/lightning-language-server/issues/493
