### ISSUE TITLE
Retrieve and Deploy to sandbox is very slow

### ISSUE THREAD

**Issue by amitkumarj1979** [forcedotcom/salesforcedx-vscode#917] opened 2018-08-22 23:07 UTC
### Summary

When using the prerelease version against a sandbox the Deploy and Retrieve takes lot of time even though its a single file or component.

### Steps To Reproduce:

1.  Once you retrieve the complete package.
2.  Try to retrieve a single Apex class. you will see it takes lot of time.
3.  Same with Deploy as well.

### Expected result

Single files should be much faster the whats its today.

### Actual result

Performance should be much better.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.26.1

**SFDX CLI Version**: Pre release

**OS and version**: Windows 10
**Internal Work Item**: [W-5552612](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005wp8NIAQ/view)

**Comment by ntotten** [comment] 2019-01-30 16:59
Anyone on this thread who has experienced slow retrieves/deploys please email me details. We are working on definitively solving this problem once and for all and I need as much data as possible. OrgId, time, logs, command run, etc. The more detail the better. ntotten@salesforce.com

**Comment by trailheaddxvinod** [comment] 2019-02-06 15:22
@ntotten - I'm experiencing this today and I'm on government cloud. Any issues or risks with using salesforce extension pack for vscode/salesforce cli on government cloud?

**Comment by ntotten** [comment] 2019-02-06 15:30
@trailheaddxvinod The issue generally isn't with VSCode or the CLI, it is usually with the backend APIs. Feel free to email me details per the instructions here: https://github.com/forcedotcom/salesforcedx-vscode/wiki/How-to-Collect-Performance-Information-for-Support

**Comment by jjTorrent** [comment] 2019-03-12 22:15
Any updates here? Still need more data?

**Comment by ntotten** [comment] 2019-03-12 22:37
This is actively being worked on. There are several efforts - one is updates to the CLI that will improve performance, another is work on the backend for performance. It isn't going to be one fix, but it's something we are working on.

**Comment by ChuckJonas** [comment] 2019-03-15 05:53
I just wanted to add that there seems to be a considerable delay BEFORE the command even starts to execute when using "deploy on save" (with classic org).  

IDK if this is due to intended debouncing, but if that's the case, it should be configurable.  

![save-delay](https://user-images.githubusercontent.com/5217568/54411179-13196600-46b4-11e9-91c7-771bbd4d8429.gif)

`11.13-4.39=6.74s`

It seems to consistently take 5-7 seconds before the deploy command even starts to run.  If I right click and run "deploy", the prompt comes up immediately.

**Comment by ChuckJonas** [comment] 2019-03-15 06:10
[found it](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts#L18).

I must say this is quite odd behavior... Seems like it's trying to avoid sending multiple requests by reseting a 4.5s timeout each time a file is saved then sending a single request for all saved files once the timeout expires?

Curious what the use case is behind this?  I get wanting to handle scenarios like `Files: save all` (this is actually really nice for refactoring), but why such a tremendous timeout?  Surely a hundred milliseconds would be enough to accomplish the same thing...

At the very least can we make it configurable?

**Comment by sanjuoo7** [comment] 2019-03-15 11:20
Any updates on this is getting very slow, it take a minute to push data to sandbox org, i am developing against sandbox. It used to be saved quickly but after recent update it taking minutes to push changes to sandbox.

Moreover i found that it doesn't saved the apex class to server though it does show successful save message to end user in VS Code.

Let me know if you need any more information from me on this issue.

**Comment by ntotten** [comment] 2019-03-15 14:03
@ChuckJonas This is something that we plan to fix. I wrote up our proposed solution here: https://github.com/forcedotcom/salesforcedx-vscode/issues/1155

Please let me know what you think. We certainly could make the timeout configurable, but I think the linked proposal is much better.

**Comment by maaaaarco** [comment] 2019-04-03 08:27
I'm also experiencing very long deploy time for single files, like Apex classes. I think the main problem is not vscode itself but the fact that the deploy of single files is done through the Metadata API. Would be possible to switch to Tooling API for individual files?
This is something that IlluminatedCloud supports and was also part of the good old MavensMate.

**Comment by luchom** [comment] 2019-04-12 14:32
Hope this gets fixed soon. Really hard to work with this issue.

**Comment by enreeco** [comment] 2019-05-09 08:04
any news?

**Comment by AlbertoMata** [comment] 2019-05-09 16:41
> I'm also experiencing very long deploy time for single files, like Apex classes. I think the main problem is not vscode itself but the fact that the deploy of single files is done through the Metadata API. Would be possible to switch to Tooling API for individual files?
> This is something that IlluminatedCloud supports and was also part of the good old MavensMate.

This

**Comment by ntotten** [comment] 2019-05-09 18:12
It isn't about the Tooling API vs Metadata API. They are both the same on the backend. The issue is that we are using the Metadata API asynchronously because the command was initially optimized for all cases - large deployments or small deployments. We are working to switch to use the Metadata API synchronously for small deployments (probably less than 30 items). The work is scheduled, but we don't have an exact ETA right now. Once we make this switch the performance will be identical to what other tools have through the Tooling API.

**Comment by matteobosc** [comment] 2019-05-14 12:50
Hi, this switch will improve the Apex Test Run performances too? The test run is even slower than retrieve/deploy.

**Comment by RESTORE-thaierissa** [comment] 2019-05-15 04:22
Sometimes deploy works fine, but once it stops working it really stops. Hope this gets fixed soon. Ill try rebooting my computer. 
Thanks

**Comment by ivanovivelin** [comment] 2019-05-31 13:57
Is there any update on this ? It takes minutes against a Sandbox.

**Comment by RESTORE-thaierissa** [comment] 2019-05-31 16:53
> Is there any update on this ? It takes minutes against a Sandbox.

I found that if i reauthorize the org first, the issues subside.

**Comment by ivanovivelin** [comment] 2019-06-05 07:15
> > Is there any update on this ? It takes minutes against a Sandbox.
> 
> I found that if i reauthorize the org first, the issues subside.

Well, for me it is unusable against a Sandbox

**Comment by ntotten** [comment] 2019-06-07 14:06
The issue with deployment time against sandboxes is something that is known and we are working on. It is, however, something that is on the backend and not something we can resolve with VS Code. There is an update going out soon that will speed up deployment time against sandboxes for smaller deployments that should help out with this issue. We are continuing to do work to improve this over time, but some of the work is somewhat long term.

**Comment by monirkohi2006** [comment] 2019-06-07 19:05
"There is an update going out soon that will speed up deployment time against sandboxes for smaller deployments that should help out with this issue."  Where can we find the status of the update or any info regarding the update?

**Comment by ntotten** [comment] 2019-06-07 19:09
@monirkohi2006 There isn't anything public about it. It's purely internal systems updates and will have no functional changes to APIs, etc. Its a performance update on how queues work internally.

**Comment by delcs827** [comment] 2019-06-17 17:44
Can confirm this is happening to me as well. 2 minutes to deploy a LWC seems much longer than it should normally take.

**Comment by aotolbert** [comment] 2019-06-18 18:09
I can also confirm that it can take up to 5 minutes to deploy (from VS Code using integrated CLI) and I often have to cancel the deploy and try again multiple times before it is successful within an "acceptable time-frame" nowadays about 20-30 sec.

**Comment by pibenettmodis** [comment] 2019-06-19 09:41
The same here! Could you solve this please :)

**Comment by arunmitteam** [comment] 2019-06-20 17:15
Is there any workaround for this? It has become totally unusable at this time.

**Comment by monirkohi2006** [comment] 2019-06-21 04:38
This issue was reported on Aug 22, 2018.  Any update please?

**Comment by mitchspano** [comment] 2019-06-27 19:50
I am facing deploy and retrieve times exceeding 10 minutes in my development environment.

**Comment by michaelsoriano** [comment] 2019-07-15 23:58
Same situation here. There is a significant delay when saving and deploy - as described by @ChuckJonas above. https://github.com/forcedotcom/salesforcedx-vscode/issues/917#issuecomment-473167626

Any word on the fix?

**Comment by cemerson** [comment] 2019-08-13 11:40
+1. Retrieve is currently painfully slow for me too. I actually haven't finished one Retrieve yet so I'm not sure how long it takes but 10+ minutes so far. I even tried the SFDX: Auth first even though I'd assume that shouldn't have to happen every VS Code session (?).

* VS Code 1.36.1
* Salesforce Extension Pack: 46.9.0
* Windows 10 x64

**Comment by wwwmonkey** [comment] 2020-02-27 06:12
Deploy to Org of a small LWC component takes 2-**20**mins currently on our project.

**Comment by talcarmi** [comment] 2020-04-16 15:07
@ntotten experiencing 5 minutes to deploy tiny LWC to sandbox

**Comment by timswilson** [comment] 2020-05-15 02:02
I'm experiencing the same as @wwwmonkey 2-20 minutes to deploy LWCs. This has killed my productivity. I can't tell if it is dependent on time of day or not. Right now it is 10 pm for me and deploy source to org is taking 10 minutes on average.

**Comment by handlerda** [comment] 2020-06-08 14:24
I am running into the same problem. It takes anywhere from 2-25 minutes for me to deploy to the source.

**Comment by timswilson** [comment] 2020-06-08 14:33
@handlerda, my issue ended up being due to a faulty sandbox. I have heard of that happening to other people but hadn't experienced it myself until this issue. I was working in a recently refreshed sandbox that for whatever reason was causing this issue. I created a new sandbox, deployed my code over to it and the issue was resolved.

**Comment by handlerda** [comment] 2020-06-08 14:44
@timswilson thanks for the quick response! I am working in GovCloud so that could be part of it. Sometimes it's super quick and sometimes it will take 20+ minutes. I will keep your suggestion in mind to see if other sandboxes are just as slow!

**Comment by pranayjswl007** [comment] 2020-06-08 16:22
I am not sure if refreshing sandbox and expecting it to work is a better strategy. It can happen you refresh n times and you get such faulty sandboxes every time.  I refreshed 1 today, super slow 3-8 mins for most deployments, I do agree sometimes it does save in 2-3 seconds.

**Comment by handlerda** [comment] 2020-06-08 17:06
@pranayjswl007 I agree. It's just so inconsistent. Today I have ranged from 2seconds to 22 minutes.

**Comment by jacobpeterson2012** [comment] 2020-06-24 09:17
Just adding to the list of people facing this issue. Facing at least 20 mins for small `sfdx force:source:deploy` executions.    We have also noticed this more recently in our CI process, which in the last week has failed multiple times due to timeout in our job which is waiting for deploy to finish.

**Comment by ram4ufriends** [comment] 2020-07-23 23:05
I am guessing its an issue with the extension itself..because using same org and same package file, ForceCode retrieves components in half the time against SFDX Plugin..

**Comment by rajendrasnagar** [comment] 2021-02-18 10:07
I am facing slow deployment issues when I am working on using Apex Enterprise patterns. I don't know, whether it validate something internally or what. But it usually takes > 10 minutes to deploy.

**Comment by smaddox-sf** [comment] 2021-02-18 22:55
@rajendrasnagar & All - We've done significant work to make deploys & retrieves faster, particularly for single file scenarios.  The work is still in progress so for now you need to check the "Deploy Retrieve" setting in VS Code to try it the changes.  

![image](https://user-images.githubusercontent.com/59572234/108431535-d89d9980-71f7-11eb-93a7-ddac178f5bb5.png)

**Comment by vpreet** [comment] 2021-02-22 23:07
OMG. This is a true life saver. Good bye to frustrating hours of staring at the screen doing nothing. Good bye to sick and tired of excuses during every sprint meeting why a dev/deploy job that takes hardly an hour ends up taking whole day.  Tried single file retrieve and deploy of an Apex and an LWC. It is lightning fast. For the time being I care only about that. Hope other features also speeds up in near future.  This is Godsend especially for heavy UI  LWC development. You won't even remember what finer UI change you were trying to accomplish  if you have to wait for five minutes( and lose focus) to see the results on screen. Hope this speed stays that way. Awesome. Thank you very much.

**Comment by sushilgit** [comment] 2021-03-08 02:43
Hello, Thank you for improving speed of retrieve process. Its running lightning fast for some objects. But does fail for some. e.g. I tried for case and opportunity and i ran into some issues. screenshot attached. let me know if i can provide some additional information. 
![image](https://user-images.githubusercontent.com/10637275/110267619-32d78200-7f8e-11eb-9d55-1f07e4798684.png)

**Comment by smaddox-sf** [comment] 2021-03-08 23:20
Hi @sushilgit - Thanks for trying it out and glad it's helping at least some of the time.  [Can you open a new issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) with the details of the steps you are executing so we can try to repro & fix it?

**Comment by smaddox-sf** [comment] 2021-05-03 19:58
Hi All - Closing this issue as the deploy / retrieve performance enhancements are now in use by default.  You can check to see if you are using them by checking the "Deploy Retrieve" setting in VS Code.

**Closed by smaddox-sf** 2021-05-03 19:58 UTC
Labels: area:deploy/retrieve, type:feedback
