### ISSUE TITLE
Force Source Deploy Context Menu Error

### ISSUE THREAD

**Issue by jamesquinn103** [forcedotcom/salesforcedx-vscode#2199] opened 2020-05-14 23:31 UTC
### Summary

Getting the following error when trying to deploy an apex class via the VS Code right click >> SFDX: Deploy This Source To Org:

 

11:21:01.583 Starting Deploy (Beta)

When retrieving results with Metadata or FullName fields, the query qualifications must specify no more than one row for retrieval. Result size: 2

 

I believe this is due to the Apex class having the same name (minus the namespace) as another Apex class in a Managed Package. This error did not used to happen, and it does not happen when I run the same command on a uniquely named Apex class. The issue also does not happen if I try to do the same thing via CLI.

### Steps To Reproduce:

1.  Connect to an org that has 2 apex classes with the same name (in my example, it was OpportunityLineItemTriggerHandler, one with ffrr namespace)
1.  Right-click on the class you want to deploy and click SFDX: Deploy This Source To Org

### Expected result

Successful deployment, or compilation error
### Actual result

Error message: "When retrieving results with Metadata or FullName fields, the query qualifications must specify no more than one row for retrieval. Result size: 2"
### Additional information

**VS Code Version**: 1.45.1

**SFDX CLI Version**: sfdx-cli/7.57.1-dbf54fc584 darwin-x64 node-v10.15.3

**OS and version**: macOS Catalina 10.15.4

**Comment by smaddox-sf** [comment] 2020-05-15 14:13
Thanks for logging this @jamesquinn103 .  Looks like it's a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/2188.  Closing this one as a duplicate - please feel free to add any other info you think might be missing from that issue.

**Closed** 2020-05-15 14:19 UTC
Labels: status:duplicate
