### ISSUE TITLE
Deploy should alert on modified metadata in the server

### ISSUE THREAD

**Issue by jonathanwiesel** [forcedotcom/salesforcedx-vscode#675] opened 2018-10-15 12:52 UTC
**Is your feature request related to a problem? Please describe.**
In org based development is common that many developers are modifying metadata at the same time or also that a piece of metadata could be modified both via the Salesforce UI or via API. These leads to the situation when a developer using VS Code deploys a change (on an apex class for example) that overwrites other person changes that have been made in the org after the developer retrieved it initially, then the other person development / configuration.

**Describe the solution you'd like**
When deploying verify that the last retrieved version of the metadata is the last one, otherwise show a diff between whats in the org and your deploying changes.

**Comment by vazexqi** [comment] 2018-10-15 17:38
Duplicate of #633.

**Closed by vazexqi** 2018-10-15 17:38 UTC
Labels: duplicate
