### ISSUE TITLE
SFDX Commands not running

### ISSUE THREAD

**Issue by shalvijohari** [forcedotcom/salesforcedx-vscode#2379] opened 2020-07-27 18:13 UTC
Press -> Ctrl+Shift+p
Enter SFDX
Click on SFDX:Create Project

Getting error : Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)
In Output tab error is as below :
[Error - 1:01:11 PM] Connection to server is erroring. Shutting down server.

In Console I see errors as below :
abstractExtensionService.ts:411 Activating extension 'salesforce.salesforcedx-vscode-core' failed: spawn c:\Users\HP\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Cannot activate extension 'Apex' because it depends on extension 'salesforce.salesforcedx-vscode-core', which failed to activate.
_logMessageInConsole @ abstractExtensionService.ts:411
abstractExtensionService.ts:411 Cannot activate extension 'Lightning Web Components' because it depends on extension 'salesforce.salesforcedx-vscode-core', which failed to activate.
_logMessageInConsole @ abstractExtensionService.ts:411
abst

VS Code version: Code 1.47.1 (485c41f, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 6.3.9600

**Comment by smaddox-sf** [comment] 2020-07-28 22:55
Hi @shalvijohari - From the error, it sounds like the CLI is not installed or not setup.  have you installed the CLI?  can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?

**Comment by sirrud** [comment] 2020-07-29 16:10
I am getting the same error and I verified in System Variables in Windows 10 that path is set up with Salesforce CLI.

**Comment by shalvijohari** [comment] 2020-07-29 17:26
I have installed CLI and path variable is also set correctly still I am getting the error...this is the window log I am getting 

[2020-07-29 22:52:26.928] [renderer1] [warning] UNRESPONSIVE extension host, 'salesforce.salesforcedx-vscode-core' took 99% of 5703.128ms, saved PROFILE here: 'C:\Users\HP\AppData\Local\Temp\exthost-e34329.cpuprofile' [{"id":"gc","total":35792,"percentage":1},{"id":"salesforce.salesforcedx-vscode-core","total":5652152,"percentage":99}]

**Comment by lcampos** [comment] 2020-08-04 00:48
This is a duplicate of #2295 , we're working on addressing the issue and will provide an update on the other open issue. I'm doing to close this one in favor of the other open issue.

**Closed by lcampos** 2020-08-04 00:48 UTC
