### ISSUE TITLE
Saving apex (to server) takes approximately 7 minutes

### ISSUE THREAD

**Issue by srkhari** [forcedotcom/salesforcedx-vscode#1389] opened 2019-06-11 14:27 UTC
When trying to save any apex file (controller, an apex class, trigger, ...), VS Code take approximately 7 minutes to successfully save. In case if there are any errors, it fails in few seconds. I tried connecting with multiple sandboxes and I see the same issue consistently. All of this started two weeks ago and before that, it used to take few seconds to a minute at most. 

Steps to reproduce:
1. Connect any sandbox
2. Create a new apex class or edit an existing apex class.
3. Right click the file from the explorer and click 'SFDX: Deploy to source org'

Expected: The file should get saved in SFDC server in few seconds if it is successfully compiled. 
Actual: It takes approximately 7 minutes to save.

<img width="1519" alt="VSCode-Issue-01" src="https://user-images.githubusercontent.com/10715147/59280233-42982a00-8c33-11e9-9c49-37ea5b7020d0.png">

Version: 1.35.0 (system setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063
SFDX CLI Version**: 45.15.1

**Comment by ntotten** [comment] 2019-07-08 18:13
Duplicate of #917

**Closed by ntotten** 2019-07-08 18:13 UTC
