### ISSUE TITLE
Deploy Source to Org Has Exit Code 0 But File Is Not Deployed Into Org

### ISSUE THREAD

**Issue by RCMoonpie** [forcedotcom/salesforcedx-vscode#3042] opened 2021-03-09 15:17 UTC
```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.3 (1.4.3)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.1.1 (core)
├─ limits 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 51.3.0 (core)
├─ salesforce-alm 51.1.1 (core)
├─ schema 1.0.4 (core)
├─ user 1.1.2 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.90.2 (core)
telemetry 1.1.1 (core)
```

Default Org authorized:
![Deploy Source Exit Code 0 But No Deployment_02](https://user-images.githubusercontent.com/42147369/110479032-922ab480-80aa-11eb-889a-7d14d6a5ec1f.png)

Right-click an Apex class and select `SFDX: Deploy Source to Org`:
![Deploy Source Exit Code 0 But No Deployment_03](https://user-images.githubusercontent.com/42147369/110479669-462c3f80-80ab-11eb-9535-265086c215b2.png)

Pop-up indicates success; Output shows `exit code` of `0`:
![Deploy Source Exit Code 0 But No Deployment_01](https://user-images.githubusercontent.com/42147369/110480172-d2d6fd80-80ab-11eb-84f5-3b6e266b3bff.png)
_NOTE: The usual `Deployed Source` table that shows in the Output below the `exit code`, which lists the file(s) that were deployed, does not appear._

File does not appear in Org:
![Deploy Source Exit Code 0 But No Deployment_04](https://user-images.githubusercontent.com/42147369/110480147-cc488600-80ab-11eb-96bf-9b859edb70d9.png)

---------------------
Relevant?
Prior attempts failed:
![Deploy Source Exit Code 0 But No Deployment_05](https://user-images.githubusercontent.com/42147369/110502705-112ae780-80c1-11eb-952e-d0b9ddeed75e.png)

After multiple tries, a subsequent attempt fully succeeded:
![Deploy Source Exit Code 0 But No Deployment_06](https://user-images.githubusercontent.com/42147369/110502941-49322a80-80c1-11eb-8b6d-91912af150da.png)

![Deploy Source Exit Code 0 But No Deployment_07](https://user-images.githubusercontent.com/42147369/110492236-9e693e80-80b7-11eb-94ef-f25b852ea63e.png)

---------------------
I think I have DNS issues causing the early failures (and other problems that I often have), so this issue is not necessarily pertaining to that.  It is pointing out that I get a success message and a success `exit code` when there was not success.

**Comment by smaddox-sf** [comment] 2021-03-09 22:15
Hi @RCMoonpie - Thanks for reaching out and for the detailed steps.  I believe this may be a duplicate of an open CLI issue - https://github.com/forcedotcom/cli/issues/904.  

To confirm whether it is the same, issue, can you try running deploy command directly from the terminal?  Do you get the same result?  (the command is within the output shown in the screenshots - `sfdx force:source:deploy...`)

**Comment by RCMoonpie** [comment] 2021-03-10 17:58
Hi Stephanie [@smaddox-sf] : My apologies - I really did search around for a similar issue to which to add my comments, rather that submit a new issue; but I failed to look in the **cli** repository.

I've tried a number of times this morning to run the command in the terminal:
![Deploy Source Exit Code 0 But No Deployment_08](https://user-images.githubusercontent.com/42147369/110667916-5cf89200-8190-11eb-9834-998a85156a41.png)

A few items to note:
- I thought the INVALID_SESSION_ID was part of the DNS issues I think I have.  But that last run of the command was on a VPN, and when I am on this VPN I usually don't have some of the same issues (hence partly why I think I have DNS issues).
- The **Output** tab shows nothing after each of these runs - literally nothing.
- `*** Deploying with REST ***` only recent began to appear when deploying/retrieving via terminal, and I haven't found any information on that.  So I don't know if it is "works as designed" or if that is some indication of an issue.

Sometimes after I get the INVALID_SESSION_ID, I will run `sfdx force:org:list` to verify everything looks good.  And if it does, and then I re-run my deploy command, it often works - as is the case just now:
![Deploy Source Exit Code 0 But No Deployment_09](https://user-images.githubusercontent.com/42147369/110669230-bca36d00-8191-11eb-9645-949537d6df03.png)

**Comment by smaddox-sf** [comment] 2021-03-11 23:39
Hi @RCMoonpie - No apology necessary!  We've confirmed this is the same as https://github.com/forcedotcom/cli/issues/904, so closing this issue in favor of that one.  Please follow https://github.com/forcedotcom/cli/issues/904 for updates.

**Closed by smaddox-sf** 2021-03-11 23:39 UTC
