### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kagool** [forcedotcom/salesforcedx-vscode#1048] opened 2019-02-13 09:35 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.1.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/2859685/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment] 2019-02-13 10:03
Duplicate of #968

**Comment by praksb** [comment] 2019-02-22 21:21
@Kagool We have made some improvements to Apex LSP performance in our latest extension update. Can you please update to the latest Apex extension (v45.3.0) and let us know if you still have any performance issues? Please open a new github issue if you still see any perf related problems.

#1092

**Closed by praksb** 2019-02-22 21:21 UTC
Labels: bug
