### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sourabh42** [forcedotcom/salesforcedx-vscode#2761] opened 2020-11-25 04:25 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.5.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\hp\AppData\Local\Temp\salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-11-30 20:03
Dupe of #2410

**Closed by smaddox-sf** 2020-11-30 20:03 UTC
