### ISSUE TITLE
Schema.SObjectType.[] Is not resolving

### ISSUE THREAD

**Issue by JJWinter** [forcedotcom/salesforcedx-vscode#3076] opened 2021-03-18 09:20 UTC
### Summary
Any reference to Schema.SObjectType.[Standard or Custom] is indicated and highlighted as an Error:
**Variable does not exist: Schema.SObjectType.Lead**
**Variable does not exist: Schema.SObjectType.Opportunity**
All SObject definitions have been refreshed, and files for these objects exist within .sfdx/tools/sobjects

### Steps To Reproduce:

1.  View a class referencing  Schema.SObjectType.[Object].getRecordTypeInfosByName();
1.  Refresh SObject Definitions
1. Save

### Expected result

No error should occur.

### Actual result

Error panel and window highlights references to Schema.SObjectType.[Object] as an error.

### Additional information

![image](https://user-images.githubusercontent.com/26584951/111601651-7cb03b80-87ca-11eb-9522-8ecaf3c67d2f.png)

**VS Code Version**: 1.54.3

**SFDX CLI Version**: sfdx-cli/7.91.0-6a6ed69ebe darwin-x64 node-v14.15.4

**OS and version**: macOS Big Sur 11.2.1 (20D74)

**Comment by smaddox-sf** [comment] 2021-04-09 18:36
Duplicate of #2028

**Closed by smaddox-sf** 2021-04-09 18:36 UTC
Labels: status:needs eng review
