### ISSUE TITLE
Cannot read property 'getInstance' of Undefined.

### ISSUE THREAD

**Issue by aman993** [forcedotcom/salesforcedx-vscode#2418] opened 2020-08-14 10:24 UTC
When I try to retrieve source from org or authorize an org in VSCode, it says 'Cannot read property 'getInstance' of Undefined'. I tried everything that has to be done. Please let me know what else can be done. This is not for lwc component. It is happening for normal salesforce project authorization as well which not in lwc.

**Comment by chriswill** [comment] 2020-08-14 16:02
This is a dupe of #2414

**Comment by lcampos** [comment] 2020-08-14 16:49
Closing since it's a duplicate of #2414 as pointed out in the previous comment

**Closed by lcampos** 2020-08-14 16:49 UTC
