### ISSUE TITLE
Error: Unable to retrieve source from Trailhead Playground.

### ISSUE THREAD

**Issue by ashar165** [forcedotcom/salesforcedx-vscode#708] opened 2018-10-30 09:44 UTC
### Summary

Error: ERROR:  **Unexpected file found in package directory: c:\Users\ashar165\Desktop\Google TP\.sfdx\orgs\aashish.1710.sharma@resourceful-moose-221075.com\metadataTypeInfos.json.** comes when I try to retrieve source from a successfully connected trailhead playground. 

### Steps To Reproduce:

1.  Authenticate a Trailhead Playground.
1.  Create a SFDX project with manifest.
1. right click on .sfdx folder inside your project in VS code and run SFDX: Retrieve Source from an ORG.

### Expected result

All metadata mentioned in package.xml should be retrieved.

### Actual result

Retrieve command failed giving error: unexpected file found in directory<directory_Path>

### Additional information

![image](https://user-images.githubusercontent.com/26997260/47698925-2d880100-dc37-11e8-90d4-90866d38839e.png)

**VS Code Version**: 1.26.1

**SFDX CLI Version**: 6.36.0-391bf95737 (windows-x64) node-v8.9.4

**OS and version**: Win10 Pro(64 bit) Version-1703

**Comment by ntotten** [comment] 2018-10-30 11:53
You need to right click on the `package.xml` file and click `Retrieve source`. Duplicate of #678

**Closed by ntotten** 2018-10-30 11:53 UTC

**Comment by ashar165** [comment] 2018-10-31 05:49
Yeah, It worked when right clicked on package.xml. Thanks 👍
