### ISSUE TITLE
Execute anonymous no longer responding with logs

### ISSUE THREAD

**Issue by Techley-git** [forcedotcom/salesforcedx-vscode#2979] opened 2021-02-24 00:48 UTC
### Summary

Execute anonymous no longer responding with logs

### Steps To Reproduce:

1.  Insert account via SFDX execute anonymous with editor contents (via command pallet - ctrl+shift+p) 
Example:
Account a = new Account();
a.RecordTypeId = '012220000004bXeAAI';
a.Name = 'testt';
insert a;
system.debug('account id =====' + a.id);

### Expected result

Output tab  - Salesforce CLI acknowledges the command and displays the response/log from the executed anonymous apex

### Actual result

Just the notification 
![image](https://user-images.githubusercontent.com/72884210/108928120-87761700-75f6-11eb-8065-f83230307eac.png)

### Additional information
The only thing I can think of that I changed that might have affected this is turning on the setting sync feature in VSCode (prepping for a new machine)?

_Feel free to attach a screenshot_.

**VS Code Version**:1.53.2

**SFDX CLI Version**:7.81.0 and 7.88.4

**OS and version**: Win10 20H2

**Comment by lcampos** [comment] 2021-02-24 01:39
Hi @Techley-git , this is a duplicate of issue https://github.com/forcedotcom/salesforcedx-vscode/issues/2947. We have a fix that will go out in this week's release, in the meantime you can manually focus on the correct Output option and see the command's response. Sorry for the inconvenience this has caused you.

**Closed by lcampos** 2021-02-24 01:39 UTC
