### ISSUE TITLE
SFDX does not clear Problems panel after fixing errors and submit again

### ISSUE THREAD

**Issue by gtiancai** [forcedotcom/salesforcedx-vscode#2645] opened 2020-10-20 10:08 UTC
### Summary

SFDX does not clear Problems panel after fixing errors and deploy the metadata file again, it's confused and make harder to fix issues.

### Steps To Reproduce:

1. create a SFDX project and log into an Org
2. create a class with some syntax error
3. deploy it
4. errors is shown in Problems panel.
5. fix all issues and deploy it again

### Expected result

Should no errors in Problem Panel

### Actual result

Errors are still there.

### Additional information

**VS Code Version**:
1.50.1
**SFDX CLI Version**:
7.76.1
**OS and version**:
Win 10

**Comment by aranwe** [comment] 2020-10-26 12:56
I confirm this bug.

**Comment by lcampos** [comment] 2020-10-26 21:15
Closing this as a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/2608, please follow that issue for updates

**Closed by lcampos** 2020-10-26 21:15 UTC
