### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ajith007** [forcedotcom/salesforcedx-vscode#1885] opened 2020-01-17 16:20 UTC
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `47.10.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.41.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 6338,
		"activateCallTime": 115,
		"activateResolvedTime": 1167,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-lwc",
				"_lower": "salesforce.salesforcedx-vscode-lwc"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by ntotten** [comment] 2020-01-17 17:57
I am not clear on what the issue is here. Could you please provide reproduction steps and any error messages, etc. and reopen this issue. Thanks!

**Comment by ajith007** [comment] 2020-01-17 19:53
@ntotten, I was trying to troubleshoot why the extension is running very slow. Sometimes it takes few minutes to just start the deploy to sandbox. The Lightning Web Components extension was showing unresponsive and indicated a performance issue, so I tried reporting it directly from VS Code - 
![image](https://user-images.githubusercontent.com/1762945/72641424-c9328980-392f-11ea-9639-aa8e5de4204b.png)
I just pasted the information that was collected by the extension. But sounds like it didn't pull enough information.

What should I do to improve the speed of deploying files into the sandbox? Why is it even taking a while to show the progress? It has gotten bit worse in the past week or so. Once I right click and select 'Deploy this source to Org', I switch to something else and come back and check after several minutes. That's not good. Its taking lot of time to get things done. 

Please let me know if you need any additional info to troubleshoot the issue.

**Comment by ajith007** [comment] 2020-01-17 20:13
@ntotten, here's the log of a JS file I just deployed to the sandbox. 

> Starting SFDX: Deploy Source to Org
> 
> 14:07:56.247 sfdx force:source:deploy --sourcepath c:\Users\Ajith\vscode\br-uatpartial-new\force-app\main\default\staticresources\brds_hiring_event_app_js.js --json --loglevel fatal
> 14:08:56.973 sfdx force:source:deploy --sourcepath c:\Users\Ajith\vscode\br-uatpartial-new\force-app\main\default\staticresources\brds_hiring_event_app_js.js --json --loglevel fatal ended with exit code 0
> 
> === Deployed Source
> STATE  FULL NAME                 TYPE            PROJECT PATH                                                                     
> ─────  ────────────────────────  ──────────────  ─────────────────────────────────────────────────────────────────────────────────
> Add    brds_hiring_event_app_js  StaticResource  force-app\main\default\staticresources\brds_hiring_event_app_js.js               
> Add    brds_hiring_event_app_js  StaticResource  force-app\main\default\staticresources\brds_hiring_event_app_js.resource-meta.xml

As you can see from the timestamps, it took about 1 minute to save the file. But it took few minutes to start the deploy.

**Comment by ntotten** [comment] 2020-03-30 19:00
Duplicate of #917

**Closed by ntotten** 2020-03-30 19:00 UTC
Labels: area:lwc
