### ISSUE TITLE
Retrive taking too long

### ISSUE THREAD

**Issue by dima007arenko** [forcedotcom/salesforcedx-vscode#5359] opened 2024-01-24 14:30 UTC
### Summary

Retrive of Metadata other that LWC or ApexClass is taking so much time, that I never waited when it finishes

### Steps To Reproduce:

1. Select and open Permission Set
2. Right click inside of opened XML file
3. click retreive source from org

### Expected result

file is retrived normally

### Actual result

file is never retreived

### Additional information

I tried both with enabled and disabled source tracking checkbox

**Salesforce Extension Version in VS Code**:
Latest 59.13.0
**SFDX CLI Version**:
@salesforce/cli/2.24.4 win32-x64 node-v20.10.0
**OS and version**:
Windows 10
**VS Code version**:
Latest

**Comment by dima007arenko** [comment] 2024-01-24 15:02
downgrade to 58.14.1 and 2.22.2 helped

**Comment by daphne-sfdc** [comment] 2024-01-24 15:12
Hi @dima007arenko,
Our team is aware of this long-running issue of slow deploy and retrieve times, and we have been keeping track of it at #4865.  We are planning to investigate this issue further and try to tackle it in this iteration. 

I'm happy to hear that downgrading your CLI and extensions is a usable workaround, although v58.14.1 is quite old and the downgrade means you won't be able to access our latest updates to the extensions.

I'm going to close this issue as a duplicate of #4865.  If you continue to find slow speeds in other areas that are not deploy/retrieve, please feel free to reopen or submit another issue - we're keeping track of slowness in each individual feature as a separate issue.

**Closed by daphne-sfdc** 2024-01-24 15:12 UTC
