### ISSUE TITLE
Retrieve Standard Value Sets in Org Browser 

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/salesforcedx-vscode#1579] opened 2019-08-22 09:48 UTC
### Summary

No Standard Value Set visible in Org Browser.

### Steps To Reproduce:

1.  Open Org Browser.
1.  Click on Standard Value Sets.

### Expected result

The list of Standard Value Sets should be displayed.

### Actual result

Just displaying "No components available".

### Additional information

**VS Code Version**: 1.37.1 + Extension pack 46.10

**SFDX CLI Version**: sfdx-cli 7.20.1 (core)

**OS and version**: MacOS Mojave

**Comment by FabienTaillon** [comment] 2019-08-26 08:39
Actually there are several metadata where it does not work, so I'm sure you already know about it.

**Comment by aldoforce** [comment] 2020-04-03 16:23
any update around this? I'm facing the same problem. Can't retrieve Case status fields.

**Comment by aldoforce** [comment] 2020-04-03 16:27
@FabienTaillon even if you don't use OrgBrowser, the issue is the same with CLI:

```
sfdx force:source:retrieve -m StandardValueSet

=== Retrieved Source
No results found

```

**Comment by FabienTaillon** [comment] 2020-04-03 17:40
If you know which StandardValueSet, you can specify then name directly:
`sfdx force:source:retrieve -m StandardValueSet:CaseStatus`

You can't retrieve all at once with the command because this Metadata Type doesn’t support the wildcard character * (asterisk).

However, regarding the VS Code extension, I would expect to see the list anyway because from a user perspective we don't care that the API is not good. I would even prefer an hardcoded list that would be updated at every release than seeing nothing.

Obviously the best fix would be to fix the API itself.

**Comment by AltiusRupert** [comment] 2020-05-15 16:52
You can stick this file into your manifest folder, then click-right and "SFDX: Retireve Source in Manifest from Org"


[package-StandardValueSet.xml.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/4635848/package-StandardValueSet.xml.zip)

**Comment by MooseAteJack** [comment] 2020-09-21 22:47
Also having this issue.

There are ways to work around the issue and force:source:pull is fine with seeing change in StandardValueSets but  the browser can't find them.

**Comment by kennethkim1221** [comment] 2020-10-05 12:28
Hi all. I am experiencing the same thing now. I tried Fabien's suggestion in using sfdx force:source:retrieve -m StandardValueSet:LeadSource but the result was:

=== Retrieved Source
No results found

Anyone figured out how to to this?

**Comment by FabienTaillon** [comment] 2020-10-05 12:59
Have you checked that nothing was retrieved ? I sometimes get a "No results found" message, but the metadata is retrieved anyway.

**Comment by dsobkowiakWorkBench** [comment] 2021-02-11 17:04
Thanks a lot the hint with sfdx force:source:retrieve -m StandardValueSet:CaseStatus helped me out.
Many thanks

**Comment by austinmyer** [comment] 2021-09-03 05:55
I am unable to retrieve the inactive value. Only the active values gets retrieved. Is it a default behavior of source:retrieve command?

**Comment by pbattisson** [comment] 2021-11-18 16:36
Also having this same issue - is this because it doesn't support wildcard in the metadata API?

**Comment by MoTalhaSPW** [comment] 2021-11-22 10:59
> sfdx force:source:retrieve -m StandardValueSet:CaseStatus
This command is a life saver. Thank you

**Comment by klewis-sfdc** [comment] 2022-05-03 20:22
Closing as resolved by https://github.com/forcedotcom/salesforcedx-vscode/issues/1579#:~:text=support%20for%20StandardValueSet%20(-,%233992,-)

**Closed by klewis-sfdc** 2022-05-03 20:22 UTC
Labels: area:orgbrowser
