### ISSUE TITLE
i have download the updated version both java jdk and sfdx (cli) and when i am trying to install salesforce extension pack in the vs code facing below errors

### ISSUE THREAD

**Issue by vai12** [forcedotcom/salesforcedx-vscode#3530] opened 2021-09-03 13:27 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:
<img width="956" alt="Screenshot 2021-09-03 104027" src="https://user-images.githubusercontent.com/55106242/132012825-fcc71460-215f-4a21-974a-ae16aeb06223.png">

**Comment by smaddox-sf** [comment] 2021-09-07 16:31
Hi @vai12 - Are you seeing the error at the time VS Code is trying to download the extension?  If so, it seems like it might be related [to this open issue on the VS Code repo](https://github.com/microsoft/vscode/issues/131022).

**Comment by smaddox-sf** [comment] 2021-09-07 16:33
Possible duplicate of #3519

**Closed** 2021-09-14 17:25 UTC
Labels: more information required
