### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pri-art** [forcedotcom/salesforcedx-vscode#2525] opened 2020-09-15 06:47 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.9.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\User\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-09-15 15:48
There's not a lot of details here, but I believe it's a duplicate of #2410.  There's a workaround posted on that issue.  Please check it out and weigh in if you have other input.

**Closed by smaddox-sf** 2020-09-15 15:48 UTC
