### ISSUE TITLE
Compiles on pull of Git

### ISSUE THREAD

**Issue by JorneVL** [forcedotcom/salesforcedx-vscode#906] opened 2019-01-28 09:59 UTC
### Summary

Pull changes on apex classes via Git.
The changed classes will compile when the pull is completed.

### Steps To Reproduce:

1.  Create Repo locally with some classes and connect to SF
1.  Change classes on other location
1.  Open VS Code on repo where these plugins are active.
1.  Pull everything and wait until these classes will be compiled on the server

### Expected result

The extensions shouldn't do anything

### Actual result

The extensions compile classes

### Additional information

**VS Code Version**: 1.30

**SFDX CLI Version**: 6.5

**OS and version**: W 10

**Comment by ntotten** [comment] 2019-01-28 14:33
Duplicate of #883

**Closed by ntotten** 2019-01-28 14:33 UTC
Labels: duplicate
