### ISSUE TITLE
Salesforce CLI not installed when it is and available on Path

### ISSUE THREAD

**Issue by rahulchaudharyofficial** [forcedotcom/salesforcedx-vscode#2178] opened 2020-05-07 07:32 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  install salesforcecli using npm command npm install -g sfdx-cli and then make sure sfdx is available on path. check with echo $PATH
1.  Try open an existing or new sfdxproject in vscode.

### Expected result

Vscode should start working with sfdx-cli
### Actual result
getting salesforce cli not installed error while it is and available on path
### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.44.2

**SFDX CLI Version**: 7.56.1

**OS and version**: Linux manjarobook 5.6.8-1-MANJARO #1 SMP PREEMPT Wed Apr 29 19:05:17 UTC 2020 x86_64 GNU/Linux

**Comment by lcampos** [comment] 2020-07-10 00:51
I'm closing this since it's a duplicate of #2254 . We'll post follow ups on that issue.

**Closed by lcampos** 2020-07-10 00:51 UTC

**Comment by MarcTCruz** [comment] 2024-01-15 14:19
> I'm closing this since it's a duplicate of #2254 . We'll post follow ups on that issue.

Since the other has been closed, the other has no mention of CLI not being installed, the subject of the other is not precise to the issue presented here, the other does not provide installation infos, etc, etc, this can at most be related instead of duplicate, can someone reopen this?
