### ISSUE TITLE
Apex Language Server no longer detects any custom object or field

### ISSUE THREAD

**Issue by ebraun95** [forcedotcom/salesforcedx-vscode#5335] opened 2024-01-12 22:57 UTC
### Summary

I was getting this null error for the past few days, "Cannot read properties of null (reading 'capabilities')". I found a solution stating to remove my_sfdx_repo/.sfdx/tools/246, and relaunch vscode. Once it came back up, the language server can not find any custom objects/fields and is throwing warnings for all classes/triggers that contain a custom object or field.

### Steps To Reproduce:

1.  remove .sfdx/tools/246
1.  restart vscode

### Additional information
The apex language server is running, it only sees standard objects and fields. We have just under 200 custom objects.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/a8b812eb-dd31-4607-a764-eb620a34975a)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/b9b32d92-bb14-40a9-afc7-b02042931e15)

**Salesforce Extension Version in VS Code**:
v59.13.0 (newest) have tried to downgrade with same results

**SFDX CLI Version**:
salesforce/cli/2.23.20 darwin-arm64 node-v20.10.0

**OS and version**:
MacOs Ventura 13.4.1 Apple Silicon m2 chip

**VS Code version**:
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

**Comment by CristiCanizales** [comment] 2024-01-15 21:41
Hi @ebraun95, can you try deleting whole `.sfdx` folder, reload vscode, reauth to your org, run `SFDX: Refresh SObject Definitions` from the command palette (CMD + Shift + P) and check again?

**Comment by CristiCanizales** [comment] 2024-01-15 22:13
@ebraun95 if you reload vscode again, are all the warnings still there?

**Comment by ebraun95** [comment] 2024-01-15 22:17
@CristiCanizales I closed the project, quit vscode, relauched it, reopened the project and the warnings are still present.

**Comment by peternhale** [comment] 2024-01-16 13:37
@ebraun95 Please run `SFDX: Refresh SObject Definitions` to see if that helps.

**Comment by ebraun95** [comment] 2024-01-16 14:53
@peternhale I have already done this several times. The warming from the last image are still there.

**Comment by peternhale** [comment] 2024-01-16 15:06
@ebraun95 Just double checking, does dir `.sfdx/tools/sobjects/customObjects` have any contents?

**Comment by ebraun95** [comment] 2024-01-16 15:29
also the warnings from the last image are only from 1 class. I get these warnings whenever i open any class/trigger. For example 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/183ce005-3888-474d-822c-810f68b693e3)

**Comment by peternhale** [comment] 2024-01-16 15:59
@ebraun95 I am trying to reproduce what you are seeing, using dreamhouse-lwc from Salesforce trailhead. These are the steps I have done thus far.

* remove `.sfdx/tools/246` and `.sfdx/tools/sobjects`
* reload vscode window
This is the initial state for a workspace wrt Apex language server and sobjects and one should find a structure like this
```
tree -d .sfdx/tools 
.sfdx/tools
├── 246
│   └── StandardApexLibrary
│       ├── ApexPages
│       ├── AppLauncher
│       ├── Approval
│       ├── Auth
│       ├── Cache
│       ├── Canvas
│       ├── ChatterAnswers
│       ├── ConnectApi
│       ├── DataSource
│       ├── Database
│       ├── Datacloud
│       ├── Dom
│       ├── EventBus
│       ├── Flow
│       ├── KbManagement
│       ├── Messaging
│       ├── Metadata
│       ├── Process
│       ├── QuickAction
│       ├── Reports
│       ├── Schema
│       ├── Search
│       ├── Site
│       ├── Slack
│       ├── Support
│       ├── System
│       ├── TerritoryMgmt
│       ├── TxnSecurity
│       ├── UserProvisioning
│       ├── VisualEditor
│       └── Wave
├── debug (optional)
│   └── logs
├── sobjects
│   └── standardObjects
├── soqlMetadata
│   ├── customObjects
│   └── standardObjects
```
The language server will create the apex.db and install the StandardApexLibrary (~1100 Apex classes). The Apex extension will also seed the `sobject/standadObjects` with 19 sobjects, mostly related to CRM.

The output from the Apexlanguage server should look like this 
```
08:35:56.668 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
08:35:56.744 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in Apex types.
08:35:56.746 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Collecting built-in standard types from jar
08:35:57.874 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done collecting built-in standard types from jar
08:35:57.874 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning Apex Standard Library.
08:35:58.101 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done scanning Apex Standard Library.
08:35:58.103 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Starting ApexIndexer.
08:35:58.103 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Start indexer.
08:35:58.107 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
08:35:58.108 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning workspace source.
08:35:58.127 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Loading existing resource files from apex.db.
08:35:58.144 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Building change list.
08:35:58.167 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Applying found changes
08:35:58.167 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Creating 32 Apex artifacts in Apex DB
Jan 16, 2024 8:35:58 AM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 6 ms.
08:35:59.724 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: StandardObjects: 19
08:35:59.725 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: CustomObjects: 0
08:35:59.725 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: ApexFiles: 13
08:35:59.725 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: ErrorFiles: 6
08:35:59.725 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Total Memory (MB): 384
08:35:59.725 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Used Memory (MB): 162
08:35:59.725 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 1592 ms.
08:35:59.726 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 3058 ms.
```

The language server, in the ApexIndexer section, scans the local workspace for changes between the apex index and apex artifacts. Given this is the initial scan after installing a new apex.db, one would expect to see your custom apex class and trigger files discovered and indexed, as noted by `ApexIndexer: ApexFiles: 13`. This scan would also include entries found in `.sfdx/tools/sobjects`, as noted by `ApexIndexer: StandardObjects: 19` in the log.

This appears to be similar to your original share of the language server output.

In this state one "should" see warnings for custom object that are not present.

During sobject refresh, the org is queried for the requested sobject metadata sobjects (All, standard or custom), those results are written to the appropriate subfolder in sobjects and then the language server will reindex the workspace.

This is what I see after sobject refresh with dreamhouse-lwc repo

```
08:53:54.746 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - Processing changes to SObjects Created
08:53:54.749 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Start indexer.
08:53:54.750 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
08:53:54.750 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning workspace source.
08:53:54.773 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Loading existing resource files from apex.db.
08:53:54.784 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Building change list.
08:53:54.815 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Applying found changes
08:53:54.815 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Updating 19 Apex artifacts in Apex DB
08:53:55.401 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Creating 1144 Apex artifacts in Apex DB
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: StandardObjects: 1161
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: CustomObjects: 2
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: ApexFiles: 13
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: ErrorFiles: 6
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Total Memory (MB): 624
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Used Memory (MB): 388
08:53:57.945 [ApexIndexer RUNNING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 3179 ms.
```
These two entries show that the scanner found 19 existing sobjects in the DB that required updating because they changed on the files system and it is adding 1144 entries that are new in the file system.

Would you retrace these steps for you project and capture the language server results as I have done?

**Comment by ebraun95** [comment] 2024-01-16 16:17
@peternhale I retraced what you did, the first image is after removing the 246 and sobjects folders. The second image is after I refreshed the sobject definitions.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/15b3994c-a0a1-4036-91eb-88cbdfcf33bd)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/e468f25b-a85a-431d-ba54-aeddf7a7d7f8)

**Comment by ebraun95** [comment] 2024-01-16 16:25
@peternhale sorry i refreshed the window after refreshing. I did it again but did not reload. Here is what I see.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/4dfed730-1608-41dd-8beb-d759c97fd4fd)

**Comment by peternhale** [comment] 2024-01-16 16:28
@ebraun95 Thank you. The results show that the custom objects are being picked up by the language server during indexing. I assume you are still seeing the warnings?

**Comment by ebraun95** [comment] 2024-01-16 16:32
@peternhale That would be correct.

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/984f94cc-4ae9-46e0-b682-b8cf29a1c5cc)

**Comment by peternhale** [comment] 2024-01-16 16:41
@ebraun95 would it be possible to either provide a snippet of your code around these warnings? I just want to see the syntax you are using.

**Comment by ebraun95** [comment] 2024-01-16 17:00
@peternhale after going though a few classes, here are a few that I can share.

Getting error on all of these
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/a5131600-f276-4d6c-8f96-422942f901a8)

Getting error on all of these
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/2ba94b11-f043-4101-a1ea-26eafbb5e92e)

Getting error on all of these
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/828f8fe2-558c-4a3e-9ee8-a5a5acab6e93)

Seems to be anytime have Database.Query. Normal loops with the object directly referenced seem to be okay
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/4ac3433c-ce2a-49b4-b3be-1b55be9e8c74)

Same error with Attachment object and Parent as well
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/9e91aab5-7159-43f0-8a24-268a74174c0f)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/19348568/74b08fdd-d83a-401f-a42a-1db40d715caa)

**Comment by peternhale** [comment] 2024-01-16 17:39
@ebraun95 In general, its seems to be related to the notion of namespaces in the apex world, or at least the first example is.

I was able to reproduce the warning with this `Schema.RecordTypeInfo mid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('foo');`

In this case `Schema` is both a standard apex class in the `System` namespace AND as a namespace itself.

I was able to deploy the snippet above w/o error. I know the warning are annoying (and appear to be incorrect), so I will log a bug to investigate.

**Comment by ebraun95** [comment] 2024-01-16 17:51
@peternhale thank you for looking into this. Since the custom objects and fields are mainly no longer throwing errors and its not hindering my ability to actually do anything it doesn't appear to be a major issue.

**Comment by peternhale** [comment] 2024-01-16 18:04
Thanks for letting me know @ebraun95. Hopefully we will be able to improve the language server to provide more accurate information.

**Comment by diyer** [comment] 2024-02-23 19:23
Created a new work item for the warnings. Closing this as the original issue has been fixed

**Closed by diyer** 2024-02-23 19:23 UTC
Labels: type:bug, area:apex
