### ISSUE TITLE
Unable to sync the data to local machine in VS Code.

### ISSUE THREAD

**Issue by vikash-ag** [forcedotcom/salesforcedx-vscode#2483] opened 2020-09-03 16:49 UTC
Issue Type: <b>Bug</b>

After the last update of VS code, when I'm creating a new project and syncing the salesforce sandbox to the local machine is throwing some error message consisting this: "ERROR running force:source:retrieve:  Cannot read property 'record' of undefined".  This error needs to be resolved as soon as possible as I'm not able to sync any new projects.

Extension version: 49.8.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by smaddox-sf** [comment] 2020-09-15 16:32
I believe this is a duplicate of [a CLI bug](https://github.com/forcedotcom/cli/issues/581) that was patched last week.  Can you update the SFDX CLI to the latest version and retry?  Let us know if it succeeds.

**Comment by vikash-ag** [comment] 2020-09-16 12:44
Yes, it was due to older CLI version. I already updated. This can be closed
now.

Thanks!

*Vikash Agarwal*
*Email: vikashagarwal208.va@gmail.com <vikashagarwal208.va@gmail.com>*
*Contact:  +91-8910819645*

**Comment by lcampos** [comment] 2020-09-16 16:24
Closing since the fix was released on the latest version of the Salesforce CLI

**Closed by lcampos** 2020-09-16 16:24 UTC
