### ISSUE TITLE
Retrieving metadata for lookup fields to standard sobjects results in invalid metadata

### ISSUE THREAD

**Issue by JNiedle** [forcedotcom/salesforcedx-vscode#1294] opened 2019-04-29 01:14 UTC
### Summary

When retrieving a new custom object from an org, if there is a lookup field to a standard object, an "__c" is appended to the object name in the "referenceTo" node of the XML:

![image](https://user-images.githubusercontent.com/1660128/56872627-ee0f6580-6a5d-11e9-81e2-1e69f41a7d4c.png)

### Steps To Reproduce:

1.  Create a new object in an org
1.  Add the new object's developername to the project.xml in the CustomObject section
1.  Run command "Retrieve source in Manifest from Org"
1.  Switch to a different org (like another sandbox)
1.  Right click on the object's folder and deploy the source to the new org.

### Expected result

In the <fieldname>.field-meta.xml for lookup fields, standard sobjects should not have "__c" appended to them in the "referenceTo" field.

### Actual result

In the <fieldname>.field-meta.xml for lookup fields, standard objects do have "__c" appended to them in the "referenceTo" field which prevents the deployment to other orgs:
![image](https://user-images.githubusercontent.com/1660128/56872710-a937fe80-6a5e-11e9-9791-217686b71c03.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.33.1

**SFDX CLI Version**: 7.3.0-94ecf2d5ee

**OS and version**: Windows 10 version 1809

**Comment by lcampos** [comment] 2019-06-20 01:32
@JNiedle I'm closing this since the issue has been addressed in the CLI. I've confirmed it works in version 7.11.2. Thanks for providing feedback and feel free to re-open the issue if you still run into it after updating your Salesforce CLI.

**Closed by lcampos** 2019-06-20 01:32 UTC
