### ISSUE TITLE
Cannot read property 'split' of undefined when retrieve package.xml

### ISSUE THREAD

**Issue by filipaGitHub** [forcedotcom/salesforcedx-vscode#3234] opened 2021-05-12 17:24 UTC
Hi,

I am trying to retrieve source from my org through the **package.xml** - **SFDX:Retrieve This Source from Org**
I am getting this error:

**SFDX: Retrieve Source from Org failed to run**
**Cannot read property 'split' of undefined**

I have been working on this project in GitHub and it was working just fine until it suddenly stopped retrieving through the **package.xml**
I have already tried to reinstall Salesforce Extension Pack from Visual Studio Code. (Complete Package which comprises of multiple extension) from visual studio and also visual studio itself but I am still getting this error.

If I use the command line **sfdx force:source:retrieve -x manifest/package.xml** it works. But it only works if I use the command line and before I didn't have to use it.

<img width="960" alt="github issue 1" src="https://user-images.githubusercontent.com/78536080/118018037-305b2500-b34f-11eb-9120-265871b170f8.PNG">
<img width="810" alt="github issue2" src="https://user-images.githubusercontent.com/78536080/118018051-32bd7f00-b34f-11eb-84ea-9e894165a3fa.PNG">

**Comment by smaddox-sf** [comment] 2021-05-12 17:37
Thanks for reporting this @filipaGitHub .  Marking this as a duplicate of #3218 .  Please feel free to add any other comments on that issue.

**Closed by smaddox-sf** 2021-05-12 17:37 UTC
