### ISSUE TITLE
Aura Language Server - Request textDocument/hover failed.

### ISSUE THREAD

**Issue by scromiecaremore** [forcedotcom/salesforcedx-vscode#1265] opened 2019-04-15 20:43 UTC
### Summary

While in a separate project folder, I try to work with JavaScript code and get complaints from the Aura Language Server in the Output window.  The error is:

[Error - 1:00:10 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'aura' of undefined
  Code: -32603 

This is repeated whenever I hover on any text.

### Steps To Reproduce:

1.  Open VS Code.
1.  Open a non-sfdc project folder
1.  Open a javascript file
1.  Hover on any word (for instance, I hover on "return", "catch", "finally", "try". 

### Expected result

The error 

[Error - 1:00:10 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'aura' of undefined
  Code: -32603 

Should not pop up on the Output window.

### Actual result

The error

[Error - 1:00:10 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'aura' of undefined
  Code: -32603 

pops up on the Output window.

### Additional information

![image](https://user-images.githubusercontent.com/48261521/56163923-71bc5300-5f84-11e9-809f-fcbb50a4b41a.png)

**VS Code Version**:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
**SFDX CLI Version**:
Salesforce Extension Pack (salesforce.salesforcedx-vscode v45.10.0
**OS and version**:
Windows 7 Enterprise SP1

**Comment by pauljuneau** [comment] 2019-11-22 16:06
I am getting this output error popping up all the time even when I just have a regular apex classes open in my VS Code.  

Here is the error from my output log:
[Error - 9:01:08 AM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4j.adapters.HoverTypeAdapter.writeContents(HoverTypeAdapter.java:82)
	at org.eclipse.lsp4j.adapters.HoverTypeAdapter.write(HoverTypeAdapter.java:142)
	at org.eclipse.lsp4j.adapters.HoverTypeAdapter.write(HoverTypeAdapter.java:38)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:412)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:143)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:138)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:59)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$1(RemoteEndpoint.java:281)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	... 9 more

**Comment by tgentet-obrien** [comment] 2019-11-26 16:33
I started getting this with the latest update that I ran... not sure if I was before but it's started force opening the output panel and even when I click on an LWC JS File.

**Comment by hiteshgodhajain** [comment] 2020-09-28 02:37
Has anyone found the resolution to this problem, the LWC Language Server in the output panel keeps opening and at this point it's becoming annoying to close it every time or resize it to a small size to hide it, which then you have to restore again to work with SFDX grrrhhh  :(

**Comment by joeferraro** [comment] 2020-11-12 15:31
It is extremely annoying to have the Apex Language Server panel grab focus

**Comment by shridharpuntambekar-okta** [comment] 2022-03-05 17:04
Hello, I am facing the same issue. I have cloned the [salesforce e-bikes app ](https://github.com/trailheadapps/ebikes-lwc) and the HTML keeps failing when hovered over the CSS classes.
Extremely annoying as the output window is pulled into focus.
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/54118230/156892975-9558e6b5-c1da-469e-a838-202095139fae.png">

**Comment by jeffb-sfdc** [comment] 2022-04-01 18:47
@scromiecaremore I'm not able to reproduce the issue you described.  Are you still able to reproduce this?

If you are still able to reproduce this, could you describe the repro steps again, and add any missing details?  For example, for step 2 ("Open a non-sfdc project folder"), in my project's directory I created `/non-proj` and then created `/non-proj/test.js`, and then used this for my JS file:
```
function test() {
  return 'this is a test';
}
```

When I hovered over `return`, I didn't get any errors.

**Closed** 2022-04-08 19:45 UTC
Labels: type:bug, more information required, area:aura, area:quality
