### ISSUE TITLE
SFDX: Create Project failed to run

### ISSUE THREAD

**Issue by popoca** [forcedotcom/salesforcedx-vscode#1252] opened 2019-04-09 20:48 UTC
### Summary

I'm just starting with VSCode and SFDX trying to create my project following trailhead,  verified my CLI installation but can't create a project.

### Steps To Reproduce:

1.  Installed Salesforce Extension Pack and am trying to create a project with ' sfdx force:project:create --projectname VSCodeQuickStart' .

### Expected result

Project Created.

### Actual result

SFDX: Create Project failed to run
log.ts:173   ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined.

### Additional information

![image](https://user-images.githubusercontent.com/255034/55833928-519d1780-5ade-11e9-97e0-10a4d806dddc.png)

![image](https://user-images.githubusercontent.com/255034/55834111-c1ab9d80-5ade-11e9-8582-820fd54e8604.png)

![image](https://user-images.githubusercontent.com/255034/55834178-e3a52000-5ade-11e9-9bc5-2e5486222cee.png)

**VS Code Version**:
1.33.0 (user setup)
**SFDX CLI Version**:
  sfdx-cli/7.2.0-179c9078fc win32-x64 node-v10.15.3
**OS and version**:
Windows 10 Home

**Comment by lcampos** [comment] 2019-04-09 21:27
Hi @popoca, looking at the stack trace it looks like the issue is coming from your mavens mate extension. I'm going to close this issue since it's unrelated to the Salesforce VS Code extensions.

**Closed by lcampos** 2019-04-09 21:27 UTC

**Comment by popoca** [comment] 2019-04-09 21:37
Hello, Thanks for the reply, but this issue was happening even before the mavensmate extension (uninstalled it ), now it says: 
![image](https://user-images.githubusercontent.com/255034/55837015-c031a380-5ae5-11e9-9bd8-da7afd4e6b3c.png)
