### ISSUE TITLE
!!! MISSING LABEL !!! predicates_no_sfdx_project_found_text

### ISSUE THREAD

**Issue by chan22111** [forcedotcom/salesforcedx-vscode#3135] opened 2021-04-08 02:57 UTC
### Summary

Unable to create project from VS code . Getting error : !!! MISSING LABEL !!! predicates_no_sfdx_project_found_text
### Steps To Reproduce:

1. After installing salesforce CLI and extension pack
1.  Try creating project from Command Palette

### Expected result

Project should get created

### Actual result

!!! MISSING LABEL !!! predicates_no_sfdx_project_found_text

Vs code version :
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Salesfroce CLI version 
 sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

![image](https://user-images.githubusercontent.com/82131305/113961815-3fc4eb00-9844-11eb-9129-f7ab07cdbdeb.png)

**Comment by sfsholden** [comment] 2021-04-08 15:42
@chan22111 Thank you for reporting this issue. I'm going to be closing this as a duplicate of #3111. We are currently working on a fix!

**Closed** 2021-04-08 15:43 UTC
