### ISSUE TITLE
Cross-class compilation errors not getting triggered

### ISSUE THREAD

**Issue by evanmcd** [forcedotcom/salesforcedx-vscode#1833] opened 2019-12-09 16:12 UTC
I'm noticing some behavior regarding throwing errors (or not) at compile time in VS Code that I think might be different from how MavensMate handled it.

Example:
```
// inside TestClass.cls
private static callerMethod1() {
    String foo = publicMethod('foo', false);

}

public static publicMethod(String testString, Boolean testBoolean {
    System.debug('pubicMethod called with: ' + testString);
    return testString;
}

// inside TestClass2.cls
private string getTest() {
    return TestClass.publicMethod('bar');
}
```

If I save TestClass I don't get an error, despite the fact that another class is calling one of its methods incorrectly (there are no overloaded methods).

I do get an error when I save TestClass2, but shouldn't a compiler error be thrown when I save TestClass?

Thanks.

**Comment by brpowell** [comment] 2020-01-06 21:14
Hi @evanmcd. You're saying that if you have TestClass saved and you try to save TestClass2, that's when the error is thrown and you don't believe that should be the expected behavior? Am I understanding correctly?

**Comment by evanmcd** [comment] 2020-01-13 14:08
Hi @brpowell. Thanks for the response. I'm wondering if the fact that saving TestClass _doesn't_ produce an error is the expected behavior. It seems like an error there would be the ideal, as TestClass2 will now produce an error the next time it is saved, or (likely) tests are run against it, or (perhaps) at runtime.

**Comment by evanmcd** [comment] 2020-02-10 14:08
Hey @brpowell, just wanted to check in on this. Any thoughts on my response? Thanks.

**Comment by brpowell** [comment] 2020-02-10 18:15
I would expect TestClass2 to produce the error because it's the one trying to access a method that doesn't exist. There's nothing wrong with the implementation of TestClass itself, so I'm not sure it'd be appropriate for it to be the one to report problems.

**Comment by evanmcd** [comment] 2020-02-11 14:14
OK, thanks for the clarification.

**Comment by brpowell** [comment] 2020-02-11 18:11
Sure thing, let us know if you want to discuss further. For now I'll go ahead and close the issue.

**Closed by brpowell** 2020-02-11 18:11 UTC
