### ISSUE TITLE
"SFDX: Push Source to Default Org" failing with exit code 1 on compilation failures

### ISSUE THREAD

**Issue by bobalicious** [forcedotcom/salesforcedx-vscode#5450] opened 2024-02-23 14:55 UTC
### Summary

In one of our SFDX projects we are finding that if a push of more than one file fails due to compilation errors, instead of getting feedback on the issues, we're getting a simple:

```
sfdx project:deploy:start --json
 ended with exit code 1
```

### Steps To Reproduce:

Have tried to produce a small project that presents this behaviour, but I cannot.

Characteristics of the scenario:

- Multiple folders defined in the sfdx-project.json
- Namespaced scrartch org
- More than one file has changed and will be pushed
- At least one file has a compilation error
- 

### Expected result

List of compilation issues shown and errors highlighted in the file.

### Actual result

```
sfdx project:deploy:start --json
 ended with exit code 1
```

### Additional information

If the command `sfdx project:deploy:start --json` is executed in the terminal window, the JSON is returned as expected.

Here is an example of a response that causes the problem:

```
{
  "status": 1,
  "result": {
    "checkOnly": false,
    "completedDate": "2024-02-23T09:22:55.000Z",
    "createdBy": "005Nq000005Ftm8",
    "createdByName": "User User",
    "createdDate": "2024-02-23T09:22:52.000Z",
    "details": {
      "componentFailures": [
        {
          "changed": false,
          "columnNumber": 83,
          "componentType": "ApexClass",
          "created": false,
          "createdDate": "2024-02-23T09:22:54.000Z",
          "deleted": false,
          "fileName": "classes/RecordFilterDmlRecordTest.cls",
          "fullName": "RecordFilterDmlRecordTest",
          "lineNumber": 25,
          "problem": "Variable does not exist: SOME_VARIABLE_THAT_IS_WRONG",
          "problemType": "Error",
          "success": false
        }
      ],
      "componentSuccesses": [
        {
          "changed": true,
          "componentType": "ApexClass",
          "created": false,
          "createdDate": "2024-02-23T09:22:54.000Z",
          "deleted": false,
          "fileName": "classes/RecordFilterRowDmlRecordTest.cls",
          "fullName": "RecordFilterRowDmlRecordTest",
          "id": "01pNq0000014mm4IAA",
          "success": true
        },
        {
          "changed": true,
          "componentType": "",
          "created": false,
          "createdDate": "2024-02-23T09:22:54.000Z",
          "deleted": false,
          "fileName": "package.xml",
          "fullName": "package.xml",
          "success": true
        }
      ],
      "runTestResult": {
        "numFailures": 0,
        "numTestsRun": 0,
        "totalTime": 0,
        "codeCoverage": [],
        "codeCoverageWarnings": [],
        "failures": [],
        "flowCoverage": [],
        "flowCoverageWarnings": [],
        "successes": []
      }
    },
    "done": true,
    "id": "0AfNq000005IeDpKAK",
    "ignoreWarnings": false,
    "lastModifiedDate": "2024-02-23T09:22:55.000Z",
    "numberComponentErrors": 1,
    "numberComponentsDeployed": 1,
    "numberComponentsTotal": 2,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": true,
    "runTestsEnabled": false,
    "startDate": "2024-02-23T09:22:52.000Z",
    "status": "Failed",
    "success": false,
    "files": [
      {
        "fullName": "RecordFilterDmlRecordTest",
        "type": "ApexClass",
        "state": "Failed",
        "error": "Variable does not exist: SOME_VARIABLE_THAT_IS_WRONG (25:83)",
        "problemType": "Error",
        "filePath": "/Users/robertbaillie/Work/logging-service/force-app/main/record-filter/classes/dml/tests/RecordFilterDmlRecordTest.cls",
        "lineNumber": 25,
        "columnNumber": 83
      },
      {
        "fullName": "RecordFilterRowDmlRecordTest",
        "type": "ApexClass",
        "state": "Changed",
        "filePath": "/Users/robertbaillie/Work/logging-service/force-app/main/record-filter/classes/dml/tests/RecordFilterRowDmlRecordTest.cls"
      },
      {
        "fullName": "RecordFilterRowDmlRecordTest",
        "type": "ApexClass",
        "state": "Changed",
        "filePath": "/Users/robertbaillie/Work/logging-service/force-app/main/record-filter/classes/dml/tests/RecordFilterRowDmlRecordTest.cls-meta.xml"
      }
    ]
  },
  "warnings": []
}
```

Prior to the above output, the following is reported:
```
(node:58802) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

However, this is also true of successful deployments.

Note also - compilation errors are reported as expected when a single file is changed and pushed.  It only occurs when multiple files are pushed.

**Salesforce Extension Version in VS Code**:
Salesforce CLI Integration: v60.0.0

**SFDX CLI Version**:
SFDX: @salesforce/cli/2.29.5 darwin-arm64 node-v21.6.2

**OS and version**:
MacOs Ventura 13.5.2 (22G91)

**VS Code version**:
Version: 1.86.2 (Universal)

**Comment by daphne-sfdc** [comment] 2024-02-23 15:28
Hi @bobalicious, We just released v60.1.2 of the extensions about an hour ago, which should contain a fix for this issue.  Please upgrade your extensions and let me know if the problem is still present.  Thanks!

**Comment by bobalicious** [comment] 2024-02-23 15:35
First impressions - it looks like the issue is fixed.  I'll report back if I see any more instances of this.

**Comment by daphne-sfdc** [comment] 2024-02-23 15:38
Thank you for letting us know.  I'm going to close this issue - feel free to reopen if you find any more instances later on.

**Closed by daphne-sfdc** 2024-02-23 15:38 UTC
