### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AnthonyNTK** [forcedotcom/salesforcedx-vscode#2110] opened 2020-04-04 17:16 UTC
Issue Type: Performance
    Extension Name: salesforcedx-vscode-core
    Extension Version: 45.6.0
    OS Version: Windows_NT x64 10.0.17134
    VSCode version: 1.32.3

⚠️ Make sure to attach this file from your home-directory: [salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/4432012/salesforce.salesforcedx-vscode-lwc-unresponsive.cpuprofile.txt)⚠️

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-04-27 22:19
Duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/2050

**Closed by smaddox-sf** 2020-04-27 22:19 UTC
Labels: area:lwc, area:performance
