### ISSUE TITLE
No source backed components present in the package

### ISSUE THREAD

**Issue by jcottonenf** [forcedotcom/salesforcedx-vscode#3538] opened 2021-09-08 23:37 UTC
### Summary

When trying to deploy via VS Code SFDX: Deploy Source to Org, get the following error:

`No source backed components present in the package`

### Steps To Reproduce:

1.  Make sure new project with manifest created and authenticated
1.  Try to deploy an Apex class (right click and choose `SFDX: Deploy Source to Org`)

### Expected result

The Apex class should deploy

### Actual result

Class doesn't deploy and receive an error:
`No source backed components present in the package`

### Additional information

![image](https://user-images.githubusercontent.com/90359902/132599088-b051b1b4-b4a7-4a4a-94b7-4f380374e115.png)

**Salesforce Extension Version in VS Code**: v52.13.0

**SFDX CLI Version**: (VS Code CLI v52.13.0 and global SFDX CLI sfdx-cli/7.116.2)

**OS and version**: Mac OS 11.5.2

**Comment by jcottonenf** [comment] 2021-09-09 00:02
Notice that this issue also happens when SFDX: Retrieve Source from Org:

```16:59:11.65 Starting SFDX: Retrieve Source from Org

No components in the package to retrieve```

**Comment by smaddox-sf** [comment] 2021-09-10 18:32
Hi @jcottonenf - Thanks for reaching out on this.  It looks like it's a duplicate of this CLI issue (which you see both in the CLI and in VS Code).  https://github.com/forcedotcom/cli/issues/1151. Please follow that issue for updates.

Closing this as a duplicate, but feel free to comment back if you feel this is a different issue

**Closed by smaddox-sf** 2021-09-10 18:32 UTC
