### ISSUE TITLE
Takes too much time to setup when creating a new project

### ISSUE THREAD

**Issue by navaneeth908** [forcedotcom/salesforcedx-vscode#5153] opened 2023-10-16 09:03 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by peternhale** [comment] 2023-10-16 11:57
@navaneeth908 To better assist you, please provide the details that describe the issue you are reporting, including CLI, platform and vscode versions.

**Comment by gbockus-sf** [comment] 2023-10-17 05:53
Very likely this is a dupe of https://github.com/forcedotcom/salesforcedx-vscode/issues/4919 which is top of our list.  Please reopen if not the case.

**Closed by gbockus-sf** 2023-10-17 05:53 UTC
