### ISSUE TITLE
SFDX command not registering

### ISSUE THREAD

**Issue by vikrantu** [forcedotcom/salesforcedx-vscode#2336] opened 2020-07-09 19:35 UTC
Issue Type: <b>Bug</b>

Open command prompt for Saleforce extension and run SFDX: create project

get the following error message:
Command 'SFDX: Create Project' resulted in an error (command 'sfdx.force.project.create' not found)

Extension version: 48.23.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment] 2020-07-10 00:49
I'm closing this since it's a duplicate of #2254 . We'll post follow up on that issue.

**Closed by lcampos** 2020-07-10 00:49 UTC
