### ISSUE TITLE
SFDX DIFF Unexpected error while running ApexProcessor

### ISSUE THREAD

**Issue by libomyles** [forcedotcom/salesforcedx-vscode#1805] opened 2019-11-18 02:10 UTC
### Summary

SFDX DIFF Unexpected error while running ApexProcessor

### Steps To Reproduce:

1.  XXXX.cls right click SFDX: Diff File Against Org.

### Actual result

Unexpected error while running ApexProcessor. Error: XXXXXX.cls was not found in org when querying with username XXXXX@XXXXXX

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version: 1.40.1 (system setup)

**SFDX CLI Version**:
sfdx-cli 7.33.2 (core)

**OS and version**:
OS: Windows_NT x64 10.0.17763

**Comment by lcampos** [comment] 2019-11-20 19:36
Hi @libomyles this looks to be a duplicate of #1798 . As mentioned in that issue, this could happen if the ApexClass has not been deployed to the org. I'll close this issue and let's follow up on the thread in issue #1798

**Closed by lcampos** 2019-11-20 19:36 UTC
Labels: status:duplicate
