### ISSUE TITLE
Managed Package's Object in Org Browser : Metadata

### ISSUE THREAD

**Issue by nikhil-sfdev** [forcedotcom/salesforcedx-vscode#1998] opened 2020-02-18 07:54 UTC
I have installed some packages in my org, and their sObject's Info are NOT available(in Org Browser : Metadata) in following categories : 
- Custom Object
- Workflows
- Flow Definitions
( Probably in other categories as well(Not Checked) )

Though some info is available in sObject Definitions (location : .sfdx>tools>sObjects) for field's description, can we have all kind of info in "Org Browser" as well (similar to other standard and Unmanaged sObjects)?.

Currently using extension's info :
`sfdx-cli/7.46.1-3d2451fad8 darwin-x64 node-v10.15.3` 
`vs_code_version : 1.42.1`

**Comment by lcampos** [comment] 2020-02-19 01:07
Thanks for opening this @nikhil-sfdev. The org browser does not display metadata inside of managed packages because that metadata cannot be retrieved (metadata retrieve) by a subscriber.
Can you provide more info on what you are trying to accomplish ?

**Comment by nikhil-sfdev** [comment] 2020-02-19 06:47
@lcampos 
We are using few package's object in our sales process, and wrote few validations, flows, and other custom configurations to extend their functionalities. But it is difficult to maintain versioning of the same.

It would be great if we can pull out these informations to our repositories. 
Plus , it can also help us in our CI/CD pipelines. 

Thanks !

**Comment by lcampos** [comment] 2020-02-19 17:29
@nikhil-sfdev so you want some sort of reference to the sobjects in a managed package e.g. opening a file that lists all the fields ? Or you want to get this information while you're coding with the extensions e.g. typing the managed package namespace in an apex class and seeing a list of suggestions for the objects, fields, etc in that namespace ?

Can you also clarify how this info would help you in your CI/CD pipeline ?

**Comment by nikhil-sfdev** [comment] 2020-02-20 08:27
@lcampos 
I guess we can reference managed package's objects and fieldName__c from sObject Definitions (location : .sfdx>tools>sObjects), so ,no issue in that.

Components in which i am interested are: 

**Object's Metadata** 
![Screenshot 2020-02-20 at 1 32 31 PM](https://user-images.githubusercontent.com/22937196/74913120-09c96b00-53e6-11ea-8b46-e3fb36b9695f.png)

**FlowDefinition of written on managed package's object**
![Screenshot 2020-02-20 at 1 34 12 PM](https://user-images.githubusercontent.com/22937196/74913128-0f26b580-53e6-11ea-94a3-87334daad011.png)

**Workflows written on managed package's object**
![Screenshot 2020-02-20 at 1 36 06 PM](https://user-images.githubusercontent.com/22937196/74913136-14840000-53e6-11ea-9b08-a574842c59c4.png)

Currently, Admins/Devs configure above categories informations for package's object, therefore it is difficult to trace down those changes ( where git helps ) and In addition, we can deploy these metadata via our git branches instead of Change Sets. 


Thanks !

**Comment by snugsfbay** [comment] 2020-03-26 19:08
I would love this capability so that I can include custom fields and record types that we build onto objects in managed packages.  For example, when I add a field to the Affiliations object that is part of EDA and NPSP managed packages from Salesforce, I want to include that custom field or record types in the metadata I can browse, download and pull into our repository.

**Comment by anellurirocket** [comment] 2020-04-16 21:37
We use Salesforce CPQ and extended its functionality by creating custom fields, workflows, process builders, email alerts etc. There is no way to access that metadata using Org Browser where as manifest file can retrieve that metadata.

**Comment by az-oolloow** [comment] 2020-04-28 06:13
@lcampos 
You say:
> because that metadata cannot be retrieved (metadata retrieve) by a subscriber.

However, if i just add that managed component (e.g. object) in the correct folder as an empty .xml, right click in VS code and say 'retrieve from source' it is retrieved correctly.

**Comment by Christopher-B-Carpenter** [comment] 2020-06-16 18:57
@az-oolloow that is how I have been getting around this limitation as well. We create a lot of customizations within the SBQQ namespace (Salesforce CPQ) and it would be great if we could access this metadata through the org browser.

**Comment by peternoges** [comment] 2021-02-12 15:50
Hey @lcampos  - 

Hopefully this is helpful to the issue discussion:

I'm believing Orgbrowser uses sfdx retrieve commands and its unusual that, given vanilla .forceignore file,   the command `sfdx force:source:retrieve -m CustomObject`  does only a PARTIAL  job at retrieving managed package sObjects.   This could be related to the OP's issue.

For example, why when running sfdx force:source:retrieve -m CustomObject  do i see just a few (but not all) managed (namespaced) sobjects in the retrieval results?  Many sobjects from installed packages are not retrieved, but some are.  The few that are  definitely are namespaced sObjects (not custom settings, not metadatatypes,   but in fact sobject from managed packages).

I think sfdx retrieve commands, and orgbrowser should both be upgraded to honor the expectation that ISVs have, which, to my knowledge, is that only some metadata is hidden;  therefore please upgrade both OrGBrowser and `sfdx force:source:retrieve -m CustomObject` so that it retrieves all (not just some)  namespaced sObjects (at least those that are not forceignored)

**Comment by peternoges** [comment] 2021-02-12 21:45
I revised the “
I think sfdx retrieve commands, and orgbrowser should both be upgraded” sentence with additional clarity

**Comment by JodieM** [comment] 2022-05-14 10:18
Over two years later and this is still not fixed. Please please please allow us to download our FULL org metadata from our orgs, of which 99.99% of orgs use Managed Packages and people customise objects in Managed Packages so we need to be able to see everything in VSCode.

**Comment by mattmartin26** [comment] 2022-08-19 17:43
Agreed, this is pretty important for those of us who are extending Managed Packages (eg. NPSP, EDA).

**Comment by mspiep01** [comment] 2023-10-10 15:15
Any update on progress or prioritization? If we're supporting managed packages, we should include them across our pipelines as well

**Comment by DaveHahn-Fuel** [comment] 2023-11-06 14:32
This is a major issue for us as well. We may add a new custom field to the Managed Package object and need to retrieve it into source to be checked in via git so our ci/cd process can deploy it since the new field could be referenced in Apex, on a page layout or flexipage or any other number of dependencies that break the automated build/deploy process.  With Salesforce pushing the CI/CD process, how is this not possible.  It is available in Illuminated Cloud for itelliJ.  We are forced to use the cli every time we add or change anything on a custom object in a managed package. This is not great for an admin who is on windows and has never used a bash terminal.

**Comment by twkirumba** [comment] 2023-11-06 15:53
@DaveHahn-Fuel the slight workaround I've been using is maintaining a "ManagedPackage.xml" manifest. When we make a change to something managed, I add it to the manifest then use that to retrieve and add to my VCS. It's not much but it's better than cli commands in the terminal, especially for an admin who isn't familiar

**Comment by DaveHahn-Fuel** [comment] 2023-11-07 13:52
Thanks @twkirumba thats an interesting work around, I will give it a try

**Comment by sakarettm07** [comment] 2024-03-27 16:18
This is so important to my workflow. It keeps me using IntelliJ + IlluminatedCloud because I can't get a reference to the objects and fields within VisualStudio.

**Comment by twkirumba** [comment] 2024-03-27 16:49
@sakarettm07  how does IntelliJ + IlluminatedCloud provide references to managed metadata components? Does it use a different CLI tool?

**Comment by daphne-sfdc** [comment] 2024-06-13 19:04
Hello everyone, This issue has been fixed in https://github.com/forcedotcom/salesforcedx-vscode/pull/5403.  Please try updating to the latest version of the VSCode extensions and see if the problem is resolved.  I'm going to close this issue - if the problem still persists, feel free to let us know by opening a new issue.

**Closed by daphne-sfdc** 2024-06-13 19:04 UTC
Labels: area:namespaces, area:orgbrowser, type:enhancements
