### ISSUE TITLE
Error re-indexing workspace: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Shababsoft** [forcedotcom/salesforcedx-vscode#1766] opened 2019-11-01 09:13 UTC
# Summary

I am receiving the following error message when pulling metadata from Salesforce. The error comes against the Aura Component (Extension)

"Error re-indexing workspace: Cannot read property 'indexOf' of undefined"

After receiving the error I cannot retrieve or deploy any lightning component to an org.

![image](https://user-images.githubusercontent.com/4686730/68014577-dffa0600-fc87-11e9-9488-7a3605d47053.png)

**VS Code Version**:
1.39.2

**SFDX CLI Version**:
7.31

**OS and version**:
Windows 10

**Comment by AndrewStopchenko-SO** [comment] 2020-11-27 18:36
Hi guys, I have faced with similar issue after refreshing metadata from org too.
I checked the Aura Language Server logs, where it was stating one particular Aura component which was producing this error:
```
Error parsing markup from **componentPath**: TypeError: Cannot read property 'indexOf' of undefined
    at AuraIndexer.searchAura (***\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-50.5.0\node_modules\@salesforce\aura-language-server\lib\aura-indexer\indexer.js:197:22)
    at AuraIndexer.searchAura (***\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-50.5.0\node_modules\@salesforce\aura-language-server\lib\aura-indexer\indexer.js:201:34)
. . . . .
```
I checked that particular `aura-indexer\indexer.js:197:22` source as well:
```javascript
searchAura(node) {
  const results = [];
  if (node.tag.indexOf(':') !== -1) {  // line 197, <-- ERROR HERE
    results.push(node);
  }
  for (const child of node.children) {
    results.push(...this.searchAura(child));
  }
  return results;
}
```

So, it looks like when traversing the HTML nodes parsed from the Aura component's markup, it found some node which had the `node.tag == undefined`.

In the component's code, what dragged my attention were the `<![CDATA[ ... ]]>` tags inside. In that particular component, they seem to inject some `<svg>...</svg>` social network icons into the `<a />` tags.

So, my guess - maybe it is the `<[CDATA[ ... ]]>` node that breaks the parser?

**Comment by jeffb-sfdc** [comment] 2022-04-01 19:47
@Shababsoft this looks to be a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/2624, which has been fixed.  I'm going to close this ticket.  If this issue still happens, please reopen this ticket, and let us know what repro steps you are performing.

**Closed by jeffb-sfdc** 2022-04-01 19:47 UTC
Labels: type:bug, area:aura, status:in review
