### ISSUE TITLE
Causes PHP Syntax Highlighting Issue

### ISSUE THREAD

**Issue by westc** [forcedotcom/salesforcedx-vscode#1988] opened 2020-02-14 23:10 UTC
### Summary

When this extension is enabled in Visual Studio Code the native syntax highlighting for PHP doesn't highlight other embedded languages (HTML, CSS and JavaScript) as expected.

### Steps To Reproduce:

1.  Enable this extension.
1.  Create a new file tab.
1.  Set the language to PHP.
1.  Enter the following code:
    ```php
    <?php if (true): ?>
      <div>Hello world!!!</div>
      <script type="text/javascript">
      var x = 3;
      document.write(x);
      </script>
      <style type="text/css">
      div {
        color: #00F;
      }
      </style>
    <?php endif; ?>
    ```

### Expected result

All of the code will be syntax highlighted depending on the language:
![image](https://user-images.githubusercontent.com/704518/74575285-c2ae2680-4f5c-11ea-85e5-38270cb74f10.png)

### Actual result

The PHP code will be highlighted as PHP but the inline HTML, CSS and JS will not be highlighted:
![image](https://user-images.githubusercontent.com/704518/74575338-fc7f2d00-4f5c-11ea-92d2-03da5527be40.png)

### Additional information

**VS Code Version**:  1.42.1

**SFDX CLI Version**:  sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**OS and version**:  macOS Mojave 10.14.6

**OS According to VS Code**:  Darwin x64 18.7.0

**Comment by lcampos** [comment] 2020-03-12 19:33
Thanks for reporting this @westc , we've made changes in release `48.6.0` to make sure the extensions are only active in Salesforce projects which will take care of this.

**Comment by xyc** [comment] 2020-04-23 22:55
Looks like this is related to [html](https://github.com/forcedotcom/salesforcedx-vscode/blob/7184190b8659cf38733c31f2c355709945da5f7f/packages/salesforcedx-vscode-lightning/package.json#L77-L97) language contribution. While "Aura Components" extension is enabled (even if not activated) this issue would present. @mysticflute @nrkruk could we continue conversation here WRT modification for aura support?

**Comment by ntotten** [comment] 2020-04-24 14:42
@lcampos Is it even possible to disable the `language` contribution of an extension without deactivating it entirely?

**Comment by jeffb-sfdc** [comment] 2022-04-01 17:34
I'm still able to reproduce this.

**Comment by michaelsoriano** [comment] 2022-10-18 23:56
This is still happening. Messing up HTML color syntax in PHP files. 

I'm using VSCode 1.72 + SF Extension Pack v v55.8.0. 
It immediately gets fixed as soon as I disable the SF Extension pack.  Shouldn't it disable automatically in non SF projects? Or is there a setting I have to turn on?

**Comment by randi274** [comment] 2022-10-31 16:25
<img width="756" alt="Screen Shot 2022-10-31 at 12 24 02 PM" src="https://user-images.githubusercontent.com/9795193/199058336-190c91f5-aa0d-4198-b1d1-33e4575414a5.png">

@michaelsoriano we actually do have a setting for this! It's possible it's not being respected now, but we would recommend using "Autodetect" in your case, or using "off" definitively should stop the LWC and Aura Language Servers from activating.

**Comment by michaelsoriano** [comment] 2022-11-01 17:34
@randi274  thank you. I checked the settings and "autodetect" is already on. 

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/5881081/199299674-358df8c7-07fe-4054-bfac-e1e0942ce75c.png">

I've learned to just manually "disable" the entire extension pack in PHP projects.

**Comment by gbockus-sf** [comment] 2023-10-17 17:30
PR merged.  Will be included with next release https://github.com/forcedotcom/salesforcedx-vscode/pull/5159

**Closed by gbockus-sf** 2023-10-17 17:30 UTC
Labels: type:bug, area:lwc, area:syntaxhighlighting
