### ISSUE TITLE
Stop Nagging Me About Code Coverage In Unit Tests

### ISSUE THREAD

**Issue by brianmfear** [forcedotcom/salesforcedx-vscode#5290] opened 2023-12-21 17:59 UTC
**Is your feature request related to a problem? Please describe.**

Whenever I open a unit test Apex class with code coverage display enabled, I get a warning that there is no code coverage and that I should enable the flag to retrieve code coverage.

**Describe the solution you'd like**

I shouldn't be notified about this condition, as there is nothing I can do about it.

**Describe alternatives you've considered**

There isn't any alternative if I'm working on code coverage.

**Comment by peternhale** [comment] 2023-12-21 21:29
@brianmfear thanks for the suggestion. Happy Holidays

**Comment by brianmfear** [comment] 2023-12-22 01:21
@peternhale Thanks! Happy Holidays to you as well!

**Comment by peternhale** [comment] 2024-01-02 14:03
@brianmfear I am going to close this as a duplicate of #1178

**Closed by peternhale** 2024-01-02 14:03 UTC
Labels: status:duplicate, feature
