### ISSUE TITLE
Extension issue - Unresponsive Performance Issue

### ISSUE THREAD

**Issue by jojoforce** [forcedotcom/salesforcedx-vscode#2520] opened 2020-09-13 02:59 UTC
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 12446,
		"activateCallTime": 4,
		"activateResolvedTime": 4073,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by smaddox-sf** [comment] 2020-09-14 17:36
Not a lot of detail here, but I believe it's a duplicate of #2410.  We posted a workaround on that issue.

**Closed by smaddox-sf** 2020-09-14 17:36 UTC
