### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by seregaone** [forcedotcom/salesforcedx-vscode#1114] opened 2019-03-02 22:20 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `45.3.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Сергей\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment] 2019-03-03 07:50
@seregaone Is the issue you are seeing similar to: https://github.com/forcedotcom/salesforcedx-vscode/issues/1100

**Comment by praksb** [comment] 2019-03-03 07:50
Possible duplicate of: https://github.com/forcedotcom/salesforcedx-vscode/issues/1100

**Comment by praksb** [comment] 2019-03-07 19:57
@seregaone We just released our latest Apex extension update which has fixes to improve the performance of Apex editing experience. Please upgrade to v45.5.0 and let us know if you still run into any issues.

**Closed by praksb** 2019-03-07 19:57 UTC
