### ISSUE TITLE
100% CPU Utilization on VS Code - DX MacBook Pro

### ISSUE THREAD

**Issue by cagarwa** [forcedotcom/salesforcedx-vscode#2462] opened 2020-08-28 16:38 UTC
### Summary

_I am unable to multitask on my macbook pro while working on SFDX project with VS Code. The extension pack is consuming 100% CPU, >3 GB Memory and the laptop freezes._.

### Steps To Reproduce:

1.  Open VS Code & navigate to a SFDX project
1.  Run any SFDX command 
1. Open Process Explorer and see CPU Utilization, Memory

### Expected result

_CPU Utilization should not touch 100%_.

### Actual result

_CPU Utilization is over 100%_.

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/40841169/91591657-ddf1e980-e922-11ea-9cf9-df0efbdc3e04.png)

Configurations:

OS - macOS Catalina 10.15.6

VS Code - version 1.48.1

SFDX CLI - 7.71.0-4193fb4acc

DX Extension pack - v49.6.0

**Comment by smaddox-sf** [comment] 2020-08-31 17:19
HI @cagarwa - Thanks for reaching out.  When you started experiencing the high CPU load, did you `Refresh SObject Definitions` either via a command or the new prompt in the lower righthand corner?  

I believe this is a duplicate of #2410 but need a bit more info to be sure

**Closed** 2020-08-31 18:59 UTC
