### ISSUE TITLE
LightningComponentBundle

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#1760] opened 2019-10-29 19:28 UTC
### Summary

Can't retrieve LWC.

### Steps To Reproduce:

1.  Connect to a production org that has LWC in it
2. Use the cloud sidebar (org explorer?) 
3. click the download cloud icon

### Expected result

LWCs download to local source

### Actual result

Error running command sfdx.force.source.retrieve.component: Node of type empty does not have a parent metadata type node. This is likely caused by the extension that contributes sfdx.force.source.retrieve.component.

### Additional information

running this yields "no results found" but no errors.
$ sfdx force:source:retrieve -m LightningComponentBundle

**VS Code Version**:
1.39.2

**SFDX CLI Version**:
sfdx-cli/7.23.1 darwin-x64 node-v10.16.3
salesforcedx 47.3.7

**OS and version**:
mac mojave 10.14.6

**Comment by mshanemc** [comment] 2019-10-29 19:57
https://github.com/forcedotcom/cli/issues/214

**Comment by brianevanmiller** [comment] 2019-12-17 08:51
Any updates or any workaround here?  I don't know how to bring existing LightningComponentBundle metadata into my SFDX project from a non-scratch org

**Comment by lcampos** [comment] 2020-12-02 04:06
Closing as a duplicate of the existing CLI issue linked above

**Closed by lcampos** 2020-12-02 04:06 UTC
Labels: status:needs cli support
