### ISSUE TITLE
SObject Tokens and Custom Settings

### ISSUE THREAD

**Issue by NathanWenslaff** [forcedotcom/salesforcedx-vscode#2020] opened 2020-02-21 02:50 UTC
### Summary

The Apex Language server gives errors when referencing SObject tokens and Custom Settings.
1. Referencing SObject tokens gives the following error:
"Variable does not exist: SObjectType"
2. Referencing the `getOrgDefaults()` method for Custom Settings gives the following error:
"Not of type Custom Settings"

### Steps To Reproduce:

1.  Reference an SObject token or the `getOrgDefaults()` method of a Custom Setting.

### Expected result

There should be no errors.

### Actual result

![image](https://user-images.githubusercontent.com/35071304/74999911-79f5e200-5422-11ea-8a90-324c011067b4.png)

**VS Code Version**:
1.42.1

**SFDX CLI Version**:
sfdx-cli/7.46.3-4cf515d568 darwin-x64 node-v10.15.3

**OS and version**:
10.15.3 (19D76)

**Comment by lcampos** [comment] 2020-03-27 02:16
@NathanWenslaff thanks for the feedback, I'm closing this as a duplicate of #2028 since there's more details and activity in that other issue.

**Closed by lcampos** 2020-03-27 02:16 UTC
