### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by emongwe** [forcedotcom/salesforcedx-vscode#2611] opened 2020-10-08 15:21 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.12.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.49.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\abema92\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-10-08 21:26
Duplicate of #2410

**Closed by smaddox-sf** 2020-10-08 21:26 UTC
