### ISSUE TITLE
salesforcedx-vscode-apex.java.home Issue

### ISSUE THREAD

**Issue by Sylvainp-Ribbonfish** [forcedotcom/salesforcedx-vscode#1504] opened 2019-07-24 13:34 UTC
### Summary

_Short summary of what is going on or to provide context_.
When I start the editor I get the following error:

The salesforcedx-vscode-apex.java.home setting defined in VS Code settings points to a missing folder. For information on how to setup the Salesforce Apex extension, see Set Your Java Version.

### Steps To Reproduce:

1.  Start the editor with a new SF project

### Expected result

_Describe what should have happened_.

No error messages.

### Actual result

_Describe what actually happened instead_.

Error message...

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.36.1

**SFDX CLI Version**:
sfdx-cli/7.15.3-c7d407d236 darwin-x64 node-v10.15.3

**OS and version**:
Mac os 10.14.6

My setting in VS:
"salesforcedx-vscode-apex.java.home": "/Library/Java/‎⁨JavaVirtualMachines⁩/⁨jdk-11.0.4.jdk⁩/Contents⁩/Home⁩",
    "java.home": "/Library/Java/‎⁨JavaVirtualMachines⁩/⁨jdk-11.0.4.jdk⁩/Contents⁩/Home",

my java version:
/usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    12.0.2, x86_64:	"Java SE 12.0.2"	/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
    11.0.4, x86_64:	"Java SE 11.0.4"	/Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home

Any ideas?

Thanks
Sylvain

**Comment by PhilipJohnBasile** [comment] 2019-07-26 21:02
dupe of #1472

**Comment by ntotten** [comment] 2019-07-30 21:43
JDK 12 isn't supported. Please see the Java setup instructions here: https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/java-setup

**Closed by ntotten** 2019-07-30 21:43 UTC
