### ISSUE TITLE
Sfdx commands keep running when executed.... 

### ISSUE THREAD

**Issue by jpoonam4** [forcedotcom/salesforcedx-vscode#2401] opened 2020-08-06 06:48 UTC
**Summary**
From past few days the SFDX commands are taking way to long to execute, infact I had to cancel them because they are just shown as running for infinite

For Ex: 1.SFDX: Create Project will run infintly,it will create project on system but vsc don't reload/ shows the created project.
I observed this for more than 20 min and i have to cancel that.

 2.SFDX: Authorize an Org / SFDX: Deploy Source to Org command progress indicator keeps on running.
Steps To Reproduce:

**1.** execute sfdx command : SFDX: Create Project
used Standard standard project template(default)

**Expected result**
Project should be created and it should open in vsc.

**Actual result**
The command progress indicator keeps on running.
It creats Project folder on system but command do not terminate.
Not getting 2nd Output on vsc which contains ended with exit code 0.

**2.** execute sfdx command : SFDX: Authorize an Org
**Expected result**
![actual](https://user-images.githubusercontent.com/22389139/88762654-38b2ec80-d18f-11ea-9ce3-9ab9ad48af48.jpg)

**Actual result**
The command progress indicator keeps on running.
![Result](https://user-images.githubusercontent.com/22389139/88762713-58e2ab80-d18f-11ea-8f62-66d463aaa782.png)

**Additional information:**

VS Code Version:
1.47.3

SFDX CLI Version:
sfdx-cli/7.60.0-e2bb2907cb win32-x64 node-v10.15.3

Java Version:
1.8.0_261

System type :
64-bit Operating System,x64-based processor
Windows 10

**Comment by smaddox-sf** [comment] 2020-08-17 16:17
Hi @jpoonam4 - Thanks for submitting this feedback.  If I've read the details correctly, the commands execute successfully, but the pop-up dialog doesn't close.  Is that accurate?

**Comment by jpoonam4** [comment] 2020-08-17 17:03
Command executes but not successfully, if command is success then why not getting on output terminal that the command executed with exit code 0.
Also it keeps on running until I don't cancel that.
When I run sfdx  commabd for creating project then folder gets created on system but it don't open in vsc Or Vsc do not reload with project which I have created.

**Comment by smaddox-sf** [comment] 2020-08-24 19:09
Duplicate of #2385

**Closed by smaddox-sf** 2020-08-24 19:09 UTC
