### ISSUE TITLE
Source Diff: Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by SalesforceBobLightning** [forcedotcom/salesforcedx-vscode#1637] opened 2019-09-06 12:07 UTC
### Summary

I want to use the `Source Diff` feature in VSCode.

When I follow the [instructions](https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/source-diff):

`sfdx plugins:install @salesforce/sfdx-diff`

I get this error:

$ sfdx plugins:install @salesforce/sfdx-diff
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at onUnexpectedError (C:\Users\Robert\AppData\Local\sfdx\client\7.22.0-de5c6ecff8\node_modules\yarn\lib\cli.js:91833:100)
    at C:\Users\Robert\AppData\Local\sfdx\client\7.22.0-de5c6ecff8\node_modules\yarn\lib\cli.js:91936:9
Installing plugin @salesforce/sfdx-diff... !
Error: yarn add @salesforce/sfdx-diff@latest --non-interactive --mutex=file:C:/Users/Robert/AppData/Local/sfdx/yarn.lock --preferred-cache-folder=C:/Users/Robert/AppData/Local/sfdx/yarn --check-files exited with code 1
    at ChildProcess.forked.on (C:/Users/Robert/AppData/Local/sfdx/client/7.22.0-de5c6ecff8/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)

### Additional information

Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

sfdx --version
sfdx-cli/7.22.0-de5c6ecff8 win32-x64 node-v10.15.3

**Comment by SalesforceBobLightning** [comment] 2019-09-25 11:09
@lcampos please may I get an update on the status of this bug?

**Comment by lcampos** [comment] 2019-09-28 01:09
Hi @SalesforceBobLightning , the only way I've been able to replicate this issue was by changing the permissions of the CLI files to root instead of them being assigned to my user. 

This could be caused by installing the CLI as root or by running a `sudo sfdx update`. Could you verify the files under `C:/Users/Robert/AppData/Local/sfdx` are not assigned to root ?

**Comment by SalesforceBobLightning** [comment] 2019-09-30 13:50
@lcampos thanks for responding.

I am using windows, so it's not possible to run `sudo sfdx update`, but as an alternative, I ran `sfdx update` from the command line as Administrator. 

But I still get the same error when I run command `sfdx plugins:install @salesforce/sfdx-diff`

**Comment by lcampos** [comment] 2019-09-30 17:57
@SalesforceBobLightning right, sudo is for mac, my bad. So did you confirm that your CLI is running with the correct user permissions ? It wasn't clear to me if your user is the same as the admin in the machine.

**Comment by SalesforceBobLightning** [comment] 2019-10-01 13:15
@lcampos thanks again for responding. 

When I run the command `dir /Q` it says I own all the files.

Additionally, my user has admin rights on the machine.

And if I open the folder properties via window explorer, it says that I have full permissions on the files.

Hope this helps.

**Comment by lcampos** [comment] 2019-10-03 01:46
Thanks, that helps. Do you remember if you installed the cli using the installer or `npm install sfdx-cli` ? I'm trying to have a set up as close as possible to the one you have in order to find the issue.

**Comment by SalesforceBobLightning** [comment] 2019-10-03 08:26
@lcampos I used the installer

**Comment by SalesforceBobLightning** [comment] 2019-10-06 21:49
@lcampos I've updated to the latest CLI and I am still getting the error :-(

$ sfdx --version
sfdx-cli/7.27.0-714f62f9c1 win32-x64 node-v10.15.3

**Comment by gdbrianj** [comment] 2021-01-27 15:55
This is still a problem for me.

C:\Users\brian>sfdx update
sfdx-cli: Updating CLI... already on latest version: 7.84.2-a2868a68d5

C:\Users\brian>
C:\Users\brian>sfdx plugins:install @salesforce/sfdx-diff
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at onUnexpectedError (C:\Users\brian\AppData\Local\sfdx\client\7.84.2-a2868a68d5\node_modules\yarn\lib\cli.js:92121:100)
    at C:\Users\brian\AppData\Local\sfdx\client\7.84.2-a2868a68d5\node_modules\yarn\lib\cli.js:92233:9
Installing plugin @salesforce/sfdx-diff... failed
    Error: yarn add @salesforce/sfdx-diff@latest --non-interactive --mutex=file:C:\Users\brian\AppData\Local\sfdx\yarn.lock --preferred-cache-folder=C:\Users\brian\AppData\Local\sfdx\yarn
     --check-files exited with code 1

**Comment by j-fischer** [comment] 2021-03-12 18:32
I ran into this issue and was able to resolve it by deleting the `yarn.lock` folder in `C:/Users/Me/AppData/Local/sfdx/` manually and then re-running the install command.

I hope this helps anyone else running into this issue, it applies to any plugin installation.

**Comment by smaddox-sf** [comment] 2021-07-12 17:24
We have updated the Source Diff commands in VS Code.  You no longer need a CLI plugin.  [Check out the documentation for more details](https://developer.salesforce.com/tools/vscode/en/user-guide/source-diff).

**Closed by smaddox-sf** 2021-07-12 17:24 UTC
Labels: type:bug
