### ISSUE TITLE
Slow startup of SFDX VSCode plugins

### ISSUE THREAD

**Issue by klivian** [forcedotcom/salesforcedx-vscode#3831] opened 2022-02-13 11:50 UTC
### Summary

When loading a Salesforce project into VSCode, there is an increased delay in the extensions recognising it as such and loading.

### Steps To Reproduce:

1.  Open VS Code.
1.  Either open a Salesforce/SFDX project (or nothing if VS Code was last closed with such a project open and is set to restore state on load)

### Expected result

Project is detected as an SFDX project, extensions start (for example, the Open Org and Change Default Org items appear in the bottom toolbar, SFDX commands become available in the command palette)

### Actual result

Project *is* detected as per expected result, but it take anything up to a minute to do so, which is markedly slower than previously

### Additional information

Anecdotally, by canvassing other Salesforce devs on Twitter, this is affecting a lot of other people, on both PC and Mac.  I don't have definitive timings on before/after startup times, but many of us are noticing degradation of performance.  Whether this is a VS Code issue or a SFDX Extension issue remains to be seen.  This machine is no slouch either, see below...

**Salesforce Extension Version in VS Code**: Extension Pack 53.16.0

**SFDX CLI Version**: sfdx-cli/7.136.2 win32-x64 node-v16.13.2

**OS and version**:  Win 11 Pro 21H2 update

**Machine spec**: AMD Rynzen 3950X @3.49GHz, 32gb RAM, all drives fast SSD

**Comment by RitamAgrawal** [comment] 2022-04-01 20:12
Duplicate of #3198

**Closed by RitamAgrawal** 2022-04-01 20:12 UTC
Labels: area:performance

**Comment by rafaelgbo** [comment] 2023-06-13 12:37
I have been facing the same slow activation of Salesforce Extensions on VS Code on my Windows machine, and by trial and error I seem to have fixed it. I was initially using JDK 17 (more specifically, Eclipse Adoptium 17.0.6+10, for Windowx x64) and my activation times were the one you can see below:

![Eclipse Adoptium 17 0 6 10](https://github.com/forcedotcom/salesforcedx-vscode/assets/8685960/f4a99616-5088-4298-b198-2c83372a33c0)

I then uninstalled JDK 17 and installed JDK 11 (more specifically, Eclipse Adoptium 11.0.19+7, for Windowx x64) and my activation times were reduced by a factor of 9 (see below).

![Eclipse Adoptium 11 0 19_7](https://github.com/forcedotcom/salesforcedx-vscode/assets/8685960/69a4719f-331b-4472-81c2-afe13930a8eb)

Hope this helps!

**Comment by ghuroo** [comment] 2023-06-16 09:50
> I have been facing the same slow activation of Salesforce Extensions on VS Code on my Windows machine, and by trial and error I seem to have fixed it. I was initially using JDK 17 (more specifically, Eclipse Adoptium 17.0.6+10, for Windowx x64) and my activation times were the one you can see below:
> 
> ![Eclipse Adoptium 17 0 6 10](https://user-images.githubusercontent.com/8685960/245476647-f4a99616-5088-4298-b198-2c83372a33c0.png)
> 
> I then uninstalled JDK 17 and installed JDK 11 (more specifically, Eclipse Adoptium 11.0.19+7, for Windowx x64) and my activation times were reduced by a factor of 9 (see below).
> 
> ![Eclipse Adoptium 11 0 19_7](https://user-images.githubusercontent.com/8685960/245477084-69a4719f-331b-4472-81c2-afe13930a8eb.png)
> 
> Hope this helps!

it did help! a lot! I did exactly what you described and loading times are now back to normal.
