### ISSUE TITLE
Unable to install Salesforce Extension Pack in my VS code

### ISSUE THREAD

**Issue by saurabhsoodsfdc** [forcedotcom/salesforcedx-vscode#3864] opened 2022-02-28 07:11 UTC
### Summary
My “Salesforce Extension Pack” extension got crashed and when I’m trying to re-install it, facing the below issue and was unable to re-install it.
I tried re-installing VS code again but no luck same error getting again!!

> 2022-02-25 21:11:02.015] [renderer1] [error] ["Error: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found","    at vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17874","    at Array.reduce (<anonymous>)","    at w (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17860)","    at O.joinAllSettled (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:9049)","    at async O.installExtension (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:6762)","    at async O.installFromGallery (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3030)"]
> [2022-02-25 21:11:02.078] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found: Error: Corrupt ZIP: end of central directory record signature not found,Corrupt ZIP: end of central directory record signature not found
>     at vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17874
>     at Array.reduce (<anonymous>)
>     at w (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:17860)
>     at O.joinAllSettled (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:9049)
>     at async O.installExtension (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:6762)
>     at async O.installFromGallery (vscode-file://vscode-app/private/var/folders/d2/6lk9kp613tz_5gwvz7jh27dr0000gp/T/AppTranslocation/A5135E4B-E6A8-4BE3-AB8F-9BC1D0093AD8/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:3030)
> 

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by jag-sfdc** [comment] 2022-02-28 18:05
Seems like a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/3862. Closing this.

**Closed by jag-sfdc** 2022-02-28 18:05 UTC
