### ISSUE TITLE
Org Picker shows incorrect default org

### ISSUE THREAD

**Issue by EstebanRomero84** [forcedotcom/salesforcedx-vscode#3226] opened 2021-05-11 15:59 UTC
After I selected a different org in Org Picker, it keeps showing the previous selected org.
![Capture](https://user-images.githubusercontent.com/30849643/117847426-b6487480-b258-11eb-875c-71550bb1e135.PNG)

**Comment by smaddox-sf** [comment] 2021-05-12 17:45
Hi @EstebanRomero84 - Thanks for reaching out.  Can you share a bit more detail:

1. VS Code Version
2. SFDX CLI Version
3. OS and version
4. What type of Orgs are you working with?
4. **Confirm the steps to reproduce** From the description, it sounds like it might be something along the lines of what I put below.  Can you share the steps you executed to hit this issue so we can reproduce it?
- Authenticate an org using `SFDX Authorize an Org`
- Click the Org alias in the status bar to bring up the Org Picker
- Click on another org that you previously authenticated

**Comment by EstebanRomero84** [comment] 2021-05-12 19:33
Hi @smaddox-sf - Please find more details bellow:

1. VS Code Version: 1.56.1
2. SFDX CLI Version: sfdx-cli/7.99.0 win32-x64 node-v15.14.0
3. OS and version: Windows 10 Pro 19042
4. Type of Orgs: Sandbox
5. Exactly as you said: 

- Authenticate an org using SFDX Authorize an Org

- Click the Org alias in the status bar to bring up the Org Picker

- Click on another org that you previously authenticated

**Comment by smaddox-sf** [comment] 2021-05-12 19:40
Thanks @EstebanRomero84 - On the VS Code version, can you share the version of the Salesforce extensions?  You can see it from the marketplace tab - example:

![image](https://user-images.githubusercontent.com/59572234/118034715-27eaf600-b31f-11eb-9f6d-7233dc4ff369.png)


Can you also copy & paste what you see in the 'Output' panel for the steps you listed above?

**Comment by EstebanRomero84** [comment] 2021-05-13 16:02
@smaddox-sf 
Salesforce Extension Pack: 51.12.0

![Capture](https://user-images.githubusercontent.com/30849643/118152692-5fbf6f80-b3eb-11eb-9ba6-2ef0b5ec27d8.PNG)

**Comment by xyc** [comment] 2021-06-08 18:52
can we confirm that `defaultusername` field in `.sfdx/sfdx-config.json` file in your project folder is the username of the correct org (previous org you have authenticated in the step "Authenticate an org using SFDX Authorize an Org")?

**Comment by EstebanRomero84** [comment] 2021-06-08 19:42
defaultusername field in .sfdx/sfdx-config.json file is the username of the org I selected in step 3 (In my example it would be Cladd_Qa)

**Comment by xyc** [comment] 2021-06-08 20:17
As I understand, the actual default org is set correctly, just that the org picker doesn't show the correct one. Is that right?

**Comment by jeffb-sfdc** [comment] 2022-06-07 17:10
@EstebanRomero84 I'm looking into this, however, I wasn't able to reproduce the issue.  I created a developer edition org, and from that created two scratch orgs.  When I launched VS Code, I was able to switch back and forth, and everything 
seemed to function correctly.  This ticket was opened a while ago, so I'd like to know 1) does this issue still happen?  2) If so, could you provide more detailed (step-by-step) instructions to reproduce the issue?  Perhaps I'm going about trying to reproduce the issue in a way that's different from what you are doing.

**Comment by EstebanRomero84** [comment] 2022-06-07 17:29
@jeffb-sfdc no, I haven't face this issue again.

**Comment by jeffb-sfdc** [comment] 2022-06-21 20:33
@amtrack I'm not able to reproduce this.  Do you have steps to reproduce this?

**Comment by amtrack** [comment] 2022-06-24 11:11
@jeffb-sfdc 
I recorded a short video to show you the steps and the outcome:

https://user-images.githubusercontent.com/789765/175522571-bbcd4f49-b686-43c1-9950-97479fb562a7.mov

I've installed the latest sfdx version using:

```console
$ yarn global add sfdx-cli
...
$ sfdx --version
sfdx-cli/7.156.1 darwin-x64 node-v16.13.2
```

I've installed the following VS Code extensions:

```console
$ code --list-extensions --show-versions
dbaeumer.vscode-eslint@2.2.2
eamodio.gitlens@12.1.1
EditorConfig.EditorConfig@0.16.4
esbenp.prettier-vscode@9.5.0
janisdd.vscode-edit-csv@0.7.1
ms-vscode-remote.remote-containers@0.238.2
ms-vscode-remote.remote-ssh@0.82.1
ms-vscode-remote.remote-wsl@0.66.3
ms-vscode-remote.vscode-remote-extensionpack@0.21.0
salesforce.salesforce-vscode-slds@1.4.8
salesforce.salesforcedx-vscode@55.0.0
salesforce.salesforcedx-vscode-apex@55.0.0
salesforce.salesforcedx-vscode-apex-debugger@55.0.0
salesforce.salesforcedx-vscode-apex-replay-debugger@55.0.0
salesforce.salesforcedx-vscode-core@55.0.0
salesforce.salesforcedx-vscode-lightning@55.0.0
salesforce.salesforcedx-vscode-lwc@55.0.0
salesforce.salesforcedx-vscode-soql@55.0.0
salesforce.salesforcedx-vscode-visualforce@55.0.0
streetsidesoftware.code-spell-checker@2.2.5
```

Here is more info about my OS and VS Code:

```text
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z (1 wk ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0
```

**Comment by angela-young** [comment] 2022-07-05 23:00
@amtrack I have followed your steps but am unable to reproduce this bug on my end. Both `.sfdx/sfdx-config.json` and `.sf/config.json` are updating correctly, and the default org is displaying correctly. 

https://user-images.githubusercontent.com/60243824/177430496-1f60db93-3d42-44e5-a3f6-337be7d6ad64.mov

Closing this issue due to lack of reproducibility.

**Closed as completed by angela-young** 2022-07-05 23:00 UTC
Labels: type:bug, more information required, area:orgmanagement
