### ISSUE TITLE
Error pulling metadata - but only using command palette, on Windows, very first time. Repo and YouTube link provided.

### ISSUE THREAD

**Issue by jflowers45** [forcedotcom/salesforcedx-vscode#2602] opened 2020-08-05 23:39 UTC
### Summary

A bit of context first - I am a DEX602 instructor (Salesforce's LWC Class) and also helped build the course. This issue is impacting students on Windows machines. I have spent several hours troubleshooting this so that I could provide a very simple reproducible issue.

In the beginning of the course, we ask students to do the following:

1. Create a scratch org using a repo provided by class.
1. Create a custom lwc and place it on a new custom flexipage.
1. Pull metadata back down to repo.

The metadata pull fails for Windows users - and ONLY Windows users. It only fails the first time, and it only fails that first time if they use the command palette command `SFDX: Pull Source from Default Scratch Org` rather than typing `sfdx force:source:push` in a terminal. 

I am unable to reproduce the issue on a Mac, and I am also unable to reproduce the issue if I directly use the `sfdx force:source:pull` command from a Windows terminal rather than the command palette. Also, if I use `SFDX: Pull Source from Default Scratch Org and Override Conflicts` the first time, everything comes through fine.

I have significantly simplified the issue by providing an extremely basic project and a short set of steps to follow to reproduce. To be extra clear, I've created the following YouTube video because you almost have to see it to believe it: https://www.youtube.com/watch?v=aCZ_Zxakbh0

We can work around it by having Windows students run the pull twice from command palette, or use the force override palette command, or run the pull directly from a Terminal, but if we have to do that it would be nice to provide some sort of explanation for this quirk. 

### Steps To Reproduce:

**Repository to reproduce:** [cli-conflict](https://github.com/jflowers45/cli-conflict)

1.  Use a Windows machine
1.  Clone repo https://github.com/jflowers45/cli-conflict
1.  Make sure a default dev hub is set
1.  Run CreateOrg.bat
1.  Create a flexipage in the scratch org, activate it and add it to the Commerce App and Mobile Navigation Menu
1.  Run the command - MUST use the command palette -  `SFDX: Pull Source from Default Scratch Org`
1.  Run the command a second time using the command palette -  `SFDX: Pull Source from Default Scratch Org`

### Expected result

First metadata pull succeeds.

### Actual result

First metadata pull gives a conflict on the training user profile. Second metadata pull succeeds.

### Additional information

YouTube video: https://www.youtube.com/watch?v=aCZ_Zxakbh0

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.68.6-d37008df83 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.4.1 (core)
├─ salesforcedx-templates 48.32.0 (core)
├─ custom-metadata 1.0.7 (core)
├─ salesforce-alm 49.4.0 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.68.6 (core)

**OS and version**:
Edition: Windows 10 Home
Version: 1903
OS Build: 18362.959

**Comment by lcampos** [comment] 2020-10-07 02:01
Thanks for providing all these details @jflowers45 . As @aheber already mentioned this is a duplicate of issue https://github.com/forcedotcom/cli/issues/108 which is an issue with how the cli handles tracks file paths for a project that use source tracking, mainly affecting commands source:push & source:pull.

@clairebianchi should we close this a duplicate or do you want me to transfer it back to the cli repo ?

cc @smaddox-sf @ntotten

**Comment by clairebianchi** [comment] 2020-10-07 20:52
@lcampos we can close it here as a dup of forcedotcom/cli#108

**Closed by clairebianchi** 2020-10-07 20:52 UTC
