### ISSUE TITLE
VSCode Stuck on 'Activating Extensions' When Running 'SFDX: Create Project with Manifest

### ISSUE THREAD

**Issue by urstrulyvaibhav26** [forcedotcom/salesforcedx-vscode#5817] opened 2024-09-05 19:53 UTC
![Activating Extensions](https://github.com/user-attachments/assets/8a99e86f-fd19-4313-9cd3-fb78606c87c7)
![Developer Show Running Extension](https://github.com/user-attachments/assets/a7540dec-cbd2-43ba-990d-2b37ab9ce3d6)
Type: <b>Bug</b>

I installed VSCode Version 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

I then installed the Salesforce extension package, i.e., Salesforce CLI Integration (61.12.0), as well as the Salesforce Extension Pack (61.12.0). Now, when I press Ctrl+Shift+P, type 'SFDX: Create Project with Manifest,' and press Enter, VSCode says 'Activating extensions...' for a few seconds and then does nothing.

Expected result: Things work.
Actual result: Things don't work.

Extension version: 61.12.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.10GB free)|
|Process Argv|--crash-reporter-id 7f5b327d-3ce7-4d76-8ea1-2de7d1b23b6b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by urstrulyvaibhav26** [comment] 2024-09-05 20:06
Here’s the requested info:

Salesforce Extension Version in VS Code:
Salesforce CLI Integration (61.12.0), Salesforce Extension Pack (61.12.0)

Salesforce CLI Version:
61.12.0

OS and version:
Windows_NT x64 10.0.19045

VS Code version:
Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0

Most recent version of the extensions where this was working:
Not sure, as I installed it newly on Sep 4, 2024.

**Comment by urstrulyvaibhav26** [comment] 2024-09-05 20:14
To Reproduce the Issue:

1. Install VSCode:

Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

2. Install the Extensions:

Salesforce CLI Integration (version 61.12.0)
Salesforce Extension Pack (version 61.12.0)

3. Execute the Command:

Open the Command Palette with Ctrl+Shift+P.
Type SFDX: Create Project with Manifest and select it.
Press Enter.

4. Observe the Behavior:

- VSCode will display "Activating extensions..." for a few seconds.

- It then does nothing, and the expected project creation does not occur.

Expected Result: The SFDX: Create Project with Manifest command should successfully create a new Salesforce project with the specified manifest.

Actual Result: VSCode gets stuck on "Activating extensions..." and does not proceed with the project creation.

**Comment by daphne-sfdc** [comment] 2024-09-05 20:19
Hi @urstrulyvaibhav26, I see that you wrote "61.12.0" for "Salesforce CLI Version".  That's the value of the extensions version.  To get the CLI version, can you please run `sfdx --version` in your Terminal and send us the result?

**Comment by urstrulyvaibhav26** [comment] 2024-09-05 20:27
@salesforce/cli/2.57.7 win32-x64 node-v20.16.0
![Salesforce CLI Version](https://github.com/user-attachments/assets/cfb82b3d-c196-4569-ab4f-896908fc5d8b)

**Comment by daphne-sfdc** [comment] 2024-09-05 20:42
@urstrulyvaibhav26

In the command palette, run `Developer: Toggle Developer Tools`.  What do you see there?

Also, do you see any problems in the Problems tab?

**Comment by urstrulyvaibhav26** [comment] 2024-09-05 20:55
Hey, just a quick update: In the meantime, I uninstalled everything, including VSCode, deleted the .vscode folder, and the code folder under AppData > Roaming > Code. I also uninstalled Salesforce CLI. After that, I reinstalled everything, and now everything works fine. Thanks for your helpful assistance and quick support. I really appreciate it.

**Comment by urstrulyvaibhav26** [comment] 2024-09-05 20:56
![Uploading active extension.png…]()

**Comment by urstrulyvaibhav26** [comment] 2024-09-05 20:57
![active extension](https://github.com/user-attachments/assets/7b085562-c52c-4845-bfd2-f2048b87f365)

**Comment by daphne-sfdc** [comment] 2024-09-05 20:59
Thanks for the update, and glad to hear that everything is now working for you!  Yes, your last screenshot of the Problems tab and status bar looks as expected.

I'll close this issue as the problem is now resolved. ✅ Feel free to reopen if the problem comes back.

**Closed by daphne-sfdc** 2024-09-05 20:59 UTC
Labels: more information required, validated
