### ISSUE TITLE
Showing this error when i open the html file

### ISSUE THREAD

**Issue by Sourabh42** [forcedotcom/salesforcedx-vscode#3924] opened 2022-03-16 07:33 UTC
![image](https://user-images.githubusercontent.com/41413465/158539063-c61b4472-e9d4-4ca0-86e0-59c0859261a2.png)

**Comment by randi274** [comment] 2022-03-16 21:02
Thanks for reporting this! It looks to be a duplicate of #3929; so closing this one as we track changes on that ticket.

**Closed by randi274** 2022-03-16 21:02 UTC
Labels: status:duplicate
