### ISSUE TITLE
Deploy with problems for LWC using Experimental: Deploy Retrieve

### ISSUE THREAD

**Issue by gabriel-alvis** [forcedotcom/salesforcedx-vscode#2411] opened 2020-08-12 11:49 UTC
### Summary

When I deploy the LWC indicated in the Hello world LWC trailhead it is created but it can't be included in the Lightning App Builder having considered the special indications. When I deactivated the setting in VSCode: Salesforce Feature Previews - Experimental: Deploy Retrieve then it worked

### Steps To Reproduce:

1.  In VSCode enable setting Experimental: Deploy Retrieve from Salesforce Feature Previews
2. Create and deploy a LWC configured to be included in a Lightning page. For example in the Sales app home page.

### Expected result

The component should appear in the custom group in Lightning App Builder

### Actual result

The component doesn't appear in the custom group in Lightning App Builder

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.47.3
Extension pack
49.4.0

**SFDX CLI Version**:
7.69.0-c7be45ae22 
Node-v12.18.3

**OS and version**:

Windows 10 Enterprise
x64
10.0.19041

**Comment by lcampos** [comment] 2020-08-14 17:01
Thanks for logging this @gabriel-alvis . This is a duplicate of #2302 which we're looking into it. We'll be providing updates on that github issue so I'm closing this one for now.

**Closed by lcampos** 2020-08-14 17:01 UTC
