### ISSUE TITLE
Error in clearing Problem tab in VS Code after Successful deployment of code

### ISSUE THREAD

**Issue by suchir-agrawal** [forcedotcom/salesforcedx-vscode#4914] opened 2023-06-07 15:27 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. Create an Apex class having an error
2. Try to deploy it, System will show errors on the Problem tab.
3. Resolve that error and deploy again.

### Expected result

The Problem tab should get empty and stop showing those false errors

### Actual result

Even after successful deployment problem tab keeps showing Error.

### Additional information

this start happening after latest version.
<img width="613" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/51295535/5ac14aad-9466-4472-b24e-2c4d0753222a">
<img width="1151" alt="Screenshot 2023-06-07 at 8 55 58 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/51295535/ad94d3f5-ad60-4b93-8517-446ce1f87fd4">

**Comment by CristiCanizales** [comment] 2023-06-07 16:02
HI! Thanks for the screenshots and detailed info. This seems to be a duplicate of #4904 though, so I'll close this one and will get back to you there.

**Closed by CristiCanizales** 2023-06-07 16:02 UTC
