### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jojoforce** [forcedotcom/salesforcedx-vscode#2528] opened 2020-09-16 01:14 UTC
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5229017/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\joseph.s.orcio\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-09-16 16:54
There's not a lot of details here, but I believe this is a duplicate of #2410.  Check out that issue for a workaround and please post any further feedback.  (or open a new issue with the 'bug' template if this is a different issue)

**Closed by smaddox-sf** 2020-09-16 16:54 UTC
