### ISSUE TITLE
Not able to create project. My Salesforce extensions are not getting activated.

### ISSUE THREAD

**Issue by AnveshSingh1707** [forcedotcom/salesforcedx-vscode#2332] opened 2020-07-08 09:25 UTC
### Summary

When I open my vs code & when I click on the link "create a project with manifest" from the command palette, the VS code doesn't respond. After a few minutes, I get a message 
![image](https://user-images.githubusercontent.com/68004649/86901413-329a9480-c12a-11ea-892f-7d6b1352c472.png)
NOTE: I have set my Java.memory to 4096 MB

### Steps To Reproduce:

1.  Open VS Code.
1.  From command Palette, click ">SFDX Create Project With Manifest".
### Expected result
An option should come up To choose the template, standard, empty something like that.

### Actual result

Nothing happens. 

### Additional information

My Jdk is 11, I have set the java path in vs code too.
![image](https://user-images.githubusercontent.com/68004649/86901790-b6548100-c12a-11ea-8568-297e1d2d003c.png)

**VS Code Version**: [Version 10.0.18362.900]

**SFDX CLI Version**: sfdx-cli/7.63.0-c897e8bb1a win32-x64 node-v10.20.1

**OS and version**: Windos 10 pro, version 1903

**Comment by smaddox-sf** [comment] 2020-07-08 18:15
HI @AnveshSingh1707 - Do you see the same error when you open an existing project?

**Comment by AnveshSingh1707** [comment] 2020-07-09 05:21
@smaddox-sf No, I don't get any error. But I don't see anything happening either.
I waited for 15-20 minutes before clicking "Create Project with Manifest" to be assured that all my extensions are loaded correctly.
But still, nothing happens.
I at the bottom left it says "Activating Extensions.." and then nothing happens.
Please help me out. I am in deep need of VS code.
I have tried update,install, reinstall.

**Comment by lcampos** [comment] 2020-07-10 00:23
@AnveshSingh1707 we released some changes in version 48.24.0 that speed up the activation of the extensions. We're working on follow up enhancements but let us know if your experience got a bit better now.

I'm closing this issue since it's a duplicate of #2295 which is where we'll keep posting updates.

**Closed by lcampos** 2020-07-10 00:23 UTC

**Comment by Seshadri724** [comment] 2024-12-28 05:40
> @smaddox-sf No, I don't get any error. But I don't see anything happening either. I waited for 15-20 minutes before clicking "Create Project with Manifest" to be assured that all my extensions are loaded correctly. But still, nothing happens. I at the bottom left it says "Activating Extensions.." and then nothing happens. Please help me out. I am in deep need of VS code. I have tried update,install, reinstall.

Did you find the solution for the issue ??
i got the same issue ,i am not able to rectify
Help me someone!!
