### ISSUE TITLE
When I try to create SFDX Project in VS Code, it showing activating extensions. after that nothing happens

### ISSUE THREAD

**Issue by kmukesh246** [forcedotcom/salesforcedx-vscode#2288] opened 2020-06-24 05:21 UTC
### Summary

When I try to create SFDX Project in VS Code, it showing activating extensions. after that nothing happens

### Steps To Reproduce:

Open VS code
Ctrl + Shift + P and hit SFDX Create Project

### Expected result

Project Name and type pop up should come to enter

### Actual result

It is just showing Activating Extensions for a second then it disappeared after this nothing happens.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:  1.46.1

**SFDX CLI Version**: 7.63.0-c897e8bb1a

**OS and version**: Windows 10

**Comment by smaddox-sf** [comment] 2020-06-30 17:08
Hi @kmukesh246 - Thanks for reaching out. It sounds like the CLI setup might not be quite right.  
can you verify if the CLI configuration is [setup as described here](https://developer.salesforce.com/tools/vscode/en/troubleshooting/#set-salesforce-cli-path-windows)?

**Comment by kmukesh246** [comment] 2020-07-01 13:44
Hi @smaddox-sf, I had verified the CLI setup. It was the same as documentation. but it didn't work. then I have installed the Operating System (OS) again. then it worked. and even now when I close and open the VS code, The SFDX extensions taking much time to load and activate. sometimes when trying to create a project at that instance only the extensions getting activated.

**Comment by lcampos** [comment] 2020-07-10 00:25
We released some changes in version 48.24.0 that speed up the activation of the extensions. We're working on other enhancements but let us know if your experience got a bit better now.

I'm going to close this issue since it's a duplicate of #2295 which is where we'll keep posting updates.

**Closed by lcampos** 2020-07-10 00:25 UTC

**Comment by aanshkumar** [comment] 2024-09-24 06:03
@mukesh-kandasamy i am facing the same issue again, previously i removed the extension and after re installing and with the extenion it worked but again after a week i am facing the same issue, could anyone help me out with this.

**Comment by peternhale** [comment] 2024-09-24 12:16
@aanshkumar Would you mind opening a new issue for the behavior you are seeing?

**Comment by mukesh-kandasamy** [comment] 2024-09-24 17:51
@aanshkumar This might sound ridiculous, but it only started working after I reinstalled the OS!

**Comment by ShivamK2002** [comment] 2024-12-21 07:39
@mukesh-kandasamy @aanshkumar any better solution than reinstalling the os cause I am tired of doing so.

**Comment by Mahak37** [comment] 2025-03-07 09:56
Hi
I am also having same issue, I cannot create project or create project with manifest it is activating extensions for a second and then nothing happens. I have tried authorizing an org it is working fine but I cannot create any project after that. Please tell me how to solve this problem.

**Comment by Mahak37** [comment] 2025-03-07 10:00
@mukesh-kandasamy is your issue solved?
