### ISSUE TITLE
Retrieve Source from Org "Unknown Exception"

### ISSUE THREAD

**Issue by jdagrawal008** [forcedotcom/salesforcedx-vscode#3177] opened 2021-04-25 21:12 UTC
### Summary

Whenever I try to retrieve with SFDX it is throwing Unknown Exception. Sometimes this works sometimes it doesn't. Not sure what's wrong here. It works for a few orgs but not for others. No specific detail is provided in this issue. Tired of getting this issue a ton of time.

### Steps To Reproduce:

1. Create a new project with SFDX: Create a Project with Manifest.
2. Authorize any org (Dev Org/Sandbox/Production) doesn't matter
3. Try to retrieve the code from Package.xml (Nothing specific is needed in Package.xml)
4. You'll find the "Unknown Exception" in the Output Panel of the VSCode

***NOTE:**  If it works for the new project then try with an existing project.*

1. Try to retrieve the code from Package.xml (Nothing specific is needed in Package.xml)
2. You'll find the "Unknown Exception" in the Output Panel of the VSCode

### Expected result

The code should get retrieved which is defined in the package.xml

### Actual result

Starting SFDX: Retrieve Source from Org

Unknown Exception

![image](https://user-images.githubusercontent.com/72457872/116009955-d877ab00-a639-11eb-8413-1eddc10c3b33.png)

### Additional information

Tried with 
1. Re-authorizing the org
2. Updating the sfdx cli
3. Restarted VSCode
4. Restarted complete system

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.98.0 win32-x64 node-v15.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ apex 0.1.21 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.0.5 (core)
├─ user 1.2.8 (core)
├─ schema 1.0.5 (core)
├─ templates 51.3.0 (core)
├─ org 1.6.2 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.11 (core)
sfdx-cli 7.98.0 (core)
telemetry 1.1.2 (core)

**OS and version**: Windows 10 Pro, 20H2

**Comment by tony-tawk-ei** [comment] 2021-04-26 16:38
The right click retrieve from inside package.xml is working when I disabled "use library for deploy and retrieve commands instead of the CLI" , Thank you

**Comment by jdagrawal008** [comment] 2021-04-26 16:53
@WillieRuemmele Can you please provide me with an example for the command `sfdx force:source:retrieve -x <path to your package>` I'm not sure how I enter the path to package for Windows OS?

**Comment by sfsholden** [comment] 2021-04-26 17:02
Closing as a duplicate of #3137.

For more information on the setting, please see #3109. 

This was a fairly recent change that should help a lot with performance on deploys and retrieves. We are still working out some of the gaps. Thank you for bringing this to our attention and please continue to let us know if you see any other issues!

@jdagrawal008 
For the command `sfdx force:source:retrieve -x <path to your package>`:
It should be possible to copy the path directly from VSCode. Right click on your `package.xml` file within VSCode > Select `Copy Path`.  Then this value can be substituted in for <path to your package>.

**Closed by sfsholden** 2021-04-26 17:02 UTC

**Comment by jdagrawal008** [comment] 2021-04-26 17:29
>It should be possible to copy the path directly from VSCode. Right click on your package.xml file within VSCode > Select Copy Path. Then this value can be substituted in for <path to your package>.

@sfsholden I did tried the above steps which you mentioned. But I'm getting an error "Unexpected argument: flowPBSmanifestpackage.xml"

Even I tried with sfdx force:source:retrieve -x manifest\package.xml
That also throws the error "The specified manifest file [manifestpackage.xml] does not exists, or you don't have access to it."
