### ISSUE TITLE
Project create throws `Unrecognized flag : {"name":"projectname" ..` error

### ISSUE THREAD

**Issue by ashaalex28** [forcedotcom/salesforcedx-vscode#1351] opened 2019-05-16 12:25 UTC
Issue Type: <b>Bug</b>

Install Salesforce Extension pack and Salesforce CLI Integration.From Command Pallette->SFDX:Create Project with manifest->Enter project name
This gives error:
Starting SFDX: Create Project

17:49:36.933 sfdx force:project:create --projectname NPPTest3 --outputdir c:\Salesforce\NPPProjects --template standard --manifest
Error: Unrecognized flag: {"name":"projectname","char":"n","required":true,"description":"name of the generated project","longDescription":"The name for the new project. Any valid folder name is accepted.","type":"string","values":[]}
    at flags.forEach.flag (C:/Program Files/Salesforce CLI/client/node_modules/force-language-services/dist/common/main/LegacyCommand.js:77:31)
    at Array.forEach (<anonymous>)
    at Function.toFlagsConfig (C:/Program Files/Salesforce CLI/client/node_modules/force-language-services/dist/common/main/LegacyCommand.js:28:19)
    at Object.<anonymous> (C:/Program Files/Salesforce CLI/client/node_modules/force-language-services/dist/oclif/force/project/create.js:31:66)
    at Module._compile (C:/Program Files/Salesforce CLI/client/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at LazyLoader.loadModule (C:/Program Files/Salesforce CLI/client/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:139:21)
    at Function._load (C:/Program Files/Salesforce CLI/client/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:115:29)
    at require (C:/Program Files/Salesforce CLI/client/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at fetch (C:/Program Files/Salesforce CLI/client/node_modules/@oclif/config/lib/plugin.js:101:21)
    at Plugin.findCommand (C:/Program Files/Salesforce CLI/client/node_modules/@oclif/config/lib/plugin.js:115:21)
    at Object.load (C:/Program Files/Salesforce CLI/client/node_modules/@oclif/config/lib/plugin.js:48:72)
17:49:48.90 sfdx force:project:create --projectname NPPTest3 --outputdir c:\Salesforce\NPPProjects --template standard --manifest ended with exit code 1

Extension version: 45.14.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by lcampos** [comment] 2019-05-16 12:27
Hi @ashaalex28 , I think this might be caused by you being on an old Salesforce CLI version. Can you open your terminal and run sfdx --version to see in which version you are on ? The latest version is 7.5.0. If you are in version 6.x.x or below, you can run sfdx update and re-running SFDX: Create Project with Manifest should work.

I'm also closing this as a duplicate of #1324, please re-open the issue if updating your cli version does not fix this.

**Comment by ashaalex28** [comment] 2019-05-16 12:32
I ran the sfdx update command..This is what I see:
sfdx-cli: Updating CLI... already on latest version: 7.5.0-e6ca93eee8

**Comment by lcampos** [comment] 2019-05-16 13:27
Do you see a `--manifest` line under the Options section when you run `sfdx force:project:create --help` ? 

<img width="623" alt="sfdx_project_create_help" src="https://user-images.githubusercontent.com/1041842/57857271-a00b9900-77a3-11e9-8bcf-e1fb1b934b8d.png">

**Comment by ashaalex28** [comment] 2019-05-16 14:10
Yes.I do see it.

**Comment by lcampos** [comment] 2019-05-16 14:20
Do you still see that error if you run `SFDX: Create Project with Manifest` again ?

**Comment by ashaalex28** [comment] 2019-05-16 14:51
Yes

**Comment by ashaalex28** [comment] 2019-05-17 04:28
Can you please reopen the issue?

**Comment by lcampos** [comment] 2019-05-17 09:39
Sure. When you execute `sfdx --version` from VSCode's terminal, do you get that same version number ? I'm not able to replicate your cli error and it seems that the issue is with the `projectname` flag and not with the `--manifest` flag.

What happens if you run `sfdx force:project:create --projectname NPPTest3 --outputdir c:\Salesforce\NPPProjects --template standard --manifest` directly in the command line ? Does it create the project ?

**Comment by ashaalex28** [comment] 2019-05-17 14:04
From VSCode's terminal,this is what i see:
 sfdx --version
sfdx-cli/7.5.0-e6ca93eee8 win32-x64 node-v10.15.3

On running the commandfrom command line,I get the same error:"Error: Unrecognized flag:"

**Comment by Stragis** [comment] 2019-05-20 18:00
I am also receiving this error. Do you guys have JDK 12 installed?

**Comment by ashaalex28** [comment] 2019-05-21 06:05
No.These are my java version details.
java -version
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by ashaalex28** [comment] 2019-05-21 06:10
@lcampos -do we have a work around till this gets fixed? It would be very helpful to proceed with my work.

**Comment by Stragis** [comment] 2019-05-21 08:15
I was able to resolve my issue by installing specific version of SFDX
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm 

` sfdx plugins:install salesforcedx@45.15.6`

**Comment by ashaalex28** [comment] 2019-05-21 12:49
@Stragis -Thanks a lot! That worked. :)

**Comment by lcampos** [comment] 2019-05-21 13:41
@Stragis thanks for providing the fix. Just to clarify some things before closing this. This was not related to Java or JDK configuration since that exclusively affects functionality for the apex debuggers & the apex extension.

The reason why @Stragis' answer is the correct fix is because you've previously installed a version of the `salesforcedx` cli plugin which does not include the code for the `--manifest` flag. Having the `salesforcedx` plugin installed overrides the module provided out-of-the-box by the Salesforce CLI which is the one that includes the `--manifest` flag. Updating to a more recent version of that plugin or uninstalling the plugin will address the issue.

**Closed by lcampos** 2019-05-21 13:41 UTC

**Comment by ashaalex28** [comment] 2019-05-22 08:01
Thanks for the explanation.
