### ISSUE TITLE
"File Not Found" Message When Clicking On Apex (Deploy) Errors In The Problem Pane

### ISSUE THREAD

**Issue by MenachemShanowitzSide** [forcedotcom/salesforcedx-vscode#4140] opened 2022-05-18 02:15 UTC
### Summary

After deploying an apex file (SFDX: Deploy Source to Org), clicking on the Salesforce errors in the problem pane does not navigate to the line with the error and "Unable to open 'Filename.cls': File not found." message is shown.

### Steps To Reproduce:

1.  Deploy apex file with errors

### Expected result

_Clicking on the error in the error pane should navigate to the line with the error_.

### Actual result

_Unable to open 'Filename.cls': File not found. message is shown_.

### Additional information

Output in Log(Window)
[2022-05-17 21:49:06.140] [renderer8] [error] Error: File not found
    at handleSetInputError (vscode-file://vscode-app/private/var/folders/9r/12n3905x6b74_g2xbj4_yzl40000gq/T/AppTranslocation/0B8F6C83-CDCB-4186-93DA-FC1A3695F5AF/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2376:112112)
    at async h.setInput (vscode-file://vscode-app/private/var/folders/9r/12n3905x6b74_g2xbj4_yzl40000gq/T/AppTranslocation/0B8F6C83-CDCB-4186-93DA-FC1A3695F5AF/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2376:111787)
    at async i.doSetInput (vscode-file://vscode-app/private/var/folders/9r/12n3905x6b74_g2xbj4_yzl40000gq/T/AppTranslocation/0B8F6C83-CDCB-4186-93DA-FC1A3695F5AF/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2376:26829)
    at async i.doOpenEditor (vscode-file://vscode-app/private/var/folders/9r/12n3905x6b74_g2xbj4_yzl40000gq/T/AppTranslocation/0B8F6C83-CDCB-4186-93DA-FC1A3695F5AF/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2376:25202)
    at async i.openEditor (vscode-file://vscode-app/private/var/folders/9r/12n3905x6b74_g2xbj4_yzl40000gq/T/AppTranslocation/0B8F6C83-CDCB-4186-93DA-FC1A3695F5AF/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2376:24828)
    at async vscode-file://vscode-app/private/var/folders/9r/12n3905x6b74_g2xbj4_yzl40000gq/T/AppTranslocation/0B8F6C83-CDCB-4186-93DA-FC1A3695F5AF/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2576:16600

**Salesforce Extension Version in VS Code**: 54.12.0

**SFDX CLI Version**: sfdx-cli/7.148.3 darwin-x64 node-v16.13.1

**OS and version**: MacOS 12.3.1

**Comment by klewis-sfdc** [comment] 2022-05-26 00:45
Hi @MenachemShanowitzSide, thanks for reporting the issue.  The same issue has been logged so I am closing this as a duplicate of #4132. Feel free to follow that issue for updates.  Thank you!

**Closed by klewis-sfdc** 2022-05-26 00:45 UTC
Labels: status:needs eng review
