### ISSUE TITLE
Cannot install 40.5.1 (Cannot upgrade Apex extension to 40.5.1)

### ISSUE THREAD

**Issue by PeterLinBiz** [forcedotcom/salesforcedx-vscode#50] opened 2017-08-11 14:15 UTC
### Summary
Cannot install 40.5.1 (Cannot upgrade Apex extension to 40.5.1)

### Steps To Reproduce:
Cannot install 40.5.1
1. Uninstall all current salesforcedx-vscode extension bundle
2. Install salesforcedx-vscode-core
3. The "Install" came back to green status from Grey Blue "Installing" button

Cannot upgrade Apex extension to 40.5.1
1. Install salesforcedx-vscode extension bundle 40.4.0
2. Except for Apex extension, all other salesforcedx-vscode extension bundle members has been upgraded to 40.5.1 automatically.
3. Click green "Install" under salesforcedx-vscode-apex 40.4.0
3. The "Install" came back to green status from Grey Blue "Installing" button, and salesforcedx-vscode-apex remained as 40.4.0

### Expected result
Install as 40.5.1 or upgrade to 40.5.1

### Actual result
Cannot install 40.5.1
The "Install" came back to green status from Grey Blue "Installing" button

Cannot upgrade Apex extension to 40.5.1
The "Install" came back to green status from Grey Blue "Installing" button, and salesforcedx-vscode-apex remained as 40.4.0

### Additional information

**VS Code Version**: 1.14.2

**SFDX CLI Version**: 40.5.0, 40.4.0

**OS and version**: Windows 7 Microsoft Windows [Version 6.1.7601]

**Comment by vazexqi** [comment] 2017-08-11 15:49
@PeterLinBiz I don't have a Windows 7 machine handy but I just tried it on Windows 10 and the installation (both through upgrade and uninstall/install) went fine.

Let's try to do this manually. Could you give me the output of running the following from the command prompt:

C:\Users\nchen>code --list-extensions --show-versions
C:\Users\nchen>code --uninstall-extension salesforce.salesforcedx-vscode
C:\Users\nchen>code --list-extensions --show-versions
C:\Users\nchen>code --install-extension salesforce.salesforcedx-vscode
C:\Users\nchen>code --list-extensions --show-versions

This is what mine looks like:

```
C:\Users\nchen>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11
donjayamanne.githistory@0.2.3
eg2.tslint@0.17.0
esbenp.prettier-vscode@0.22.1
salesforce.salesforcedx-vscode@40.5.1
salesforce.salesforcedx-vscode-apex@40.5.1
salesforce.salesforcedx-vscode-core@40.5.1
salesforce.salesforcedx-vscode-lightning@40.5.1
salesforce.salesforcedx-vscode-visualforce@40.5.1
spoonscen.es6-mocha-snippets@0.0.2
stkb.rewrap@1.4.2
vscodevim.vim@0.9.0

C:\Users\nchen>code --uninstall-extension salesforce.salesforcedx-vscode
Uninstalling salesforce.salesforcedx-vscode...
Extension 'salesforce.salesforcedx-vscode' was successfully uninstalled!

C:\Users\nchen>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11
donjayamanne.githistory@0.2.3
eg2.tslint@0.17.0
esbenp.prettier-vscode@0.22.1
spoonscen.es6-mocha-snippets@0.0.2
stkb.rewrap@1.4.2
vscodevim.vim@0.9.0

C:\Users\nchen>code --install-extension salesforce.salesforcedx-vscode
Found 'salesforce.salesforcedx-vscode' in the marketplace.
Installing...
Extension 'salesforce.salesforcedx-vscode' v40.5.1 was successfully installed!

C:\Users\nchen>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11
donjayamanne.githistory@0.2.3
eg2.tslint@0.17.0
esbenp.prettier-vscode@0.22.1
salesforce.salesforcedx-vscode@40.5.1
salesforce.salesforcedx-vscode-apex@40.5.1
salesforce.salesforcedx-vscode-core@40.5.1
salesforce.salesforcedx-vscode-lightning@40.5.1
salesforce.salesforcedx-vscode-visualforce@40.5.1
spoonscen.es6-mocha-snippets@0.0.2
stkb.rewrap@1.4.2
vscodevim.vim@0.9.0
```

**Comment by PeterLinBiz** [comment] 2017-08-13 05:38
Thank you, @vazexqi !
On my personal Windows 10 [Version 10.0.15063] and VS Code 1.14.2
Everything work like your above instructions and results. (CLI)
In the UI clicking the Install and Uninstall button works as expected.

On my personal Windows 10 [Version 10.0.15063] and VS Code 1.15.0 ia32 bit & x64 bit
In the UI clicking the Install and Uninstall button works as expected for both ia32 bits & x64 bits.
But the CLI works fine for uninstalling but installing got errors as below.
C:\Users\Peter>code --uninstall-extension salesforce.salesforcedx-vscode
Uninstalling salesforce.salesforcedx-vscode...
Extension 'salesforce.salesforcedx-vscode' was successfully uninstalled!

C:\Users\Peter>code --install-extension salesforce.salesforcedx-vscode
Found 'salesforce.salesforcedx-vscode' in the marketplace.
Installing...
(node:3688) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:3688) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^CTerminate batch job (Y/N)? y

**Comment by PeterLinBiz** [comment] 2017-08-13 05:42
On my work computer behind some Firewall Windows 7 [Version 6.1.7601]
VS 1.14.2 + DX-vscode 40.4.0
"Install" button worked as expected.

**Comment by PeterLinBiz** [comment] 2017-08-13 05:53
On my work computer behind some Firewall Windows 7 [Version 6.1.7601]
This is the same situation as my first comment above with additional CLI results details.
VS 1.15.0 ia32 bits & x64 bits + dx-vscode 40.5.1
The "Install" worked as below.
Windows UI:
After I clicked the "Install" button, the button changed as grey "Installing" and I run the following 3 CLI commands.
Step 1:
C:\Users\peelin>code --install-extension salesforce.salesforcedx-vscode
Extension 'salesforce.salesforcedx-vscode' is already installed.

Step 2: (MISSING Apex sub extension)
C:\Users\peelin>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11
salesforce.salesforcedx-vscode@40.5.1
salesforce.salesforcedx-vscode-core@40.5.1
salesforce.salesforcedx-vscode-lightning@40.5.1
salesforce.salesforcedx-vscode-visualforce@40.5.1

Step 3: (after about 30 seconds, when the grey "installing" button turned back to a green "Install" button)
C:\Users\peelin>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11

**Comment by PeterLinBiz** [comment] 2017-08-13 05:59
On my work computer behind some Firewall Windows 7 [Version 6.1.7601]
Without any Windows UI "Install" button clicking, the following CLI commands got errors.
VS 1.15.0 ia32 bits & x64 bits + dx-vscode 40.5.1

Step 1: (The dx-vscode was not installed.)
C:\Users\Peter>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11

Step 2: 
C:\Users\Peter>code --install-extension salesforce.salesforcedx-vscode
Found 'salesforce.salesforcedx-vscode' in the marketplace.
Installing...
(node:1752) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then
 is not a function
(node:1752) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
ApplicationInsights:Sender [ { Error: connect ECONNREFUSED 65.55.44.109:443
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
^CTerminate batch job (Y/N)? y

**Comment by PeterLinBiz** [comment] 2017-08-13 06:32
I've just found a workaround.
On my work computer behind some Firewall Windows 7 [Version 6.1.7601]

1. Uninstall VS Code (1.15.0)

2. Install VS Code (1.14.2)

3.
C:\Users\Peter>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11

4.
C:\Users\Peter>code --install-extension salesforce.salesforcedx-vscode
Found 'salesforce.salesforcedx-vscode' in the marketplace.
Installing...
ApplicationInsights:Sender [ { Error: connect ECONNREFUSED 65.55.44.109:443
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
Extension 'salesforce.salesforcedx-vscode' v40.5.1 was successfully installed!

5. 
C:\Users\Peter>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11
salesforce.salesforcedx-vscode@40.5.1
salesforce.salesforcedx-vscode-apex@40.5.1
salesforce.salesforcedx-vscode-core@40.5.1
salesforce.salesforcedx-vscode-lightning@40.5.1
salesforce.salesforcedx-vscode-visualforce@40.5.1

6. VS Code 1.14.2 Windows UI
Click "Reload" button to reload the window.

7. Use the VS Code 1.14.2 Auto Update to update to VS Code 1.15.0
C:\Users\Peter>code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.11
salesforce.salesforcedx-vscode@40.5.1
salesforce.salesforcedx-vscode-apex@40.5.1
salesforce.salesforcedx-vscode-core@40.5.1
salesforce.salesforcedx-vscode-lightning@40.5.1
salesforce.salesforcedx-vscode-visualforce@40.5.1

**Comment by vazexqi** [comment] 2017-08-14 20:04
@PeterLinBiz  - Glad you got it resolved.

What does "VS 1.15.0 ia32 bits & x64 bits + dx-vscode 40.5.1" mean? You mean you have a 32-bit version of VS Code on a 64-bit machine? That should be fine since that is the default.

I checked on the IP of 65.55.44.109. That IP is owned by Microsoft. As you can see from the trace, it is for their information gathering to see who installed what.

I am not sure if this is the issue (since it should have given problems to the other plug-ins as well). But, you can try disabling telemetry following https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting

We are not planning a release this week but please let me know if you run into any other issues next time we push an upgrade.

**Comment by PeterLinBiz** [comment] 2017-08-15 04:53
Thank you, @vazexqi !
Sorry for the confusion. "VS 1.15.0 ia32 bits & x64 bits + dx-vscode 40.5.1" means a lot. :)
1. VS 1.15.0 ia32 bits = VSCodeSetup-ia32-1.15.0.exe
2. VS 1.15.0 x64 bits = VSCodeSetup-x64-1.15.0.exe
3. VS 1.14.2 = VSCodeSetup-ia32-1.14.2.exe
4.  dx-vscode 40.5.1 = Version 40.5.1 https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode
5. DX-vscode 40.4.0 = Version 40.4.0 https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

I am not sure whether you can reproduce my comments above, but I hope the above explanation helps you understand them.

It seems that both VSCodeSetup-ia32-1.15.0.exe and VSCodeSetup-x64-1.15.0.exe cause dx-vscode 40.5.1 (specifically salesforce.salesforcedx-vscode-apex@40.5.1) cannot be install by CLI on both my Win 10 (personal) and Win 7 (work behind firewall) laptops.

**Comment by vazexqi** [comment] 2017-08-15 17:04
@PeterLinBiz - There is a regression in 1.15.0 of VS Code. I just filed a bug at https://github.com/Microsoft/vscode/issues/32580

So, the way that I showed a few days ago with 1.14 to install using the command line is not an option at this point.

That being said, I just tried again on my Windows 10 box to install it _through the UI_ and didn't run into any issues. 

It seems that you are able to install the extensions now on all your machines? If that is the case then I think we can close this issue. Not being able to install through the CLI seems to be a new VS Code 1.15 issue that the VS code team needs to track. 

Or, if there is still some issue that I missed, please let me know.

**Comment by PeterLinBiz** [comment] 2017-08-15 18:18
Thank you, @vazexqi !
Yes. Please close this issue.
I will create a new one if I find some new issue.

**Closed** 2017-08-15 18:19 UTC
