### ISSUE TITLE
Running SFDX: Authorize an Org keeps running and never connected to Org

### ISSUE THREAD

**Issue by hsomareddy** [forcedotcom/salesforcedx-vscode#2996] opened 2021-02-27 17:35 UTC
![Salesforce CLI Keeps running](https://user-images.githubusercontent.com/79624351/109395048-51b39400-7950-11eb-9dd6-bf101c5c3081.PNG)

### Summary

I am not able to connect Salesforce Org thru VS code. It keeps on running. I tried changing multiple browsers and also multiple times un-installed VS code but no luck.

### Steps To Reproduce:

1. Clicked 'No Default Org Set' and then selected SFDX: Authorize an Org option
2. Routed to Chrome web browser and then entered Salesforce credentials.

### Expected result

Salesforce Org should be connected.

### Actual result

It keeps on running but never connect to Salesforce Org.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18362

**SFDX CLI Version**:
v51.2.0
**OS and version**:
OS Name	Microsoft Windows 10 Pro

**Comment by peternoges** [comment] 2021-02-27 21:55
Same for me.

sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4
 
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by hsomareddy** [comment] 2021-02-28 17:26
> Same for me; i'm guessing its related to #2931 ?
> 
> I fixed this on my machine after doing all three steps 1,2, and 3. I only Noticed it working after completing 1,2,3 in sequential order:
> 
> 1. uninstalled/reinstalling  node.js,
> 2. uninstalling/reinstalling sfdx
> 3. uninstalling/reinstalling Salesforce CLI in the following way:
>    https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm
>    https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli
> 
> My environment:
> 
> SFDX version:
> sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4
> 
> Other info:
> Salesforce CLI Integration 51.2.0
> Salesforce Extension Pack 51.2.0
> ...
> 
> VSCODE:
> Version: 1.53.2 (user setup)
> Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Date: 2021-02-11T11:48:04.245Z
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19041

Hi Peter, I tried but not working for me. Please suggest what else be the problem?

**Comment by peternoges** [comment] 2021-02-28 19:18
> > Same for me; i'm guessing its related to #2931 ?
> > I fixed this on my machine after doing all three steps 1,2, and 3. I only Noticed it working after completing 1,2,3 in sequential order:
> > 
> > 1. uninstalled/reinstalling  node.js,
> > 2. uninstalling/reinstalling sfdx
> > 3. uninstalling/reinstalling Salesforce CLI in the following way:
> >    https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm
> >    https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli
> > 
> > My environment:
> > SFDX version:
> > sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4
> > Other info:
> > Salesforce CLI Integration 51.2.0
> > Salesforce Extension Pack 51.2.0
> > ...
> > VSCODE:
> > Version: 1.53.2 (user setup)
> > Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> > Date: 2021-02-11T11:48:04.245Z
> > Electron: 11.2.1
> > Chrome: 87.0.4280.141
> > Node.js: 12.18.3
> > V8: 8.7.220.31-electron.0
> > OS: Windows_NT x64 10.0.19041
> 
> Hi Peter, I tried but not working for me. Please suggest what else be the problem?

@hsomareddy how did you perform 1 and 2? The trouble could be in how these steps are done. Can you share more detail?

**Comment by hsoma11** [comment] 2021-03-01 07:28
> > > Same for me; i'm guessing its related to #2931 ?
> > > I fixed this on my machine after doing all three steps 1,2, and 3. I only Noticed it working after completing 1,2,3 in sequential order:
> > > 
> > > 1. uninstalled/reinstalling  node.js,
> > > 2. uninstalling/reinstalling sfdx
> > > 3. uninstalling/reinstalling Salesforce CLI in the following way:
> > >    https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm
> > >    https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli
> > > 
> > > My environment:
> > > SFDX version:
> > > sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4
> > > Other info:
> > > Salesforce CLI Integration 51.2.0
> > > Salesforce Extension Pack 51.2.0
> > > ...
> > > VSCODE:
> > > Version: 1.53.2 (user setup)
> > > Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> > > Date: 2021-02-11T11:48:04.245Z
> > > Electron: 11.2.1
> > > Chrome: 87.0.4280.141
> > > Node.js: 12.18.3
> > > V8: 8.7.220.31-electron.0
> > > OS: Windows_NT x64 10.0.19041
> > 
> > 
> > Hi Peter, I tried but not working for me. Please suggest what else be the problem?
> 
> @hsomareddy how did you perform 1 and 2? The trouble could be in how these steps are done. Can you share more detail?

Thanks a lot Peter. It worked fine after I followed the sequence.

**Comment by Koslan** [comment] 2021-03-01 09:25
reproduced steps 1,2,3

but didn't help

My environment:
Windows 10 Enterprise   OS Version: 10.0.19042 N/A Build 19042

sfdx-cli --version     6.14.11
sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4

node --version
v14.16.0

VSCODE:
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by smaddox-sf** [comment] 2021-03-01 17:25
This is a duplicate of #2931   Closing this issue so we can consolidate the discussion.

It's noted on the thread of #2931, but I will note it here as well: The root cause is within the CLI. We will keep #2931 open for visibility or feel free to follow the CLI issue directly: forcedotcom/cli#881

**Closed by smaddox-sf** 2021-03-01 17:25 UTC

**Comment by FedPete** [comment] 2021-04-20 09:42
I think the problem lies in GIT preparation.
I had this problem too. Left VCode terminal open for some time and saw a lot of Git time outs.
I didn't have a Git repo for my Trailhead project (didn't know I needed one).
So I did a `git init` and the problem when away in my case.
