### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hsomareddy** [forcedotcom/salesforcedx-vscode#3016] opened 2021-03-04 03:38 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.2.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\HARIKI~1.SOM\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2021-03-04 22:37
In order to diagnose this issue, we need more information.  Next time you hit this issue, please copy the info from the clipboard.  Alternatively, you can also [open a new issue using the 'bug' template](https://github.com/forcedotcom/salesforcedx-vscode/issues/new?assignees=&labels=&template=Bug_report.md) anytime.  Guessing this might be a duplicate of #2410 but there's not enough info to say for sure.

**Closed by smaddox-sf** 2021-03-04 22:37 UTC
