### ISSUE TITLE
Retrieve metadata operation runs "save and deploy"

### ISSUE THREAD

**Issue by anandbn** [forcedotcom/salesforcedx-vscode#887] opened 2019-01-21 01:49 UTC
### Summary

When retrieving metadata for an org and have the `salesforcedx-vscode-core.push-or-deploy-on-save.enabled` set to `true` triggers a deploy once the source is fetched.

### Steps To Reproduce:

1.  Create project with manifest.
2.  Authorize the org
3. Do a "Retrieve from Source in Manifest from Org" on the default `package.xml` file under manifest directory.
4. After the retrieve operation completes, you'll notice the "deploy" operation starts to run before you do anything.

### Expected result

Deploy should not be triggered when the source is fetched.

### Actual result

kicks off `sfdx force:source:deploy` for the recently saved files as part of the retrieve operation.

### Additional information

Below screenshot shows an example where I'm creating a new Lightning component and within 7 secs (i.e. after the component creation is complete) it kicks of the deployment of the same component.

![screenshot](https://gist.githubusercontent.com/anandbn/7830d410ab94d2c19130ac51f8718949/raw/b03c6b2751156f4c2d8a99c0db3394014679cccc/Screen%2520Shot%25202019-01-20%2520at%25208.48.05%2520PM.png)

**VS Code Version**:

1.30.2

**SFDX CLI Version**:

sfdx-cli/6.49.0-8edc6e0f5d (darwin-x64) node-v8.9.4

**OS and version**:

MacOS High Sierra - 10.13.6 (17G4015)

**Comment by praksb** [comment] 2019-01-21 23:08
Duplicate of #883

**Comment by praksb** [comment] 2019-01-21 23:13
Thanks @anandbn for giving this feedback. We are working on some enhancements to this feature to make it better and will look into this as well.

**Closed by praksb** 2019-01-21 23:13 UTC
Labels: feedback
