### ISSUE TITLE
Deploy on VS Version

### ISSUE THREAD

**Issue by mrainboldt** [forcedotcom/salesforcedx-vscode#2534] opened 2020-09-16 15:45 UTC
Issue Type: <b>Bug</b>

sfdx force:source:deploy -m LightningWebComponentBundle:helloWorld
ERROR running force:source:deploy:  core_1.SfdxProject.resolveProjectPathSync is not a function
PS 

Extension version: 49.9.0
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (11.53GB free)|
|Process Argv|--crash-reporter-id 4f065e83-8727-499c-95d9-660b35e7b201|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lcampos** [comment] 2020-09-16 16:06
This is a duplicate of #2533

**Closed by lcampos** 2020-09-16 16:06 UTC
