### ISSUE TITLE
Deploy on Save

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/salesforcedx-vscode#577] opened 2018-08-20 23:38 UTC
**Is your feature request related to a problem? Please describe.**
I'm running the new [change_set_based_tools](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Develop-Against-Any-Org-in-Visual-Studio-Code) and a compile on save is desperately needed.  

**Describe the solution you'd like**
Setting you can add to cause it to run `deploy this source file to org` command on save

**Describe alternatives you've considered**
Could probably use a "Run on save extension" but it would be much nicer to have it supported out of the box

**Internal Work Item**: [W-5552627](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000005wp9BIAQ/view)

**Comment by renatoliveira** [comment] 2018-08-21 14:34
If this ever gets implemented I think it would be a great addition to have the option to **deploy only files that were modified since the last successful push**.

For example: I get three files, and worked on two of them. Instead of deploying all three, or deploying each individual file, the extension can check which files were modified since the last successful deployment (this is important, because if a deployment fails due to a compile error, it would still need to be marked as "changes that we can try to deploy next time").

And of course, this would be great if it were optional as well. Three modes to work with:

1. Deploy everything everytime;
2. Deploy just the single file the user specifies (current);
3. Deploy just the modified files in the project folder.

I don't think there are extensions for this kind of workflow (yet).

**Comment by toadgeek** [comment] 2018-08-21 16:27
That would be a great improvement!

**Comment by ChuckJonas** [comment] 2018-08-21 19:46
@renatoliveira that would be great; I imagine it would require some type of data structure to track everything.   I opened #578 as a different solution to a similar problem.

**Comment by ntotten** [comment] 2018-10-25 18:37
@omniphx You're also welcome to send a PR to add it to the official package if you want. We are aiming to do it pretty soon though if not.

**Comment by smrobert09** [comment] 2018-10-31 16:27
@renatoliveira @omniphx @ntotten We have an extension that adds the file system tracking. It creates a hash table of the folder structure, detects changes, and allows a 'deploy all changes' type command. 

SFDX creates the hash file automatically on 'force:source:retrieve --manifest' (the sourcePathInfos.json file under .sfdx/orgs/<orgUsername>/sourcePathInfos.json). The problem is that it deletes as soon as the command finishes, making us rebuild it or try to capture/copy it. I know sandboxes aren't source tracking orgs, meaning that we override changes on every push, but if that file were left in place, this would be an easy win. Is this something we can request from the CLI team @ntotten ?

**Comment by NikitaChizhik** [comment] 2018-12-19 12:34
**Please** , could you do deploy on save. (I should press ctrl+save then with mouse choose file from left sidebar and right click and choose to deploy source to org. and repeat it every time I want to deploy) - that's a nightmare.)

Note: I am dealing with not scratch org. I develop against any org(simple). Thats my case for now.
VSCode version is latest and salesforcePack version is latest.

Now I made a shortcut(ctrl+d) to deploy current open file . BUT it also doesnt work. it writes to me Cannot read property 'fsPath' of undefined.

Please look at these two bugs**(which prevent me and many others not to use vsCode and this SF plugin)**.

**Thanks for your project and work.**

**Closed** 2019-01-10 15:16 UTC
Labels: feature

**Comment by ntotten** [comment] 2019-02-28 16:04
This feature has been implemented as of Dec. 19th.

You can find instructions here: https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/org-development-model#deploy-source

> To deploy files each time you save them, set the user or workspace setting `salesforcedx-vscode-core.push-or-deploy-on-save.enabled` to true.
