### ISSUE TITLE
Cannot deploy Custom Fields by package.xml or by Command Line.

### ISSUE THREAD

**Issue by rahulkapoor83** [forcedotcom/salesforcedx-vscode#2555] opened 2020-09-20 17:42 UTC
### Summary

While Deploying Custom Fields using Command or by package.xml - it shows 
=== Deployed Source
No results found

### Steps To Reproduce:

1. Retrierved a field by below command and it is successful:

![image](https://user-images.githubusercontent.com/71480553/93735189-baf0e780-fbf9-11ea-9f0e-3cef4fd10bff.png)

2. Deploying same field shows = "No results found.

![image](https://user-images.githubusercontent.com/71480553/93719888-278cc780-fba3-11ea-8c55-d1ec983a3cbf.png)

3. Try to do same operation using package.xml. First try to retrieve using package.xml

![image](https://user-images.githubusercontent.com/71480553/93718043-1a69db80-fb97-11ea-886c-da72ff55c902.png)

![image](https://user-images.githubusercontent.com/71480553/93719908-45f2c300-fba3-11ea-8b55-b233fe297b94.png)

That Works !!

4. Now lets try to deploy same field using same package.xml

![image](https://user-images.githubusercontent.com/71480553/93719921-5c008380-fba3-11ea-8f21-888f879d32d5.png)

**Its not working.** 

### Expected result

Custom Fields should get deployed by package.xml or by SFDX command.

### Actual result

Custom Fields are not getting deployed by package.xml or by SFDX command.

### Additional information

Version: 1.49.1 (user setup)
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
![image](https://user-images.githubusercontent.com/71480553/93720282-a682ff80-fba5-11ea-959e-5991acaa975f.png)

**Comment by Sms112477** [comment] 2020-09-21 05:49
Hi @rahulkapoor83 ,all,

I am facing the exact issues with latest CLI upgrade, unable to deploy the specific fields to a target org.

Thanks,
Malthesh

**Comment by smaddox-sf** [comment] 2020-09-21 17:52
This is a duplicate of https://github.com/forcedotcom/cli/issues/628 and https://github.com/forcedotcom/cli/issues/625.  Please follow one of the CLI issues for updates and feel free to add other feedback to those issues as well.

**Closed by smaddox-sf** 2020-09-21 17:52 UTC
