### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by himanshu-IN** [forcedotcom/salesforcedx-vscode#2511] opened 2020-09-11 04:51 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\HI376315\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-09-14 17:31
Not a lot of detail here, but I think this is a duplicate of #2410

**Closed by smaddox-sf** 2020-09-14 17:31 UTC
