### ISSUE TITLE
Run Test not reporting all executed classes

### ISSUE THREAD

**Issue by Rich0635** [forcedotcom/salesforcedx-vscode#2880] opened 2021-01-21 15:25 UTC
### Summary

Running a test class method (Run Test) or whole test class (Run All Tests) produces output with a single arbitrary executed class (Class Being Tested), instead of all executed classes. Highlight Apex Code Coverage on executed class shows no coverage.

### Steps To Reproduce:

1.  Create a test class with test method, that executes more than one class or trigger. E.g. one class executes another class method.
2. VSCode settings, Salesforce Features: "salesforcedx-vscode-core.retrieve-test-code-coverage": true
3. VSCode should show a "Run Test" line after @isTest, at the top of the test method. Click "Run Test" to run the test.

### Expected result

All of the executed classes appear in the Output result window. Opening any of the classes and click the highlight coverage icon. It shows green/red line coverage in the editor.

### Actual result

Only one of the executed classes appears in the Output result window (Class Being Tested column) - apparently a random choice. Opening one of the other classes (which is executed but not output) and click the highlight coverage icon. "No code coverage information was found for this file." message appears.

### Additional information
"Run All Tests" in test class has similar results. It will only show one executed class (Class Being Tested) per test method.
Opening developer console shows all tests and executed classes with coverage as expected.

Below test run is meant to test class CaseAnonymizeBatch...
![Screenshot 2021-01-21 at 11 51 44](https://user-images.githubusercontent.com/60474144/105371722-cd594d00-5bfc-11eb-8563-de1cf4abc8a5.png)
Run same test again - different class reported...
![Screenshot 2021-01-21 at 12 11 10](https://user-images.githubusercontent.com/60474144/105371961-0c879e00-5bfd-11eb-804f-f4aa1ab9dbdb.png)

**VS Code Version**: 1.52.1
**SFDX CLI Version**: sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3
**Salesforce Extension Pack**: 50.13.0

**OS and version**: Mac OSX v11.1

**Comment by AnanyaJha** [comment] 2021-01-21 16:51
Hi @Rich0635 thanks for reporting this! This is a known issue and we are currently working on a fix for it, we'll update you when it is released. As a workaround, since this feature is still in Beta, you can go back to the old behavior by going into your Preferences and turning off the `Salesforcedx-vscode-core › Experimental: Use Apex Library` setting.

**Comment by AnanyaJha** [comment] 2021-01-21 18:03
Duplicate of #2872

**Closed** 2021-01-21 18:05 UTC
Labels: type:bug

**Comment by BrotherZach** [comment] 2021-01-21 19:32
> Hi @Rich0635 thanks for reporting this! This is a known issue and we are currently working on a fix for it, we'll update you when it is released. As a workaround, since this feature is still in Beta, you can go back to the old behavior by going into your Preferences and turning off the `Salesforcedx-vscode-core › Experimental: Use Apex Library` setting.

I am also having this issue. Would turning that off fix the issue of not showing all covered classes or would that just fix the issue with highlighting code coverage?

**Comment by balanandam** [comment] 2021-10-07 00:23
Hello Team,

Is above issue resolved, if yes could you pls provide the solution as we are also facing similar issue.

Here is my issue details:
![sfdx-apex-test-run-coverage-issue](https://user-images.githubusercontent.com/29630122/136300422-e8ea1c82-624b-43fc-84f0-caba73e25ac9.jpg)

Current sfdx version: sfdx-cli/7.120.0 win32-x64 node-v14.18.0

As per image shows above, getting wrong output in the test summary results(100%) as actually, the main required class is having only 72%. I am not sure why test results summary shows wrongly and also several other test classes are considered and showing in the detailed report while running command 
sfdx force:apex:test:run --testlevel RunSpecifiedTests --tests "XXXXXXImageTriggerHandlerTest" --outputdir testReport --codecoverage -r human -y -w 20

How can we get absolute test class result only for the required test class which is passed in the command. Could anyone pls share your inputs to move forward on this issue.
Finally we want to integrate this test results report to the sonarqube code analysis tool for the code coverage through SonarQube.
`sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.apex.coverage.reportPath=**/testReport/test-result-codecoverage.json`


Pls let us know your inputs and Thanks for your time and appreciate your support.
-----
Bala.
