### ISSUE TITLE
Apex Language Server crashes as soon as starting VSCode

### ISSUE THREAD

**Issue by jgrimaldos** [forcedotcom/salesforcedx-vscode#1581] opened 2019-08-22 15:49 UTC
### Summary

Apex Language Server crashes as soon as VSCode starts, so no code completion or testing is available

### Steps To Reproduce:

1.  Open VSCode.
2.  Call SObject Refresh.
3. Apex Language Server is now unusable.
4. Restart VSCode.
5. Same thing happens all over again.

### Additional information
Error Message:

0:08:36.643 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
10:08:36.649 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
10:08:37.289 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
10:08:37.291 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 3202 ms.
ago. 22, 2019 10:14:31 A. M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space

**VS Code Version**:
1.37

**SFDX CLI Version**:
sfdx-cli/7.20.1-d88ae4707c darwin-x64 node-v10.15.3

**OS and version**:
macOs Mojave 10.14.6 (18G87)

**Comment by BrianEA** [comment] 2019-09-25 20:45
I can report this problem as well - I hadn't seen it until today,  Occurred after I'd manually ran SObject refresh for the first time in a project folder (that I'd been working successfully with for months)

**Comment by jgrimaldos** [comment] 2019-09-30 16:21
I'm really worried about the lack of followup from the product team, this is a really serious issue as the development enviroment for big orgs is fragmented due to the lack of lwc support in Development Console and the poor Apex support in Visual Studio Code

**Comment by lcampos** [comment] 2019-09-30 17:33
We believe one of the causes for this issue is the number of SObject Definitions being synced. In last week's release we modified `SFDX: Refresh SObject Definitions` to allow the user to sync SObjects by category; All, Custom Object or Standard Objects. Can you confirm if you still run into that issue when using the new options ?

We are also aware of the need for both Custom and Standard SObjects in projects and we're currently working on a 4th option that will exclusively sync the sobjects defined in your local project.

If non of these options work let me know and we can take a deeper look at other areas which could improve the experience.

**Comment by lcampos** [comment] 2019-10-03 01:11
@AntunBartonicek thanks for confirming. We've been thinking of only retrieving `__ChangeEvent`, `__History`, etc if the user explicitly asks for them but we haven't thought about also having a category for objects coming from a package.

In your scenario, are you exclusively working with a limited set of standard and custom objects and the rest of the sobjects are coming from packages your codes does not interact directly with ? I'm wondering if the other option I mentioned before, exclusively syncing sobjects defined in the local project, would help be enough for your usecase.

**Comment by AntunBartonicek** [comment] 2019-10-03 09:02
Retrieving changeEvent and History objects on demand would make sense at least to me, no need to introduce another category.
Not sure if I understand the "exclusively syncing sobjects defined in the local project" way of working.
I might be a hoarder but ideally I would like to have everything locally as all changes (done by any team member) would be tracked in GIT.
I'm open to any suggestions, though :)

**Comment by jitenderpadda** [comment] 2019-11-03 23:05
I faced the same issue and the reason I believe it was happening was because I was using 32-bit Java which has a lower heap size. I installed 64-bit Java and pointed the Apex language server to use the 64-bit version in the vs code settings and that seems to have done the trick.

**Comment by arneper** [comment] 2019-11-03 23:37
May I ask which version of Java you are using?

**Comment by jitenderpadda** [comment] 2019-11-03 23:42
Java version - 1.8.0_231

![image](https://user-images.githubusercontent.com/10905262/68093989-d07cf600-feef-11e9-82fc-86f6c708417e.png)

**Comment by arneper** [comment] 2019-11-04 00:15
Thanks.

**Comment by AntunBartonicek** [comment] 2019-11-04 08:48
> 
> 
> I faced the same issue and the reason I believe it was happening was because I was using 32-bit Java which has a lower heap size. I installed 64-bit Java and pointed the Apex language server to use the 64-bit version in the vs code settings and that seems to have done the trick.

I already used 64-bit Java and still had issues:
![image](https://user-images.githubusercontent.com/19833052/68108497-39f90680-fee8-11e9-8aec-bd7d9bec82ee.png)

**Comment by diyer** [comment] 2024-08-23 20:36
Does not reproduce anymore. Closing this

**Closed by diyer** 2024-08-23 20:36 UTC
Labels: type:feedback, area:performance
