### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by karanp009** [forcedotcom/salesforcedx-vscode#5124] opened 2023-09-27 08:34 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by CristiCanizales** [comment] 2023-09-27 14:14
Hi again @karanp009, I am closing this issue as a duplicate of https://github.com/isomorphic-git/isomorphic-git/issues/1821. Please try the solution provided there. Thanks.

**Closed by CristiCanizales** 2023-09-27 14:14 UTC
Labels: more information required
