### ISSUE TITLE
LWC retrieve not working

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1071] opened 2019-02-18 06:33 UTC
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1. retrieve
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.
retrieve lwc 
### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/93057/52932260-c5a81400-3314-11e9-9986-6fc3680c5667.png)

**VS Code Version**:
1.31
**SFDX CLI Version**:
45
**OS and version**:
windows

**Comment by chandra2ravi** [comment] 2019-03-22 22:56
@ntotten 
Any update on this. Deployment pending I'm unable to get the component. I tried both windows and mac

**Comment by ntotten** [comment] 2019-03-22 22:59
Duplicate of #1072

**Closed by ntotten** 2019-03-22 22:59 UTC
Labels: bug
