### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by avinashchourasiya** [forcedotcom/salesforcedx-vscode#3413] opened 2021-07-13 11:27 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `52.4.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.58.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Avinash\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2021-07-14 00:40
Duplicate of #2410.  Please add the CPU profile doc to that issue if you are able.

**Closed by smaddox-sf** 2021-07-14 00:40 UTC
