### ISSUE TITLE
Go To Definition doesn't working on methods

### ISSUE THREAD

**Issue by urbanex** [forcedotcom/salesforcedx-vscode#596] opened 2018-08-24 11:54 UTC
Issue Type: <b>Bug</b>

Autocompletion and Go To Definition (by ctrl+click or F12) features work properly only with Classes objects, but whenever I try to use Go To Definition on a method, a popup message appears 'No definition found for 'methodName''. Also when I type a Class name then dot then Ctrl+Space Autocompletition doesn't suggest any method (although they exist inside that class!). :( Please help me, because it's a horror to work without these features. Ofc I installed fresh VSC instance, and fresh Extensions and a problem still occurs.

Extension version: 43.13.0
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.88GB (13.33GB free)|
|Process Argv|C:\Users\jurbanowsk001\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

!

[image](https://user-images.githubusercontent.com/31351412/44583326-16dfac80-a7a5-11e8-8be3-f3c96ef798a4.png)

**Comment by ntotten** [comment] 2018-08-24 20:44
Duplicate of #320

**Closed by ntotten** 2018-08-24 20:44 UTC
Labels: duplicate
