### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by markkindred** [forcedotcom/salesforcedx-vscode#3028] opened 2021-03-06 03:39 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.2.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/rr/vqzygnkj0_795cplg_tmcl700000gp/T/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2021-03-08 16:16
Duplicate of #2410

**Closed by smaddox-sf** 2021-03-08 16:16 UTC
