### ISSUE TITLE
Null pointer exceptions from Apex Language Service

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/salesforcedx-vscode#587] opened 2018-08-21 15:01 UTC
### Summary

Started up VS Code with the pre-release version of the Salesforce CLI to try out the new manifest deployment commands.

### Steps To Reproduce:

1.  Checked out my source from version control
1.  Created a manifest sfdx project
1. Converted the source code to SalesforceDX source format
1. Opened VS Code

### Expected result

Apex Language Service starts okay and features such as Go to definition work.

### Actual result
Many null pointer exceptions and features not working. Here's one example:

13:00:25.613 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 2875 ms.
13:00:26.164 [ApexIndexer STARTING] ERROR a.jorje.lsp.impl.index.ApexIndexer - exception thrown in traversing codeunit for references
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.getMethod(MethodCallExpression.java:504)
	at apex.jorje.lsp.impl.index.ApexIndexer$1.visitEnd(ApexIndexer.java:473)
	at apex.jorje.lsp.impl.index.ApexIndexer$1.visitEnd(ApexIndexer.java:268)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.traverse(MethodCallExpression.java:157)
	at apex.jorje.semantic.ast.statement.VariableDeclaration.traverse(VariableDeclaration.java:82)
	at apex.jorje.semantic.ast.statement.VariableDeclarationStatements.traverse(VariableDeclarationStatements.java:88)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:141)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:76)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:128)
	at apex.jorje.lsp.impl.index.ApexIndexer.insertCodeUnit(ApexIndexer.java:268)
	at apex.jorje.lsp.impl.index.ApexIndexer.buildCacheInternal(ApexIndexer.java:196)
	at apex.jorje.lsp.impl.index.ApexIndexer.buildCache(ApexIndexer.java:207)
	at apex.jorje.lsp.impl.index.ApexIndexer.lambda$startUp$2(ApexIndexer.java:941)
	at java.util.Optional.ifPresent(Optional.java:159)
	at apex.jorje.lsp.impl.index.ApexIndexer.startUp(ApexIndexer.java:939)
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$2.run(AbstractScheduledService.java:217)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Additional information

**VS Code Version**:
VS Code 1.26.1
Salesforce Extensions for VS Code 43.12.0

**SFDX CLI Version**:
salesforcedx 44.0.8 (pre-release)

**OS and version**:
MacOS 10.13.6

**Comment by vazexqi** [comment] 2018-08-21 15:04
@keirbowden (Similar to #581) - Are you able to open up a support case – once you do that reference this bug and tell them to assign it to Nick Chen (Platform Dev Tools)? If we can take a look at the code it would help. This seems very specific to what you have in your code base.

If you can't do that then we need to put more logging in or we need to have some other way to get access to the code (if that is possible).

**Comment by keirbowden** [comment] 2018-08-21 15:17
@vazexqi sure thing - I've just deployed everything to a dev org to try out the new manifest feature so I'll raise a case and point at that org.

**Comment by keirbowden** [comment] 2018-08-21 15:28
@vazexqi case raised - 19879233 - login access granted too.

**Comment by keirbowden** [comment] 2018-08-22 15:18
@vazexqi for some reason developer support have taken ownership of the case and want to call me and do a screen share so that I can show them the exception.  I've asked them (again) to assign it to you.

**Comment by amitkumarj1979** [comment] 2018-08-22 18:35
I am also getting the same issue. Some more info is:
Aug 22, 2018 11:34:41 AM apex.jorje.semantic.compiler.CodeUnit traverse
INFO: unexpected error during apex ParentVisitor:

Sometime also getting java.util.ConcurrentModificationException

**Comment by vazexqi** [comment] 2018-08-24 22:32
@keirbowden - Thanks for opening the case. I have been able to reproduce the issue and have a fix. would you mind trying to install the .vsix from https://1676-95021029-gh.circle-artifacts.com/0/home/circleci/project/extensions/salesforcedx-vscode-apex-43.13.0.vsix?

You can follow the instructions at https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by vazexqi** [comment] 2018-08-24 22:40
@amitkumarj1979  - I am not able to reproduce a `java.util.ConcurrentModificationException`

**Comment by keirbowden** [comment] 2018-08-26 14:30
@vazexqi I've installed from the .vslx and everything is working as expected with no null pointer exceptions!

**Comment by vazexqi** [comment] 2018-08-27 17:47
Closed by #598. This will go out this Thursday in v43.14.0

**Closed by vazexqi** 2018-08-27 17:47 UTC
Labels: bug
