### ISSUE TITLE
Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.

### ISSUE THREAD

**Issue by prakash-ac** [forcedotcom/salesforcedx-vscode#5106] opened 2023-09-19 17:41 UTC
Type: <b>Bug</b>

Open VSCode and try ctrl+shift+p and select SFDX: Create Project with Menifest. 
Expected result:  Allows entering new project name to create an sfdx project.
Actual result: It will show "Extension host terminated unexpectedly 3 times within the last 5 minutes." message.

Extension version: 58.14.2
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.14GB free)|
|Process Argv|--crash-reporter-id 07d28bc3-5cf4-47b3-b937-a99d01f5966b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
vscrp:30673768
showlangstatbar:30737416
0bi6i642:30835152
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015cf:30829746

```

</details>

**Comment by prakash-ac** [comment] 2023-09-19 17:43
I uninstalled the Salesforce Extension pack, and VSCode. Then re-installed VSCode and the extension. I get the same issue.

**Comment by daphne-sfdc** [comment] 2023-09-19 19:54
Can you run "Developer: Show Running Extensions" from the command palette and send me a screenshot?

**Comment by prakash-ac** [comment] 2023-09-19 20:08
Hi thank you for quick response. 

I uninstalled the VSCode and installed VSCode - Insiders version. It seems to be working fine. I ran the command you asked me to run in the Insiders version and got results as seen in the screenshot. I assume it would show the same results in the previous version as well, since I had installed the same Salesforce Extension Pack.
  
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/4730b3d3-8534-4436-aa34-59b041492eb9)

**Comment by daphne-sfdc** [comment] 2023-09-19 20:33
Actually, I wanted to make sure your extensions are activated before you used them, since it takes much longer to activate on Windows than Mac and also your error message said 'No extensions were activated'.  It seems like that isn't the problem here, although 89902 ms is very slow!

Are you getting this problem in both the Insiders version and the regular version of VSCode?  If not, let's stick to debugging whichever version contains the problem and not jump around.

Try deleting the .sfdx and .sf folders from the Explorer view and running "Developer: Reload Window".  Then run "SFDX: Create Project with Manifest" again.

**Comment by prakash-ac** [comment] 2023-09-19 21:10
I deleted the .sfdx and .sf folders in the VSCode (regular version). I reloaded the window, and ran the create project with menifest command. I get similar error. I ran the show extensions command, and got this result (different than my assumption before, sorry about that) - 

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/1b2c62dc-2697-4cdb-9e29-bb70258d60a2)

**Comment by CristiCanizales** [comment] 2023-09-19 21:51
Hi @prakash-ac, in this last screenshot we can see that the extensions are not running yet. You need to wait for them to be running before trying any of the commands! Specially Salesforce CLI Integration

**Comment by prakash-ac** [comment] 2023-09-19 22:04
Hi @CristiCanizales after the error occurs, VSCode does not seem to be trying to activate the extensions. Nothing happens when I run the "Developer: Show Running Extensions" command after the error occurs.

**Comment by daphne-sfdc** [comment] 2023-09-19 23:53
Hi @prakash-ac,
The slow activation of extensions on Windows is a known issue.  Please follow it here: #4919 

After you finished waiting for the extensions to activate, were you able to run "SFDX: Create Project with Manifest"?  You can tell that the extensions finished activating if you see "Startup Activation: ___ ms" after each one in the list of running extensions.

**Comment by prakash-ac** [comment] 2023-09-20 00:16
It is rediculously slow like folks in other threads mentioned. But my issue is not slow activation. It never finishes activating the extensions. It crashes before finishing the activation. After it crashes, it shows the error message as mentioned in the title of this issue. When I run the command "Developer: Show Running Extensions" after it crashes, I get no response - 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/fb71facc-5863-46e5-8b96-ad2e5ed7e746)

And when I run the "SFDX: Create Project Menifest" command, I get error like this - 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/bdab7a8b-3168-4d47-8955-cd35729d93a3)

**Comment by CristiCanizales** [comment] 2023-09-20 19:21
hi @prakash-ac, could you please send us the logs in the Extension Host output tab?

**Comment by daphne-sfdc** [comment] 2023-09-20 20:39
Hi @prakash-ac,
We're also wondering if it's possible that one of the non-Salesforce extensions you currently have installed might be conflicting with the Salesforce CLI Integration extension.  Can you disable all non-Salesforce extensions that you currently have installed, run "Developer: Reload Window", and then try "SFDX: Create Project with Manifest" again?

**Comment by prakash-ac** [comment] 2023-09-20 21:13
@CristiCanizales where is the Extension Host output tab? If it's the Terminal output tab, I do not see any log there. 

@daphne-sfdc I followed the steps you recommended. It did not help.

**Comment by daphne-sfdc** [comment] 2023-09-21 00:54
To answer your question to Cristi: In the bottom panel, select Output.  On the right side of the panel, there is a dropdown.  Select 'Extension Host' from the dropdown.
<img width="1348" alt="Screenshot 2023-09-20 at 8 52 37 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/139700604/9ff92e66-e855-4304-bff7-58ceba477456">

**Comment by daphne-sfdc** [comment] 2023-09-21 00:55
Since we're now looking at logs, can you also run "Developer: Toggle Developer Tools" and send us the contents of your Console?

**Comment by prakash-ac** [comment] 2023-09-21 14:44
Extension host output 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/81cc9d58-9373-4811-89a0-4a59135d0bc4)

Contents of console after running "Developer: Toggle Developer Tools"
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/78f8f045-e00b-41dd-9556-b5294a1e599b)

**Comment by daphne-sfdc** [comment] 2023-09-23 04:00
In your Extension Host log, I see an error message "root cause: salesforce.salesforcedx-vscode-apex-debugger".  That is the Apex Interactive Debugger extension.  Can you try disabling that extension?

**Comment by prakash-ac** [comment] 2023-09-25 19:14
Hi, I tried disabling the extensions "Apex Interactive Debugger" and "Apex Replay Debugger" and kept getting the error. Then I unistalled the both extensions. Now it seems to be working fine, although I also get that "root cause" message for lwc.

![lwc-error](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/32c15c48-c609-4ed3-b28c-79a92c2af9d9)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/52327969/536bbabc-33d9-428b-8aa5-8817e1789a94)

**Comment by daphne-sfdc** [comment] 2023-09-26 16:43
Hi @prakash-ac,
Glad to hear that you're now able to proceed with this workaround! 😀

Since the conflict is with a Salesforce extension, we have something for you to try if you are interested in digging further into this issue.  
1. Kill VSCode
2. Go to "%USER%\\.vscode\extensions" (or) "%USERPROFILE%\.vscode\extensions" in your File Explorer.  (That is the folder where all the VSCode extensions are stored.) 
3. Delete all Salesforce extensions from that folder.  
4. Reopen VSCode and reinstall the Salesforce extensions to see if the error still occurs.

**Comment by prakash-ac** [comment] 2023-09-27 21:28
I followed the steps you mentioned above. It is working perfectly fine now. 

I really appreciate your help with this issue.

**Comment by daphne-sfdc** [comment] 2023-09-27 21:40
Thank you @prakash-ac for your feedback.  We're happy this is now working for you. 🙂

Closing this issue as completed.

**Closed by daphne-sfdc** 2023-09-27 21:40 UTC
Labels: more information required
