### ISSUE TITLE
Unable to change default org

### ISSUE THREAD

**Issue by chrissagario** [forcedotcom/salesforcedx-vscode#5402] opened 2024-02-06 10:11 UTC
### Summary

When I click on the change default org on the status bar I'm unable to see the connected orgs with my project

****
### Expected result

Connected orgs on the org list should be visible to set as a default org.

### Actual result

No org is visible.

### Additional information

<img width="689" alt="Screenshot 2024-02-06 at 6 03 16 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/51990141/722f2d5a-9b2a-4e83-9fa6-71354578be33">

<img width="787" alt="Screenshot 2024-02-06 at 6 04 27 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/51990141/644ec02d-0e7a-4b37-b401-eb3bec0cf57a">

**Salesforce Extension Version in VS Code**: v59.16.0

**SFDX CLI Version**:  @salesforce/cli 2.26.10 (core)

**OS and version**:  macOS Ventura 13.6.3

**VS Code version**: 1.79.2

**Comment by CristiCanizales** [comment] 2024-02-06 13:49
Hi @chrissagario! Can you update your VS Code version, delete your .sf/.sfdx folders, reload VS Code, reauth your orgs and try again? I'll be closing this as a duplicate of #5386 so please keep us posted there if issue persists.

**Closed by CristiCanizales** 2024-02-06 13:49 UTC
