### ISSUE TITLE
Extension causes high cpu load. Not Loaded and block other extension to load. 

### ISSUE THREAD

**Issue by ROYHeroku** [forcedotcom/salesforcedx-vscode#2550] opened 2020-09-18 23:54 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.10.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.49.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\370837\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by akkibaddi** [comment] 2020-09-20 14:50
facing the same here for CLI extension as well

**Comment by rogers-sfdc** [comment] 2020-09-21 17:07
on Mac as well

**Comment by smaddox-sf** [comment] 2020-09-21 17:46
There's not much detail on this, but I believe it's a duplicate of #2410.  Please review that issue and add any other feedback. I also posted a work around on that issue - would love to know if it helps.

**Closed by smaddox-sf** 2020-09-21 17:46 UTC
