### ISSUE TITLE
SFDX: Retrieve Source in manifest from Org gives "Unknown Exception"

### ISSUE THREAD

**Issue by rajesh-kemisetti** [forcedotcom/salesforcedx-vscode#3162] opened 2021-04-21 14:09 UTC
### Summary

Retrieve Source in Manifest from Org gives an Unknown Exception in VS Code. Issue is noticed on sfdx-cli/7.96.0 and sfdx-cli/7.97.0.

Below is the package I have used and I have noticed this error with just any supported metadata type

![image](https://user-images.githubusercontent.com/18335231/115569416-33508180-a28b-11eb-951f-099eb64aea55.png)

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Connect the VS Code to any sandbox
2. Right click on the manifest/package.xml that has the above sample content and select SFDX: Retrieve Source in manifest from Org
3. The command fails with an error "Unknown Exception"

### Expected result

Code should be successfully retrieved from the Org.

### Actual result

Unknown Exception

![image](https://user-images.githubusercontent.com/18335231/115567214-0307e380-a289-11eb-9c2f-2e8ecbd9d255.png)

### Workaround

Run the below command in Terminal tab in VS Code as below to retrieve the source from org.

sfdx force:source:retrieve -u username --manifest manifest/package.xml

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.97.0 win32-x64 node-v15.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): salesforcedx 50.12.0 (50.12.0)

**OS and version**: Windows 10

**Comment by leonardopmacedo** [comment] 2021-04-22 14:16
I have the same problem!
With a brand new sandbox org. =/

**Comment by VenkatPattapu** [comment] 2021-04-23 08:25
I do have same problem even after Updating to latest

**Comment by cfarmer99** [comment] 2021-04-23 15:44
Same problem, started yesterday. I am able to retrieve and deploy individual files but I can't use the package file.

**Comment by smaddox-sf** [comment] 2021-04-23 22:12
Thanks for reaching out on this.  This is a duplicate of #3137 and we're working on a fix.  Closing this issue and we will update #3137 as we have a resolution.  In the meantime, you an try this workaround: disable the setting "Experimental: Deploy Retrieve"
https://developer.salesforce.com/tools/vscode/en/user-guide/perf-enhancements/#setup

CC @brpowell

**Closed by smaddox-sf** 2021-04-23 22:12 UTC
