### ISSUE TITLE
Unable to deploy scheduled Apex classes with new Performance Enhancements for single class deploys

### ISSUE THREAD

**Issue by klouf-mp** [forcedotcom/salesforcedx-vscode#2076] opened 2020-03-16 15:58 UTC
### Summary

When enabling the new experimental preference "salesforcedx-vscode-core.experimental.deployRetrieve" and deploying a class that is used by another class that is currently scheduled, the class fails to deploy and returns error message "This schedulable class has jobs pending or in progress" despite the setting in the org for "Allow deployments of components when corresponding Apex jobs are pending or in progress." being enabled.

### Steps To Reproduce:

1.  In Salesforce, enable setting "Allow deployments of components when corresponding Apex jobs are pending or in progress." under Deployment Settings (Classic)
2.  In VSCode, enable preference "salesforcedx-vscode-core.experimental.deployRetrieve"
3. Deploy a single class that is used by another class that is currently scheduled with Scheduled Apex

### Expected result

Class should deploy without error

### Actual result

Class fails to deploy with error "This schedulable class has jobs pending or in progress"

**VS Code Version**: 1.43.0

**Salesforce Extensions Version**: 48.6.0

**SFDX CLI Version**: sfdx-cli/7.50.0-9030e49cbb darwin-x64 node-v10.15.3

**OS and version**: macOS Catalina 10.15.3

**Comment by lcampos** [comment] 2020-04-25 00:53
Hi @klouf-mp thanks for logging this issue. I was able to replicate it and I think the root cause might be that the `"Allow deployments of components when corresponding Apex jobs are pending or in progress."` feature is incorrectly reporting an issue when doing a save via Tooling API (which is what we're using).

I say this because when I go to the org I do see the change to my class being in the org. Btw, if you try this same steps in the Dev Console you'll also see the same behavior since Dev Console also uses Tooling API.

I'll check with the api team to see if this is a known issue. cc @smaddox-sf

**Comment by lcampos** [comment] 2020-04-25 01:03
@klouf-mp I found the release notes (https://docs.releasenotes.salesforce.com/en-us/winter15/release-notes/rn_deploy_with_jobs.htm) and the currect help docs (https://help.salesforce.com/articleView?id=changesets_inbound_deploy.htm&type=5 `Deployment Options` section) this feature is only supported in Metadata API. I'll go ahead and close this since the API is working as designed.

**Closed by lcampos** 2020-04-25 01:03 UTC
Labels: area:deploy/retrieve, type:bug

**Comment by klouf-mp** [comment] 2020-04-28 18:37
@lcampos Ah, bummer but that makes sense -- I have definitely run into that in the Dev Console before. Thanks for checking!

I realize this isn't exactly the best place to ask (and it might even be a bit of a silly question since the current situation has been the same for years now), but since we're on the topic -- are there any plans to support this setting with the Tooling API? Or perhaps that is (one reason) why the Tooling API is inherently quicker so it would defeat some of the purpose?

**Comment by lcampos** [comment] 2020-06-05 16:44
@klouf-mp sorry for the late reply. I'm not aware of this being in the roadmap of the api team or apex team. I'd say opening an Idea in the IdeaExchange would be the best way to go.

However, something that is in our roadmap is to keep working in the deploy/retrieve enhancements. The next version of changes will allow for deploying using the Metadata API which would cover this scenario. Our testing so far has been positive and the performance of the new code is similar to what you can currently get with the changes under the `salesforcedx-vscode-core.experimental.deployRetrieve` setting which currently only use Tooling API.
