### ISSUE TITLE
Test pane ignores code coverage param setting

### ISSUE THREAD

**Issue by JamieBriersSageCom** [forcedotcom/salesforcedx-vscode#891] opened 2019-01-23 11:07 UTC
### Summary

When using the tests pane to run unit tests, the tests are run without the --codecoverage parameter, despite the option being set in 'settings'.  Running the same tests through the command pallet or through 'Run Test' in CodeLens works correctly.

SFDX command in 'output' when test class ran from 'Test' pane:

`sfdx force:apex:test:run --tests MyClass_Test --resultformat human --outputdir c:\Git\myRepo\.sfdx\tools\testresults\apex --loglevel error`

Same class executed through CodeLens

`sfdx force:apex:test:run --tests MyClass_Test --resultformat human --outputdir c:\Git\myRepo\.sfdx\tools\testresults\apex --loglevel error --codecoverage`

**VS Code Version**:
1.30.2

**SFDX CLI Version**:
sfdx-cli/6.49.0-8edc6e0f5d (windows-x64) node-v8.9.4

**Comment by lcampos** [comment] 2019-01-23 17:30
Thanks for reporting this @JamieBriersSageCom. I'm closing this since it's a duplicate of #677 but I'd like to point out that this work is on our queue and will update the open issue once the fix is released.

**Closed by lcampos** 2019-01-23 17:30 UTC

**Comment by JamieBriersSageCom** [comment] 2019-01-24 10:09
Thanks, I did do a quick search but couldnt find it previously mentioned.  I was probably missing a few keywords.
