### ISSUE TITLE
Methods not detected in Apex under VS Code

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/salesforcedx-vscode#1405] opened 2019-06-17 13:37 UTC
I updated my SFDX tooling this morning following Summer 19 release (thanks to the reminder by Rene Winkelmeyer) and now one of my classes is getting VS Code warning to "Declare missing method" even though the method exists as a public method in the base class of my class.  This was not the case on Friday and I've not touched the code since then, only updated the SFDX CLI and VS Code plugins thereupon

**Comment by robcowell** [comment] 2019-06-17 13:43
Also being triggered for private methods declared in the same class as the method call

**Comment by robcowell** [comment] 2019-06-17 13:53
https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode/CHANGELOG.md includes PR-1391 that talks about the `Declare missing method` message - coincidence?

**Comment by praksb** [comment] 2019-06-17 14:41
@robcowell This is a new Code action -> Quick fix option that we added recently. What you are observing looks like a bug to me. Can you please share a screenshot of the issue along with the source code that we could use to repro? 

Thanks!

**Comment by robcowell** [comment] 2019-06-17 15:12
So it suggests a quick fix of declaring the "missing method" like so
![1](https://user-images.githubusercontent.com/2143167/59615439-67503e00-911a-11e9-9539-901e33584835.png)

but the method definitely exists as below
![2](https://user-images.githubusercontent.com/2143167/59615470-7800b400-911a-11e9-904e-997e6f5349ea.png)

Source test harness to follow shortly

**Comment by dcstuff** [comment] 2019-06-17 15:15
@robcowell Can you screenshot what you're trying to pass into the method? Is it possible the argument types don't _exactly_ match? I.e., maybe passing in `Map<Id, Event>` when it expects `Map<Id, sObject>`. I'm just thinking out loud...

**Comment by robcowell** [comment] 2019-06-17 15:18
![image](https://user-images.githubusercontent.com/2143167/59615844-2c023f00-911b-11e9-8911-ba7437888c8f.png)

@dcstuff is right in that the base methods use generic sObject collections new newList/oldMap whereas in the derived class(es) where they are used, things are a little more strongly-typed, which may confuse the code parser looking for method signature matches

**Comment by robcowell** [comment] 2019-06-17 15:23
Another example from the Test class associated with the above methods - existing code has `private static List<Event> getEventsForContact(){` but the quick fix version generates the same without the static modifier.

**Comment by robcowell** [comment] 2019-06-17 15:33
In each of these cases, the right-click `View Definition` capability seems affected too, i.e., no longer can match the signature and jump to the definition

**Comment by praksb** [comment] 2019-06-17 15:40
@robcowell What is the type of newList and oldMap where you call method UpdateLastMeeting? Can you also share the code that is generated when you invoke the quick fix?

**Comment by robcowell** [comment] 2019-06-17 15:46
@praksb it generates

`private void UpdateLastMeeting(List<SObject> newList, Map<Id,SObject> oldMap){} `

versus actual definition of

`private void UpdateLastMeeting(List<Event> newList, map<Id, sObject> oldMap){}`

so does look like a generic vs specific sObject thing at first glance

**Comment by praksb** [comment] 2019-06-17 16:51
@robcowell Can you go to View->Command Palette and run "SFDX: Refresh SObject Definitions" command? After that can you do a Go-to-definition on "Event" to verify if it goes to the generated Event.cls file?

Please let us know if the issue still repros after trying the steps above.

**Comment by robcowell** [comment] 2019-06-17 17:10
Have left office for the day, will try first thing in the morning (UK) and 
confirm

**Comment by joeferraro** [comment] 2019-06-17 17:18
Having the same problem even after refreshing SObject definitions and reloading the workspace. Missing method quick fixes are suggested when the method already exists in the class and I can never clear them.

**Comment by praksb** [comment] 2019-06-17 17:56
@joeferraro Do you have a code sample that you could share?

**Comment by robcowell** [comment] 2019-06-18 13:11
Has a patch been rolled out for this already?  The same class I was looking at yesterday now has zero issues flagged, with no changes made to my Apex

**Comment by robcowell** [comment] 2019-06-18 13:19
@praksb I attempted to make a generic sample code example but couldn't reproduce the issue, so I loaded up the class I had struggled with yesterday and it's no longer affected.  But this is a different DX project pointing at the same sandbox.  I loaded the original DX project, loaded up the same class and the 11 missing method errors came back.  This makes me think it could be something in the DX project that's causing the problem

**Comment by robcowell** [comment] 2019-06-18 14:46
Sample code
![image](https://user-images.githubusercontent.com/2143167/59694154-10ad3780-91e0-11e9-86c6-5609a67a2ba6.png)

`public with sharing class SampleClass extends baseclass
{
    public SampleClass()
    {
        List<Contact> contactList = new List<Contact>();
        ExampleMethod(contactList);
    }

    public override void ExampleMethod(List<SObject> contacts)
    {
        for (SObject c : contacts)
        {
            System.debug(contact.Name);
        }
    }
}`

with base class defined as
`public virtual class baseclass {
    public baseclass()
    {

    }

    public virtual void ExampleMethod(List<SObject> objects)
    {

    }
}`

**Comment by camisotro** [comment] 2019-06-18 18:04
Also experiencing this. In my case the context is, the constructor of an inner class invokes a static method of the parent class. This invocation is highlighted as if it were a missing method.

**Comment by nkadis** [comment] 2019-06-19 08:09
I get the same Quick fix message for any method that inherits from another class, or generic methods. I can `cmd+click` or `right-click->Go to Definition` and I'm taken to the method declaration - even though I get the `Quick fix available: Declare missing method` message.

**Comment by keirbowden** [comment] 2019-06-19 08:15
I'm getting this for pretty much every method call in my class and any that are statically referenced from other classes. Not sure if it makes any difference, but in this case I'm using the metadata rather than source structure, so ./src/classes.

**Comment by robcowell** [comment] 2019-06-19 08:18
@keirbowden yeah, I get it in both metadata formats/folder structures

**Comment by praksb** [comment] 2019-06-19 18:04
@robcowell For the project where this issue repros, what happens when you do a Go-To-Definition on "Contact" in SampleClass.cls?

**Comment by praksb** [comment] 2019-06-19 18:06
@camisotro Can you provide me with a simple code sample that repros for you? It would be great if you could possibly share a zip file for the project so that I can see if any types are missing that may be the cause of this problem.

**Comment by praksb** [comment] 2019-06-19 18:10
@nkadis That is interesting. I am able to repro this only when there is a compile error due to missing types. In your case it looks like the compiler bound successfully. Do you have a simple repro project that you could share with me?

**Comment by praksb** [comment] 2019-06-19 18:11
@keirbowden Project structure shouldn't matter. Does go-to-def on method invocations work?

**Comment by camisotro** [comment] 2019-06-19 18:38
I managed to reproduce a minimal example. I think I see what is happening.

If I call a method using an sObject field as a parameter, but the IDE can't figure out the type of that sObject field, it will fail to resolve that the method signature points to a method I have in the class. In this case for example it can't tell that Opportunity.Description is a String. This despite the fact that in the project I have even retrieved Opportunity object metadata.

![image](https://user-images.githubusercontent.com/9795642/59791324-d5723d80-929f-11e9-9f5d-0c44ed93f776.png)

**Comment by praksb** [comment] 2019-06-19 20:14
@camisotro Can you do Ctrl+Click on "Opportunity"? This will do a Go-to-defition on "Opportunity" and if it succeeds do you see an "Opportunity.cls" file and does it have "Description" field defined?
Please refer to the attached screenshot for reference:

![Screen Shot 2019-06-19 at 1 10 51 PM](https://user-images.githubusercontent.com/10749920/59797270-2c721580-9294-11e9-9aff-b028c672048b.png)

**Comment by camisotro** [comment] 2019-06-20 00:06
I did in the end learn that there's a special command for auto-generating those fake classes that help VSCode understand what it's doing. And in some cases that does appear to have fixed it.

However it would be much nicer if the IDE could flag that by suggesting the user run that command, rather than giving an error that is factually incorrect.

**Comment by robcowell** [comment] 2019-06-20 08:22
@praksb to answer your question - it navigates to `.sfdx/tools/sobjects/standardObjects/Contacts.cls`

**Comment by nkadis** [comment] 2019-06-20 09:09
@praksb Thanks for the quick fix - no pun intended. I no longer get that message for any methods that inherit from a parent or any generic methods for that matter, but I do get it in this situation:

![Screenshot 2019-06-20 at 10 02 58](https://user-images.githubusercontent.com/12812036/59836154-ee7ffa80-9342-11e9-8357-0bb507a1665a.png)

Both methods work fine, as in, you can deploy without any errors and the code actually runs.

**Comment by shamina-acn** [comment] 2019-06-20 11:18
Hello, i am facing this issue with methods for lightning apex controller class and test classes too.
if this can help, here is a extract of sample code

![image](https://user-images.githubusercontent.com/40169125/59845394-5ac42380-936e-11e9-8e24-510a87b3fe32.png)

**Comment by nkadis** [comment] 2019-06-20 14:11
Also, something I've noticed - that might not be related to this issue - is that you don't get the `getDescribe()` auto-suggestion on SObjects:

![Screenshot 2019-06-20 at 15 00 20](https://user-images.githubusercontent.com/12812036/59855121-3b2bfb80-936c-11e9-93eb-9f03371c4860.png)

Could it be something to do with some Schema classes or the Schema namespace in general just not being recognised/indexed by the extension?

**Comment by camisotro** [comment] 2019-06-20 15:19
I've found another edge case. If my Custom Metadata Type has a lookup to FieldDefinition or EntityDefinition, the generated class file in /sfdx/tools/sobjects/customObjects does not contain the reference field to the lookup. 

So if MyMeta__mdt.Object__c is a lookup to EntityDefinition, then I should expect the generated class to have **global EntityDefinition Object__r**. Because it doesn't, I'm getting this error when I call my method that takes a String, with an argument of **myMetaRecord.Object__r.QualifiedApiName**.

**Comment by lcampos** [comment] 2019-06-20 18:15
I'm closing this since we've disabled showing the squiggly lines in version `46.2.0` of the extensions. In the meantime, we'll take all your feedback and address it for the next iteration of that feature.

**Closed by lcampos** 2019-06-20 18:15 UTC

**Comment by praksb** [comment] 2019-06-20 19:43
@nkadis I have opened a different issue to track the error that you were getting with Opportunity.SObjectType: https://github.com/forcedotcom/salesforcedx-vscode/issues/1420
We already have story in our backlog for improving completion items for the other issue that you mentioned.

**Comment by praksb** [comment] 2019-06-20 19:44
@camisotro Lets track the issue you found separately: https://github.com/forcedotcom/salesforcedx-vscode/issues/1421

**Comment by praksb** [comment] 2019-06-20 19:48
As Luis had mentioned, we have disabled showing the quick fix message for now, however, you can still invoke the Declare missing method quick fix in cases where it is applicable. If you have salesforcedx-vscode-apex.enable-semantic-errors": true in your settings.json then if you hover over the error message squiggly then the quick fix option will show up in cases where it is applicable.

Thanks for all the feedback.
