### ISSUE TITLE
SFDX: retrieve source in Manifest from org - Metadata API request failed: INVALID_LOCATOR: Retrieve result has been deleted

### ISSUE THREAD

**Issue by matthewcoolidge** [forcedotcom/salesforcedx-vscode#3496] opened 2021-08-12 20:13 UTC
### Summary

SFDX: retrieve source in Manifest from org - Metadata API request failed: INVALID_LOCATOR: Retrieve result has been deleted

VS Code 1.59.0 - suddenly I cannot run "retrieve source in Manifest from org" command without failure: Metadata API request failed: INVALID_LOCATOR: Retrieve result has been deleted. Oddly, if the manifest ONLY contains the ApexTrigger type, it works fine. 

Salesforce CLI Integration is v52.9.0

retrieve source in Manifest from org works fine for a different developer (same Org) using VS Code v1.47.3

### Steps To Reproduce:

1.  SFDX : Create new Project with Manifest, pick save folder
2. Trust the project folder
3.  SFDX: Authorize an Org, select Sandbox, type name, log in Salesforce (SUCCESS)
4. Right click package.xml file in manifest folder, select SFDX: Retrieve Source in Manifest from Org

### Expected result

SFDX: Retrieve Source from Org successfully ran

### Actual result

Metadata API request failed: INVALID_LOCATOR: Retrieve result has been deleted.

### Additional information

This seems to be a new problem, I didnt notice it until I applied the June 2021 version of VS Code. I do not know how to get more verbosity on the error message or if there is logging somewhere

**Salesforce Extension Version in VS Code**:
v52.9.0

**SFDX CLI Version**:
sfdx-cli/7.112.1 darwin-x64 node-v14.17.4

**OS and version**:
MacOS Cataline 10.16.6

**Comment by xyc** [comment] 2021-08-12 20:22
Duplicate of #3495

**Closed by xyc** 2021-08-12 20:23 UTC
