### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MrKaveh** [forcedotcom/salesforcedx-vscode#1370] opened 2019-05-25 15:13 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `45.15.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/mohammadhossein/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by praksb** [comment] 2019-05-28 05:42
Dupe of #1369

**Closed by praksb** 2019-05-28 05:42 UTC
