### ISSUE TITLE
"sfdx force:apex:test:run --wait 60" no longer waits

### ISSUE THREAD

**Issue by aidan-harding** [forcedotcom/salesforcedx-vscode#3456] opened 2021-07-28 14:36 UTC
### Summary

When I run tests with the `--wait N` flag, the command now returns immediately as if I hadn't supplied a `--wait` flag at all

### Steps To Reproduce:

In any project, just run

```
sfdx force:apex:test:run --wait 60
```

### Expected result

Within 60 minutes, a summary of the test results.

### Actual result

CLI responds with:

```
Run "sfdx force:apex:test:report -i 70763000021RJhE -u test-removed@example.com" to retrieve test results
```

### System Information

```
{
        "cliVersion": "sfdx-cli/7.110.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.17.3",
        "pluginVersions": [
                "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.7.0",
                "@oclif/plugin-autocomplete 0.3.0",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.0 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.10.0",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.2 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.13 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.5.2 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "mentz 1.0.1",
                "org 1.6.7 (core)",
                "salesforce-alm 52.1.0 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.110.0 (core)",
                "telemetry 1.2.2 (core)",
                "templates 52.1.0 (core)",
                "user 1.3.1 (core)"
        ],
        "osVersion": "Darwin 20.5.0"
}
```

**Comment by mshanemc** [comment] 2021-07-30 14:49
@aidan-harding  the team that runs vscode also owns the apex testing CLI commands, so I'm transferring it there.

**Comment by AnanyaJha** [comment] 2021-08-04 00:04
This issue is a duplicate of #3161. Marking this as closed in favor of the other.

**Closed by AnanyaJha** 2021-08-04 00:04 UTC
Labels: area:apex, status:needs eng review
