### ISSUE TITLE
No Content Appeared after project created

### ISSUE THREAD

**Issue by kumquatlily** [forcedotcom/salesforcedx-vscode#2463] opened 2020-08-28 21:29 UTC
### Summary

Project Created But nothing appeared in project folder.  This issue is related to several reported issues -  #2295, #2332, #2288, #2283.
However, I have tried installing other versions of Salesforce extension version already and still nothing appears after project folder created.  Currently, the SF extension version is 49.7.0.
Please help??

### Steps To Reproduce:

1.  Installed VSC Windows
1.  This is step 2. Installed Salesforce CLI
1.  This is step 3.  Installed Salesforce Extension. 49.7.0.
1.  This is step 4.  Create Project
1.  This is step 5.  Create Project folder

### Expected result

While Project folder creating, VSC notification should run and then the project folder content(setup bases, etc) should appear under the Project Folder.

### Actual result

VSC notification of Salesforce appeared for 2 seconds and no notifications appear.
The project folder has no content.  
Also, I have tried 10x, there are no error messages, except once, see screenshots below.
![1st error](https://user-images.githubusercontent.com/62514479/91616199-17821f00-e93a-11ea-9e5c-da2da78e2fbe.jpg)
![2nd error](https://user-images.githubusercontent.com/62514479/91616258-31bbfd00-e93a-11ea-8112-a04b6b41af3e.jpg)
![4th pic](https://user-images.githubusercontent.com/62514479/91616270-37194780-e93a-11ea-9c0c-8989fd8bccf1.jpg)

### Additional information

Expected Results: 
![Annotation 2020-08-28 130915](https://user-images.githubusercontent.com/62514479/91616338-57e19d00-e93a-11ea-8997-7956febbb4ff.png)
Actual Results:
![Annotation 2020-08-28 141610](https://user-images.githubusercontent.com/62514479/91616358-60d26e80-e93a-11ea-86d3-47b2182ff5ed.png)

**VS Code Version**:  1.48.2

**SFDX CLI Version**: 7.72.0.0

**OS and version**: Windows 10 x64

**Comment by xyc** [comment] 2020-08-31 16:49
Hi @kumquatlily , I couldn't reproduce this issue with the VS Code version and CLI version on Windows. Could you check if this works for you if you run the command from CLI? For example, running the following command:
`sfdx force:project:create -n MyProject -d <outputDir>`

**Comment by kumquatlily** [comment] 2020-09-01 15:19
> Hi @kumquatlily , I couldn't reproduce this issue with the VS Code version and CLI version on Windows. Could you check if this works for you if you run the command from CLI? For example, running the following command:
> `sfdx force:project:create -n MyProject -d <outputDir>`

Hi @xyc , when I ran cmd, not recognized with the command and same as in vsc.  Sorry, I am new using CLI. is this what you meant to run the command from CLI?

**Comment by xyc** [comment] 2020-09-02 03:46
hi @kumquatlily What I meant by running commands from CLI is running the command from your system terminal (powershell) for example. Could you check if your CLI path is inside your system PATH env variable? When you have installed CLI correctly, running `sfdx` should say:
```
Salesforce CLI

VERSION
  sfdx-cli/7.72.0-...
```
Also, we will be releasing a new extension version this week that doesn't require you to install CLI for project creation.

**Comment by kumquatlily** [comment] 2020-09-02 16:38
Hi @xyc,

yes, I checked them already and here screenshots reconfirming.
so the new version don't need to download CLI, does that mean I should delete/uninstall CLI?
![Annotation 2020-09-02 093456](https://user-images.githubusercontent.com/62514479/92011508-ff2a4f80-ecff-11ea-8e77-8cd09929e3b1.jpg)
![Annotation 2020](https://user-images.githubusercontent.com/62514479/92011515-02bdd680-ed00-11ea-8604-629fc79c368f.jpg)

**Comment by xyc** [comment] 2020-09-02 22:11
hi @kumquatlily :
> so the new version don't need to download CLI, does that mean I should delete/uninstall CLI?

No, please don't. There're some other functionalities still depend on CLI.

The new version 49.8.0 is out, please let us know if it fixes your issues.

**Comment by kumquatlily** [comment] 2020-09-03 18:51
@xyc:
thank  you is working, However, another issue came up #2482.  I tried authorizing just to confirm 49.8.0 works and I got below:
any advise please?
![Annotation 2020-09-03 112658](https://user-images.githubusercontent.com/62514479/92155007-8f899280-eddb-11ea-932f-1b4da7d4564e.jpg)
![Annotation 2020a](https://user-images.githubusercontent.com/62514479/92155018-93b5b000-eddb-11ea-9eca-0ad3328aca4c.jpg)
![Annotation 2020b](https://user-images.githubusercontent.com/62514479/92155029-97e1cd80-eddb-11ea-947c-2425ccefee1a.jpg)

**Comment by lcampos** [comment] 2020-09-04 01:28
I'm closing this issue since the originally reported one got addressed with the changes in 49.8.0 and the other issue is being discussed in another thread as well.

**Closed by lcampos** 2020-09-04 01:28 UTC
