### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by snafuy** [forcedotcom/salesforcedx-vscode#2564] opened 2020-09-23 13:55 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.10.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.1`

[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/5268599/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.zip)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-10-05 16:32
Not a lot of details here, but guessing this is a duplicate of #2410.  Check out that issue and the workaround I posted in the comments.

**Closed by smaddox-sf** 2020-10-05 16:32 UTC
