### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GeetaSoni** [forcedotcom/salesforcedx-vscode#3450] opened 2021-07-27 03:59 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `52.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\2014352\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by xyc** [comment] 2021-07-29 21:18
Duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/3198

**Closed by xyc** 2021-07-29 21:18 UTC
Labels: type:duplicate
