### ISSUE TITLE
VS Code Errors Activating salesforce.salesforcedx-vscode-core Extension

### ISSUE THREAD

**Issue by ricex242** [forcedotcom/salesforcedx-vscode#67] opened 2017-08-25 15:10 UTC
### VS Code Errors Activating salesforce.salesforcedx-vscode-core Extension

After installing VS Code Ext pack, the core extension will not activate. CLI commands are not available from the command palette.

### Steps To Reproduce:
1. Install VS Code. 
1. Install VS Code Extension pack from within VS Code. 
1. Clone [sfdx-dreamhouse](https://github.com/forcedotcom/salesforcedx-vscode) to local (or any valid sfdx project; doesn't seem to matter which)
1. Open sfdx project in VS Code as root folder
1. Attempt to run sfdx commands from command palette

### Expected result
_Should be able to run CLI commands from VS Code_.

### Actual result
_Can't run sfdx CLI commands_.

### Additional information

![untitled](https://user-images.githubusercontent.com/17648635/29719549-2ea20568-897c-11e7-87dd-b48a6d0d5ba4.png)

**VS Code Version**: 1.15.1 (shell 1.6.6) win64

**SFDX CLI Version**: sfdx-cli/5.7.6-d42cf65 (windows-amd64) go1.7.5 sfdxstable

**OS and version**: Windows 7 Enterprise 6.1.7601 Service Pack 1 Build 7601

**Comment by vazexqi** [comment] 2017-08-25 23:41
I'm not able to reproduce this but I've seen it happen on one of my VS Code instances that had `"extensions.autoUpdate": true` (this is the default). It updated in the background and then I closed it.

I tried to simulate this by building an older version of the VS Code extensions (git clone git@github.com:forcedotcom/salesforcedx-vscode.git; git co v40.5.1; npm install; npm run compile; npm run vscode:package). Then I installed this into VS Code and waited for it to auto-update.

I can't reproduce the issue. 

I think I know what the issue is though: it is not getting everything from the v40.7.0 bundle.

![screen shot 2017-08-25 at 4 38 40 pm](https://user-images.githubusercontent.com/54414/29736216-168310ca-89b4-11e7-8cb7-b05b7e0145d0.png)

I wonder if this happens when VS Code itself tries to download things before it has fully propagated to all the servers and end up with a partial version.

**Comment by vazexqi** [comment] 2017-09-05 14:58
Suspecting it was a download issue, I monitored this on three different machines (Linux, Mac, and Windows) and was not able to reproduce this issue during the 40.7.0 -> 40.8.0 auto-upgrade. The reload button showed up for the extensions and I was able to update each one successfully.

@ricex242 - Has this happened to you again since you filed the bug?

**Comment by ricex242** [comment] 2017-09-05 16:12
@vazexqi Nope no issues since I re-downloaded.

**Comment by vazexqi** [comment] 2017-09-05 16:30
All right. I'm going to close this for now. If this happens again, we can reopen this issue.

**Closed by vazexqi** 2017-09-05 16:30 UTC
Labels: investigating
