### ISSUE TITLE
ApexIndexer throwing NullPointerException

### ISSUE THREAD

**Issue by PhilippOrtnerUp2Go** [forcedotcom/salesforcedx-vscode#581] opened 2018-08-21 11:19 UTC
### Summary

When starting VSCode in a valid folder with a sfdx-config.json I am missing most of the LS features since I can observe an error in the output of the Apex Language Server in the output window.

Other features such as Debugging or the CLI plugin work perfectly fine.

### Steps To Reproduce:

1.  Open sfdx-config.json containing folder (connection and CLI works in this folder).
2.  Observe output window of Apex Language Server. 

### Expected result

Full LS features / no errors.

### Actual result

Multiple of these NullPointerExceptions:

[ApexIndexer STARTING] ERROR a.jorje.lsp.impl.index.ApexIndexer - exception thrown in traversing codeunit for references
java.lang.NullPointerException: null

### Additional information

[apex-ls.log](https://github.com/forcedotcom/salesforcedx-vscode/files/2306031/apex-ls.log)

**VS Code Version**:

1.26.1

**SFDX CLI Version**:

sfdx-cli/6.29.0 (linux-x64) node-v10.6.0

**OS and version**:

Ubuntu 16.04 LTS 
4.15.0-32-generic

**Comment by PhilippOrtnerUp2Go** [comment] 2018-08-21 11:29
Thanks for the quick reply @vazexqi .

Seems to be similar to issue [#388](https://github.com/forcedotcom/salesforcedx-vscode/issues/388) which was solved.

If you need any other logging info or want me to test something I'll happily help you. 

Will look into opening a support case, need to talk to my supervisors, also not really sure about looking at the code at the moment.

**Comment by vazexqi** [comment] 2018-08-24 22:29
Duplicate of #587.

**Closed by vazexqi** 2018-08-24 22:29 UTC
Labels: bug, duplicate
