### ISSUE TITLE
Error Java runtime could not be located

### ISSUE THREAD

**Issue by daveb-501commons** [forcedotcom/salesforcedx-vscode#138] opened 2017-09-23 22:08 UTC
### Summary
Following the video on https://github.com/forcedotcom/salesforcedx-vscode/wiki.  Installing on Windows 10.  When I go to open the sfdx-dreamhouse project using code . it opens in VS Code and then get error message

Error: Java runtime could not be located.  Set one using the salesforcedx-vscode-apex.java.home VS Code Settings

How do I go about doing that?

**Comment by guhaanandhnec08** [comment] 2017-09-23 23:55
Am having the same issue...  any workarounds?

**Comment by guw** [comment] 2017-09-24 07:24
Duplicate of #100

**Closed by guw** 2017-09-24 07:24 UTC
