### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gitsalesforce** [forcedotcom/salesforcedx-vscode#2600] opened 2020-10-05 19:39 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `49.12.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\adminuser\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5329727/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)

**Comment by Arkin69** [comment] 2020-10-06 08:40
Issue Type: Performance
Extension Name: salesforcedx-vscode-apex
Version: 1.49.3 (user setup)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

OS: Windows_NT x64 10.0.19041
RAM : 16 Go
CPU : i7

I have the issue since 3 months

OUTPUT (Apex Language Server) on VS Code :

10:30:19.886 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
oct. 06, 2020 10:30:20 AM apex.jorje.parser.impl.BaseApexLexer dedupe
INFOS: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 8 ms.
10:30:22.106 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
10:30:22.111 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
10:30:22.842 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
10:30:22.843 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 2955 ms.
oct. 06, 2020 10:30:59 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFOS: Unsupported notification method: $/setTraceNotification
oct. 06, 2020 10:37:33 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
GRAVE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by smaddox-sf** [comment] 2020-10-06 17:49
Thanks for reaching out with feedback.  From reviewing the details provided, it looks like this is a duplicate of #2410.  Please check out that issue and add other feedback if it doesn't completely cover your scenarios.  I also posted a workaround that might help in a comment on that issue.  Post back on #2410 and let us know if it helps.

**Closed by smaddox-sf** 2020-10-06 17:49 UTC
