### ISSUE TITLE
Extension issue: Apex testing from VSCode takes too long

### ISSUE THREAD

**Issue by juandomenechh** [forcedotcom/salesforcedx-vscode#2832] opened 2021-01-03 14:36 UTC
Hello! I am having this problem where I am able to test my Apex Classes from VSCode using the Apex and the Salesforce CLI Integration extensions, but the amount of time this process is taking is huge. Despite beeing able to test the code after -aprox- 9000ms, it's really annoying to wait that long every time. Could anyone help me solve this? I leave some details below. Thanks!

- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `50.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8642,
		"activateCallTime": 3,
		"activateResolvedTime": 310,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-apex",
				"_lower": "salesforce.salesforcedx-vscode-apex"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by lcampos** [comment] 2021-02-02 00:36
Closing this as a duplicate of https://github.com/forcedotcom/salesforcedx-vscode/issues/1582. You can follow that issue for the most recent updates.

**Closed by lcampos** 2021-02-02 00:36 UTC
Labels: status:needs eng review
