### ISSUE TITLE
Java.home points to missing folder

### ISSUE THREAD

**Issue by mattbratton** [forcedotcom/salesforcedx-vscode#1472] opened 2019-07-12 16:48 UTC
### Summary

I am unable to get VS Code/SFDX to recognize Java on my Mac.  I've downloaded JDKs from Oracle (both 8 & 11) and tried Adopt Open, and still receive the same error message.

### Steps To Reproduce:

1.  Download Java
2.  In VS Code, navigate to Code -> Preferences -> Settings. In search bar, search for "apex java", select "Edit in settings.json".
3.  Change "salesforcedx-vscode-apex.java.home" path to Java path on computer. Latest path is "‎⁨/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home". 
4.  I save and restart VS Code.

### Expected result

I would expect to see "Apex Language Server" as an option in the "Output" tab and be able to use the language server for type ahead, be able to run testing and much more.

### Actual result

Receive the following error message: The salesforcedx-vscode-apex.java.home setting defined in VS Code settings points to a missing folder. For information on how to setup the Salesforce Apex extension, see Set Your Java Version.

### Additional information

![Screen Shot 2019-07-12 at 10 34 50 AM](https://user-images.githubusercontent.com/38227497/61144464-2dacf180-a492-11e9-9641-e91923492c12.png)

**VS Code Version**: 1.36.1

**SFDX CLI Version**: 7.14.0-bd96f098e0

**OS and version**: macOS Mojave 10.14.5

**Comment by bbacharz** [comment] 2019-07-24 02:05
I am having this issue as well. Any guidance would be appreciated!
Version numbers are the same with the exception below.

**SFDX CLI Version:** 7.15.3-c7d407d236

**Comment by PhilipJohnBasile** [comment] 2019-07-26 20:27
same here

**Comment by ntotten** [comment] 2019-07-30 21:38
Can you confirm that you followed the instructions on this page? https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/java-setup

I would suggest trying it with Oracle Java 11 as that is the _most_ tested version. All of them should work, but that is the best starting point.

**Comment by ntotten** [comment] 2019-07-30 21:40
One other thing I just realized is that in the string you pasted there seems to be a white space character in your string. Not sure if it is a weird copy/paste issue from github or if it is actually present in your `setting.json` file, but if it is that could be the issue.

![image](https://user-images.githubusercontent.com/282782/62167383-19ba1a00-b2f1-11e9-81e8-4df454e09457.png)

**Comment by bbacharz** [comment] 2019-07-31 19:05
I can confirm that I followed the directions as explicitly as possible (it looks like the discrete steps need to be updated slightly). Here is a screenshot of the current settings file.
![SFDX VS Code Error](https://user-images.githubusercontent.com/44268100/62240269-33646b80-b39c-11e9-8a13-61a3d1cb342c.png)

**Comment by ntotten** [comment] 2019-07-31 19:54
@bbacharz Is it possible your `settings.json` on your project is overrideing that setting? I see that setting in the user settings, but is something else set in the workspace `.vscode/settings.json` file?

**Comment by bbacharz** [comment] 2019-08-01 13:13
@ntotten I thought about that as well. Originally, it was empty with the same result, so I added the same line to the settings and am getting the same message.
<img width="1552" alt="vscode settings" src="https://user-images.githubusercontent.com/44268100/62296143-209d7580-b434-11e9-8772-ce2641467c78.png">

**Comment by brpowell** [comment] 2019-08-01 16:29
Hi @bbacharz - can you verify that this path really is where Java is installed? You can open the VS Code terminal and do `ls /Library/Java/JavaVirtualMachines/jdk-1.8.0_221.jdk/Contents/Home/`

**Comment by bbacharz** [comment] 2019-08-01 16:44
Thanks @brpowell 

That showed where my issue was! I left a - in the file path that should not have been there for that version. 

Version 8
"/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home"

Version 11
"/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home"

My error is now fixed, however it will not allow me to use version 11 (it says that java 8 is required). If you have any insight on this, I would appreciate it. Otherwise I will work with what I have. Thank you, again!

**Comment by brpowell** [comment] 2019-08-01 16:57
Awesome @bbacharz! It looks like that path you put for version 11 is actually 12 (jdk 12.0.2) which we currently do not support. Try installing from this downloads page https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html

**Comment by bbacharz** [comment] 2019-08-01 17:06
@brpowell Yep, chalk another one up for not paying attention! I just downloaded installed and changed the settings. All is well with the world. Thanks for all your help!!

**Comment by mattbratton** [comment] 2019-08-01 18:02
@bbacharz Here is a screenshot of the terminal.  As far as I can see it looks correct.  Appreciate the help.

![Screen Shot 2019-08-01 at 11 59 31 AM](https://user-images.githubusercontent.com/38227497/62316187-2acf6c00-b454-11e9-8edb-4470a307a238.png)

**Comment by brpowell** [comment] 2019-08-01 18:11
@mattbratton Does your home path in settings have an extra slash at the end? like `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/` instead of `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`?

**Closed** 2019-08-08 21:43 UTC
Labels: more information required

**Comment by vidyut99** [comment] 2020-06-17 20:23
hello @ntotten 

could you please help out- i am using adopt OpenJDK and i have put correct path in apex language server-  C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot

and when i run this command -PS C:\Users\VIDYUT\Documents\LWC-VS Code\helloworldLWC> sfdx force:auth:web:login -a Vdeva -d

then I get below error

{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://login.salesforce.com/services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=53f345dbc51b^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=Az78w9nam0dLRwJ1c1XEfnGgF9ZRfS3ObyxB662BoUc' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://login.salesforce.com/services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=53f345dbc51b^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=Az78w9nam0dLRwJ1c1XEfnGgF9ZRfS3ObyxB662BoUc' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://login.salesforce.com/services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=53f345dbc51b^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=Az78w9nam0dLRwJ1c1XEfnGgF9ZRfS3ObyxB662BoUc' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://login.salesforce.com/services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=53f345dbc51b^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=Az78w9nam0dLRwJ1c1XEfnGgF9ZRfS3ObyxB662BoUc' ] }
![image](https://user-images.githubusercontent.com/20460103/84946533-7f301880-b106-11ea-8f82-ce1f2a775bde.png)


Any help will be greatly appreciated i am stuck at it for few days.

**Comment by jpmorrissee** [comment] 2021-01-07 21:42
I had this same error for months. I added the path to my settings.json file and it fixed it! I finally have Apex auto completion now.

`{
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/.sfdx": true
  },
  "salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
}
`

**Comment by leto96** [comment] 2022-04-18 14:21
> Can you confirm that you followed the instructions on this page? https://forcedotcom.github.io/salesforcedx-vscode/articles/getting-started/java-setup
> 
> I would suggest trying it with Oracle Java 11 as that is the _most_ tested version. All of them should work, but that is the best starting point.

Restuling in a page not found
![image](https://user-images.githubusercontent.com/26888271/163821761-a4d9243d-d6a0-4571-9c2c-b70076d378b2.png)
