### ISSUE TITLE
Error: Request initialize failed with message: Cannot read properties of undefined (reading 'location')

### ISSUE THREAD

**Issue by SalesforceAlexS** [forcedotcom/salesforcedx-vscode#5099] opened 2023-09-18 01:05 UTC
### Summary

When loading the LWC extension, I got this error.
```
[error] Error: Request initialize failed with message: Cannot read properties of undefined (reading 'location')
    at be (c:\Users\***\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.14.2\dist\index.js:23:227)
    at Te (c:\Users\***\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.14.2\dist\index.js:22:12217)
    at Immediate.<anonymous> (c:\Users\***\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-58.14.2\dist\index.js:22:12068)
    at processImmediate (node:internal/timers:476:21)
```

### Steps To Reproduce:

Start VS code with salesforcedx-vscode-lwc in a salesforce project

### Actual result

The VS code will show a error on the right bottom when start.

### Additional information

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:
@salesforce/cli/2.7.11 win32-x64 node-v18.15.0

**OS and version**:

Windows 11 Enterprise 21H2

**Comment by SalesforceAlexS** [comment] 2023-09-18 01:12
Duplicate of the issue https://github.com/forcedotcom/salesforcedx-vscode/issues/5069

**Comment by daphne-sfdc** [comment] 2023-09-18 14:20
Hi @SalesforceAlexS, Since this is a duplicate of #5069, I'll close this issue and continue tracking the problem there. Thanks!

**Closed** 2023-09-18 14:20 UTC
