### ISSUE TITLE
Replay debugger ignoring breakpoints when replaying lightning controller action

### ISSUE THREAD

**Issue by socialsuiteDan** [forcedotcom/salesforcedx-vscode#481] opened 2018-06-13 05:23 UTC
### Summary
We've been able to set up and use the Apex Replay Debugger with breakpoints behaving correctly when using a log file triggered by a test execution for a lightning controller action, but when debugging the log file generated by accessing the lightning component in the browser, the breakpoints get ignored. The DX project is for our managed package, so the Apex code is all namespaced. We did note that when debugging the first log file from the test, the call stack lists the namespaced class and method names correctly, but with the second log file from the lightning component, if we step through the log file lines the call stack doesn't show the namespace, and everything is listed as 'Unknown source'.

### Steps To Reproduce:
1. Set up a DX project with a namespace
1. Create a lightning component with a server-side controller action
1. Create a test that runs the server-side action, and generate a debug log by running the test
1. Generate another debug log by accessing the component in the browser
1. Set a breakpoint on the apex controller method.
1. Use the Apex Replay Debugger to debug both log files

### Expected result
In both log files, the debugger should hit the breakpoint and wait

### Actual result
The breakpoint worked correctly in the test log file, but in the log file generated by accessing the component, the debugger continued through to the end of the log without stopping.

### Additional information

**VS Code Version**:
1.24.0

**SFDX CLI Version**:
sfdx-cli/6.19.0-a2585faec2 (windows-x64) node-v8.9.4

**OS and version**:
Windows 10

**Internal Work Item**:
[W-5171319](https://gus.my.salesforce.com/a07B0000005PDewIAG)

**Comment by DatGuyJonathan** [comment] 2018-06-13 15:09
Thanks for reporting this @socialsuiteDan . I'm looking into it.

**Comment by DatGuyJonathan** [comment] 2018-06-14 18:54
@socialsuiteDan , I can reproduce this issue as well. The problem is the debug log is missing namespace prefixes whenever it mentions your controller's class name. As a workaround for now, you can either use Apex controllers in a non-namespaced org or manually edit your debug log to include the namespace.

For example, you might see `CODE_UNIT_STARTED`, `CODE_UNIT_FINISHED`, `CONSTRUCTOR_ENTRY`, `CONSTRUCTOR_EXIT`, `METHOD_ENTRY`, and `METHOD_EXIT` log lines. If these lines mention your Apex controller, prefix the namespace to the controller name.

`timestamp|CODE_UNIT_STARTED|[EXTERNAL]|someID|MyController.getContacts(Id)`
becomes
`timestamp|CODE_UNIT_STARTED|[EXTERNAL]|someID|mynamespace.MyController.getContacts(Id)`

VS Code editor has a mass replace functionality, so I hope that helps with the workaround. Apologies for the inconvenience; we'll look into fixing the issue as soon as possible.

**Comment by DatGuyJonathan** [comment] 2018-08-16 15:39
Closing this because the fix has been rolled out to all orgs.

**Closed by DatGuyJonathan** 2018-08-16 15:39 UTC
Labels: bug, in-gus
