### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sachine96patil** [forcedotcom/salesforcedx-vscode#3024] opened 2021-03-05 10:06 UTC
[salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/6089709/salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-apex`
- Extension Version: `51.3.0`
- OS Version: `Windows_NT x64 10.0.21322`
- VSCode version: `1.54.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\sachi\AppData\Local\Temp\salesforce.salesforcedx-vscode-apex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ajw725** [comment] 2021-03-05 15:39
i'm having problems with this as well, but on a mac. i just got a new-to-me macbook pro (16-inch, 2019) running big sur 11.2.2. if i open vs code with the salesforce extension pack disabled, everything else starts up fine; and as soon as i enable the extension pack, it maxes out my CPU. i've tried running through [these steps](https://github.com/microsoft/vscode/wiki/Performance-Issues) to export the extension host profile, but the option to save the host profile is never enabled, so i can't even do that.

i've tried downgrading the extension version, switching jdk versions (8 vs 11), etc...nothing helps. i've tried deactivating individual extensions within the bundle that seemed likely culprits - the CLI integration, apex, lwc, aura - but none of these things individually solved the problem. only shutting down the entire extension pack fixed it.

my old laptop is on catalina 10.15.7. it has exactly the same versions of vs code (1.54.1), the extension pack (51.3.0), and the salesforce CLI (7.81.0-7b953c80d1 darwin-x64 node-v12.18.3), but everything works just fine. the only slight difference there is that i have openjdk 11.0.9, whereas on the new laptop, i have 11.0.10 from oracle.

it's completely unusable on the new computer and i'm not sure what else to try. anyone have any suggestions?

**Comment by ajw725** [comment] 2021-03-05 17:54
ok, more info...it seems that for me, the problem is not just the extensions themselves; it's the extensions loading in a large project. if i enable all the extensions and open vs code to a non-salesforce project, it loads just fine. it's only when i open a salesforce project with a lot of custom code that it slows down. in that case, one extension by itself - just the CLI integration, just the apex extension, etc. - is enough to cause this problem.

**Comment by smaddox-sf** [comment] 2021-03-08 16:13
Thanks for providing feedback.  I believe this is a duplicate of #2410.  @ajw725 - Can you share details about the size of your project?  (# of classes, # of objects in your org, etc). I'll wait for your reply before combining this into the issue we're already tracking for this.

**Comment by ajw725** [comment] 2021-03-08 16:58
@smaddox-sf yep, sorry - i found this one first and realized later there were a few similar issues.

there are two main projects i work on regularly. both are first-generation managed packages.

project 1 (1266 total components in package):
- 239 apex classes (including tests)
- 24 apex triggers
- 14 LWC bundles
- 43 aura bundles
- 62 VF pages
- 15 VF components
- 32 custom objects (and 10 custom settings)

project 2 (819 total components in package):
- 184 apex classes (including tests)
- 9 apex triggers
- 60 LWC bundles
- 21 aura bundles
- 19 VF pages
- 9 VF components
- 21 custom objects (and 1 custom setting)

let me know if there's any other useful info i can provide.

**Comment by smaddox-sf** [comment] 2021-03-11 23:17
Thanks for the details @ajw725 !  We are working to get to the bottom of the performance issues and will update #2803 and #2410.  Closing this one as a duplicate to continue the discussions on those issues.

**Closed by smaddox-sf** 2021-03-11 23:17 UTC
Labels: more information required
