### ISSUE TITLE
force:apex:test:run calculating codecoverage when not requested 7.115.1

### ISSUE THREAD

**Issue by jajimenezffdc** [forcedotcom/salesforcedx-vscode#3541] opened 2021-09-09 15:22 UTC
### Summary

We have just updated from 7.75 to **7.115.1**, after having fixed a previous issue in **force:apex:test:run** not running async (https://github.com/forcedotcom/salesforcedx-vscode/issues/3164)

A lot of things added and fixed since then, but we are still finding issues with the test:run command.
Taking into account that we are keeping the same code in all of our tests, we've found the following errors in the "Apex Test Execution" section in the org:
+ Lots of "Code coverage from running this test class was not applied due to a conflicting recompilation task running at the same time. Please rerun this test class to recalculate code coverage." messages on successful tests BUT **we are not using the --codecoverage option**
+ Huge increase in our CI pipelines times at that specific stage. It looks like caused by that codecoverage calculation
+ Some errors like "Could not run test on class XXXX because: connection was cancelled here"

None of these problems was in place in 7.75 (I guess because the codecoverage was introduced in 7.96.1) but the point is that we are not interested in that coverage data and it looks like we can't avoid its calculation.

### Steps To Reproduce:

Can't provide the exact steps to recreate as it depends on the tests code, so probably with some basic test you won't get those messages for timeouts and conflicts, but this is how we have tested it.

1. Create a scratch-org
2. Ensure you have enableCompileOnDeploy = true
3. Push your code (tests included)
4. Run: **sfdx force:apex:test:run -u XXXXXXX -r human -w 60 -l RunLocalTests --verbose** 
5. Open your org (web ui) and go to Setup > Apex Test Execution
6. Measure the time it takes to execute the test
7. Check status of the tests

### Expected result

This is the expected behaviour and what is actually happening if you run on 7.75.0
- All the tests are executed successfully

### Actual result

This is the actual result running 7.115.1
- Execution time way longer than usual
- Warnings: "Code coverage from running this test class was not applied due..."
- Errors for classes timing out.

### Additional information

We have isolated the issue in the test:run command after discarding a push issue. We prepared an org, pushed the code and then, over the same org, we ran the test:run comnand on 7.75, upgrade to 7.115, test again and downgrade to 7.75 again.
It always worked on 7.75 and always the same issues on 7.11.5

We have tried sync and async runs, several orgs, several products code, but the pattern is the same for all of them.

**SFDX CLI Version**:
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.3 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.7 (core)
auth 1.7.1 (core)
config 1.2.24 (core)
custom-metadata 1.0.12 (core)
data 0.6.0 (core)
generator 1.2.0 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.2.6 (core)
schema 1.0.8 (core)
sfdx-cli 7.115.1 (core)
source 1.0.10 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)

**OS and version**:
Both MAC and Linux

**Comment by AnanyaJha** [comment] 2021-09-15 17:31
Hi @jajimenezffdc thanks for reporting this! Do you mind sharing some more info with us - where exactly are you seeing the message `Code coverage from running this test class was not applied due..` is this in the terminal? Or in the Apex Test Execution UI?
When you were running the command with CLI version 7.75, what was the version of the Apex plugin? You can find this by running `sfdx plugins --core`

**Comment by jajimenezffdc** [comment] 2021-09-16 15:07
Hi, @AnanyaJha .
That message can be seen only in the UI, not shown in the terminal.

These are the versions on 7.75:

@ffdev/ffdx 3.6.0 (3.6.0)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.13.0 (core)
├─ salesforce-alm 49.12.1 (core)
├─ templates 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.0 (core)
sfdx-cli 7.75.0 (core)

**Comment by AnanyaJha** [comment] 2021-09-20 15:38
@jajimenezffdc can you provide us with a sample repository to repro this with? unfortunately, we haven't been able to reproduce this error, so we'll need to be able to do that before we can debug further. could you also try running a smaller number of tests? what happens in the test execution page when there's only a few tests being run?

**Comment by jajimenezffdc** [comment] 2021-09-27 16:48
Hi @AnanyaJha 
 
We know it's not easy to recreate outside our company. This is happening with large code products, so makes no sense to provide a simple example, it won't fail. We have smaller products where we have not that issue. Only happen on products with a large number of tests.

I'm happy to help as much as I can if you tell me what's needed, have a call and show you, or any other thing you consider useful, but we'll need your guidance here.

Regards,
Jose

**Comment by jrahadfield** [comment] 2021-11-10 16:27
Hi @AnanyaJha,

I've been doing some more investigation into this on our side, and I believe that I've found some behaviour changes between the two CLI versions that can be replicated even with small or quick-running tests.

The first is the increase in test execution time - running a test as `sfdx force:apex:test:run -y -t <testClassName> --json`, the results contain a 'testExecutionTime' property. I've found this to be significantly higher when running on version 7.115 of the CLI compared to 7.75. For 500 executions of the same test class, the testExecutionTime on v7.75 averaged 362 milliseconds but on v7.115 the average testExecutionTime was 10183 milliseconds.

The other is evidence of code coverage being calculated - before running the test, I cleared code coverage information by going to Setup > Apex Test History and following the "View Test History" link, then clicking "Clear Test Data". I confirmed that code coverage had been deleted by running the following SOQL query through the Tooling API, which returned 0 results:
`SELECT ApexTestClassId, TestMethodName, ApexClassorTriggerId  FROM ApexCodeCoverage`
I then ran a test using `sfdx force:apex:test:run -y -t <testClassName> --json` and ran the same SOQL query to see whether any ApexCodeCoverage records had been created. When running the test using v7.75 of the CLI, none were created; when running the test using v7.115, it created several hundred records.
After that, I experimented with turning on the "Store Only Aggregated Code Coverage" option in the org, this resulted in no ApexCodeCoverage records being created on either version of the CLI. With this option turned on, running a large number of tests on v7.115 progresses quite a bit faster and doesn't produce as many timeout errors as it does when running with this option turned off, although the performance is still worse than on v7.75.

I hope this may be helpful in investigating this issue.

**Comment by randi274** [comment] 2021-11-23 18:58
Thanks @jrahadfield this narrowing of the issue has been extremely helpful! I've spent the better part of the morning working through this, and was able to reproduce the issue and track it down to the specific version that has the issue, which corresponds to a major rewrite of how we run our apex tests. You should be able to get up to v7.94.3 of the CLI with the old performance; v7.95.0 is where it takes a major hit. I'm still digging a bit further to see why the code coverage is being triggered, but unfortunately when I also tested adding the -c code coverage flag using the old version of the CLI, it was still much faster than the new version without that flag. Since it was such a large rewrite with that cutover to the new code (which was also refactored for readability, clearer business logic, and testing reasons), I'm not sure we'll be able to recuperate all of the performance degradation, but we've made much better testing inroads so far. Will keep you updated if we find anything else helpful!

**Comment by sfryffdc** [comment] 2021-11-26 17:42
@randi274 We have now tested this with a patch. We ensure that the skipCodeCoverage flag is set in the payload sent to the tooling API test method.

So for example in this file https://github.com/forcedotcom/salesforcedx-apex/blob/232657305fbc10c220399a77d6a865a23cdc53f3/packages/plugin-apex/src/commands/force/apex/test/run.ts

Line 178 would become

payload.skipCodeCoverage = true

This seems to improve the test times for us.

**Comment by ncrebbinffdc** [comment] 2021-12-01 12:00
@randi274 Did you get a chance to look at the testing we have done and the patch applied by @sfryffdc ? It would be really helpful if you could review this with a view to including in a release. Any timescales for this would be really useful too. We are blocked up upgrading our cli due to this so a quick fix and release would get us moving. Thanks

**Comment by AnanyaJha** [comment] 2021-12-02 04:24
Hi @ncrebbinffdc thanks for reaching out on this issue! We'll be prioritizing this item in our next iteration, so it should be addressed within the next month or two - with some leeway for the holiday season in the middle :) We'll be sure to update this thread once we have any more info or the fix has been released!

**Comment by ncrebbinffdc** [comment] 2021-12-02 08:55
Thanks for the updates @AnanyaJha and @randi274

**Comment by randi274** [comment] 2021-12-16 16:37
@ncrebbinffdc thanks for your patience. The fix also involved making sure tests were updated, and that we were putting the fix in the right spot. I have a change ready which I'm testing currently, which if all goes well should be ready for review and merge soon.

**Comment by randi274** [comment] 2021-12-16 17:09
The PR didn't link since the fix is in a different repository, but the fix is now in review [here](https://github.com/forcedotcom/salesforcedx-apex/pull/268) if y'all want to take a look.

**Comment by ncrebbinffdc** [comment] 2021-12-16 18:22
Thanks, I appreciate the update @randi274. Would I be pushing it a bit if i asked for a rough idea of a date if all goes well with your testing? i.e. are we looking at early January?

**Comment by randi274** [comment] 2021-12-16 18:44
@ncrebbinffdc so if it doesn't make it in for today's CLI release, it should be ready by the time their automated releases run next week before our holiday code freeze 🙂 Our fix here will just be the codecoverage fix, which may not be able to solve all of your team's latency issues, but we can work to further hone in on them once this fix is in!

**Comment by ncrebbinffdc** [comment] 2021-12-16 19:28
That is fantastic @randi274, many thanks

**Comment by ncrebbinffdc** [comment] 2022-01-20 09:20
Hi @randi274 Do you know when this will be released? It has not made it into the cli yet

**Comment by randi274** [comment] 2022-01-28 19:50
Hi @ncrebbinffdc this change should have been released a while ago, and I've been meaning to follow up! Are you still seeing tests are run even without the code coverage flag?

**Closed** 2022-02-09 17:51 UTC
Labels: type:bug, more information required, area:apex

**Comment by sfryffdc** [comment] 2022-02-10 09:13
Thanks, this is looking good now. 7.136.2 of sfdx-cli which now includes this fix is providing results that are comparable to the previous good ones.
