### ISSUE TITLE
Deployment errors are not shown after updating sfdx to version 7.112

### ISSUE THREAD

**Issue by pfrandsen** [forcedotcom/salesforcedx-vscode#3489] opened 2021-08-11 03:10 UTC
### Summary

After updating to sfdx cli version 7.112 the VS Code extension do not show error messages on Apex code deployment.

### Steps To Reproduce:

1.  Update sfdx cli to 7.112
1.  Create an Apex class with error
1. Try to deploy the class to an org
1. Look at result in output window - see the the text "ended with exit code 1" is shown instead or actual errors.
1. Execute "sfdx force:source:deploy --sourcepath <path to class> --json --loglevel fatal in terminal tab and see that it generates json output with errors

### Expected result

Errors shown in Salesforce CLI output tab

### Actual result

Extension shows the message "ended with exit code 1" instead of showing the the compile errors. Example:

sfdx force:source:deploy --sourcepath force-app\main\default\classes\DevOpsDemoTest.cls --json --loglevel fatal
 ended with exit code 1

### Additional information

<img width="625" alt="example" src="https://user-images.githubusercontent.com/1440545/128963132-21e30446-51f0-4d57-b968-96378ec6777c.png">
Instead of showing that the class "DevOpsDemo2" referenced in line 6 does not exist it just outputs "ended with exit code 1"

When deploying the same file with the force:source:deploy command the result does contain the correct error.

sfdx force:source:deploy --sourcepath 
<img width="454" alt="example2" src="https://user-images.githubusercontent.com/1440545/128963505-1d7272dd-acdb-422d-a11e-a0d198b45903.png">
force-app\main\default\classes\DevOpsDemoTest.cls --json --loglevel fatal

**Salesforce Extension Version in VS Code**:

v52.8.0

**SFDX CLI Version**:
sfdx-cli/7.112.1 win32-x64 node-v14.17.4

**OS and version**:
Windows 10

**Comment by smaddox-sf** [comment] 2021-08-11 22:47
Thanks for reporting this @pfrandsen - It looks like this is a duplicate of #3488 .  I'm closing this issue, so please follow #3488 and add any other comments on that issue.

**Closed by smaddox-sf** 2021-08-11 22:47 UTC
