### ISSUE TITLE
all deployments and authorizations to salesforce just spin after logging in to salesforce order 

### ISSUE THREAD

**Issue by tednesseth** [forcedotcom/salesforcedx-vscode#3007] opened 2021-03-02 07:05 UTC
I know we aren't receiving support but i think there a quite a few people experiencing the same or similar session errors
- would appreciate whatever you can do 

thanks!

Starting SFDX: Deploy Source to Org

01:00:35.410 sfdx force:source:deploy --sourcepath c:\Users\thehe\.sfdx\WebComponent\force-app\main\default --json --loglevel fatal
01:00:38.117 sfdx force:source:deploy --sourcepath c:\Users\thehe\.sfdx\WebComponent\force-app\main\default --json --loglevel fatal
 ended with exit code 1

Error: INVALID_SESSION_ID: Session expired or invalid

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1. i attempt to authorize an org.. and nope

### Expected result - authorize and deploy

_Describe what should have happened_. nothing - spinning after sfdc login

### Actual result - nothing - spinning after sfdc login

_Describe what actually happened instead_.  nothing - spinning after sfdc login

### Additional information

_Feel free to attach a screenshot_.

![image](https://user-images.githubusercontent.com/66988105/109612532-7a28c300-7af5-11eb-94f3-6f274cfe1c83.png)

**VS Code Version**: 1.53.2

**SFDX CLI Version**:

**OS and version**:

**Comment by lcampos** [comment] 2021-03-02 20:59
Thanks for logging this @tednesseth . The issue is with the Salesforce CLI (the vscode extensions delegate the auth flow to it). The CLI team is looking into this and you can follow issue https://github.com/forcedotcom/cli/issues/881 for updates. I'll close this issue as a duplicate.

**Closed by lcampos** 2021-03-02 20:59 UTC
