### ISSUE TITLE
static resource creation

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/salesforcedx-vscode#997] opened 2019-01-31 16:43 UTC
**Is your feature request related to a problem? Please describe.**
To add a new static resource, you either have to build in SetupUi and pull down, or manually mess with xml.  So I made a plugin for that `sfdx shane:static:create -n myJSResource -y js`

**Describe the solution you'd like**
This, in the command palette (ask me name it, specify the type)

**Describe alternatives you've considered**
making it by hand in xml, or in the ui.

**Additional context**
options and code here: https://github.com/mshanemc/shane-sfdx-plugins#sfdx-shanestaticcreate

**Comment by ntotten** [comment] 2019-02-05 21:35
Duplicate of #928

**Closed by ntotten** 2019-02-05 21:35 UTC
