### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by S-Dex** [forcedotcom/salesforcedx-vscode#2720] opened 2020-11-10 04:52 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.1.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\SUSHAN~1\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-11-10 15:28
I believe this is a dupe of #2410

**Closed by smaddox-sf** 2020-11-10 15:28 UTC
