### ISSUE TITLE
LWC Extension not activating

### ISSUE THREAD

**Issue by bconners1005** [forcedotcom/salesforcedx-vscode#2862] opened 2021-01-13 19:24 UTC
- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-lwc`
- Extension Version: `50.8.0`
- OS Version: `Darwin x64 20.2.0`
- VSCode version: `1.52.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 13977,
		"activateCallTime": 5,
		"activateResolvedTime": 15275,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "salesforce.salesforcedx-vscode-lwc",
				"_lower": "salesforce.salesforcedx-vscode-lwc"
			},
			"activationEvent": "workspaceContains:sfdx-project.json"
		}
	},
	"runtimeErrors": []
}
```

Steps to reproduce:
   Go to VS Code and load any existing project w/ a workspace

Expected outcome:
    LWC extension to load properly without becoming unresponsive.

Actual outcome:
   LWC extension listed as being Unresponsive

**Comment by smaddox-sf** [comment] 2021-01-14 17:37
Hi @bconners1005 - Thanks for reaching out.  Does the LWC extension successfully load for you with any project?

Has it successfully loaded in the past?

Are other Salesforce extensions fully activating?

**Comment by bconners1005** [comment] 2021-01-20 14:15
Hi @smaddox-sf

The LWX extension does not load properly on ay project at the moment.  It seems to happen across all projects.

It has loaded successfully in the past as well, yes.

The other extensions are, with the exclusion of refreshing all code from the org to the local, working correctly.

**Comment by xyc** [comment] 2021-01-22 23:50
hi @bconners1005 , thanks for the info. Some more info that can help troubleshoot this:
- Which part of LWC extension is not working? Sometimes the extension might report as unresponsive, but still functional.
- Is there any output on VS Code Menu -> View -> Output -> Select `LWC Extension` from dropdown?
- Is LWC extension [consuming a lot of CPU](https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu)? You can tell from Help>Open Process Explorer and see if extension host is taking a high CPU percentage.

**Comment by maaaaarco** [comment] 2021-02-03 12:46
Similar issue here... autocomplete is not working anymore for LWC... The extension seems to be active, in the Output panel I can't see any output though...
<img width="1005" alt="Screenshot 2021-02-03 at 13 46 43" src="https://user-images.githubusercontent.com/8080936/106748975-46599b00-6626-11eb-8c6f-8b4b6e3678a2.png">

**Comment by muenzpraeger** [comment] 2021-02-04 05:24
I can repro the issue, also in a different way. First, the extension breaks for me because of an issue with the set up of the Red Hat extension (where the extension works well for me).

```shell
Failed to setup Red Hat XML extension
Cannot read property 'addXMLCatalogs' of undefined
```

This seems to relate to [this line](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-lwc/src/metasupport/metaSupport.ts#L58).

After removing the offending part here [locally](https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-lwc/src/index.ts#L119) (which is IMHO a bit fragile, as this breaks the whole extension), I'm in the same boat as @maaaaarco. No output.

Will dig a bit more.

**Comment by muenzpraeger** [comment] 2021-02-04 05:36
Just to add what doesn't work (on my machine).

- No output on the `Output` panel
- No intellisense in markup (i. e. class field lookup within expression)
- No commands in the command palette available for interaction with LWC Local Dev Server

And for example this works for me:
- LWC Test commands in command palette
- LWC compiler validation (i. e. throwing LSP errors on invalid LWC syntax)
- GoToDefinition from markup into JS

It looks a bit like some part of the LSP work, and others not. 🤷🏼‍♂️

**Comment by lcampos** [comment] 2021-02-04 21:43
@maaaaarco , @muenzpraeger I've been able to repro this and have opened issue https://github.com/forcedotcom/salesforcedx-vscode/issues/2923 to track it, I'll close this since it was originally opened for something different.

As Rene mentions it's specific to the use of the XML extension, you can disable the use of the XML extension for now while we get the fix out.

Thanks again for reporting this.

**Closed by lcampos** 2021-02-04 21:43 UTC
Labels: area:lwc, area:performance, more information required

**Comment by jag-sfdc** [comment] 2021-02-11 16:55
@maaaaarco @muenzpraeger - We confirmed this is a regression with 0.15.0 Redhat XML extension. There is a fix in our VSCode extension release yesterday (50.17.0) to ignore activation for this specific version. We are working on fixing the root cause meanwhile.
