### ISSUE TITLE
Problems window is not populated with errors during compile

### ISSUE THREAD

**Issue by amitkumarj1979** [forcedotcom/salesforcedx-vscode#595] opened 2018-08-22 23:15 UTC
### Summary

When we deploy a file to Salesforce and there are errors reported during compilation. The same are shown in Output window. They should also be shown in the Problems window.

### Steps To Reproduce:

1.  In an Apex class, put something that will result in a syntax error on salesforce side.
2.  Compile the class.
3. Output window will show errors .
4. Problem window is blank.

### Expected result

Problem window should have the errors listed against the file as well.

### Actual result

Problem window is blank.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.26.1

**SFDX CLI Version**: Pre release

**OS and version**: Windows 10

**Comment by vazexqi** [comment] 2018-08-23 18:00
Duplicate of #588 .

**Closed by vazexqi** 2018-08-23 18:00 UTC
