### ISSUE TITLE
[Known Issue with Release 55.4.0 and now 56.16.0 ] Not able to deploy or retrieve source from Org on Windows #4261

### ISSUE THREAD

**Issue by meilingk** [forcedotcom/salesforcedx-vscode#4664] opened 2023-02-07 01:14 UTC
I am getting this errror with version 56.16.0. I have to roll back to 55.8 to get it working again. So please fix.

Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

**Comment by gbockus-sf** [comment] 2023-02-07 06:07
Hi @meilingk 
Can you provide more details about how you are attempting to deploy/retrieve?  Is it using a manifest or directly on the source files? Are you using the context menu (right click) or using the command pallet.  Please include the full name of the command you are attempting to run. 

Thanks!

**Comment by gbockus-sf** [comment] 2023-02-07 16:28
I tested this locally on the latest extensions and  VSCode V 1.73.0 and 1.75.0 and I haven't been able to repo the issue.  (I saw your comment on the past issue, I don't think it's the same exact problem but wanted to verify in code).

**Comment by meilingk** [comment] 2023-02-07 18:35
@gbockus-sf  I have installed the debug extension and here are the logs. i will revert to the last working version with is 55.8.0 .. i have tested the others after this version and they all presented the same error. My email is meiling.kuan@invenco.com

[vscode-app-1675794207554 - attempted righ click deploy2.log](https://github.com/forcedotcom/salesforcedx-vscode/files/10678268/vscode-app-1675794207554.-.attempted.righ.click.deploy2.log)
[vscode-app-1675794207554 - attempted righ click deploy.log](https://github.com/forcedotcom/salesforcedx-vscode/files/10678269/vscode-app-1675794207554.-.attempted.righ.click.deploy.log)

**Comment by gbockus-sf** [comment] 2023-02-07 20:33
Reviewing the logs now and slack invite sent.

**Comment by gbockus-sf** [comment] 2023-02-07 20:47
Looking at the logs provided I see the issue.  When comparing the file to be deployed there is a directory in the path that has a different case then when we check the eligible directories. 

"c:\\Users\\MeilingK\\GitHub\\*s*alesforce\\force-app\\main\\default\\classes\\OnBoardUserComponentCaseControllerTest.cls" 
VS
packageDirectoryPath: "c:\\Users\\MeilingK\\GitHub\\*S*alesforce\\force-app"[[Prototype]]
(note the [Ss]alesforce directory)

When you look at your file explore does that directory have an upper or lower case S?

**Comment by meilingk** [comment] 2023-02-07 21:33
Thanks @gbockus-sf  i will lower case my sfdx-project.json and see if this has any impact 
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "name": "salesforce",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "55.0"
}

**Comment by meilingk** [comment] 2023-02-07 21:34
I dont' see your slack invite could you please resend to meiling.kuan@invenco.com 
thanks

**Comment by gbockus-sf** [comment] 2023-02-07 22:32
I resent the invite to slack.  This is the first time I'm trying to add an external user so maybe there is something issue there.  I'll see if I can get it figured out.  

The issue is the Salesforce directory in your path: 
c:\Users\MeilingK\GitHub\Salesforce\force-app
                                            |---here--|

It's lower case when looking at the file to be deployed and Uppercase when looking at the package directories.  

![Screenshot 2023-02-07 at 4 32 12 PM](https://user-images.githubusercontent.com/76090802/217381693-67656b63-069e-427e-8869-b7405bd9a3b2.png)

I tried to repo the issue on my windows box, but can't seem to make it behave the same way.  Is there anything special about the Salesforce directory?  When you look at it in the file explore is it a link or does it have anything unique about it?

**Comment by gbockus-sf** [comment] 2023-02-07 22:40
@meilingk I think the email is getting blocked on your end.  I attempted to email you directly and the message was rejected.  Here is the slack joining link. I'll delete this message as soon as you are able to use it: https://join.slack.com/share/enQtNDc2NjI5MTgyMzIzNC0yNzMyZjYwMmQ0NGFiMDhmZjcyNjJhOWMzMGJmNzhlZmViNTU3NTE3MDExZmFjMjE3Y2IzZDJhZTcwNzVjZDhl

**Comment by gbockus-sf** [comment] 2023-02-07 23:30
@meilingk I created another debug vsix to add more debug logging and attempt to resolve file paths with case differences.  Give it a try when you have a chance: https://github.com/gbockus-sf/salesforcedx-vscode/releases/tag/v56.1.0.2

**Comment by meilingk** [comment] 2023-02-07 23:45
thanks i have join slack

I will test with the new debug and let you know as soon as i can. thanks,

Mei Ling Kuan
Systems Applications Developer
Invenco Group Limited
O: +6499567487
***@***.******@***.***>

www.invenco.com<http://www.invenco.com>


Disclaimer: This email is confidential and may be legally privileged.  If you are not the intended recipient you must not use any of the information in it and must delete the email immediately.



________________________________

**Comment by gbockus-sf** [comment] 2023-02-14 18:46
We tracked this down to a case mismatch for the project.  The directory that had the casing issue was outside the SF project, but it was never determined why it was different when attempting deploys/retrieves.  Thanks for working with me to get this figured out @meilingk I think we can close this more now as the issue is resolved.

**Closed by gbockus-sf** 2023-02-14 18:46 UTC
Labels: type:bug, area:deploy/retrieve

**Comment by meilingk** [comment] 2023-02-14 18:49
@gbockus-sf  No problem at all. It is such an obscure bug that I am sure most people doesn't hit. I am just the lucky one that name my folders in lower case. lol

Thanks again for turning around the solution quickly.
