### ISSUE TITLE
Command 'SFDX: Create Project' resulted in error(command 'sfdx.force.project.create' no found)

### ISSUE THREAD

**Issue by dongzhi-yang** [forcedotcom/salesforcedx-vscode#3684] opened 2021-12-06 11:33 UTC
I face the following error when I try to create a project. 
![image](https://user-images.githubusercontent.com/16980857/144836997-7ea4f8e6-8a32-421b-86e5-ecf7dd33c1f6.png)
This is what I see when I tried to select the command
![image](https://user-images.githubusercontent.com/16980857/144838174-126a7247-e833-4841-aeef-da21c960132e.png)
I have installed this package
![image](https://user-images.githubusercontent.com/16980857/144838271-ac80f416-c482-4e79-8688-6a84a0541900.png)
and this package
![image](https://user-images.githubusercontent.com/16980857/144838300-f23c0641-bb07-49a1-9d95-01997bfe34da.png)
Java 11 is installed and path set correctly
![image](https://user-images.githubusercontent.com/16980857/144838354-95895a3d-2a9c-4e2f-bd25-8df334650b5d.png)
Path of sfdx also set up correctly
![image](https://user-images.githubusercontent.com/16980857/144838410-b29e7a6d-1c1a-44cc-b9c3-8c33ed887cc2.png)
![image](https://user-images.githubusercontent.com/16980857/144838532-ccd9a899-ae54-47b9-b215-e240add1c0f4.png)
And I am able to create project in command line. 
Here is the error in console in VSC
![image](https://user-images.githubusercontent.com/16980857/144838885-8fb84b73-5849-4b9b-abdd-5cd9d8d2cbce.png)
Nodejs also installed properly
![image](https://user-images.githubusercontent.com/16980857/144839052-ca4f3d2b-91e0-4de4-87aa-dab41227c26b.png)

I have checked this thread but unable to find a solution
https://github.com/forcedotcom/salesforcedx-vscode/issues/1670
Please help.

**Comment by dongzhi-yang** [comment] 2021-12-06 16:09
This is VSC version:
----------------------
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by jeffb-sfdc** [comment] 2021-12-06 23:18
@dongzhi-yang I started to look into this but wasn't able to reproduce the issue.  I was able to create a new project w/o any issues.  I see from your screenshot you are running `sfdx-cli/7.129.0`.  When you run `sfdx plugins`, what plugins and versions are listed?  Also, if you haven't done so recently, be sure to run `sfdx update`.

**Comment by dongzhi-yang** [comment] 2021-12-06 23:59
![image](https://user-images.githubusercontent.com/16980857/144941575-4dad7fa8-bc81-4e23-86c3-1616344a3a2d.png)
Hi@jeff-sfdc, no plugins are installed

**Comment by dongzhi-yang** [comment] 2021-12-07 00:12
I ran the update earlier today, I also tried to install it with npm install sfdx --global.

**Comment by petersivak13** [comment] 2022-01-03 10:23
I have the same problem. The latest VS Code, sfdx, Salesforce Extension pack 
![image](https://user-images.githubusercontent.com/52290787/147920226-e32fc1ed-1280-4d18-9c38-08e0deed41a3.png)

**Comment by dongzhi-yang** [comment] 2022-01-03 10:26
I resolved the problem by uninstall VSC and reinstall it on C: drive. Previously it was installed on D: drive.

**Comment by petersivak13** [comment] 2022-01-04 10:23
Thanks for tip, this is my experience: 

- uninstall +install Salesforce Extension Pack doesnt's help.
- uninstall +install VSCode doesn't help - extensions are still there and cli integration is not working

**THIS HELP:**

- Uninstall all extensions in VS Code
- uninstall VS Code
- install the latest VS Code version (doesn't matter C: or D:), I installed it to custom folder
- install extensions including Salesforce Extension Pack

**Comment by randi274** [comment] 2022-01-05 18:40
Thanks for the follow-up on the resolution @dongzhi-yang and @petersivak13! I'm going to go ahead and close this now, since you've been able to resolve the issue.

**Closed by randi274** 2022-01-05 18:40 UTC
Labels: status:needs eng review, status:waiting
