### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by adamtzur1996** [forcedotcom/salesforcedx-vscode#2633] opened 2020-10-15 10:41 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.1.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\"username"\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-10-19 17:20
Not much detail here, but I believe this is a duplicate of #2410. Please check out that issue and the workaround I posted. Feel free to comment on whether the workaround helped you.

**Closed by smaddox-sf** 2020-10-19 17:20 UTC
