### ISSUE TITLE
SFDX is not properly ignoring non-salesforce workspaces

### ISSUE THREAD

**Issue by paustint** [forcedotcom/salesforcedx-vscode#5463] opened 2024-02-24 14:32 UTC
### Summary

I have a workspace which has nothing related to salesforce, but when I start vscode (or restart extension host), this extension incorrectly activates and creates `3K+` files in an `.sfdx` folder (which is not in my .gitignore because this is not an SFDX project).

In that past, I would often see an error pop up "This is not an sfdx workspace" or something like that, which was really annoying and I had considered filing a bug for that but never got around to it.

The issue does not happen every time and not sure exactly how to reproduce it.

### Steps To Reproduce:

1.  open vscode in a non-sfdx workspace
2. restart extension host (maybe a few times)

### Expected result

if sfdx extensions are installed and I am in a non-sfdx workspace, the extension should remain 100% dormant. files should never be created, I should never see any notifications etc..

### Actual result

sfdx invades all workspaces and creates `.sfdx` folder with thousands of files. and sometimes shows error notifications about missing project file.

### Additional information

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/5461649/0e1644cc-0556-44c7-a220-5a23ade99e36)

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/5461649/cb76d906-ebc2-421d-be2c-05d01ce554b5)

**Salesforce Extension Version in VS Code**: `v60.1.2` (this does appear to have updated recently)

**SFDX CLI Version**: 2.22.7

**OS and version**: osx latest

**VS Code version**: `1.86.2`

**Comment by peternhale** [comment] 2024-02-26 13:41
@paustint I was unable to reproduce this in my environment. Could you check to see if any of the parent directories of you project has an `sfdx-project.json` file?

**Comment by paustint** [comment] 2024-02-27 03:10
I'll try to determine that when back at my computer. It only happened once and does not appear to continue to happen - so not exactly sure what happened. I will play around with restarting vscode and restarting extension host etc...

**Comment by peternhale** [comment] 2024-02-27 13:04
@paustint thank you. I am going to close this issue. Please feel free to reopen it if you encounter the problem again.

**Closed by peternhale** 2024-02-27 13:04 UTC
Labels: more information required

**Comment by paustint** [comment] 2024-02-27 14:25
@peternhale - Is it normal that the extension shows an error message for all non-sfdx projects? This is really annoying to see this every time I start VSCode in non-sfdx workspaces.

These are the only things that show up in the output logs (this is from extension host output)
```
2024-02-27 07:22:08.596 [info] ExtensionService#_doActivateExtension salesforce.salesforce-vscode-slds, startup: false, activationEvent: 'onLanguage:javascript'
2024-02-27 07:22:08.638 [info] ExtensionService#_doActivateExtension salesforce.salesforcedx-vscode-core, startup: false, activationEvent: 'onView:sfdx.tasks.view'
```

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/5461649/1b4dad01-bc85-4320-9913-e2ff69cb6953)

**Comment by peternhale** [comment] 2024-02-27 15:15
@paustint extensions should not activate if preconditions for activation are not met.

vscode-core precondition is `"workspaceContains:sfdx-project.json"` so not sure what is happening.
I tried this on a new folder whose contents are from a simple npm init and I am not seeing vscode-core mentioned in in ext host log.

I will see if I can find a reasonable explanation.

**Comment by paustint** [comment] 2024-02-28 01:38
[Here is the repo](https://github.com/jetstreamapp/jetstream) that I normally work in, but have seen the same happen on other computers with different codebases.
there is not an `sfdx-project.json` in the codebase, I am not using a multi-root workspace, and I have 100% confirmed that there is not an `sfdx-project.json` in any parent folders.

It is a very minor annoyance, so not something I am very concerned about.

**Comment by paustint** [comment] 2024-03-10 15:58
@peternhale - I don't know if this helps at all, but I just noticed that this entry is showing up in the "Extension Hosts" log when I start VSCode:
`2024-03-10 08:53:04.306 [info] ExtensionService#_doActivateExtension salesforce.salesforcedx-vscode-core, startup: false, activationEvent: 'onView:sfdx.tasks.view'`

**Comment by paustint** [comment] 2024-03-23 01:32
@peternhale - lol, one other thing is that an `.sfdx` folder is magically created at the same time this error message shows up. I just downloaded a metadata package, unzipped, and opened in VSCode and I get the error (in my downloads folder) and then the sfdx folder is created.

This issue happens on 4 different computers, but I do have settings-sync so there must be something there.

These are the only user settings that seem related to this extension AFAIK

```
"salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home",
"settingsSync.ignoredSettings": ["salesforcedx-vscode-apex.java.home"],
```

<img width="1210" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/5461649/e6db29ed-d7fe-4b6a-bc45-0f7274c90e8a">

**Comment by skostojohn** [comment] 2024-04-19 14:33
I am seeing this same behavior, running extension pack 60.8.0

**Comment by peternhale** [comment] 2024-04-19 15:02
@paustint @skostojohn what is the state of E4D extension for each of you.

**Comment by skostojohn** [comment] 2024-04-19 15:37
@peternhale I think my issue was related to the einstein for developers extension.  Once I removed that, I stopped having this problem.

**Comment by paustint** [comment] 2024-04-21 21:44
I do not have `einstein for developers` installed, I just learned about it from your comments.

**Comment by paustint** [comment] 2024-04-21 21:48
Also - I no longer see the `.sfdx` folder get created, but I still get the activation error message.

Video showing my experience
https://jam.dev/c/420a2b18-d1ef-426d-81a0-6dff88a335c8
