### ISSUE TITLE
Testing Tab does not display Apex tests

### ISSUE THREAD

**Issue by sfsupportmlp** [forcedotcom/salesforcedx-vscode#5103] opened 2023-09-18 15:44 UTC
Type: <b>Bug</b>

I have Salesforce Extension Pack installed that is required prerequisite to run SFDX projects in VSCode. When I go into the testing tab, it does not load up any apex unit tests even though I have a whole bunch of them.

Extension version: 58.14.2
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600 CPU @ 3.10GHz (6 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.71GB free)|
|Process Argv|--crash-reporter-id 63baa670-9e56-4e1c-8814-214a7a618bfb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30835152
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by daphne-sfdc** [comment] 2023-09-18 16:07
Hi @sfsupportmlp,

Is this what you are seeing?
<img width="381" alt="Screenshot 2023-09-18 at 12 05 49 PM" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/139700604/5dece844-7da1-479a-a5b1-fe2db4e84c67">

If yes, click the Refresh button and wait a few seconds for the tests to load.  If you click the refresh button multiple times and you still don't see the tests, please let me know.

**Comment by sfsupportmlp** [comment] 2023-09-18 16:39
That worked!! 
But i have tried that several times before and it never worked until now.

**Comment by daphne-sfdc** [comment] 2023-09-18 16:57
Great to hear that the problem is resolved!  We believe the Apex Tests not showing up is due to VSCode's cache.  If this continues to be a problem in the future, and the Refresh button doesn't work, you can try running "Developer: Reload Window" from the command palette to reload the entire window.

Closing this issue as completed.

**Closed by daphne-sfdc** 2023-09-18 16:57 UTC
Labels: more information required
