### ISSUE TITLE
Saving LWC Component Bundle throws error "An object 'X' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory"

### ISSUE THREAD

**Issue by molsi01** [forcedotcom/salesforcedx-vscode#2375] opened 2020-07-24 07:43 UTC
### Summary

Making a change to .js file of an LWC Component Bundle will not allow a Save & Deploy when using CMD & S (File / Save) or ALT & CMD & S (File / Save All).  When attempting this, an error is thrown:
"An object 'X' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory"
Using the manual 'SFDX:Deploy Source to Org' on the .js file, via the menus (or right click on the file) works.
Saving the .html file _does_ work as expected using CMD & S

### Steps To Reproduce:

1.  Create a new LWC in VS Code
1.  Add a simple <lightning-button> component to the .html file with an onchange event
1.  Add a simple onchange handler to the .js file to console.log some output
1.  Save all components using ALT & CMD & S
1.  Error is produced
1.  Manually run SFDX:Deploy Source to Org (right click on .js file)
1.  Save & deploy works

### Expected result

Using CMD & S or ALT & CMD & S should save & deploy changes.  If editing just the .js file, using CMD & S should save & deploy the .js file

### Actual result

.js file is not deployed and error above is thrown

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.47.2

**SFDX CLI Version**:
7.66.2

**OS and version**:
MAC OS 10.15.5

**Comment by jeffb-sfdc** [comment] 2022-04-01 16:56
This is a duplicate of https://github.com/forcedotcom/lightning-language-server/issues/446

**Comment by jeffb-sfdc** [comment] 2022-04-01 17:13
@molsi01 I attempted to reproduce this but wasn't able to. Here's what I did: I created a LWC class and in the JS file added:
```
import { LightningElement } from 'lwc';

export default class LwcExample extends LightningElement {
  numberFieldValue;

  handleNumberChange(event) {
    console.log('handleNumberChange() was called');
  }
}
```


...and in the HTML file I added:
```
<template>
  <lightning-input
    type="number"
    onchange={handleNumberChange}
    label="Enter a number">
  </lightning-input>
</template>
```

I then saved (using CMD-S) but I didn't get any errors.

Are you still able to reproduce this? If so, are there different steps needed to reproduce this?

**Closed** 2022-04-08 17:40 UTC
Labels: type:bug, more information required, area:lwc, area:deploy/retrieve
