### ISSUE TITLE
Authorizing a Salesforce Org

### ISSUE THREAD

**Issue by tfranklin27** [forcedotcom/salesforcedx-vscode#3001] opened 2021-03-01 21:20 UTC
When trying to authorize an org, a localhost error is displayed. The org was authorized previously but the link used no longer exist. When trying to authorize the same org with a new link, the localhost error is shown. I'm not sure how to delete the original link from VScode to see if that would help. It is from the Salesforce extension pack. Authorizing by ctrl+shift+p, >SDFX:Authorize An Org, Sandbox (test.salesorce.com), input alias, it then sends me to chrome for the salesforce login, after entering my credentials, it will go to the next page like its going to authorize the org but never loads. It will stay on a white screen until I cancel in VScode, then I get the localhost error.

**Comment by tfranklin27** [comment] 2021-03-01 21:24
![Blankscreen](https://user-images.githubusercontent.com/50031324/109560853-fabdd400-7aa1-11eb-943b-f23d53cd13a1.png)
![localhost](https://user-images.githubusercontent.com/50031324/109560970-2640be80-7aa2-11eb-9d81-6dee108ad501.png)

**Comment by tfranklin27** [comment] 2021-03-01 21:24
![image](https://user-images.githubusercontent.com/50031324/109561037-407a9c80-7aa2-11eb-82d2-c03bb2755001.png)

**Comment by qwikag** [comment] 2021-03-02 03:48
Yes, this is a major bug.
Firefox edge and maybe chrome cannot communicate with localhost:1717
We need the configuration to setup windows to work with the integration. Or the integration needs to change.

lots of solutions out there but none work.
port changes  (settings update does not make a difference)
firewall changes (turn it off)
host files changes (add localhost)
version changes (there is a version that works, but it has other issues)
nothing works!

This needs Attention!
Thanks

**Comment by lcampos** [comment] 2021-03-02 20:49
Thanks for logging this @tfranklin27 . The issue is with the Salesforce CLI (the vscode extensions delegate the auth flow to it). The CLI team is looking into this and you can follow issue https://github.com/forcedotcom/cli/issues/881 for updates. I'll close this issue as a duplicate.

**Closed by lcampos** 2021-03-02 20:49 UTC
