### ISSUE TITLE
Remove warnings for aura:component inline style with dynamic value

### ISSUE THREAD

**Issue by combizs** [forcedotcom/salesforcedx-vscode#1123] opened 2019-03-05 18:31 UTC
### Summary

_Short summary of what is going on or to provide context_.
Using the Aura Components VSCode plugin, when you have a dynamic inline style for an aura component, error(s) should not be thrown by the validator.

### Steps To Reproduce:

1.  Create lightning component
1.  Define a `<div>` to apply an inline style
1.  Apply an inline style with a dynamic value, i.e.:
  ```
<aura:component>
    <aura:attribute name="red" type="String" default="#ff0000" />
    <div style="{!'padding:0.5rem; background-color:' + red}">hello world!</div>
</aura:component>
  ```

### Expected result

_Describe what should have happened_.
There should be no warnings for the component file regarding this matter.

### Actual result
_Describe what actually happened instead_.
There are 3 warnings: `emptyRules`, `css-rcurlyexpected`, `css-rcurlyexpected`
![screen shot 2019-03-05 at 9 58 13 am](https://user-images.githubusercontent.com/749396/53828250-fa7db300-3f31-11e9-96ba-553a8bfe3c79.png)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version 1.31.1 (1.31.1)

**SFDX CLI Version**:
sfdx-cli/6.55.1-be0b3dc4c4

**OS and version**:
mac darwin-x64

**Comment by ntotten** [comment] 2019-03-06 23:02
Duplicate of #950

**Closed by ntotten** 2019-03-06 23:02 UTC
