### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yash-pal** [forcedotcom/salesforcedx-vscode#2694] opened 2020-10-31 18:59 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.3.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\palya\AppData\Local\Temp\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sreenucnu** [comment] 2020-11-01 04:59
got the 
[salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt](https://github.com/forcedotcom/salesforcedx-vscode/files/5470228/salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt)
same issue

- Issue Type: `Bug`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `50.3.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by smaddox-sf** [comment] 2020-11-04 17:57
Can you share more details of when this happened?  Was it upon activation?  I believe it's a duplicate of #2410, but I need more info to confirm.

**Closed by smaddox-sf** 2020-11-04 17:57 UTC
