### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Venkatesh-k-ch** [forcedotcom/salesforcedx-vscode#2454] opened 2020-08-27 12:38 UTC
- Issue Type: `Performance`
- Extension Name: `salesforcedx-vscode-core`
- Extension Version: `49.6.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\DELL\salesforce.salesforcedx-vscode-core-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smaddox-sf** [comment] 2020-08-27 14:10
There's not enough information here to understand what's going on.  Please open a new issue using the "Bug" template.

Sounds like it might be a duplicate of #2410

**Closed by smaddox-sf** 2020-08-27 14:10 UTC
