### ISSUE TITLE
forceignore not working

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/salesforcedx-vscode#1409] opened 2019-06-18 21:04 UTC
I set below in forceignore and it worked before it's not working after 46 version
**listViews
#/force-app/main/default/objects/Account/listViews
**/*CloudingoAgent__**
**CloudingoAgent__**

PS C:\SalesforceDX\HMI DX\hmidelete> sfdx force:source:push
PROJECT PATH                                                                                      ERROR
────────────────────────────────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
force-app\main\default\objects\Account\fields\CloudingoAgent__BAR__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (3:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__BAV__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (29:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__BRDI__c.field-meta.xml              Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (41:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__BTZ__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (53:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__SAR__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (65:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__SAS__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (77:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__SAV__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (91:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__SRDI__c.field-meta.xml              Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (103:13)
force-app\main\default\objects\Account\fields\CloudingoAgent__STZ__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (115:13)
force-app\main\default\objects\Account\webLinks\BigMachines__iframe_resizing.webLink-meta.xml     Cannot create a new component with the namespace: BigMachines.  Only components in the same namespace as the organization can be created through the API (210:15)
force-app\main\default\objects\Account\webLinks\INQ__Send_Inquisium_Survey.webLink-meta.xml       Cannot create a new component with the namespace: INQ.  Only components in the same namespace as the organization can be created through the API (340:15)
force-app\main\default\objects\Account\webLinks\geopointe__Map.webLink-meta.xml                   Cannot create a new component with the namespace: geopointe.  Only components in the same namespace as the organization can be created through the API (221:15)
force-app\main\default\objects\Account\webLinks\geopointe__Map_Records_Account.webLink-meta.xml   Cannot create a new component with the namespace: geopointe.  Only components in the same namespace as the organization can be created through the API (251:15)
force-app\main\default\objects\Account\webLinks\geopointe__Map_newWindow.webLink-meta.xml         Cannot create a new component with the namespace: geopointe.  Only components in the same namespace as the organization can be created through the API (232:15)
force-app\main\default\objects\Account\webLinks\pi__Send_Pardot_Emails.webLink-meta.xml           Cannot create a new component with the namespace: pi.  Only components in the same namespace as the organization can be created through the API (353:15)
force-app\main\default\objects\Account\webLinks\pi__Send_Single_Pardot_Email.webLink-meta.xml     Cannot create a new component with the namespace: pi.  Only components in the same namespace as the organization can be created through the API (365:15)
force-app\main\default\objects\Account\webLinks\pi__Send_To_Prospect_Insight.webLink-meta.xml     Cannot create a new component with the namespace: pi.  Only components in the same namespace as the organization can be created through the API (376:15)
force-app\main\default\objects\Account\listViews\AFM1.listView-meta.xml                           Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (456:16)
force-app\main\default\objects\Account\listViews\APAC_IN_Accounts.listView-meta.xml               Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (518:16)
force-app\main\default\objects\Account\listViews\APAC_MY_Accounts.listView-meta.xml               Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (543:16)
force-app\main\default\objects\Account\listViews\APAC_TH_Accounts.listView-meta.xml               Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (570:16)
force-app\main\default\objects\Account\listViews\Accounts_Reviewed_Status.listView-meta.xml       In field: columns - no CustomField named Account.Account_Classification__c found (407:16)
force-app\main\default\objects\Account\listViews\AllAccounts.listView-meta.xml                    Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (477:16)
force-app\main\default\objects\Account\listViews\All_US_Accounts.listView-meta.xml                Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (495:16)
force-app\main\default\objects\Account\listViews\CN_HMI_Q_DAS1.listView-meta.xml                  Could not resolve list view column: ACCOUNT.NAME_LOCAL (626:16)
force-app\main\default\objects\Account\listViews\CN_HMQ.listView-meta.xml                         Could not resolve list view column: ACCOUNT.NAME_LOCAL (654:16)
force-app\main\default\objects\Account\listViews\CN_HMQ10.listView-meta.xml                       Could not resolve list view column: ACCOUNT.NAME_LOCAL (683:16)
force-app\main\default\objects\Account\listViews\CN_HMQ8.listView-meta.xml                        Could not resolve list view column: ACCOUNT.NAME_LOCAL (708:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_Accounts_with_no_Area6.listView-meta.xml  Could not resolve list view column: ACCOUNT.NAME_LOCAL (734:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_KA.listView-meta.xml                      Could not resolve list view column: ACCOUNT.NAME_LOCAL (761:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_KA4.listView-meta.xml                     Could not resolve list view column: ACCOUNT.NAME_LOCAL (803:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_KA_tTKA.listView-meta.xml                 Could not resolve list view column: ACCOUNT.NAME_LOCAL (829:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_MyAccounts.listView-meta.xml              Could not resolve list view column: ACCOUNT.NAME_LOCAL (862:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_NewThisWeek.listView-meta.xml             Could not resolve list view column: ACCOUNT.NAME_LOCAL (890:16)
force-app\main\default\objects\Account\listViews\CN_HMQ_View1.listView-meta.xml                   Could not resolve list view column: ACCOUNT.NAME_LOCAL (924:16)
force-app\main\default\objects\Account\listViews\CN_Serein.listView-meta.xml                      Could not resolve list view column: ACCOUNT.NAME_LOCAL (965:16)
force-app\main\default\objects\Account\listViews\Channel_Partners.listView-meta.xml               Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (602:16)
force-app\main\default\objects\Account\listViews\Fastenal.listView-meta.xml                       Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (999:16)
force-app\main\default\objects\Account\listViews\HMQ_KA.listView-meta.xml                         Could not resolve list view column: ACCOUNT.NAME_LOCAL (1032:16)
force-app\main\default\objects\Account\listViews\MyAccounts.listView-meta.xml                     Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (1060:16)
force-app\main\default\objects\Account\listViews\Reviewed.listView-meta.xml                       In field: columns - no CustomField named Account.Account_Status__c found (1073:16)
force-app\main\default\objects\Account\listViews\ShippingAddress_Missing.listView-meta.xml        In field: columns - no CustomField named Account.Shipping_Address__c found (1096:16)
force-app\main\default\objects\Account\listViews\Subregion_Missing.listView-meta.xml              Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (1138:16)
force-app\main\default\objects\Account\listViews\TKA.listView-meta.xml                            Could not resolve list view column: ACCOUNT.NAME_LOCAL (1236:16)
force-app\main\default\objects\Account\listViews\Target_Key_Accounts_NA.listView-meta.xml         Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (1171:16)
force-app\main\default\objects\Account\listViews\Tesa_acct.listView-meta.xml                      Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (1199:16)
force-app\main\default\objects\Account\listViews\Test_Acc.listView-meta.xml                       Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (1220:16)
force-app\main\default\objects\Account\listViews\VPA_Accounts.listView-meta.xml                   Could not resolve list view column: ACCOUNT.ADDRESS1_STATE_CODE (1260:16)
force-app\main\default\objects\Account\fields\CloudingoAgent__BAS__c.field-meta.xml               Cannot create a new component with the namespace: CloudingoAgent.  Only components in the same namespace as the organization can be created through the API (15:13)
ERROR running force:source:push:  Push failed.

**Comment by chandra2ravi** [comment] 2019-06-18 21:06
![image](https://user-images.githubusercontent.com/93057/59719865-06406d00-91e3-11e9-9812-a6b422164a2a.png)

**Comment by lcampos** [comment] 2019-06-25 01:22
Duplicate of #1410 , I'm closing this one and will follow up in the other issue's thread.

**Closed by lcampos** 2019-06-25 01:22 UTC
