### ISSUE TITLE
Refresh sObject not found (v46.15.0)

### ISSUE THREAD

**Issue by ProtonPS** [forcedotcom/salesforcedx-vscode#1673] opened 2019-09-19 17:41 UTC
After updating the VS Code extensions (especially Apex) the command:">SFDX: Refresh SObject Definitions" throws "command 'sfdx.force.internal.refreshsobjects' not found" error

### Steps To Reproduce:

1.  Update the "Apex" extension to 46.15.0
1.  Execute command

### Expected result

The object definitions update

### Actual result

The error is thrown

### Additional information
After reverting the extension (and only Apex) to 46.14.0 and reloading the command works again

_Feel free to attach a screenshot_.

**VS Code Version**:
-1.38.1

**SFDX CLI Version**:
-sfdx-cli/7.25.3-16d54c01ee darwin-x64 node-v10.15.3

**OS and version**:
MacOS (10.14.6)

**Comment by lcampos** [comment] 2019-09-19 17:43
Hi @ProtonPS , thanks for reporting this. This is caused by issue #1671 and the fix will be released soon. Sorry for the inconvenience.

**Comment by lcampos** [comment] 2019-09-19 18:38
This is fixed in version `46.15.1`, thanks for reporting the issue.

**Closed by lcampos** 2019-09-19 18:38 UTC
Labels: status:duplicate
