### ISSUE TITLE
Deploy speed for single components is slow

### ISSUE THREAD

**Issue by jonathanwiesel** [forcedotcom/salesforcedx-vscode#676] opened 2018-10-15 13:01 UTC
**Is your feature request related to a problem? Please describe.**
I've noticed that when using other tools like MavensMate, when you save an apex class, or other similar metadata, this triggers an implicit deploy of said class to the connected org that last a few seconds (often less than 10s but obviously depends on a lot of things). When deploying the same metadata component using SFDX the deployment time is generally considerably higher (maybe 2 - 3 times higher).

It gets worse when you want to deploy a couple of metadata components but cannot select many in the file tree to deploy them in the same operation and then you need to do it one by one.

**Describe the solution you'd like**
I've read that in the roadmap there's already "deploy on save" feature planned but would be nice to have better timings, I guess there's much more going backstage in sfdx than traditional org-based development tools.

**Comment by vazexqi** [comment] 2018-10-15 17:41
Duplicate of #594. Let's consolidate and keep track of discussions there.

**Closed by vazexqi** 2018-10-15 17:41 UTC
Labels: duplicate
