### ISSUE TITLE
Please provide Code Conflict error during Deploy code 

### ISSUE THREAD

**Issue by shahpathik81** [forcedotcom/salesforcedx-vscode#1549] opened 2019-08-09 09:53 UTC
Hello,
I am a salesforce Developer. From last 3 years i used Mavensmate and sublime text for salesforce project editor purpose. But now mavens no more longer support to Mavensmate. So i try to user friendly with VS Code. But now i got Big Problem faced during Implementation that VS can not show Code Conflict error throw. It shows and compare with Highlight of server copy and change copy.
If some changes in server copy code then VS code Deploy that code without throw any error. That is Big Problem to any salesforce developer that changes that code.
Please add this functionality in VS Code.

Thanks & Regards: 
Pathik Shah

**Comment by ntotten** [comment] 2019-08-09 16:12
Duplicate of #870

**Closed by ntotten** 2019-08-09 16:12 UTC
