### ISSUE TITLE
Salesforce extension pack does not work

### ISSUE THREAD

**Issue by jmcaudron** [forcedotcom/salesforcedx-vscode#880] opened 2019-01-17 11:30 UTC
### Summary

_After  Salesforce Installation Package Installation_. I tried to test SFDX : Create Project

### Steps To Reproduce:

1.  install package.
1.  launch command SFDX: Create Project

### Expected result

_ask project name then project should be created_.

### Actual result

_message appears : command 'sfdx.force.project.create' not found _.

### Additional information

_Feel free to attach a screenshot_.
![capture](https://user-images.githubusercontent.com/15669145/51316385-c66b3300-1a54-11e9-9193-ac7b9e67d671.JPG)

**VS Code Version**: 1.30.2

**SFDX CLI Version**: sfdx-cli/6.48.0-bfccc40118 (windows-x64) node-v8.9.4

**OS and version**: Windows 7

**Comment by ntotten** [comment] 2019-01-17 15:11
Is this a consistent problem or something that happened once? We have seen this issue when the CLI is updating, but that goes away after it finishes.

**Comment by jmcaudron** [comment] 2019-01-17 21:31
it is a consistant problem. It tried to reinstall vscode and salesforce extension. 
It looks like installation failed without error because Salesforce CLI Integration appears as Installing. When I start again VSCODE extension appears as Installed
![capture](https://user-images.githubusercontent.com/15669145/51350102-9ac56880-1aa7-11e9-8f31-b99bcd818a36.JPG)

**Comment by lcampos** [comment] 2019-01-18 00:34
@jmcaudron this seems similar to #742 for which we've released a fix as part of version `44.16.0` of the extensions. Can you verify if your issue is now fixed and if it isn't could you open the Developer Tools by going to Help > Toggle Developer Tools, then go to the Console menu option in the newly opened Dev Tools window and take a screenshot of the output to see if there's an error in it.

**Comment by jmcaudron** [comment] 2019-01-18 09:32
Hello @lcampos ,
See screenshot below. It shows many error on activation of sfdx extension
![capture](https://user-images.githubusercontent.com/15669145/51377314-e4936a80-1b0a-11e9-9e01-2764d8bd20fc.JPG)

**Comment by lcampos** [comment] 2019-01-18 17:21
@jmcaudron that error suggests the issue is with a configuration with ISV debugger (https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-apex-debugger). Are you using a project to debug a managed package for a customer ?

**Comment by jmcaudron** [comment] 2019-02-05 07:50
Thanks @lcampos ,
I had some component from managed package which cause this issue. After removal of this component, it works well.

**Closed** 2019-02-12 19:45 UTC

**Comment by MadhuriTatineni** [comment] 2019-09-16 13:12
@jmcaudron: I am having similar issues with my VS code now. Can you tell me which managed packages you removed to resolve the issue ? This will help me a lot! Thanks in advance.

**Comment by MWinnSalesforce** [comment] 2020-04-28 16:52
@jmcaudron Similar to @MadhuriTatineni, I am having issues using VS Code after installing the Salesforce Extension Pack. Which managed package component did you remove to resolve your issue?
