### ISSUE TITLE
 [error] ["validating: Corrupt ZIP: end of central directory record signature not found"

### ISSUE THREAD

**Issue by Myraa** [forcedotcom/salesforcedx-vscode#3519] opened 2021-08-26 15:39 UTC
### Summary

giving the below error while trying to install salesforce extension pack in vscode.
[2021-08-26 11:22:40.159] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at _.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)","    at async _.doRun (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)"]
[2021-08-26 11:22:40.212] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at _.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)
    at async _.doRun (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)

### Steps To Reproduce:

1.  Open VSCode
2. Install "Salesforce Extension Pack"
### Expected result

Should install all plugins of extension pack

### Actual result

giving the below error while trying to install salesforce extension pack in vscode.
[2021-08-26 11:22:40.159] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at _.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)","    at async _.doRun (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)"]
[2021-08-26 11:22:40.212] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at _.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:196354)
    at async _.doRun (vscode-file://vscode-app/c:/Users/pboddu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:58:195331)
### Additional information

![image](https://user-images.githubusercontent.com/36314837/130993218-d80db0d3-3e7d-4b85-8eef-41eba4a38667.png)

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**Comment by xyc** [comment] 2021-09-08 23:05
duplicate of #3530

**Closed by xyc** 2021-09-08 23:05 UTC
Labels: status:needs eng review

**Comment by Myraa** [comment] 2021-09-09 05:09
Installing older version of vscode (47.x) has fixed my issue with plugins. But, I think VScode should fix the issue in latest version
