### ISSUE TITLE
Functions like "SFDX: Deploy Source to Org" are missing

### ISSUE THREAD

**Issue by ViraOsinaCT** [forcedotcom/salesforcedx-vscode#5338] opened 2024-01-16 14:03 UTC
I don't see functions like "SFDX: Deploy Source to Org"  in my VS code anymore. They were present before.

### Steps To Reproduce:

1.  open SFDX Project in Visual Studio Code
2.  right click on any force-app > lwc component

### Expected result

see "SFDX: Deploy Source to Org" and other SFDX functions in the menu

### Actual result

no SFDX functions in the menu nor quick access to xml files (no dark cloud icon on the tool menu);

### Additional information

sfdx-project.json file is present in the directory

"salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home"

I tried uninstalling extensions, restarting VS code, and installing it again. No success.

<img width="447" alt="SCR-20240116-oate" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/95303580/bfe0507a-9ccc-48e9-8622-9bc5b6c3fe14">
<img width="382" alt="SCR-20240116-oawf" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/95303580/aee13388-1f3a-4153-8f9b-dff67fd19ca9">

**Salesforce Extension Version in VS Code**: v59.13.0

**SFDX CLI Version**: @salesforce/cli/2.23.20 darwin-x64 node-v20.10.0

**OS and version**: MacOS Monterey 12.7.2

**VS Code version**: 1.85.1 (Universal)

**Comment by peternhale** [comment] 2024-01-16 16:05
@ViraOsinaCT could you share the list of running extensions from vscode using `Developer: Show Running Extensions`

**Comment by ViraOsinaCT** [comment] 2024-01-16 17:03
@peternhale Suree:) Here's the full list of Developer: Show Running Extensions
<img width="1039" alt="SCR-20240116-qpow" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/95303580/ffe1ce0f-cb87-43f2-8813-e596fd89f735">

**Comment by peternhale** [comment] 2024-01-16 17:52
@ViraOsinaCT I don't see the `Salesforce Extension Pack` running. Is it installed?

**Comment by peternhale** [comment] 2024-01-16 19:46
@ViraOsinaCT I was wondering if you could share a vscode log file? The logs directory on Mac will be in your home directory `~/Library/Application Support/Code/logs`

In the logs directory will be a number of sub dirs with name like `20240116T122953`, a timestamp. Follow the most recent and you will see contents like 
```
editSessions.log
main.log
network.log
ptyhost.log
remoteTunnelService.log
sharedprocess.log
telemetry.log
terminal.log
userDataSync.log
window1
```
Navigate into `window1` and the structure will look like this 
```├── exthost
│   ├── GitHub.copilot-chat
│   ├── GitHub.vscode-pull-request-github
│   ├── Salesforce.codegenie
│   ├── output_logging_20240116T122955
│   ├── sf-core-ides.vscode-internal-marketplace
│   ├── vscode.git
│   ├── vscode.github
│   └── vscode.github-authentication
└── output_20240116T122955
```
The extHost dir will contain the log of the initialization of installed extensions and the `output_nnnn` dir will contain the output from each extension.

I would like to look at exthost.log and the salesforce related log files in the `output_nnnn` directory.

**Comment by adamdWalkMe** [comment] 2024-01-16 23:29
Hey @peternhale , confirming I've got the same/similar issue. I noticed the commands were missing, then I noticed this error:

<img width="535" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/143725530/34146788-d8e4-464a-9450-27415967014d">

I tried updating the CLI from terminal, which worked fine (and I can access all commands in the default shell). 

I'm on extension version 59.13.0 on Mac (Apple Silicon).

I looked for the logs you mentioned, and they were there, but with no content.

<img width="770" alt="image" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/143725530/a2bcfa65-c616-4cc8-96e0-9388c0127709">

When I revert just Salesforce CLI Integration to 59.9.0, the problem resolves.

**Comment by ViraOsinaCT** [comment] 2024-01-17 11:00
@peternhale Here are the logs requested, but they are empty 
<img width="793" alt="SCR-20240117-lqut" src="https://github.com/forcedotcom/salesforcedx-vscode/assets/95303580/10be01d0-25a8-4c5f-af4e-bc5628a4043e">

**Comment by peternhale** [comment] 2024-01-17 13:16
@adamdWalkMe using the vscode embedded terminal window, run `sf version --verbose` and share the results. Also, did you restart vscode after you installed the CLI?

**Comment by peternhale** [comment] 2024-01-17 16:55
@ViraOsinaCT can you send me the `exthost.log` file?

**Comment by adamdWalkMe** [comment] 2024-01-19 00:01
@peternhale here you go

```
CLI Version:
        @salesforce/cli/2.23.20

 Architecture:
        darwin-arm64

 Node Version:
        node-v20.10.0

 Plugin Version:
        @oclif/plugin-autocomplete 3.0.4 (core)
        @oclif/plugin-commands 3.1.0 (core)
        @oclif/plugin-help 6.0.9 (core)
        @oclif/plugin-not-found 3.0.7 (core)
        @oclif/plugin-plugins 4.1.14 (core)
        @oclif/plugin-search 1.0.10 (core)
        @oclif/plugin-update 4.1.7 (core)
        @oclif/plugin-version 2.0.11 (core)
        @oclif/plugin-warn-if-update-available 3.0.8 (core)
        @oclif/plugin-which 3.0.14 (core)
        @salesforce/cli 2.23.20 (core)
        apex 3.0.14 (core)
        auth 3.1.0 (core)
        data 3.0.13 (core)
        deploy-retrieve 2.2.12 (core)
        env 3.0.13 (user)
        info 3.0.13 (core)
        limits 3.1.0 (core)
        marketplace 1.0.15 (core)
        org 3.2.0 (core)
        packaging 1.25.0 (user)
        schema 3.1.0 (core)
        settings 2.0.14 (core)
        sobject 1.0.7 (core)
        source 3.0.10 (core)
        telemetry 3.1.8 (core)
        templates 56.0.8 (core)
        trust 3.2.5 (core)
        user 3.2.0 (core)
        @salesforce/sfdx-plugin-lwc-test 1.1.1 (user)
        @salesforce/sfdx-scanner 3.20.0 (user)

 OS and Version:
        Darwin 22.6.0

 Shell:
        sh

 Root Path:
        /Users/adam.d/.local/share/sf/client/2.23.20-50cd2d8
```

**Comment by peternhale** [comment] 2024-01-19 13:32
@ViraOsinaCT @adamdWalkMe for folks that are encountering this issue we are recommending that they downgrade to v59.12.0 while we assess the root cause. We apologize for the inconvenience.

**Comment by peternhale** [comment] 2024-01-19 13:42
We will be tracking this issue via #5340

**Closed by peternhale** 2024-01-19 13:42 UTC
Labels: more information required, investigating

**Comment by ViraOsinaCT** [comment] 2024-01-19 13:43
@peternhale Thank you for your assistance ❤️
