### ISSUE TITLE
Timeout or long time for retrieve and diff functions

### ISSUE THREAD

**Issue by SarveshSprk** [forcedotcom/salesforcedx-vscode#5654] opened 2024-06-21 08:58 UTC
### Summary

VSCode retrieve or diff time varies a lot and mostly on the longer side even leading to timeout in Sandbox.

### Steps To Reproduce:

1.  Open VSCode
1.  After extensions are loaded, try to retrieve single file/component using right click and select retrieve.

### Expected result

Retrieve or Diff function to execute within few seconds.

### Actual result

Most of the time it time outs, and sometimes it takes 6-7 mins. 

**Salesforce Extension Version in VS Code**: 61.1.2

**Salesforce CLI Version**: 2.45.6

**OS and version**: Windows 11 Enterprise 64 bit 10.0.22621

**VS Code version**:  1.90.2

**Most recent version of the extensions where this was working**: Not sure, the issue is happening from two weeks.

**Comment by RCMoonpie** [comment] 2024-06-21 13:06
I, too, suddenly had a seemingly related issue today when attempting to retrieve a Custom Metadata Type that was newly created via UI in a sandbox and which did not yet exist in my local project.

## Issue Details
### Initial
#### Command
`sf project retrieve start --metadata CustomObject:New_CMDT__mdt`

#### Output while running
```
>> Warning: @salesforce/cli update available from 2.34.7 to 2.46.6
Retrieving v59.0 metadata from name@example.com.sandbox using the v61.0 SOAP API
Preparing retrieve request... | Pending
```
NOTE: Spinner between "request..." and "Pending" was spinning the entire time

#### Result
After an estimated 60-90 seconds, pressed `Ctrl + C` in terminal to abort

#### Output after abort:
```
Preparing retrieve request... done
C:\Programs Portable\node-v20.10.0-win-x64\node_modules\@salesforce\cli\node_modules\@olif\core\lib\errors\index.js:20
    throw new exit_1.ExitError(code);
    ^
    
ExitError: EEXIT: 130
    at RetrieveMetadata.exit (C:\Programs Portable\node-v20.10.0-winx64\node-modules\@salesfore\cli\node_modules\@oclif\core\lib\command.js:180:16)
    at process.<anonyous> (file:///C:/Programs%20Portable/node-v20.10.0-winx64/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:262:22)
    at process.emit (node:events:526:35) {
  code: 'EEXIT',
  oclif: { exit: 130 },
  skipOclifErrorHandling: undefined,
  suggestions: undefined
}

Node.js v20.10.0
```
#### Notes
* Diff on metadata existing in local project worked fine
* Deployment of metadata from local project worked fine

#### System info
Salesforce Extension Version in VS Code: 61.1.2 (updated yesterday, 20 June 2024)
Salesforce CLI Version: @salesforce/cli/2.34.7 win32-x64 node-v20.10.0
OS and version: Windoze x64 10.0.19045
VS Code version: 1.88.1
Most recent version of the extensions where this was working: Unknown -- I do not know what version I was on before updating yesterday

### Next Step
* Retried same command : same result

### Next Step
* Restarted VS Code
* Retried same command : SUCCESS

**Comment by daphne-sfdc** [comment] 2024-06-21 17:19
Hi @SarveshZap, Can we get some info about your org shape?  For example, number of Apex classes, number of LWC components, number of custom objects, etc.  Can we also get the org id of your sandbox and the org id of the production org that created the sandbox?

**Comment by diyer** [comment] 2024-06-21 20:47
@RCMoonpie looks like you are running retrieve with cli command and not with VS Code extension. If the issue is with cli, please report it on https://github.com/forcedotcom/cli

**Comment by SarveshZap** [comment] 2024-06-28 06:11
> Hi @SarveshZap, Can we get some info about your org shape? For example, number of Apex classes, number of LWC components, number of custom objects, etc. Can we also get the org id of your sandbox and the org id of the production org that created the sandbox?

Hello, I am not sure if I can give you org id of sandboxes. Though the org has many components including number of custom objects, apex classes and LWC. The applications is customized on higher side. It used to take few seconds without single occurrence of delay before last two weeks. 

We tried to reach out salesforce support and got this article in response which has no ETA or workaround :( 
https://issues.salesforce.com/issue/a028c00000yGOhWAAW/intermittent-long-wait-time-for-metadata-retrieval-using-mdapisfdc-cli-post-migrating-to-hyperforce

**Comment by daphne-sfdc** [comment] 2024-06-28 18:47
Hello @SarveshZap, In order to investigate the logs for your issue on our systems, we need the org id of your sandbox.  If you would prefer not to send us the org id on a public forum, please email it to us at svcideebot@salesforce.com.

**Comment by SarveshSprk** [comment] 2024-07-01 09:09
> Hello @SarveshZap, In order to investigate the logs for your issue on our systems, we need the org id of your sandbox. If you would prefer not to send us the org id on a public forum, please email it to us at [svcideebot@salesforce.com](mailto:svcideebot@salesforce.com).

@daphne-sfdc Thanks for sharing email id, but it seems the email id is invalid: svcideebot@salesforce.com
Could you please check again and confirm?

**Comment by daphne-sfdc** [comment] 2024-07-01 12:57
@SarveshSprk Sorry for the typo - it's svc_idee_bot@salesforce.com.

**Comment by SarveshSprk** [comment] 2024-07-01 13:11
> @SarveshSprk Sorry for the typo - it's [svc_idee_bot@salesforce.com](mailto:svc_idee_bot@salesforce.com).

@daphne-sfdc Sent an email to that address few mins ago. Kindly check.

**Comment by daphne-sfdc** [comment] 2024-07-01 13:16
@SarveshSprk Yes I received the email.  Thank you.

**Comment by SarveshSprk** [comment] 2024-07-09 04:51
@daphne-sfdc Just wanted to check-in if there is any diagnosis / update on this issue with continuing conversation. Thanks.

**Comment by daphne-sfdc** [comment] 2024-07-09 20:16
Closing this issue as the delay is on the server side.

**Closed by daphne-sfdc** 2024-07-09 20:16 UTC
Labels: type:bug, status:owned by another team, validated
